### ISSUE TITLE
this.unsubscribeFromOffsetChange is not a function

### ISSUE THREAD

**Issue by petrbrzek** [react-dnd/react-dnd#1002]
We started to receive this error `this.unsubscribeFromOffsetChange is not a function` when `DragLayerContainer` calls `componentWillUnmount`.  
We use Electron 1.7.5 which uses Chromium 58 under the hood. It's happening on all OS's.

**Comment by darthtrevino** [comment]
Can we get a sandbox of this issue occurring? that variable should just be a redux unsubscribe function - so either componentDidMount() was not fired or there's a `this` binding issue.
