### ISSUE TITLE
Dnd lifecycle is broken when dragging items pretty fast.

### ISSUE THREAD

**Issue by RomanProkhodsky** [react-dnd/react-dnd#1004]
There are 2 issues when the user drags the item pretty fast:

1) The lifecycle gets broken when the user quickly drags an item and drops it into the panel: it should be
"beginDrag" -> "drop" -> "endDrag", but we have "beginDrag" -> "endDrag" instead.

Here is the [video](https://drive.google.com/file/d/1EIK8dmGpRxkV5yKQ_7owZdDI7IiAHn31/view?usp=sharing), first time I move the item slower and we can see that "drop" is fired, but last 2 times I move the item fast, and only "endDrag" is fired, "drop" is skipped.

2) When the user takes an item and quickly drags it outside of its drop target panel, "isOver" is never set to "true" in "componentWillReceiveProps", but it should be, since the user starts dragging the item inside the panel, so the first move should trigger "isOver" to "true".

Here is the [video](https://drive.google.com/file/d/1aAY3DvIkRaPIAmRJCs86iPmkoSpcPZAU/view?usp=sharing), first time I move the item slower, and we can see "Is over the panel Columns" message. The second time I move the item faster, and "isOver" never sets to "true", so we won't see the message.

Here is the [sandbox](https://codesandbox.io/s/j77y56p039), where you can reproduce these issues.

**Comment by jameydeorio** [comment]
I'm experiencing a symptom of this. I have DropTargets stacked on top of each other, and when I pull a DragSource from one to another "quickly" (normal speed to me), `isOver()` returns false.

It works if I drag slowly and have some pixels between the elements, but never if they are touching.

**Comment by jameydeorio** [comment]
I noticed that in `canDrop`, `isOver` is always correct, in my case anyway. It feels super hacky, but I'm managing my own `isOver` in redux state from the `canDrop` function, for now.

Might be a strategy that works for others while we wait.

**Comment by RomanProkhodsky** [comment]
I tried to check `isOver` inside the `canDrop`, it is still `false` if I move an item quite fast.

**Comment by RomanProkhodsky** [comment]
Any progress on this one?
