### ISSUE TITLE
Sending post request in drop()?

### ISSUE THREAD

**Issue by dexterleng** [react-dnd/react-dnd#1005]
```
    drop(props, monitor, component) {
        const item = monitor.getItem();

        axios.post("/api/swap_list",
            {card_id: item.id,
             list_id_dest: props._id,
             board_id: props.board_id}).then(() => {
                 component.fetchCards(props._id);
                 return {moved: true};
             });
    }
```

I tried making drop() async but that causes the following error:
`Invariant Violation: drop() must either return undefined, or an object that represents the drop result. Instead received [object Promise]`

The above code does not make the 'moved' property appear in my DragSource when I do monitor.getDropResult() in endDrag(). Is sending a post request to modify the db not advisable in drop()?

**Comment by darthtrevino** [comment]
Personally, I would engineer that side effect in your application's redux stack (assuming you're using redux) using redux-saga or something like that. At the very least you can try just returning undefined after your post invocation.
