### ISSUE TITLE
redux 4 is not supported

### ISSUE THREAD

**Issue by ArtemZag** [react-dnd/react-dnd#1010]
This library doesn't support new redux 4.
There is import of "redux/lib/createStore" in DragDropManager.js.
But this entry is missing in redux 4 now.

**Comment by KvanSteijn** [comment]
When will the fix released?

**Comment by darthtrevino** [comment]
Soonish - I'd like to get a fix in for an issue in Firefox that was reported first. ETA 1 week

**Comment by bkniffler** [comment]
Maybe we can have this with @latest tag? Thanks for your hard work!
