### ISSUE TITLE
HTML5Backend issues

### ISSUE THREAD

**Issue by DemjanUA** [react-dnd/react-dnd#1011]
Hi!
You can find demo [here](http://dnd-issue.surge.sh).
[Source code.](https://github.com/DemjanUA/HTML5Backend-issues)

I use react-dnd on my current project. My case is collapsing DragSource after 'beginDrag' and uncollapsing on 'endDrag' for easy usage elements reordering(sorting).

![f1498f27-0e81-482f-ye9f-1b202d208fae](https://user-images.githubusercontent.com/16669415/38935210-71b6e846-4326-11e8-901e-322f7310f5d5.gif)

I faced with the problem, i can start drag just on first and half of second item.
I don't have this problem without collapsing. But i am sure it isn't connected with nested reorder.
Probably it related with dimensions calculations under hood.

![image](https://user-images.githubusercontent.com/16669415/38935616-7338a3de-4327-11e8-9a55-50260004e4ff.png)

**Comment by djErock** [comment]
I am having a similar issue... Are you getting this error in the console?  Uncaught TypeError: Cannot read property 'nodeName' of undefined
