### ISSUE TITLE
Using React DnD with styled components.

### ISSUE THREAD

**Issue by joetidee** [react-dnd/react-dnd#1021]
I need to use React DnD with styled components.

I raised this question on stackoverflow, but have also posted this issue here in the hope of obtaining an answer:
https://stackoverflow.com/questions/50220622/how-to-use-react-dnd-with-styled-component

**Comment by Rinaldo** [comment]
I recently ran into this issue myself and found that Dan [answered](https://github.com/react-dnd/react-dnd/issues/347) this question a while ago. When I tried to use the snippet he posted to make a Semantic UI component draggable, I got the following error: `Warning: Stateless function components cannot be given refs. Attempts to access this ref will fail.` But I then found that Semantic UI has a `Ref` component and I was able to adapt his solution to use that.

Here's an example with Semantic UI
```javascript
import React from 'react'
import { findDOMNode } from 'react-dom';
import { Item, Ref } from 'semantic-ui-react'
import { DragSource } from 'react-dnd'

const MyItem = props => (
    <Item>
        <Item.Content>
            <Item.Header>{props.header}<Item.Header>
            <Item.Content>{props.content}<Item.Content>
        </Item.Content>
    </Item>
)

const DraggableItem = props => {
  const { connectDragSource } = props
  return (
    <Ref innerRef={instance => connectDragSource(findDOMNode(instance))}>
      <MyItem {...props} />
    </Ref>
  )
}

export default DragSource(...)(DraggableItem)
```

**Comment by zainfathoni** [comment]
You can just use Styled Component's [**innerRef**](https://www.styled-components.com/docs/advanced#refs) to get the underlying DOM node, then you can call your [connectDragSource](https://react-dnd.github.io/react-dnd/docs-drag-source-connector.html) to it.

Apparently you don't need `findDOMNode()` at all in Styled Components, because the `innerRef` already gives you the actual underlying DOM node.

In your case, it should be like this:

```jsx
class MyComponent extends Component {
...
    render() {
        const { connectDragSource } = this.props;
        return (
            <StyledComponent
                innerRef={instance => connectDragSource(instance)}
            />
        )
    }
}
```

You can also look at my implementation of [Knight](https://github.com/zainfathoni/react-dnd-tutorial/blob/master/src/Knight.js#L40) component for the official chess tutorial as a reference.

**Comment by artooras** [comment]
I have a similar use case, only inside of a `styled-component` I use an Icon component from `react-fontawesome`, like so:

```
const Container = styled.li`...`
const DragHandle = styled(FontAwesomeIcon).attrs({...})`...`

function Task(props) {
  return (
    <Container innerRef={instance => connectDropTarget(connectDragPreview(instance))}>
    <DragHandle innerRef={instance => connectDragSource(instance)} />
}
```

Using the techique suggested by @zainfathoni above works well on the `Container` component which is based on a native `li` tag. However, using it on `DragHandle` which is based on `FontAwesomeIcon` gives me the following error:

`TypeError: node.setAttribute is not a function`

Any ideas how I can 'dig down' to the native `span` tag that fontawesome renders?

**Comment by darkowic** [comment]
@artooras you probably have solved your problem until now but here is the solution - https://github.com/react-dnd/react-dnd/issues/347#issuecomment-221703726

```
ref={instance => {
  connectDragSource(instance);
  connectDropTarget(instance);
}}
```

**Comment by rzkhosroshahi** [comment]
How can I use new Ref react API to solve this problem?

**Comment by rzkhosroshahi** [comment]
@darkowic
How can I use new Ref react API to solve this problem?

**Comment by darkowic** [comment]
@rzkhosroshahi what do you exactly mean?

**Comment by rzkhosroshahi** [comment]
@darkowic
I wanna use custom component inside React DnD, but in new ref React API you cant use ref props as a callback function, like this`ref={instance => {
  connectDragSource(instance);
  connectDropTarget(instance);
}}`. 
my question is that how do like this snippet code for new ref.

**Comment by zainfathoni** [comment]
@rzkhosroshahi 
Do you mean this [`createRef` API](https://reactjs.org/blog/2018/03/29/react-v-16-3.html#createref-api)?

I think we can't use that API for this.
Anyway, there's no plan to remove the callback API, so you can still use the callback API for this.

Just as they noted in the `createRef` API docs:
> Callback refs will continue to be supported in addition to the new createRef API.
You don’t need to replace callback refs in your components. They are slightly more flexible, so they will remain as an advanced feature.

**Comment by ViggoV** [comment]
```javascript
<StyledComp ref={instance => connectDragSource(instance)} />
```

works flawlessly for me, EXCEPT it seems to completely break PropTypes as described [in my SO question here...](https://stackoverflow.com/questions/54251851/proptypes-receives-undefined-types-in-react-dnd-styled-components-combo)

It think it must be something with the refs, since I have several other components which uses one or the other as well as a few which combines the two using native DOM element wrappers..

**Comment by rzkhosroshahi** [comment]
> ```js
> <StyledComp ref={instance => connectDragSource(instance)} />
> ```
> 
> works flawlessly for me, EXCEPT it seems to completely break PropTypes as described [in my SO question here...](https://stackoverflow.com/questions/54251851/proptypes-receives-undefined-types-in-react-dnd-styled-components-combo)
> 
> It think it must be something with the refs, since I have several other components which uses one or the other as well as a few which combines the two using native DOM element wrappers..

Is that work in production? I used this approach but when I building project my component is not dragged anymore.

**Comment by aircraft721** [comment]
![2019-05-02 20_24_17-Window](https://user-images.githubusercontent.com/20306755/57094122-6acd6880-6d18-11e9-9974-cbaabcf800b4.png)
What can I do in this case? I'm using the suggested <StyledComp ref={instance => connectDragSource(instance)} /> solution, but i'm receiving an error.

**Comment by ViggoV** [comment]
@rzkhosroshahi Minification seems to break it. It's not in production yet, so I haven't found a solution, but as long as i set `minimize: false` under `optimization` in my webpack config it works.

**Comment by Raduuu** [comment]
I have the same problem. My question is, does it work when we're using react-dnd with their hooks ( useDrag and useDrop) and not decorators?

Thanks
