### ISSUE TITLE
react-dnd + react-redux low performance ，Repeated calls connectDragSource fn

### ISSUE THREAD

**Issue by SunXinFei** [react-dnd/react-dnd#1023]
> It demonstrates that React DnD keeps track of the changing props, and if a component receives the new props, React DnD recalculates the drag and drop state.

Maybe this is the reason of low performance.
my issue =>
![react-dnd redux](https://user-images.githubusercontent.com/5847281/39861339-e39a65d4-5472-11e8-8d45-bad2f1b58457.gif)
when use setstate will ok,  but !! see this in gif, i drag first to second item, and break on last item,   when use react-redux, when drag one item ,but the connectDragSource will repeated called, this prefermance is low,  how to forbid connectDragSource repeated calls when use react-redux ? here is my code 
```js
class GroupItem extends PureComponent {
   return connectDragSource(connectDropTarget(
        <div className="group-item" style={{ opacity: opacity}}>
        </div>
        ))
    }
}

const dragDropItem = DropTarget('item',groupItemTarget,collectTarget)(DragSource('item',groupItemSource,collectSource)(GroupItem));

export default (connect(
	(state) => ({
        groups: state.templateDragData.groups,
	}),{
        updateGroupList,
	}
)(dragDropItem))

```

the new test , i find when call connectDragSource(connectDropTarget(item)), and when use react-redux connect this item, when  groups change ,connectDragSource will be called,

**Comment by SunXinFei** [comment]
![react-dnd redux 2](https://user-images.githubusercontent.com/5847281/39861637-d1374b54-5473-11e8-8788-1eee849cf886.gif)

**Comment by SunXinFei** [comment]
### those  use redux connect, low performance
![redux-connect 2](https://user-images.githubusercontent.com/5847281/39871321-fe73a89c-5496-11e8-9e05-3ff71c584446.jpg)
![redux-connect](https://user-images.githubusercontent.com/5847281/39871322-feba73d0-5496-11e8-9675-cc5a631c56ce.jpg)
===============
### those no use redux connect
![no-redux-connect 2](https://user-images.githubusercontent.com/5847281/39871309-f65baa06-5496-11e8-9657-fc952c098b94.jpg)
![no-redux-connect](https://user-images.githubusercontent.com/5847281/39871310-f6a3979e-5496-11e8-8ff8-a7deb3aea68a.jpg)

**Comment by galexandrade** [comment]
@darthtrevino just to have a sense of time, is someone taking a look on this issue? We have an application using this react-dnd but we have a large number of sources and targets and when we drag something it rerenders all the sources components causing performance issues when starting dragging and when dropped.

**Comment by darthtrevino** [comment]
My time availability for this project is fairly sporatic. I usually work on this library in bursts. If you submit a PR and @-tag me on it, that's usually the fastest way to solve a problem. In this case, just from looking at it briefly - have you considered implementing a custom SCU function that does a shallow check over your injected properties?
