### ISSUE TITLE
Fails in production mode

### ISSUE THREAD

**Issue by drakoniprincessa** [react-dnd/react-dnd#1024]
In development environment my dnd component works excellent. But in production it doesn't.   Multiple `Uncaught Error: Expected sourceIds to be an array.` message in console on drag begin. How is it possible?

**Comment by narensprinter** [comment]
Yes if you minify code . its not working i'm also facing same issue.

**Comment by paguillama** [comment]
I'm having a similar problem: it works great on development, but in production (minified) once `isOver` returns `true` for a component it continues returning `true` until dropping the source element, even if the source is not over the target. Any ideas?

**Comment by rzkhosroshahi** [comment]
@paguillama @narensprinter 
@gaearon 
I have the same issue. anyone find a solution?

**Comment by RJSchmertz** [comment]
We are also experiencing this problem in production mode but not development mode when updating to current versions.  Old version we were on works (2.6 :fearful:)

**Comment by jdconner** [comment]
Currently on version 7.0.2 having the exact same issue as @paguillama 

Has anyone come across a solution?

**Comment by jdconner** [comment]
Found out a decent solution. Props to @tambeta for the initial code [here](https://github.com/react-dnd/react-dnd/issues/179#issuecomment-441077231)

If we take his implementation as is, itll destroy performance if the user hovers the DropTarget given that the DropTarget will consistently rerender. Given our situation, we only want to know if the targets have changed, so we can update his solution to:

```js
import React from 'react';
import { DropTarget } from 'react-dnd';
import pick from 'lodash-es/pick';
import isEqual from 'lodash-es/isEqual';

function RapidFireDropTarget(types, spec, collect, options = {}) {
    let collectProps = {};
    const prevHover = spec.hover;
    const { collectRapidly = [] } = options;
    let lastTargetIds = [];

    const dummyConnect = {
        dropTarget: () => () => {
            throw new Error('Rapidly collected props cannot include results from `connect`');
        },
    };

    const WrappedComponent = Component => {
        return class extends React.Component {
            render() {
                return <Component {...this.props} {...collectProps} />;
            }
        };
    };

    spec.hover = (props, monitor, component) => {
        const allCollectProps = collect(dummyConnect, monitor);
        const nextTargetIds = monitor.internalMonitor.store.getState().dragOperation.targetIds;

        collectProps = pick(allCollectProps, collectRapidly);

        if (!isEqual(nextTargetIds, lastTargetIds)) {
            component.forceUpdate();
        }

        lastTargetIds = monitor.internalMonitor.store.getState().dragOperation.targetIds;

        if (prevHover instanceof Function) {
            prevHover(props, monitor, component);
        }
    };

    return Component => {
        return DropTarget(types, spec, collect, options)(WrappedComponent(Component));
    };
}

export default RapidFireDropTarget;
```

then use it:

```js
...

export default RapidFireDropTarget(types, target, collect)(YourComponent);
```

and it should technically only rerender if the targets change.
