### ISSUE TITLE
React-dnd 3.0.0 Error in IE 11:  "Unhandled promise rejection SyntaxError" 

### ISSUE THREAD

**Issue by SunXinFei** [react-dnd/react-dnd#1025]
I try the version 2.6.0 is ok, but the 3.0.0 will get this error
==========
in react-dnd/lib/DragDropContext.js
![image](https://user-images.githubusercontent.com/5847281/40108625-0a5e5440-592e-11e8-8092-647766d8c62d.png)

**Comment by darthtrevino** [comment]
This is probably because it's transpile target is ES2015. The next version of 3.x will target ES5. Please use 2.x for now
