### ISSUE TITLE
Can't use lifecycle methods in a component decorated with @DragSource in a TypeScript project

### ISSUE THREAD

**Issue by rssfrncs** [react-dnd/react-dnd#1027]
Decorating a TypeScript component with `@DragSource` which uses a React life-cycle function (componentDidMount) results in the following TypeScript error:

```
Property 'componentDidMount' is optional in type 'DndComponent<Props, any>' but required in type 'Person'.
```

Please see the issue live in this [codesandbox ](https://codesandbox.io/s/wq935lv6ol) (Draggable.tsx).

Thanks.

**Comment by rssfrncs** [comment]
@BrandonWilliamsCS Can you try refreshing the page after adding the `experimentalDecorators: true` option? It removed the error for me, but when i refreshed it was back!

**Comment by BrandonWilliamsCS** [comment]
Ah, you're right. That was too easy a fix anyway.

**Comment by rssfrncs** [comment]
@darthtrevino Wrong repo to raise against? 

Not fixed but you can work around it by **not** using decorators. Use `lodash.flow` for when you need to enhance with both drag and drop.

**Comment by darthtrevino** [comment]
I'm sorry about that, I thought this issue was resolved.

**Comment by darthtrevino** [comment]
So in looking at your example - we're not supporting or maintaining the typings defined in DefinitelyTyped. From 3.x on, react-dnd provides its own typings. Can you retry with 3.0.2?

**Comment by rssfrncs** [comment]
@darthtrevino [could you check this fork of the above sandbox out ](https://codesandbox.io/s/k2vwrln607) is this the correct way to split component props and collected props?

**Comment by darthtrevino** [comment]
Sure, so to fix this, make the collected props on your component optional. I'd like to make the typings here a little more elegant so that you don't have to do that (I know redux's typings work that way).

https://codesandbox.io/s/0mqw0k0720
