### ISSUE TITLE
Module not found: Error: Can't resolve 'redux/lib/createStore' in '/dnd-core/lib'

### ISSUE THREAD

**Issue by glud123** [react-dnd/react-dnd#1028]
The following error occurred when I implemented `npm i` to upgrade dependencies.

Here is the error message.
```
ERROR in /Users/***/demo/node_modules/dnd-core/lib/DragDropManager.js
Module not found: Error: Can't resolve 'redux/lib/createStore' in '/Users/***/demo/node_modules/dnd-core/lib'
```

Below are the relevant libraries and versions.
```
"react-dnd": "^2.6.0",
"redux": "^4.0.0",
```
![image](https://user-images.githubusercontent.com/22994043/40435951-67524b0a-5ee4-11e8-91e2-6fefc698ad71.png)

**Comment by glud123** [comment]
![image](https://user-images.githubusercontent.com/22994043/40436853-78ae86dc-5ee6-11e8-9278-0d74dece585d.png)
If possible, please match Redux 4.0

**Comment by darthtrevino** [comment]
We're using Redux 4 and this is working on my end - can you verify what version of React-DnD you're using?

**Comment by medslt** [comment]
I have the same error @glud123 how did you resolve it ?

**Comment by Acalpha** [comment]
I have the same error @glud123 @medslt how did you resolve it ?

**Comment by Acalpha** [comment]
I have the same error @glud123 @medslt how did you resolve it ?
