### ISSUE TITLE
Non-ES5 Trailing commas in lib directory - ultimately causes webpack/uglifyjs errors

### ISSUE THREAD

**Issue by BrandonWilliamsCS** [react-dnd/react-dnd#1029]
version:
```
        "react-dnd": "^2.6.0", // resolved to 2.6.0
```

In particular, notice the trailing comma on line 97 of `decorateHandler.js` of the published package. Additionally, line 202 maps back to [line 66 of the source .tsx file](https://github.com/react-dnd/react-dnd/blob/af675a71408e434020a8593a1fb1b28b3afb7b1b/packages/react-dnd/src/decorateHandler.js#L63) with a trailing comma on both lines. Obviously it's okay in the source, but it's not removed during transformation, it seems.

Oddly, something in the build process is _trying_ to emit ES5 code, as the lambda on [line 16 of the source file](https://github.com/react-dnd/react-dnd/blob/master/packages/react-dnd/src/decorateHandler.tsx#L10) is converted from arrow to non-arrow syntax. But somehow these non -ES5 commas aren't being removed.

FWIW, I don't think 3.0.0 is generating fully ES5 output either. The perfectly-okay-in-typescript-and-ES6 method declaration on the object being returned [here](https://github.com/react-dnd/react-dnd/blob/56de3464bab54ad81473dee58fda558eba0acf7f/packages/dnd-core/src/actions/dragDrop.ts#L27) isn't being transpiled to something ES5-friendly. On that note - I noticed your `tsconfig.base.json` file at the project base is targeting `"es2015"`, so the non-ES5 output makes sense. I'm curious; why not target ES5?

**Comment by darthtrevino** [comment]
The thought here is that ES2015 is has broad browser support currently. If this is causing significant pain we can target ES5 instead and push out a new version.
