### ISSUE TITLE
isDragging always return false

### ISSUE THREAD

**Issue by gabrielCuringa** [react-dnd/react-dnd#1030]
Hi, when I try to drag/drop an element, the drop() function is never called and I noticed that isDragging() always return false.

Here is my DropTarget component : [https://code.empreintesduweb.com/12823.html](url)

Here is my DragSource component : [https://code.empreintesduweb.com/12824.html](url)

Here is my App.js : [https://code.empreintesduweb.com/12825.html](url)

I have already verified that my key props is not using the index of the map.

Thank you in advance, I'm pretty new with React... (Sorry for my english)

**Comment by azz0r** [comment]
404 links
