### ISSUE TITLE
Improve Project Testing

### ISSUE THREAD

**Issue by darthtrevino** [react-dnd/react-dnd#1036]
There are a number of issues that are arising from a combination of browser and OS that are resulting in difficult to reproduce bugs. We should look into better doing some better end-to-end tests using a variety of browsers.

**Comment by skbolton** [comment]
I would be interested in helping out with this library. Is this a good place for me to put in some work or are there other more pressing issues you could use a hand on

**Comment by darthtrevino** [comment]
This would be a good one, there's definitely a need in this project to have some automated cross-browser testing. We have a BrowserStack account that we can use to this end.

The big, untested part of this project is the html5-backend. There's a lot of idiosyncratic, browser-specific workarounds, so that piece of the code is kind of warty.

**Comment by skbolton** [comment]
I was also thinking it might be a good idea to add tests to all examples. First to have them and catch errors there. But also to improve the testing guides and help the community out on how they can test their components

**Comment by darthtrevino** [comment]
I think that's a great idea, we can use those to test the library
