### ISSUE TITLE
Integration\implementation into react-grid-layout [need info]

### ISSUE THREAD

**Issue by snezik** [react-dnd/react-dnd#1040]
Who has experience with integration dnd into react-grid-layout?

I will be glad to any information or example. 

Thank you in advance

**Comment by SunXinFei** [comment]
I did not use react-grid-layout, but I use react-dnd realized grid-layout by myself, my code is here:
https://github.com/glud123/demo-main/tree/master/src/workbench_front/pages/DesktopSetting
https://github.com/glud123/demo-main
