### ISSUE TITLE
Hover and drop not being called when a DragLayer is used.

### ISSUE THREAD

**Issue by joaquindk** [react-dnd/react-dnd#1041]
When I use the DragLayer HOC to customise the drag preview, hovering over a drop target doesn't work if the drag preview is placed directly under the mouse pointer. However if the drag preview is placed adjacent to the pointer everything works as expected.

So basically if I define a DragLayer like this...

```
const dragLayerConnector = monitor => ({
  isDragging: monitor.isDragging(),
  itemType: monitor.getItemType(),
  item: monitor.getItem(),
  currentOffset: monitor.getSourceClientOffset(),
  initialClientOffset: monitor.getInitialClientOffset(),
  initialSourceClientOffset: monitor.getInitialSourceClientOffset(),
});

class MyDragLayer extends Component {
  getStyles() {
    const { currentOffset } = this.props;

    if (!currentOffset) {
      return {
        display: 'none',
      };
    }
    const { x, y } = currentOffset;
    
    return {
      transform: `translate(${x}px, ${y}px)`,
      position: 'absolute',
      width: '200px',
    };
  }

  render() {
    const {
      isDragging,
      itemType,
      item,
      currentOffset,
      initialClientOffset,
      initialSourceClientOffset,
      ...other
    } = this.props;

    if (!isDragging) {
      return null;
    }

    if (itemType !== Types.MyItem) {
      return null;
    }

    if (!item) {
      return null;
    }

    const style = this.getStyles();

    return (
      <div style={style}>
        Preview test
      </div>
    );
  }
}

export default DragLayer(dragLayerConnector)(MyDragLayer);

```

..if my drag source is wider than 200px and I begin to drag from beyond the 200px that the drag layer draws, everything works as expected. However if I begin to drag from within the 200px width, where the draglayer preview is rendered, dragging is automatically stopped as soon as the drag layer renders the first time.

I've managed to work around this by leaving the preview drawn by the drag layer one pixel under my pointer, using the following solution inside `getStyles`, however it would be nice if this wasn't necessary:

```
getStyles() {
    const { currentOffset, initialClientOffset, initialSourceClientOffset } = this.props;

    if (!currentOffset || !initialClientOffset || !initialSourceClientOffset) {
      return {
        display: 'none',
      };
    }
    const { x, y } = currentOffset;
    const { y: yInitPointer } = initialClientOffset;
    const { y: yInitSource } = initialSourceClientOffset;

    return {
      transform: `translate(${x}px, ${y + (yInitPointer - yInitSource + 1)}px)`,
      position: 'absolute',
      width: '200px',
    };
  }
```

**Comment by darthtrevino** [comment]
So I'll need to know what version of React-DnD you're using, as well as your current OS and Browser. Could you put this into a test case repository I could clone?

**Comment by joaquindk** [comment]
Thanks @darthtrevino. 

React-Dnd: v. 3.0.2
OS: High Sierra (10.13.4)
Browser: Tried it on both Chrome 66 and Safari 11.1

I created a repo for reproducing the issue here: https://github.com/joaquindk/dnd-issue
There's also an explanatory video here: https://youtu.be/w672TAyaiIg

Thanks for the help!

**Comment by joaquindk** [comment]
Thanks for your quick feedback @darthtrevino . I see - let's hope it can get fixed. I can live with my little hack for now.

**Comment by MihirGH** [comment]
Hi, I am also facing the same issue. Here is the link to the codesandbox: https://codesandbox.io/s/awesome-currying-q646k?file=/src/components/Table.tsx 

Steps to reproduce in the codesandbox:
- Click on the button to enable custom drag layer
- Try dragging the first column cell and drop - hover/drop is not getting called and hence the rows are not getting swapped.

For me the solution above is also not working. Can someone please help?

**Comment by MihirGH** [comment]
Adding `pointer-events: none` in the preview that is rendered in my DragLayer solved this issue.
