### ISSUE TITLE
component.getDecoratedComponentInstance() not available at hover

### ISSUE THREAD

**Issue by oyshan** [react-dnd/react-dnd#1046]
Hi!

I've wrapped a component with both drag source and drop target decorators:
```
....

  render() {
    const {connectDroptarget, connectDragSource} = this.props
    return connectDropTarget(connectDragSource(
      <div
       My component...
      </div>
  }
}

export default connect(makeMapStateToProps, mapDispatchToProps)(
	injectSheetWithTheme(styles)(DropTarget(dropTargetTypes, dropTargetConf, dropTargetCollect)(DragSource(dragSourceType, dragSourceConf, dragSourceCollect)(MyComponent)))
)
```

In the hover method, I'm trying to access my decorated component using the `getDecoratedComponentInstance` method, however `component.getDecoratedComponentInstance` is undefined.

The `component` in the hover method is an instance of a `DragDropContainer`, and it does not have a method named `getDecoratedComponentInstance`.

Am I doing something wrong? How can I access my decorated component?

I'm using version ^2.6.0 + html5-backend

**Comment by amazingmarvin** [comment]
The problem is that you're using `connect` from `react-redux` as well (at least that's how it looks).  It uses its own method of "undecoration".  Here's the `undecorate` code I use in Amazing Marvin:

```javascript
/**
 * When using higher-order components, sometimes we still need to get to the
 * original component for calling instance methods.
 *
 * @param {React.Component} component - Possibly decorated component.
 * @returns {React.Component} The original component before decoration.
 */
export default function undecorate(component) {
  let curr = component;
  for (;;) {
    // react-dnd
    if (curr.getDecoratedComponentInstance) {
      curr = curr.getDecoratedComponentInstance();
      continue;
    }

    // react-redux when { withRef: true } is passed as 4th param to connect.
    if (curr.getWrappedInstance) {
      curr = curr.getWrappedInstance();
      continue;
    }

    break;
  }

  return curr;
}
```

**Comment by darthtrevino** [comment]
Thanks @amazingmarvin!

**Comment by oyshan** [comment]
Thanks, @amazingmarvin, but it din't seem to do the trick..

I changed `connect` to use `withRef`:
```
export const FormElementContainer = connect(makeMapStateToProps, mapDispatchToProps, null, { withRef: true })(
	injectSheetWithTheme(styles)(
		DropTarget(dropTargetTypes, dropTargetConf, dropTargetCollect)(
			DragSource(dragSourceType, dragSourceConf, dragSourceCollect)(
				FormElementContainerClass
			)
		)
	)
)
```

but the component in hover did not contain a `getWrappedInstance` method either.
I also tried removing the `injectSheetWithTheme` (i.e. a `react-jss`) decorator to see if that was causing the problem, but the component passed to `hover`was still the same: 

![image](https://user-images.githubusercontent.com/3329750/40823504-bfee5352-6570-11e8-984d-65c0924e61de.png)

**Comment by oyshan** [comment]
It seemed the order of wrapping/decorating was wrong. This works:
```
export const FormElementContainer =
	injectSheetWithTheme(styles)(
		DropTarget(dropTargetTypes, dropTargetConf, dropTargetCollect)(
			DragSource(dragSourceType, dragSourceConf, dragSourceCollect)(
				connect(makeMapStateToProps, mapDispatchToProps, null, { withRef: true })(
					FormElementContainerClass
				)
			)
		)
	)
```

But that means I can't access the props provided by redux's `connect` / `mapStateToProps` from the `hover` method, which is an even greater problem.. I guess I should try to find another way of doing this.

**Comment by oyshan** [comment]
Thanks, @amazingmarvin, that's absolutely an option! :)
