### ISSUE TITLE
Minification in webpack 4 seems to break something in React-DnD

### ISSUE THREAD

**Issue by jktravis** [react-dnd/react-dnd#1049]
**Describe the bug**
Receive the following error when `optimization.minimize` = `true` in Webpack 4. Disabling minification seems to work around the issue:

> Uncaught Error: Cannot call endDrag while not dragging

**To Reproduce**
https://github.com/jktravis/DnDWebpackMinificationIssue

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Both mac and windows - latest versions.
 - Browser Chrome (haven't tried others)
 - Version 66

**Additional context**

EDIT: Added link to repo.

**Comment by darthtrevino** [comment]
A test sandbox would be great. Our current testing method is manually verifying the examples, which are webpacked with webpack v4, but it's fairly brittle and webpack configs can be idiosyncratic.

**Comment by jktravis** [comment]
I finally made some time to create an isolated DnD app. I updated the original post with the link. I added a readme to it, but the gist is to try building with `webpack:prod` (the default on `start`), drag the list item around, and you should see the console error. Run the non minified version with `webpack:dev` (but keep the server running), and you should see log messages.

**Comment by jktravis** [comment]
I was just looking at this again after seeing R-DND has revved quite a bit since I posted this. My demo repo seems to be fixed now. Are you able to confirm that revving to at least 3.0.2 fixes it?

**Comment by jktravis** [comment]
Resolving this ticket since I believe the problem was resolved with work already completed.

**Comment by ViggoV** [comment]
I get an error (`When clientOffset is provided, getSourceClientOffset must be a function`) with React DnD v7.7.0 when using minification. However, the problem does not occur when the project in which i use React DnD is minified, but only when the project in which i use that project is being minified..

```
- MyParentProject (minification of this breaks DnD)
  - MyDnDModule (minification works fine)
    - react-dnd@7.7.0
```

Pretty weird
