### ISSUE TITLE
Uncaught ReferenceError: setImmediate is not defined at HandlerRegistryImpl.removeSource

### ISSUE THREAD

**Issue by atfzl** [react-dnd/react-dnd#1056]
**Describe the bug**
I am getting `setImmediate is not defined` when my app is hot reloaded.

**To Reproduce**
I am getting this error when my app was being hot reloaded.

**Expected behavior**
This error should not come.

**Screenshots**
No screenshots.

**Desktop (please complete the following information):**
 - OS: Mac os x 10.12.6
 - Browser chrome
 - Version 66.0.3359.181 (Official Build) (64-bit)

**Additional context**
Chrome does not support setImmediate so it is giving the error.
Seems like this PR added `setImmediate`: https://github.com/react-dnd/react-dnd/pull/1050
location: https://github.com/react-dnd/react-dnd/blob/master/packages/dnd-core/src/HandlerRegistryImpl.ts#L132

I tried polyfilling from https://github.com/YuzuJS/setImmediate and everything was working correctly.
So, i think we should use an alternative of setImmediate.

**Comment by darthtrevino** [comment]
TIL setImmediate is unofficial and not widely supported: https://caniuse.com/#feat=setimmediate.

I'll replace it today with either a lib or a `setTimeout` of 0 and cut a patch.
