### ISSUE TITLE
Duplicate backend error on version 4

### ISSUE THREAD

**Issue by wldcordeiro** [react-dnd/react-dnd#1058]
**Describe the bug**

Upgrading from v3 to v4 is producing errors and crashing my app saying that I can't have more than 1 DnD backend.

**To Reproduce**

Working on finding the steps but I think the problems comes from me making the component the provider is part of only render conditionally. What I think happens is that the DnD provider is getting mounted more than once, which I didn't have a problem with prior.

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: OS X
 - Browser Chrome/Firefox
 - Version: latest

**Additional context**

**Comment by darthtrevino** [comment]
Oh interesting - could you set up a test-case repo to demonstrate this? One thing I've been meaning to do is moving the flags about the HTML5Backend being installed from the window to the "backend context" object.

**Comment by wldcordeiro** [comment]
@darthtrevino do you have like a fixture or dummy project I can use for the test-case? It's always hard to make one that approximates the problem especially if it's possibly in the interactions of many moving parts. The hard part here is that the component tree looks like this, so there is react-router, react-redux, react-loadable all in the tree. From what I can tell it seems to be something to do with the `App` getting mounted more than once (maybe in very rapid succession). 

```jsx
// lite-loading.js
<GlobalErrorHandler>
  <loadables.Toaster />
  {!this.showApp() &&
    (loginStatusPending ? (
      <loadables.LoginPendingScreen />
    ) : (
      <loadables.LoadingScreen progress={appReadyPercent}>
        Loading...
      </loadables.LoadingScreen>
    ))}
  {this.showApp() && <loadables.App />}
  {!IS_LOCAL && <Pendo />}
</GlobalErrorHandler>

// app.js

<DragDropContextProvider backend={HTML5Backend}>
  <DialogProvider>
    <Navigation>
      <Switch>
        <Route exact path="/diagnostics" component={views.Diagnostics} />
      </Switch>
    </Navigation>
  </DialogProvider>
</DragDropContextProvider>

// and to make things more confusing the `App` component is exported wrapped in router and connect
const mapStateToProps = state => ({
	currentPortal: getCurrentPortal(state),
	lightboxes: getItemChildrenByType(
		state,
		getRootFolderId(state),
		itemTypes.LIGHTBOX
	),
})

const Connected = compose(
	withRouter,
	connect(mapStateToProps)
)(App)

Connected.displayName = 'App'

export default Connected
```
