### ISSUE TITLE
Unmounting drag source prevents endDrag from being invoked

### ISSUE THREAD

**Issue by glenn-allen** [react-dnd/react-dnd#1062]
In our app drag hovers can cause page navigations which result in the drag source being unmounted.

Unmounting the drag source causes the `SourceImpl.component` to become null, which prevents `spec.endDrag` from being invoked due to this commit:
[Turn the screws on the types a bit more](https://github.com/react-dnd/react-dnd/pull/1031/commits/2d33eab57615fc48fa2672ec29e0c4597581a7c1#diff-e2954799188c7c8ba3f29c0b8523dc11R107)

I'm hoping you will consider relaxing the type to allow null, so unmounted components can still handle drag ends.  We rely on this to perform moves of the dragged element to new pages.

Thanks

**Comment by tslocke** [comment]
@glenn-allen did you figure out a workaround?

**Comment by glenn-allen** [comment]
I've tested this and it seems to be working fine now, thanks heaps @darthtrevino!
