### ISSUE TITLE
tsconfig.json relative path problem

### ISSUE THREAD

**Issue by davidspiess** [react-dnd/react-dnd#1063]
After updating to v4.0.2 i get the following errors in VS Code.

![image](https://user-images.githubusercontent.com/992674/41028724-524f4258-697a-11e8-922b-d524f760ef66.png)

It seems react-dnd tries to extend my `tsconfig json`. 

```js
{
  "extends": "../../tsconfig.base.json",
  ...
}
```

I'm not sure why this is necessary. Furthermore my `tsconfig.json` resides in a subdirectory, so the path can't be resolved.

**Comment by darthtrevino** [comment]
We use that extends field to extend a common tsconfig in the dnd monorepo. This should probably be added to the .npmignore of the packages. I'll investigate what the best practice is here.

**Comment by PicusViridis** [comment]
Hello, I'm stille having this issue on version 9.4.0 of react-dnd-touch-backend

![image](https://user-images.githubusercontent.com/4224278/67140531-c6a29400-f25b-11e9-87e3-c5c82914f571.png)

Thanks
