### ISSUE TITLE
Element type is invalid

### ISSUE THREAD

**Issue by notbogdan** [react-dnd/react-dnd#1065]
**Describe the bug**
Unable to render a component wrapped with DragDropContext - getting an invalid element type error, asking me to check the render method of my wrapped component.

**To Reproduce**
Here is the code that leads to this error being thrown:

```javascript
class LayerContainer extends Component {
	constructor() {
		super();
	}
	render() {
		return (
			<div className="composerTimeline__layerContainer">
				{/* {this.props.children} */}
			</div>
		);
	}
}

export default DragDropContext(HTML5Backend)(LayerContainer);
```

```javascript
// We are in the middle of transitioning to React so we selectively inject components into the page
DOMAppend(
	<LayerContainer/>,
	this.layerContainerEl
);
```

```javascript
const DOMAppend = (component, el, cb) => {
	const wrapper = document.createElement(`div`);
	wrapper.classList.add(`js-react-wrapper`);
        // Render happens here
	ReactDOM.render(component, wrapper, () => {
		el.appendChild(wrapper);
		if (_.isFunction(cb)) {
			cb();
		}
	});
	return wrapper;
};
```

**Screenshots**
![image](https://user-images.githubusercontent.com/14274086/41051845-26bc9232-69af-11e8-9438-c7c6e282d9a9.png)

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser Chrome

**Additional context**
This is happening with React 16.4.0 & React-dnd 4.0.2

**Comment by notbogdan** [comment]
Ah looks like there was a either a version mismatch between `react` and `react-dom`, or `react-dom` was simply outdated - `react` was @ version 16.4.0 while `react-dom` was at version 16.0.0.

**Comment by dalbinaco** [comment]
@notbogdan Thanks! Upgrading `react-dom` to the same version as `react` solved it for me too.
