### ISSUE TITLE
The `Simple` Drag and Drop code Typescript example has decorator errors

### ISSUE THREAD

**Issue by damiangreen** [react-dnd/react-dnd#1071]
**Describe the bug**
The Simple Drag and Drop code example doesn't work

**To Reproduce**
1. Install latest ReactDnD
2. Include [Card.tsx](https://github.com/react-dnd/react-dnd/blob/master/packages/documentation/examples/04%20Sortable/Simple/Card.tsx) from the simple example in your solution

**Expected behavior**
No errors
The main errors:
`Unable to resolve signature of class decorator when called as an expression.
  Type 'DndComponentClass<CardProps>' is not assignable to type 'typeof Card'.
    Types of property 'propTypes' are incompatible.
      Type 'ValidationMap<CardProps>' is not assignable to type '{ connectDragSource: Validator<any>; connectDropTarget: Validator<any>; index: Validator<any>; is...'.
        Property 'connectDragSource' is optional in type 'ValidationMap<CardProps>' but required in type '{ connectDragSource: Validator<any>; connectDropTarget: Validator<any>; index: Validator<any>; is...'.`

```Unable to resolve signature of class decorator when called as an expression.
  Type 'DndComponentClass<CardProps>' is not assignable to type 'typeof Card'.
```

Other errors:
```Property 'index' does not exist on type 'Object'.```

Which I can mitigate by doing a cast:

 // tslint:disable-next-line:no-any
   ```const dragIndex = (monitor.getItem() as any).index;```

**Desktop (please complete the following information):**
 - OS: MacOS

 - Version 4.0.4

**Additional context**
@

**Comment by damiangreen** [comment]
Update, I can get the example working by removing the decorators:
```
import { compose } from 'ramda';
...
function collectDrop(connect: DropTargetConnector) {
  return {
    connectDropTarget: connect.dropTarget(),
  };
}

function collectDrag(connect: DragSourceConnector, monitor: DragSourceMonitor) {
  return {
    connectDragSource: connect.dragSource(),
    isDragging: monitor.isDragging(),
  };
}

export default compose(
  DragSource(ItemTypes.CARD, cardSource, collectDrag),
  DropTarget(ItemTypes.CARD, cardTarget, collectDrop),
)(Card);
```

**Comment by 311chaos** [comment]
Should the `simple` example shouldn't even contain TS?
