### ISSUE TITLE
Issue on build, import * as React is missing

### ISSUE THREAD

**Issue by abelkbil** [react-dnd/react-dnd#1075]
**Describe the bug**
edit 
```
import React from 'react';
chnaged to
import * as React from 'react';
```
on below files
DragDropContext.tsx and below
![image](https://user-images.githubusercontent.com/1478274/41275461-97c9d79e-6e3e-11e8-8974-9c42ba2bab0c.png)

**To Reproduce**
1. Build the application
2. See error

`node_modules/@types/react/index.d.ts (2236,19): Interface 'Element' cannot simultaneously extend types 'ReactElement<any>' and 'ReactElement<any>'. Named property 'type' of types 'ReactElement<any>' and 'ReactElement<any>' are not identical.`

**Expected behavior**
After adding react-dnd, application build successfully

**Desktop (please complete the following information):**
 - OS: Win 7
 - Browser : Chrome
 - Version : react-dnd@4.0.4

**Comment by abelkbil** [comment]
@darthtrevino Please create a pull request. I tried. Failed to create a pull

**Comment by darthtrevino** [comment]
I'm working on one, should be up today
