### ISSUE TITLE
v4.0.0 Breaks component lifecycles in app 

### ISSUE THREAD

**Issue by mattkrick** [react-dnd/react-dnd#1081]
**Describe the bug**
My app uses `componentDidMount` to measure an array of DOM elements. Those elements are wrapped in a `dragSource`
In v3.0.2, I could measure them in cDM. In v4.0.0, they all return 0s because they mount empty divs.
I dug through the diff and saw what I assume to be the offender: https://github.com/react-dnd/react-dnd/compare/v3.0.2...v4.0.0#diff-ac418ba19283aec1fb0b70e6570c5613R114

cDU is not a valid replacement for cWRP as it fires too late, although I'm not 100% sure that's the culprit. I'd like to pick your brain to see if you think something else may be the cause.
I know it isn't the HTML5 backend because i upgraded both & it was borked. I then removed the `DragSource` HOCs and it looked correct, so I'm relatively certain it's there in the `decorateHandler`

**To Reproduce**
i'll make a sample repo if needed, but should be pretty basic

**Expected behavior**
everything to work as it did in v3.0.2

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: ubuntu
 - Browser chrome
 - Version 66

**Comment by darthtrevino** [comment]
So I switched recently from using componentWillReceiveProps to componentDidUpdate to trigger changes in the decorateHandler - the reasoning being that componentWillReceiveProps is being deprecated. I'm open to ideas to fixing this - a sample repo would be great

**Comment by mattkrick** [comment]
the cleanest way is to probably write a static gDSFP and promote your instance objects like `handlerConnector` to the state so the static method can access them.

**Comment by UXDart** [comment]
I'm having this issue too... when using inside a virtualized List, sometimes the height of the virtual cell is zero... is there any workaround? if I remove the @DropSource it works perfectly... but without dnd :(
