### ISSUE TITLE
HTML5Backend should not have 'react' in peerDependencies either

### ISSUE THREAD

**Issue by cormacrelf** [react-dnd/react-dnd#1084]
I'm the author of [`angular-skyhook`](https://github.com/cormacrelf/angular-skyhook/), which invites users to install `react-dnd-html5-backend`. Installing it complains about a missing peer dependency `react@>= 16.3`.

As far as I can tell, the backend doesn't require React at all, and that is the reason why `angular-skyhook` exists. Could you leave that peer dependency for `react-dnd` to handle?

Tracking: https://github.com/cormacrelf/angular-skyhook/issues/1

**Comment by darthtrevino** [comment]
Yeah, that sounds reasonable. I'll put out a release today

**Comment by cormacrelf** [comment]
Thanks mate.

**Comment by darthtrevino** [comment]
got it, publishing now

**Comment by cormacrelf** [comment]
You are a machine. Cheers again.
