### ISSUE TITLE
Firefox hangs when dragging multiple files

### ISSUE THREAD

**Issue by djhi** [react-dnd/react-dnd#1090]
**Describe the bug**
Firefox hangs when dragging multiple files

**To Reproduce**
1. Go to http://react-dnd.github.io/react-dnd/examples-other-native-files.html
2. Drag multiple files (13 in my case, no problem with one)
3. Firefox hangs, notice you'll only get the dropping cursor after it recovers (the more files you drag the longer it hangs)

**Expected behavior**
Firefox to be as fast as chrome (haven't tested it on any other browser yet)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18
 - Browser Firefox
 - Version 60.0.2 (64 bits)

**Additional context**
It may very well be a bug in FF.

**Comment by renchap** [comment]
Is this similar to https://bugzilla.mozilla.org/show_bug.cgi?id=1449888 ?

**Comment by djhi** [comment]
It is indeed

**Comment by djhi** [comment]
Should we keep this one open ?

**Comment by renchap** [comment]
I dont think it is useful as it cant be fixed in react-dnd. If other people encounter this, they will now know where to check for status.
