### ISSUE TITLE
Decorators aren't ES7

### ISSUE THREAD

**Issue by noelebrun** [react-dnd/react-dnd#1092]
**Describe the bug**
In a few place in the documentation, you talk about the decorators as the ES7 syntax, but it isn't at all. ES7 (or ES2016) only contains two new features (Array.prototype.includes and the Exponentiation Operator). The decorators is only a proposals which is currently in Stage 2 on the ECMAScript Proposals process and we don't know when (and if) it will be in a final specification.

**To Reproduce**
1. Go to the documentation
2. Scroll down to 'What's It Look Like?'
4. See "ES7"

**Expected behavior**
It should probably be something like "Decorators proposal".

**Screenshots**
http://react-dnd.github.io/react-dnd/

**Comment by darthtrevino** [comment]
👍
