### ISSUE TITLE
[Question] Drag item must be a plain object - why?

### ISSUE THREAD

**Issue by jamiewinder** [react-dnd/react-dnd#1094]
Why does react-dnd require the drag item to be a plain object? I'm currently wrapping things like class instances in arbitrary objects, e.g.
```javascript
return {
    value: new MyDragItem(...)
};
```
... to get around this, but I'd like to understand why it's there in the first place.

**Comment by darthtrevino** [comment]
I'd have to dig around a bit to get you a conclusive answer, but I believe it has to do with serializability

**Comment by jamiewinder** [comment]
I've successfully attached functions to the drag item too. As far as I've been able to tell, I don't think there is any restriction on what the drag item contains so long as the root is a plain object.

I had a quick dig around myself after posting and as far as I can tell there no serialisation of the object involved unless perhaps this only happen in more exotic cases. 

As far as I can tell the restriction is arbitrary.

Thanks for your reply.

**Comment by jamiewinder** [comment]
Thanks for your reply. 

That seems incredibly limiting to me. Beyond the scenario raised in this issue - i.e. using class instances - I've also used plain drag objects which just happen to include functions that the drop target can call. I highly doubt I'm the only one.
