### ISSUE TITLE
TypeError: React.createContext is not a function

### ISSUE THREAD

**Issue by rubayethossain** [react-dnd/react-dnd#1101]
I am getting a TypeError: React.createContext is not a function when trying to add DragDropContext to component. I am using React v15.6.1 and I am wondering if it's required to use React v16 to use react-dnd since Context introduced in React v16. 

Here is my component where I am trying to add DragDropContext. 

```js
import React, {Component} from 'react';
import FormSpace from './FormSpace';
import TextItem from './TextItem';
import HTML5Backend from 'react-dnd-html5-backend';
import { DragDropContext } from 'react-dnd';


class AdvancedFormRnd extends Component {
    render() {
        return (
            <div className="container">
                <div className="row">
                    <div className="col-sm-8">
                        <FormSpace/>
                    </div>
                    <div className="col-sm-4">
                        <TextItem/>
                    </div>
                </div>
            </div>
        )

    }
}
export default DragDropContext(HTML5Backend)(AdvancedFormRnd);
```

``<TextItem/>`` is the component which I want to make Draggable and ``<FormSpace/>`` is Droppable component.

This happens if I just import DragDropContext from react-dnd.

**Comment by Mangaraju-Velpula** [comment]
Update react version to 16

**Comment by rubayethossain** [comment]
Thanks @Mangaraju-Velpula. I forgot to check the changelog. Now it's clear. Is there any separate documentation for version 3.0.2 or the current documentation is okay with version 3.0.2?

**Comment by Mangaraju-Velpula** [comment]
Current documentation is enough.
