### ISSUE TITLE
React-DND trigger mouse events after state changes

### ISSUE THREAD

**Issue by kjgraham** [react-dnd/react-dnd#1102]
I am building a simple script to let someone sort a list of items using Drag & Drop. The items successfully sort, but after the drag operation has ended, it triggers the onMouseEnter events of the item that took its original place.

![ReactDnD Issue](https://i.imgur.com/0Pal8p8.gif)

Here's some simple code to replicate: https://codesandbox.io/s/m33o3x610p

Is this a bug in React-DnD? Does React-DND trigger mouse events after state changes?

Browser: chrome

**Additional context**
I am able to bypass it by conditionally delaying the onMouseEnter event, but this is obviously poor practice.

**Comment by kjgraham** [comment]
bump :)

**Comment by msadahiro** [comment]
I am running into the same issue as well!

**Comment by umair-khanzada** [comment]
Had anyone solved this? I am running into the same issue.

**Comment by ksolov** [comment]
I have the same problem.
