### ISSUE TITLE
Not ideal user experiences on iPad

### ISSUE THREAD

**Issue by jingzhaoou** [react-dnd/react-dnd#1104]
React-DnD works great on a PC. However, I notice that on iPad, in order to drag a source, I need to touch and hold a small amount of time before I can drag it. Possible to start dragging immediately without the intermediate quick hold? Is it an issue with touch event handling? Any help would be highly appreciated.

**Comment by jingzhaoou** [comment]
I noticed the following note:

`For touch support, use React DnD with the touch backend instead of the HTML5 backend.`

I will put in code to detect if user is on an iPad or not. If yes, switch to use the touch backend. Hope that touch devices can be officially supported by React DnD at some point.

**Comment by froatsnook** [comment]
You're experiencing the new native D&D that Apple put in iOS 11.  Since it's the standard behavior, users will expect to have to hold for a moment before they can drag!  The touch backend, in my experience, gives a much worse user experience, and it makes scrolling a challenge.

**Comment by jingzhaoou** [comment]
@froatsnook Have not tried the touch backend yet. But really appreciate the heads-up. The HTML5 backend is acceptable at this moment. In that case, I will stay with the official backend then.

**Comment by froatsnook** [comment]
@jingzhaoou 👍

But do keep in mind that (so far) it's only iOS 11 that implements a touch HTML5 d&d (as far as I know).  If you're also targeting android or ios<11 then you might want to have an option to active the touch backend (that's what I do in my app!).
