### ISSUE TITLE
Website doesn't work in Opera 54.0

### ISSUE THREAD

**Issue by DieLaughing** [react-dnd/react-dnd#1107]
The project website doesn't display correctly

To reproduce the behavior:
1. Open http://react-dnd.github.io/react-dnd in a new window using the latest Opera
2. Observe the horror

This means I cannot click on those handy little example that show the difference between ES7 and ES6 and ES5.

**Comment by froatsnook** [comment]
Works for me in opera 56 (I'm on the developer stream).  Is it possible you have javascript disabled?  Do you see any network errors?

**Comment by DieLaughing** [comment]
The css is not loading. I am not immediately clear on how JavaScript being disabled would affect this...

**Comment by froatsnook** [comment]
The CSS is loaded by javascript on the github.io page.

**Comment by towfiqi** [comment]
The css is not loading for Chrome Latest too.. Site looks completely broken. Very hard to navigate... :disappointed:

**Comment by DieLaughing** [comment]
Discovered a rogue extension bug was causing this.
