### ISSUE TITLE
Examples in ES6

### ISSUE THREAD

**Issue by DieLaughing** [react-dnd/react-dnd#1108]
Would it be so hard to have the examples in ES6? Please.

**Comment by soupette** [comment]
@DieLaughing you should checkout the [v2.6.0 tag](https://github.com/react-dnd/react-dnd/tree/v2.6.0)

**Comment by DieLaughing** [comment]
I clicked the link. It was not informative. What were you trying to show me?

**Comment by soupette** [comment]
@DieLaughing Here's what [you're looking for](https://github.com/react-dnd/react-dnd/blob/v2.6.0/packages/documentation/examples/04%20Sortable/Cancel%20on%20Drop%20Outside/Container.js)

**Comment by DieLaughing** [comment]
Thank you. :)

**Comment by DieLaughing** [comment]
Yeah, that's not ES6.

That's the same #$%* thing I was complaining about. No decorators, or any of that ES7 bull.

**Comment by DieLaughing** [comment]
EXAMPLES.
IN.
ES6.

**Comment by DieLaughing** [comment]
ES6 is deprecated. Got it.

**Comment by camdagr8** [comment]
I feel the same way
