### ISSUE TITLE
[TypeScript] DragSource component return type expects unneeded props

### ISSUE THREAD

**Issue by dylanpyle** [react-dnd/react-dnd#1109]
**Describe the bug**

When a component is wrapped in `DragSource`, the return value is a component that expects props to be passed in from a parent, but still expects the props that DragSource is providing itself.

**To Reproduce**

Simple example:

```tsx
import * as React from 'react';
import * as ReactDOM from 'react-dom';
import { ConnectDragSource, DragSource, DragSourceConnector } from 'react-dnd';

interface OwnProps { name: string; }
interface DragProps { connectDragSource: ConnectDragSource; }

type AllProps = OwnProps & DragProps;

class Foo extends React.Component<AllProps> {
  public render(): JSX.Element {
    return this.props.connectDragSource(
      <div>{this.props.name}</div>
    );
  }
}

function mapDragProps(connect: DragSourceConnector): DragProps {
  return { connectDragSource: connect.dragSource() };
}

const source = {
  beginDrag(props: AllProps): { name: string } {
    return { name: props.name };
  }
};

const DraggableFoo = DragSource('FOO', source, mapDragProps)(Foo);

ReactDOM.render(<DraggableFoo name='dylan' />, document.body);
```

**Expected behavior**

Code compiles

**Actual behavior**

```
Type '{ name: string; }' is not assignable to type '(IntrinsicAttributes & IntrinsicClassAttributes<Foo> & Readonly<{ children?: ReactNode; }> & Read...'.
  Type '{ name: string; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<AllProps, ComponentState, any>> & Readon...'.
    Type '{ name: string; }' is not assignable to type 'Readonly<AllProps>'.
      Property 'connectDragSource' is missing in type '{ name: string; }'.
```

I also tried changing the 2nd-to-last line to:

```tsx
const DraggableFoo = DragSource('FOO', source, mapDragProps)(Foo) as React.ComponentClass<OwnProps>;
```

— which fixes the rendering props issue but fails at coercing:

```
Type 'typeof Foo & DndComponentClass<AllProps>' cannot be converted to type 'ComponentClass<OwnProps>'.
  Types of parameters 'props' and 'props' are incompatible.
    Type 'OwnProps' is not comparable to type 'Readonly<AllProps>'.
      Property 'connectDragSource' is missing in type 'OwnProps'.
```

**Desktop:**

 - OS: macOS
 - Version: react 16.4.1, react-dnd 5.0.0

**Comment by c16192** [comment]
I was having the same issue earlier. Turns out that I was typing the source wrong. 

In your code you should type props as OwnProps instead of AllProps.
`
const source = {
  beginDrag(props: OwnProps): { name: string } {
    return { name: props.name };
  }
};`

**Comment by dylanpyle** [comment]
@c16192 Nice, thanks!

**Comment by dylanpyle** [comment]
@c16192 Whoops, spoke too soon. This doesn't solve it for me. When I change the `beginDrag` line to use OwnProps, I get the following error:

```
Argument of type 'typeof Foo' is not assignable to parameter of type 'ComponentClass<OwnProps>'.
  Types of parameters 'props' and 'props' are incompatible.
    Type 'OwnProps' is not assignable to type 'Readonly<AllProps>'.
      Property 'connectDragSource' is missing in type 'OwnProps'.
```

I might be missing something obvious here...

**Comment by dylanpyle** [comment]
@schneidmaster Which version are you on? I didn't realize that was generic, so I think you're onto something here, but I'm getting `Expected 5 type arguments, but got 1.` on `react-dnd@4.0.5`.

**Comment by schneidmaster** [comment]
Ah, I'm on `react-dnd@5.0.0`. Not sure offhand what the type signature looks like on 4.

**Comment by dylanpyle** [comment]
Cool, yep, confirmed that that does work on 5.0.0, but has caused some other errors. Will try and get a reproducible example. Thank you!

**Comment by sebastian-lenz** [comment]
I stumbled upon the same problem. Looking at `DragSource.d.ts` I actually don't understand why both the argument and return type use the same probs. The argument should consume the collected probs next to the external probs?

This is the current definition from https://github.com/react-dnd/react-dnd/blob/master/packages/react-dnd/src/DragSource.ts#L79:
```
return function decorateSource<
  TargetClass extends
    | React.ComponentClass<Props>
    | React.StatelessComponent<Props>
>(DecoratedComponent: TargetClass): TargetClass & DndComponentClass<Props>
```

I think it should read something like this:
```
return function decorateSource(
  DecoratedComponent: React.ComponentType<Props & CollectedProps>
): React.ComponentType<Props> & DndComponentClass<Props>
```

`React.ComponentType` is just  a shorthand for `React.ComponentClass<Props> | React.StatelessComponent<Props>`. The important bit is appending `CollectedProps` to the props of the argument.

**Comment by jeanfortheweb** [comment]
@sebastian-lenz it totally right. Was just here to open a PR myself but checked the tickets before. Would you mind open a PR for this? Same for DropTarget of course.

**Comment by darthtrevino** [comment]
The typings should be much better in 7.4
