### ISSUE TITLE
isOver() flickers when DropTarget's type is defined as a function returning array

### ISSUE THREAD

**Issue by Samarkin** [react-dnd/react-dnd#1110]
**Description**
`monitor.isOver()` sometimes returns `false` right after the drop target props are updated, but only when `DropTarget`'s type is defined as a function returning an array.

**Example**
1. https://jsfiddle.net/69z2wepo/219863/
2. Try dragging any of the gray boxes onto the yellow box
3. See the yellow box flickering
4. Change line 50 to line 46, 47, or 48
5. Try again and see that the flickering is fixed

**Expected behavior**
Expected consistent behavior regardless of how the type is defined (as a function, an array, or the function returning an array).

**Screenshot**
![screencast](https://user-images.githubusercontent.com/432685/42981456-09e0b6c6-8b91-11e8-8247-a515622b0482.gif)

**Environment**
 - Desktop/macOS 10.13.5/Safari 11.1.1
 - Raspberry Pi/Raspbian 8.0/Chromium 56.0.2924.84
 - iPad/iOS 11.4.1/Safari (with [yahoo/react-dnd-touch-backend](/yahoo/react-dnd-touch-backend))

**Note**
The issue is not just visual – sometimes it prevents the drop from being registered.

**Comment by bhollis** [comment]
I'm seeing something similar that's causing `isOver` to be unreliable for detecting hover states.
