### ISSUE TITLE
React < 16.3 graceful degradation ("TypeError: createContext is not a function")

### ISSUE THREAD

**Issue by catamphetamine** [react-dnd/react-dnd#1113]
`TypeError: u.createContext is not a function`

In `DragDropContext`:
https://github.com/react-dnd/react-dnd/blob/master/packages/react-dnd/src/DragDropContext.tsx

```js
/**
 * Create the React Context
 */
export const { Consumer, Provider } = React.createContext<DragDropContext<any>>(
	{ dragDropManager: undefined },
)
```

This breaks React < 16.3 because there's no `React.createContext` function there.
Instead, use `create-react-context` polyfill:
https://github.com/jamiebuilds/create-react-context

For example, consider [a component library](https://github.com/catamphetamine/react-responsive-ui) using `react-dnd` for a single one of its components.
Because you're calling `React.createContext` in the root it breaks the whole library already at the `import` stage just because this particular drag'n'drop component requires React >= 16.3 while others can get away with React 0.14, so the whole library becomes unusable because there's only a single `index.js` file exporting all components.

**Comment by garygao12580** [comment]
Did you resolve this problem? I have also met this.
