### ISSUE TITLE
React drag and drop on demo doesn't work on Safari on iPad

### ISSUE THREAD

**Issue by mohamed-ahmed** [react-dnd/react-dnd#1114]
**React drag and drop on demo doesn't work on Safari on iPad**

**To Reproduce**
1. Go to https://react-dnd.github.io/react-dnd/examples-sortable-simple.html in Safari on iPad OSX V11.4
2. Click, hold, and drag a list item
4. See that item drag preview is significantly offset from cursor position

**Expected behavior**
Item drag preview should be near cursor

**Screenshots**
![ipad_dnd](https://user-images.githubusercontent.com/1468166/43608807-239256c6-9670-11e8-99d9-071fb3e28d1a.gif)

**Desktop (please complete the following information):**

**Additional context**

**Comment by DieLaughing** [comment]
The sortable examples are the most garbage examples I've ever used. Good luck getting any response. The maintainers don't seem to care much about providing robust working examples.

**Comment by blaues0cke** [comment]
To complete this: This not working on the iPad since in https://react-dnd.github.io/react-dnd/examples/sortable/simple the html5Backend is used. When you use the TouchBackend (http://react-dnd.github.io/react-dnd/docs/backends/touch) it should work well.
