### ISSUE TITLE
Disabling React-DnD for a specific DOM-subtree

### ISSUE THREAD

**Issue by havardge** [react-dnd/react-dnd#1115]
**Background**
I'm working on a webapp with react-dnd. The whole app is wrapped in the `DragDropContext` with an `HTML5Backend`.

The app has an editor where you can edit a nested structure of `DragSource`s and `DropTarget`s (some are widgets some are structural elements). E.g. I can drag an image into a column and so on. 

**The issue**
Now, I have made a very basic implementation of `<div contentEditable>`, let's call it `RichTextWidget` (similar to that of _DraftJS_ and _SlateJS_ which consumes all the events to properly control the state of the component).

The goal is to be able to drag a widget onto the `RichTextWidget`, and insert the widget at the cursor (caret) location. You probably are familiar with this functionality from _Microsoft Word_ or _Google Docs_ in which the cursor moves around in the document as you drag / hover over the document before dropping the element.

The thing is, this works as intended when `RichTextWidget` lives **outside** the `DragDropContext`. I can mark some text or an image, and move it around within the `RichTextWidget`. However, when the `RichTextWidget` lives **inside** the `DragDropContext` react-dnd seems to override the default behaviour of the `RichTextWidget` (the `<div contentEditable>`); It's consuming all the drag events and is only looking for DropTargets right? 

So what I think I need to do is; disable react-dnd for that specific DropTarget interaction, and let `RichTextWidget` consume those events.

I haven't found any discussions / documentation regarding this special case. Maybe it's easy to do, and I just overlooked something. 

Any advise would be highly appreciated.

P.S. Thanks for a great library!

**Comment by willadamskeane** [comment]
Seconding this, I'm running into the same issue.

**Comment by 0nn0** [comment]
@havardge Hi, did you manage to find a solution? Running into the same issue here...
