### ISSUE TITLE
why i can't get offset coordinate in endDrag

### ISSUE THREAD

**Issue by garygao12580** [react-dnd/react-dnd#1116]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
I want to return last coordinate when i end drag, so i can do something with it

**Describe alternatives you've considered**

**Additional context**

**Comment by garygao12580** [comment]
I just want to get last coordinate when i end drag, but return null now.

**Comment by guchengjie** [comment]
me too,
![1](https://user-images.githubusercontent.com/25757620/44143012-a400d67c-a0b4-11e8-841f-e59fa96f2b7c.png)
The API provided by monitor can not be used.

**Comment by guchengjie** [comment]
// You can access the coordinates if you need them
    const clientOffset = monitor.getClientOffset();
I'm find api.

**Comment by garygao12580** [comment]
@guchengjie yes, great! we can't get the offset in end drag's monitor, we should pass it from drop method  in  drop target ,and get it by monitor.getDropResult().
code like below:
in drop target:
`drop(props, monitor){
    return {
      clientOffset: monitor.getClientOffset(),
    }
  }`

in drag source taregt
`endDrag(props, monitor) {
    const dropTarget = monitor.getDropResult();
    let clientOffset = null;
    if(dropTarget){
      clientOffset = dropTarget.clientOffset;
    }
  },`

**Comment by Andsbf** [comment]
apparently when the dragSource is dropped in a dropTarget, the `monitor. getClientOffset` is only available/readable  at the `drop()` method. 🤔

**Comment by GriboryBogush** [comment]
@guchengjie
Thank you! I was looking for that kind of solution
