### ISSUE TITLE
limit dragging at the specific box (similar to jquery containment)

### ISSUE THREAD

**Issue by nikolakrivokapic** [react-dnd/react-dnd#1117]
Is there native way to implement dragging limitation on specific area similar to jquery containment? check this example http://jsfiddle.net/Rino_Raj/9dx1cxu8/3/
there is also 'bounds' option in react-draggable library for achieving this.
I didn't find any examples with react-dnd to achieve this functionality, is there a native way or we have to find custom solution, any ideas? 
Edit: I have achieved this with custom drag layer and calculating it's position thus preventing drag outside specified offsets, but still would be great if there is a native way.

**Comment by yash2code** [comment]
@nikolakrivokapic  can you pl tell how dod you solved it ?
