### ISSUE TITLE
Add access to dropEffect for dropTarget

### ISSUE THREAD

**Issue by user1736** [react-dnd/react-dnd#1125]
Hi there!

**Is your feature request related to a problem? Please describe.**
I'd like to have an access to the current drop effect in `canDrop` method within `dropTarget` decorator spec, so I could disable/enable drop targets according to current effect.

**Describe the solution you'd like**
I think it'll be nice to have an access to `dropEffect` from `monitor`. I prepared draft solution for version 3.0.2 [here](https://github.com/user1736/react-dnd/pull/1) and don't mind adding this feature to newer versions of the library if needed.

It might be useful in https://github.com/react-dnd/react-dnd/issues/974 as well

**Comment by user1736** [comment]
Up! Any comments on that? At least could you please triage it.

**Comment by willurmston** [comment]
This feature would be super helpful to me. I need to know if the dropped item was moved or copied from within the DropTarget, but from what I've read, you can only access the dropEffect in the DragSource. I have many DropTargets that all lead to different places, so I prefer to handle the onDrop logic in the DropTarget. Maybe I'm using the library incorrectly, but this seems like a valid use case.
