### ISSUE TITLE
Nested drop targets

### ISSUE THREAD

**Issue by eliucs** [react-dnd/react-dnd#1126]
How would we implement nested drop targets where:
- The parent containers can be drag and dropped
- Inside the parent containers are elements that can be drag and dropped within the parent container

<img width="304" alt="screen shot 2018-08-29 at 10 45 49 am" src="https://user-images.githubusercontent.com/20590875/44795459-bb346b00-ab78-11e8-95f8-fb9bb9344fb7.png">

**Comment by eliucs** [comment]
I fixed this by just specifying types accepted for each drop target. Please close this issue, thank you!

**Comment by pingbaohua** [comment]
您好，我这个目标参数type怎么来判断呢，最近遇到这个问题了

**Comment by pingbaohua** [comment]
就是一个目标源，想要放置在嵌套的droptarget上面
