### ISSUE TITLE
Uncaught Error: Expected to find a valid target.

### ISSUE THREAD

**Issue by leantide** [react-dnd/react-dnd#1127]
**Describe the bug**
Uncaught Error: Expected to find a valid target. 
Similar to https://github.com/react-dnd/react-dnd/issues/361, but in a different scenario.

I am using nested sources and targets. I have a list of items (each item being both a drag source and a drag target of type 'item'), with each item having a number of subitems (each subitem being both a drag source and a drag target of type 'subitem'). 

When swapping a dragged subitem with a hovered subitem within the **_same_** item, everything works as expected.

**To Reproduce**
When swapping a dragged subitem with a hovered subitem of a **_different_** item, the following error occurs:

Uncaught Error: Expected to find a valid target.
    at invariant (browser.js:38)
    at DragDropMonitorImpl../node_modules/dnd-core/lib/DragDropMonitorImpl.js.DragDropMonitorImpl.canDropOnTarget (DragDropMonitorImpl.js:60)
    at HTML5Backend.js:428
    at Array.some (<anonymous>)
    at HTML5Backend../node_modules/react-dnd-html5-backend/lib/HTML5Backend.js.HTML5Backend.handleTopDragOver (HTML5Backend.js:427)

**Expected behavior**
The swap occurs without the error.

**Desktop:**
 - OS: macOS High Sierra @ 10.13.5
 - Browser: Chrome @ 68.0.3440.106 (Official Build) (64-bit)
 - react@16.4.2
 - react-dnd@5.0.0
 - react-dnd-html5-backend@5.0.1

**Comment by pingbaohua** [comment]
您好，我正在实现这样一个效果：将左侧的项目列表拖拽到右侧内容区后，可以再从左侧拖拽到刚才的div上，嵌套这样子的，但是报错了，x这样的错误，感觉和您的类似，请教一下怎么实现

**Comment by ad1992** [comment]
this happens for me as well +1

**Comment by pixelass** [comment]
I can reproduce this on a setup like this:

```jsx
@DropTarget(
	(props: DroppableProps) => props.accepts,
	{},
	(connect: DropTargetConnector, monitor: DropTargetMonitor) => ({
		connectDropTarget: connect.dropTarget()
	})
)
class Dustbin extends React.Component<DroppableProps> {
	public render() {
		return this.props.connectDropTarget && this.props.connectDropTarget(<div>{this.props.children}</div>);
	}
}
```

In my case the error occurs in the following line:

```jsx
//	(props: DroppableProps) => props.accepts,
```

When I changed the code to anything but a function the error went away.


**NO ERRORS** 

```jsx
@DropTarget(
	["list", "of", "accepted", "types"],
	{},
	(connect: DropTargetConnector, monitor: DropTargetMonitor) => ({
		connectDropTarget: connect.dropTarget()
	})
)
```

**NO ERRORS** 

```jsx
@DropTarget(
	"my accepted type",
	{},
	(connect: DropTargetConnector, monitor: DropTargetMonitor) => ({
		connectDropTarget: connect.dropTarget()
	})
)
```


Sidenote: 

The OP's error occurs while the `hover` method is active.

I get a different error when I perform the same action on `drop`

```
dragDrop.js:125 
Uncaught TypeError: Cannot read property 'drop' of undefined
    at dragDrop.js:125
    at Array.forEach (<anonymous>)
    at DragDropManagerImpl.drop (dragDrop.js:123)
    at Object.drop (DragDropManagerImpl.js:40)
    at HTML5Backend../node_modules/react-dnd-html5-backend/lib/HTML5Backend.js.HTML5Backend.handleTopDrop (HTML5Backend.js:477)
(anonymous) @ dragDrop.js:125
drop @ dragDrop.js:123
(anonymous) @ DragDropManagerImpl.js:40
./node_modules/react-dnd-html5-backend/lib/HTML5Backend.js.HTML5Backend.handleTopDrop @ HTML5Backend.js:477
```

**Comment by butchmarshall** [comment]
Started getting this error after upgrading a project from v2.5.4 to v6.0.0.

Not sure if there is no issue on v2.5.4 or if its just not being reported.

**Comment by realb0t** [comment]
+1

**Comment by NZOleg** [comment]
+1

**Comment by maciejzukowski** [comment]
The issue was resolved for me by making sure the target was still in the DOM.  I had some conditional case that removed the target when the source was dragged into it causing this error to occur.

**Comment by bexoss** [comment]
+1, How do I avoid this error?

**Comment by gaoupon** [comment]
make sure your the `key` of your item unrelated to the `index` to prevent the dom node being removed.

**Comment by GNARGNARDAVE** [comment]
I added a debounce to the hover handler (with trailing option) and that solved the issue. The components were updating too quickly by setting the state before DnD could catch up, and the target ID had changed by the time the user dropped the item. So for those of you that could get the above solutions to work, maybe this may help.

**Comment by anatoljevich** [comment]
> I added a debounce to the hover handler (with trailing option) and that solved the issue. The components were updating too quickly by setting the state before DnD could catch up, and the target ID had changed by the time the user dropped the item. So for those of you that could get the above solutions to work, maybe this may help.

How did you do that?

**Comment by benjamincassidy** [comment]
@GNARGNARDAVE can you please provide sample code for how to add a debounce to the hover handler?

**Comment by GNARGNARDAVE** [comment]
This is what I used and it worked for me.  You should  add a  console output to observe the target id as you  hover the item - and you'll notice that the  target id changed/doesn't sync because everything  is happening too quick; try adding it before and after to see the result.

onDragOver={handleDragOver}

`
let debouncedFn:any = null;

const handleDragOver = (e:any):void => {
        e.persist();
        e.preventDefault();

        if (!isDraggable) {
            return;
        }

        if (!debouncedFn) {
            debouncedFn = debounce(()=> {
                e.dataTransfer.dropEffect = "move";
                const parentId = (e.target.parentNode) ? e.target.parentNode[keyId] : "";
                const targetId = e.target[keyId] || parentId; // items can be dropped on a child
                const hoverIndex = (targetId) ? state.data.findIndex((item:any) => item[keyId].toString() === targetId.toString()) : -1;

                if (hoverIndex !== state.hoverIndex) {
                    setState((prevState: IState<ITableData>) => ({
                        ...prevState,
                        hoverIndex,
                    }));
                }
            }, 100);
        }

        debouncedFn();
    };
`

**Comment by murongqimiao** [comment]
I have the same problem and fix it by this way。
```
//before 
moveItem(dragIndex, hoverIndex);
item.index = hoverIndex;
```

```
const [, drop] = useDrop({
      accept: ItemType,
      hover(item, monitor) {
        const dragIndex = item.index;
        const hoverIndex = index;

        if (dragIndex === hoverIndex) {
          return;
        }
        item.index = hoverIndex;
        setTimeout(() => {
          // 不可以同步进行, 这样会导致dnd报错, 要异步的去更新数组
          moveItem(dragIndex, hoverIndex);
        }, 0);
      }
    })
```

don`t believe in chat GPT ~ give code 1 second , debug half hours .
