### ISSUE TITLE
Can not drop on monitor screen in IE 11

### ISSUE THREAD

**Issue by hanphan2706** [react-dnd/react-dnd#1135]
**Describe the bug**
I have 1 lap and 1 monitor. I choose 'extend' display mode. Then I open IE browser on monitor screen. I can drag something, but nothing happened after drop.

When I choose 'duplicate' display mode. Now I can drop and drag everything.

My IE browser is 11.192.16299.0. I tried on another version (11.165) and I could drop.

**To Reproduce**
1. Choose 'extend' display mode on windows 10.
2. Open IE browser on monitor screen (IE Version 11.192.16299.0)
3. Go to https://react-dnd.github.io/react-dnd/examples-chessboard-tutorial-app.html
4. Try to drag and drop anything

**Expected behavior**
after dropping, something will happend

**Desktop (please complete the following information):**
 - Windows 10
 - IE
 - Version 11.192.16299.0

**Additional context**
If it can't be fix. please let know the root cause.

**Comment by louisnguyen1012** [comment]
It cannot endDrag in this case.
