### ISSUE TITLE
canDrop get current target stack/state data.

### ISSUE THREAD

**Issue by mikpalm** [react-dnd/react-dnd#1136]
So I guess Im doing stuff wrong here. 

I have multiple DragSources, and DropTargets (with DragLayer).
Each DropTarget can hold every DragSources (same ItemType). This works really good. 

But I would like to be able to say hey there are already one apple added to this bin and show that already on dragging (red bg on target).
Sure I can check this on drop() and just ignore it. But what I would like to do is when you start to drag that apple set canDrop to false on the bags that already have an apple added.
To only show avail bags to drop it into.
So lets say unlimited of apples and bananas, 10 bags but only one apple and one banana in each.

What Im doing right now is on drop() I run a set state on my component that then renders the dropped item in the bag.

```
const dropTarget = {
  canDrop(props, monitor) {
    // props returns {}
    const item = monitor.getItem();
    return true; //I Want to check the condition if this DropTarget already have for 1 banana added then return false. All of my DragSources have ids and props so I get that data here from item. But no access to my current droptarget.
  },....
```

on drop() Im doing this.

```
handleDrop(item){
	let all = this.state.all;
	if(!_.includes(this.state.all,{id: item.id})){
		all.push(item);
		this.setState({
			all:all,
		})
	}
}
```
How would I solve this issue and what am I missing. my canDrop(props, monitor) func the props is always blank. And the store saved on monitor is of my DragSource as far as I can tell?
Best regards 
Mikael

**Comment by mikpalm** [comment]
My bad, Solved it.

**Comment by blaues0cke** [comment]
@mikpalm Would be always great to know how you solved you problem! :-)

**Comment by mikpalm** [comment]
@blaues0cke this issue was an error created by my own wrong thinking. And this issue/ticket should be removed.
