### ISSUE TITLE
Upgrading from 2.x to 3.x, 4.x, 5.x export issue.

### ISSUE THREAD

**Issue by hatched** [react-dnd/react-dnd#1138]
When using: 
```
react@16.5.2
react-dom@16.5.2
react-dnd@2.6.0
```
everything works as expected however when upgrading to: 
```
react-dnd@3.0.2 
react-dnd-html5-backend@3.0.2
``` 
I get the following error:

```
Uncaught TypeError: createBackend is not a function
```
The line that seems to trigger the error is
```JS
const ReactDnDHTML5Backend = require('react-dnd-html5-backend');
...
module.exports = ReactDnD.DragDropContext(ReactDnDHTML5Backend)(MachineView);
```

The same occurs when upgrading to the 4.x and 5.x series.

The workaround is to pass `default` on the ReactDnDHTML5Backend.
```JS
module.exports = ReactDnD.DragDropContext(ReactDnDHTML5Backend.default)(MachineView);
```

This code is bundled using browserify so that may be causing issues with the exports or it's simply a documentation issue with the ES6/5 examples.

**Comment by Jorenm** [comment]
Looks like they changed the export type of react-dnd-html5-backend to default, so you want to import it like this:

import HTML5Backend from "react-dnd-html5-backend"

**Comment by hatched** [comment]
Yeah and that's totally fine, but without an additional transpilation step using the ES5 examples then need a small update to add that `.default`

**Comment by darthtrevino** [comment]
Correct, we're using a default export, and the ES5 examples have been removed from the documentation.
