### ISSUE TITLE
cannot assign to read only property 'left' of object '#<Object>'

### ISSUE THREAD

**Issue by skirankumar7** [react-dnd/react-dnd#1140]
**_I got this error when update react 15.4 to 16.0 while dragging the card from one place to another I got this error please help me with this._**

** Error is **
**TypeError: Cannot assign to read only property 'left' of object '#<Object>'**
{"componentStack":"\n in CustomDragLayer (created by DragLayer(CustomDragLayer))\n in **

**Expected behavior**
Expected to work property instead of drag stop and error coming.

**Desktop (please complete the following information):**
 - OS: [e.g. windows]
 - Browser [chrome ]

**Comment by Mangaraju-V** [comment]
@skirankumar7 did you managed to solve it?

**Comment by sahilsakhiya11** [comment]
I am having the same issue now, I am using react dnd for table functionality

**Comment by rafaRth1** [comment]
> 

asdasd

**Comment by rafaRth1** [comment]
@sahilsakhiya11 did you manage to solve it? with redux and react dnd
