### ISSUE TITLE
[Question] a lot of `@DragSource` elements

### ISSUE THREAD

**Issue by valjusha** [react-dnd/react-dnd#1141]
Can you perform fast work `React-dnd`, if on page 100 + DragSource?
I want to make a map and display a lot of svg elements.
And for everyone hangs a DragSource from `React-dnd`.
Is this a good idea?

**Comment by pd4d10** [comment]
This demo may be helpful:
http://react-dnd.github.io/react-dnd/examples/sortable/stress-test
