### ISSUE TITLE
Children of drop target receive componentDidMount after parent

### ISSUE THREAD

**Issue by tslocke** [react-dnd/react-dnd#1146]
Normal React semantics is for child components to have `componentDidMount` called before parents. Since adding react-dnd I'm seeing components inside a `DropTarget` get this callback *after* parent components. I'm guessing there children are not rendered at all initially, and then added on a subsequent render?

Is this expected behaviour? Is there any way to be notified when the component is fully mounted, with all its children in place?

Thanks

**Comment by hatched** [comment]
I can confirm this, if you have a parent component with multiple child components and break on `componentDidMount` the children have not yet entered the DOM but the parent 'raw' HTML elements have.

**Comment by cvlmtg** [comment]
I have the same problem. this breaks our app because we can't calculate the correct height of the mounted DOM nodes on first render.
