### ISSUE TITLE
Drag and Drop didn't work on firefox

### ISSUE THREAD

**Issue by IftekherSunny** [react-dnd/react-dnd#1147]
Downloaded firefox few mins ago. Tested my apps on latest firefox. Unfortunately, drag and drop didn't work. But same apps work perfectly on chrome.

**Can't Drag**

**Comment by darthtrevino** [comment]
This is one of the downsides of a manual testing environment. I'll spend some time with FF and see if any issues are obvious. PRs welcome.

**Comment by darthtrevino** [comment]
The examples on the docsite work in the latest version of FF, but I suspect you may be running into an edge case. If you have an example demonstrating your problem that would help.
