### ISSUE TITLE
Upgrading to version 6 "Couldn't find any versions for "dnd-core" that matches "^6.0.0""

### ISSUE THREAD

**Issue by rssfrncs** [react-dnd/react-dnd#1162]
Trying to upgrade our project to version 6 and getting the following prompt from Yarn "Couldn't find any versions for "dnd-core" that matches "^6.0.0""

run `yarn add react-dnd@latest react-dnd-html5-backend@latest`

react-dnd, react-dnd-html5-backend and dnd-core are at version 6.

**Comment by rssfrncs** [comment]
Weird `npm view` clearly shows version 6.0.0 as the latest tagged release...

![image](https://user-images.githubusercontent.com/7808978/48253047-41352380-e3fe-11e8-997f-d240e03a06bb.png)

**Comment by rssfrncs** [comment]
Well I installed dnd-core manually (which installed v4) and then upgraded with `dnd-core@latest` and it upgraded to v6 correctly. Odd!

**Comment by darthtrevino** [comment]
Huh, super weird! I'm glad you were able to resolve it
