### ISSUE TITLE
Cannot hide Source element behind Drag Layer

### ISSUE THREAD

**Issue by lukebelliveau** [react-dnd/react-dnd#1163]
**Describe the bug**
When dragging an element, I would like the element dragged under the mouse to look different than the original source element. When dragging, the custom drag layer is appended to the default drag layer rather than replacing it.

**To Reproduce**
1. Go to [this codesandbox example](https://codesandbox.io/s/k2wov0nn1v).
2. Drag the monster (upper left corner)
3. Observe that the monster is dragged under the mouse, with the Bird element underneath it.

**Expected behavior**
I would like to see _just_ the bird under the mouse while I am dragging the item. I expect this behavior because my custom drag layer returns a Bird element:
```es6
// DragLayer.js

const CustomDragLayer = ({ item, itemType, isDragging, currentOffset }) => {
  if (!isDragging) return null;

  return <Bird style={getItemStyles(currentOffset)} />;
};
```

**Screenshots**
This is what I currently see (undesired behavior). The two elements stacked atop each other are in mid-drag.  Ideally, the dragged element in the middle is _just_ a bird, with no monster above it.
![screenshot 2018-11-09 at 12 54 59 pm](https://user-images.githubusercontent.com/6233086/48296853-deb94300-e450-11e8-884c-5a1577c005ae.png)

**Desktop (please complete the following information):**
 - OS: Chrome OS
 - Browser: Chrome
 - Version: 69

**Additional context**
I am very new to DnD and am aware this is likely not a bug. After a few days tooling around with DragLayer, I think I need a push in the right direction. Thanks!

**Comment by lukebelliveau** [comment]
**Resolved**.

To prevent the drag preview from assuming the drag source's image, you need to pass  `react-dnd-html5-backend`'s `getEmptyImage()` to `connectDragPreview`. Do this in `componentDidMount()`.

```es6
// Source.js

import { getEmptyImage } from 'react-dnd-html5-backend'

const SourceCollector = (connect, monitor) => ({
 connectDragPreview: connect.dragPreview()
})

class Source extends React.Component {
 componentDidMount() {
   this.props.connectDragPreview(getEmptyImage())
 }
}
```

[Relevant doc example](https://github.com/react-dnd/react-dnd/blob/master/packages/documentation-examples/src/05%20Customize/Handles%20and%20Previews/BoxWithImage.tsx)

**Comment by RomanChumakov** [comment]
If you are using hooks, you can hide the default preview like this:
```
import {useDrag} from "react-dnd";
import {getEmptyImage} from "react-dnd-html5-backend";

...

function SomeComponent(props) {
    const [{isDragging}, drag, dragPreview] = useDrag(() => ({
        type: dndItems.someItem,
        item: {/*your item*/},
        collect: monitor => ({isDragging: monitor.isDragging()}),
    }), []);

    useEffect(() => { // this useEffect hides the default preview
        dragPreview(getEmptyImage(), { captureDraggingState: true });
    }, []);

    ...
}
```

**Comment by fatemehkarimi** [comment]
@chendoron the solution worked for me. you may have made a mistake.
