### ISSUE TITLE
DragSourceMonitor::isOver is missing

### ISSUE THREAD

**Issue by hanishsingla** [react-dnd/react-dnd#1166]
I am trying to achieve something like https://app.pandadoc.com/a/#/document/v1/editor/xQM9vwzfyKpct5SAAmYLwb/content

We can move DragSources freely and nicely. However this leads to some situations where Drag elements are overlapping each other, which is rarely intended by users.

In my humble opinion, if we had DragSourceMonitor::isOver then we can determine if DragSource is being dropped on some other DragSource and adjust the blocks accordingly.

If we have any method for such case, then we should add it in documentation.

**Comment by gustavooavila** [comment]
You can compose DropTarget and DragSource in the same Component.

Here is another discussion on the topic of using DropTarget and DragSource in the same Component:
https://github.com/react-dnd/react-dnd/issues/157
