### ISSUE TITLE
"Cannot call hover while not dragging" when dropping a new tab on dropzone in Edge on Windows 10

### ISSUE THREAD

**Issue by sarawinter** [react-dnd/react-dnd#1170]
**Describe the bug**
I am getting the error "Cannot call hover while not dragging" when accidentally dropping a new browser tab onto a drop-zone in my application.

**To Reproduce**
1. Go to 'http://react-dnd.github.io/react-dnd/examples/customize/drop-effects'
2. Create a new tab in the browser
3. Drag the tab to the drop-zone
4. See error in console

**Expected behavior**
Not to get the error.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge
 - Version: 42.17134.1.0

**Additional context**

**Comment by sarawinter** [comment]
The application is using the following:

**Comment by DonMcNamara** [comment]
@sarawinter  I'm seeing users hit a similar error in my code, but I'm having trouble reproducing it. I'm wondering if you were able to get any additional insight into the problem.

**Comment by DonMcNamara** [comment]
Never mind, the issue I was seeing is related to this: https://bugs.chromium.org/p/chromium/issues/detail?id=1005747
and has a corresponding issue here:
https://github.com/react-dnd/react-dnd/issues/1534
