### ISSUE TITLE
Monitor events in the collect object only firing once

### ISSUE THREAD

**Issue by ginkoh** [react-dnd/react-dnd#1171]
**Describe the bug**
Monitor events in the collect object only fires once

**To Reproduce**
Make a dragSource with getClientOffset or any other position related event
Log the prop you created
It only runs once a drag

**Expected behavior**
Continuous update of the values as the element is dragged

**Desktop (please complete the following information):**
 - OS: XUBUNTU
 - Browser [chrome, firefox]

**Additional context**
We are making a resizable HOC for an draggable element so, we have three nested DragSources

**Comment by DavidHenri008** [comment]
I do experience the same or similar issue. I tried to add a `console.log` in my collect function to see what is happening and I get only around 5 console log and then nothing. 
```
const collect = (connect, monitor) => {
  console.log(monitor.getClientOffset());
  return {
    connectDragSource: connect.dragSource(),
    isDragging: monitor.isDragging(),
  };
};
```

Is this a normal bahaviour?

**Comment by gustavooavila** [comment]
Ok... Fuck this library... We are implementing or own dnd

**Comment by Qu4dratus** [comment]
Resolved: We're using JQuery UI
