### ISSUE TITLE
Drag a list item and drop it in another component (no list)

### ISSUE THREAD

**Issue by kwnkouts** [react-dnd/react-dnd#1174]
Hi guys, lately I've been struggling with react dnd and I haven't really figured out how I am supposed to proceed. So, my app has two main components "Sidebar" and "Canvas". Then, inside sidebar I use map to render the data from the state. 

Here is the _Sidebar.js_, I am using some material-ui components

```
function Sidebar(props) {

   let Nodes = props.data.filter(node24 => node24.distribution.imagedescriptor.toLowerCase().includes(props.filter.toLowerCase())
   ).map(node24 => (
     <Node key={node24.distribution.imagedescriptor} primary={node24.distribution.imagedescriptor} />
     ))

return (

  <List>
    {Nodes}
  </List>
);
}
```
The inner Node Component is the component for each list item.
Node.js : 

```
class Node extends Component {
  render() {

    return (
      <div>
        <ListItem button key={this.props.key}>
          <ListItemText primary={this.props.primary} />
        </ListItem>
      </div>
    );
  }
}

export default Node;
```
 So eventually, there is the Sidebar with its Nodes and the rest of the App's screen is canvas witch is a completely empty component.
What I want to achieve is to drag and drop any list item (Node) inside the canvas _-without this being removed from the list-_.

I have already attached the dragSource to the Node component and the dragTarget to Canvas.
After that I do not know how to proceed since the Nodes have not default coordinates I can modify to move them.

If anyone can give me a hind so that I can move on will be very important.
I am attaching a screenshot of my app so far. 

![screenshot_1](https://user-images.githubusercontent.com/10096691/48665088-528ec780-eab1-11e8-8281-14f9251c2a81.png)

**Comment by pd4d10** [comment]
You may want to checkout this demo:
http://react-dnd.github.io/react-dnd/examples/dustbin/single-target

The difference is an additional operation, which is to copy the node from left to right after drop.

I think it could be done in `DropTargetSpec.drop` callback, add the dropped item to state(something like `droppedItems`) and render it to right side.

**Comment by kwnkouts** [comment]
Your hint was really helpful for me in order to understand the logic behind rect-dnd and move on.  Thank you very much!!
