### ISSUE TITLE
example url 404

### ISSUE THREAD

**Issue by bammoo** [react-dnd/react-dnd#1181]
http://react-dnd.github.io/react-dnd/examples-chessboard-tutorial-app.html is 404

**Comment by pd4d10** [comment]
Should be http://react-dnd.github.io/react-dnd/examples

**Comment by StephenHaney** [comment]
> Should be http://react-dnd.github.io/react-dnd/examples

Correct me if I'm wrong – won't this be a link to the same page you're already on?

**Comment by pd4d10** [comment]
Woops.. Not sure which page is the original destination. Seems the localhost port number is also mistaken, should be 8000.

I'll try to fix it and update the PR

**Comment by pd4d10** [comment]
Hi @darthtrevino,  I'm using react-dnd and willing to be a contributor(maintainer).

Trying to dig into the implementation and solve issues.
