### ISSUE TITLE
Breaks Server-Side Rendering

### ISSUE THREAD

**Issue by catamphetamine** [react-dnd/react-dnd#1192]
Seems to affect both versions 5.x and 6.x.
I have a decorator like this:

```js
import { DragDropContext, DragLayer, DropTarget } from 'react-dnd'

export function DragAndDrop() {
  const context = DragDropContext(HTML5Backend)
  const layer = DragLayer((monitor) =>({ isDragging : monitor.isDragging() }))
  return component => context(layer(component))
}
```

The I decorate my app's main component with `@DragAndDrop()`.
This results in the `.render()` method returning `null` on server-side, and so server-side rendering returns emptyness.
When I remove the `@DragAndDrop()` decorator everything renders as expected on server-side.

As a workaround, until the bug is fixed in this library, I modified my code this way:

```js
import { DragDropContext, DragLayer, DropTarget } from 'react-dnd'

export function DragAndDrop() {
  if (typeof window === 'undefined') {
    return component => component
  }
  const context = DragDropContext(HTML5Backend)
  const layer = DragLayer((monitor) =>({ isDragging : monitor.isDragging() }))
  return component => context(layer(component))
}
```

**Comment by dkarbayev** [comment]
I had the same issue with react-dnd & next.js, but in my case it was `DropTarget` for files - whenever I wrapped the container in `dropTarget()`, I got `null` on server-side. I wrote a workaround for this so that the container is only wrapped on client-side but now I get `Warning: Did not expect server HTML to contain a <div> in <div>.` even though HTML markups I get from SSR and in browser are same. My workaround:

```
const wrapForSSR = Component => {
  if (typeof window === 'undefined') {
    return function wrapped(props) {
      return <Component connectDropFileTarget={e => e} {...props} />;
    };
  } else {
    return dropFileTarget(Component);
  }
};
```

**Comment by darthtrevino** [comment]
I haven't really messed around much with SSR before. Can you put together a test case in a PR?

**Comment by darthtrevino** [comment]
I'd like this to not blow up for users. Can you show me what errors you're running into?

**Comment by catamphetamine** [comment]
@dkarbayev 
Actually, my workaround doesn't work (I guess yours too).
It still renders but then throws a warning in `React.hydrate()`: "Did not expect server HTML to contain ...".

@darthtrevino 
Here is a sample repo illustrating the bug.
https://github.com/catamphetamine/react-dnd-bug-showcase

`npm install && npm start`
Disable JavaScript in DevTools and see "Text" on the page.
Then go to `src/pages/DragAndDrop.js` and comment the lines:

```js
	// A workaround to prevent `react-dnd` from breaking server-side rendering.
	// https://github.com/react-dnd/react-dnd/issues/1192
	if (typeof window === 'undefined') {
		return component => component
	}
```

Ctrl + C and `npm start`.
See that nothing renders.
The workaround is still not the solution because it breaks `React.hydrate()`.

**Comment by catamphetamine** [comment]
Why is there no "Reopen" button?
