### ISSUE TITLE
beginDrag should allow an array

### ISSUE THREAD

**Issue by jamestalmage** [react-dnd/react-dnd#1206]
I'm maintaining a mult-selection model, and when an item is dragged, I'd like to represent that with an array.

i.e.
```js
const spec = {
  beginDrag() {
    return [{id: 1}, {id: 2}];
  }
}
```

Currently the check uses `lodash.isPlainObj` which disallows array. There doesn't seem to be a technical reason for this (though maybe best practice is to wrap with a POJO). What about loosening that check?

**Comment by darthtrevino** [comment]
Would `{ids: [1, 2]}` work?
