### ISSUE TITLE
Examples are hard to find with new navigation structure

### ISSUE THREAD

**Issue by gaearon** [react-dnd/react-dnd#1209]
With the new navigation, it's easy to miss examples in the upper right corner, and think that this is all content that's available:

<img width="259" alt="screen shot 2019-01-10 at 1 38 18 pm" src="https://user-images.githubusercontent.com/810438/50971862-05d9d280-14dd-11e9-9332-abfeef539769.png">

I strongly recommend to either revert that change, or to add "Examples" to the left sidebar that at least points to the Examples top-level menu. It is *way* too easy to miss.

**Comment by darthtrevino** [comment]
Aye aye!
