### ISSUE TITLE
How to remove the previews default background color?

### ISSUE THREAD

**Issue by ykx456654** [react-dnd/react-dnd#1218]
<img width="778" alt="wx20190126-013403 2x" src="https://user-images.githubusercontent.com/13938795/51762644-3b9ccf00-210b-11e9-99fd-caf159474a8e.png">
i just setted a border-radius on the Glass element, how can i remove the preview's 
#fff background ?

**Comment by roth1002** [comment]
I thought you can reference this

http://react-dnd.github.io/react-dnd/examples/drag-around/custom-drag-layer

**Comment by ykx456654** [comment]
thanks, i think it's the browser's behavior,  i need to use drag-layer.

**Comment by wooandoo** [comment]
you can add css style to your draggable element:

```css
transform: translate(0, 0);
```

**Comment by keremkaradenzz** [comment]
> you can add css style to your draggable element:
> 
> ```css
> transform: translate(0, 0);
> ```

thank you <3

**Comment by Jayesh2812** [comment]
Thank you 

> you can add css style to your draggable element:
> 
> ```css
> transform: translate(0, 0);
> ```
