### ISSUE TITLE
DropTarget HOC not working in `Native-files` example

### ISSUE THREAD

**Issue by brave-merida** [react-dnd/react-dnd#1219]
**I followed the `native-files` example in react.js (not typescript)**
Example URL: http://react-dnd.github.io/react-dnd/examples/other/native-files
Source: https://github.com/react-dnd/react-dnd/tree/master/packages/documentation-examples/src/06%20Other/Native%20Files

```
<div>
  <TargetBox accepts={[FILE]} onDrop={this.handleFileDrop} />
  <FileList files={droppedFiles} />
</div>
```
`TargetBox` not appear in web-browser inspector window.
```
export default DropTarget(
	(props: TargetBoxProps) => props.accepts,
	boxTarget,
	(connect: DropTargetConnector, monitor: DropTargetMonitor) => ({
		connectDropTarget: connect.dropTarget(),
		isOver: monitor.isOver(),
		canDrop: monitor.canDrop(),
	})
)(TargetBox)
```

**To Reproduce**
1. create-react-app
`npx create-react-app my-app`
2. Copy & paste the `native-files` example files
3. Convert it to `.js` files
4. See web-browser
![image](https://user-images.githubusercontent.com/30062357/52203457-39293a80-28ac-11e9-882e-8565ea0f1e2e.png)

**Expected behavior**
![image](https://user-images.githubusercontent.com/30062357/52203421-26af0100-28ac-11e9-8e2e-f47157524d7f.png)

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: firefox, safari, chrome
 - Version: latest

**Comment by nanopx** [comment]
Hi @brave-merida, did you wrap your component with [DragDropContext](http://react-dnd.github.io/react-dnd/docs/api/drag-drop-context)? 👀

**Comment by brave-merida** [comment]
Thanks @nanopx ,
Sorry, I just did wrapping the `DragDropContext` into `App` component.
Then `Cannot have two HTML5 backends at the same time.` error happened.
I am using `react-tags` library in the same page, the library is using `react-dnd`.
How can I fix this error?

**Comment by nanopx** [comment]
@brave-merida 
I haven't used the `react-tag-input` library before, but in the README there's an explanation about the DragDropContext. (In the last part of the Usage section)
https://github.com/prakhar1989/react-tags#usage

I haven't tried, but I think it would work if you create the DragDropContext of your own, and use the `.WithOutContext` one exported from `react-tag-input`

Note that both `ReactTag` and `TargetBox` should be wrapped inside DragDropContext.

**Comment by brave-merida** [comment]
Thanks
