### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by sunndeath** [react-dnd/react-dnd#1221]
Hi, guys.
I use "react-sortable-tree" for visualize Folder Tree and "react-dnd" for copying node from Folder Tree to another component.

My issue for react-sortable-tree: https://github.com/frontend-collective/react-sortable-tree/issues/457

I receive error after dropping node from Folder Tree (SortableTree) to another component (DropTarget): 
```
Uncaught TypeError: Cannot read property 'length' of undefined
```

Please, help me for fix the problem.
![annotation 2019-02-05 170644](https://user-images.githubusercontent.com/8881978/52279438-a00d2900-296a-11e9-8f94-c047195ec973.jpg)

**Comment by dehimer** [comment]
Got same error on end of dragging
