### ISSUE TITLE
How can I combine drag by the handle with custom drag preview?

### ISSUE THREAD

**Issue by vladanyes** [react-dnd/react-dnd#1222]
The problem is that I have the same problem as [here](https://github.com/react-dnd/react-dnd/issues/773). Here is the main insight from that issue:

> Make sure ItemDragPreview isnt also a DragSource

But how can I implement it, cause I need a DragPreview as a dnd handler?

This is how dnd handlers are implemented:
```
function collectSource(connect, monitor) {
  return {
    connectDragPreview: connect.dragPreview(),
    connectDragSource: connect.dragSource(),
    isDragging: monitor.isDragging(),
  };
}

function collectTarget(connect, monitor) {
  return {
    connectDropTarget: connect.dropTarget(),
    isOver: monitor.isOver(),
  };
}
const taskSource = {...}
const taskTarget = {...}

class NormalRow extends Component {
  componentDidMount() {
    const { connectDragPreview } = this.props;
    if (connectDragPreview) {
      // Use empty image as a drag preview so browsers don't draw it
      // and we can draw whatever we want on the custom drag layer instead.
      connectDragPreview(getEmptyImage(), {
        // IE fallback: specify that we'd rather screenshot the node
        // when it already knows it's being dragged so we can hide it with CSS.
        captureDraggingState: true,
      });
    }
  }
render() {
  const element = (
      <div>
        {columns.map(this.renderCell)}
      </div>
     );

 return connectDropTarget(connectDragPreview(
        <div>
          {connectDragSource(<div className="dnd__item" />)}
          {element}
        </div>,
      ));
 }
}

export default flow(
  DragSource('entity', taskSource, collectSource),
  DropTarget('entity', taskTarget, collectTarget),
)(NormalRow);
```
This is how I trying to create a custom dragLayer:
```
class CustomDragLayer extends React.Component {
  renderItem = (type, item) => {
    switch (type) {
      case 'entity':
        return <EntityDragPreview item={item} />;
      default:
        return null;
    }
  };

  render() {
    const { item, itemType, isDragging } = this.props;

    if (!isDragging) return null;

    return (
      <div style={layerStyles}>
        <div style={getItemStyles(this.props)}>
          {this.renderItem(itemType, item)}
        </div>
      </div>
    );
  }
}

export default DragLayer(collect)(CustomDragLayer);
```
```
class EntityDragPreview extends React.Component {
  render() {
    const { item: { renderRow, row, draggingRowNumber } } = this.props;

    return (
      <div style={{ position: 'relative' }}>
        <dsiv style={{ backgroundColor: 'red', position: 'absolute', left: '-20px' }}>
          {renderRow(row, 3, true, draggingRowNumber)}
        </dsiv>
      </div>
    );
  }
}

export default EntityDragPreview;
```
Here is screenshot:
https://ibb.co/X4P7JgD
grey background - shadow from draggable element,
white background - HTML styles, which I want to remove,
red background - custom drag preview.

**Comment by v5zz** [comment]
I met the same problem, if your has solved the problem ,could tell me

**Comment by vladanyes** [comment]
> I met the same problem, if your has solved the problem ,could tell me

I still haven't found any solution for this

**Comment by darthtrevino** [comment]
Have you looked at this example? http://react-dnd.github.io/react-dnd/examples/customize/handles-and-previews

**Comment by darthtrevino** [comment]
If you're looking to combine a drag-handle with a drag preview image, here's a sandbox I made to demonstrate mixing those two things: https://codesandbox.io/s/nmrp33p2m

**Comment by v5zz** [comment]
> 如果你想把拖拽手柄和拖拽预览图像结合起来，这里有一个沙盒我用来展示混合这两件事：[https](https://codesandbox.io/s/nmrp33p2m)：[//codesandbox.io/s/nmrp33p2m](https://codesandbox.io/s/nmrp33p2m)

i want to use handles to drag and sort list

**Comment by darthtrevino** [comment]
https://codesandbox.io/s/9jl8mz3x6y

**Comment by aleksa9911** [comment]
@darthtrevino how to implement custom drag layer to this code ?

**Comment by floppyvlaDISK** [comment]
I managed to combine drag source + drop target with drag preview by repeating 
`this.props.connectDragPreview(getEmptyImage());` at componentDidUpdate method of drag source component like so
![image](https://user-images.githubusercontent.com/25643386/79224651-27560680-7e64-11ea-88dd-6cf6a4d4d7a6.png)
