### ISSUE TITLE
Simplify docs my removing some concepts explanations

### ISSUE THREAD

**Issue by rg4real** [react-dnd/react-dnd#1224]
It's just a general idea. An here it is: simplify docs by removing the explanations of general concepts.

Examples:
> A higher-order component is just a function that takes a React component class, and returns another React component class. 

> Notice how, after specifying the DragSource parameters in the first function call, there is a second function call, where you finally pass your class. This is called currying, or partial application, and is necessary for the decorator syntax to work out of the box:

**Comment by darthtrevino** [comment]
I agree, it's been a while since we took a sweep through the documentation.

**Comment by githubsheng** [comment]
After 10 minutes of reading I finally reached the hello world example....

**Comment by rogovdm** [comment]
Docs are quite nice actually! 

The point is that they made more sense in this form earlier. When lots of concepts were too new for a community. Now it's more of a wall.
