### ISSUE TITLE
createBackend is not a function

### ISSUE THREAD

**Issue by redochka** [react-dnd/react-dnd#1232]
Just following the documentation, i am faced with this error: `createBackend is not a function`

See this codesandbox: https://codesandbox.io/s/10rjqx9wq7

Thanks

**Comment by gustavohenke** [comment]
The import `HTML5Backend` doesn't exist in `react-dnd-html5-backend`.
You should be doing the following instead:

```js
import HTML5Backend from 'react-dnd-html5-backend';
```

**Comment by redochka** [comment]
@gustavohenke Thank you so much.

**Comment by lengjh** [comment]
import {HTML5Backend } from 'react-dnd-html5-backend';

**Comment by Domiii** [comment]
@lengjh  is right. In the current version, it is exposed as named `export`, not as `default export`:

```js
import { HTML5Backend } from "react-dnd-html5-backend";
```

See [here](https://github.com/react-dnd/react-dnd/tree/v14.0.3/packages/backend-html5/src/index.ts) for reference, on how to import it.

**Comment by murtuzaalisurti** [comment]
still getting the issue, tried both ways

**Comment by murtuzaalisurti** [comment]
solved!

**Comment by HanTengfeifei** [comment]
> 

???

**Comment by AzlanCrypt** [comment]
import HTML5Backend from 'react-dnd-html5-backend';
This works for me!!
