### ISSUE TITLE
DragSource on functional components 

### ISSUE THREAD

**Issue by mauron85** [react-dnd/react-dnd#1235]
**Is your feature request related to a problem? Please describe.**
Allow to use DragSource on functional components. Currently there are two problems with using DragSource  on functional components.

1. DragSource as defined in `DragSource.ts` [always returns class `DndComponentClass`](https://github.com/react-dnd/react-dnd/blob/master/packages/react-dnd/src/DragSource.ts#L81)
2. I find DragSource definition overly complex. For example if you don't provide T of `DecoratedComponent: React.ComponentType<T>` you'll end up with props types mismatch in decorated component or parent class (eg `connectDragSource` prop required in parent class or missing other `props` in decorated component).

**Describe the solution you'd like**

```typescript
// custom.d.ts
import 'react-dnd';

declare module 'react-dnd' {
	declare interface IDraggable {
		connectDragSource: ConnectDragSource;
		isDragging?: boolean;
	}

	/**
	 * Decorates a component as a dragsource
	 * @param type The dragsource type
	 * @param spec The drag source specification
	 * @param collect The props collector function
	 * @param options DnD options
	 */
	declare function DragSource<Props, CollectedProps = {}, DragObject = {}>(
		type: SourceType | ((props: Props) => SourceType),
		spec: DragSourceSpec<Props, DragObject>,
		collect: DragSourceCollector<CollectedProps>,
		options?: DndOptions<Props>
	): (DecoratedComponent: React.ComponentType<Props & CollectedProps>) => React.ComponentType<Props>;
}
```
I've replaced [option to provide DecoratedComponent type](https://github.com/react-dnd/react-dnd/blob/master/packages/react-dnd/src/DragSource.ts#L26) with union of Props and CollectedProps as I consider this redundant and only requires new dummy type, which is not needed elsewhere.

Also added new IDraggable interface, which is basically the most common form of CollectedProps (but that is for separate topic).

Example usage:
```typescript
import {
	DragSource,
	DragSourceCollector,
	DragSourceSpec,
	IDraggable
} from 'react-dnd';

interface IDraggableItem {
    id: string;
    index: number;
    data: Item;
    onCreate: () => void;
}

interface IToolbarItemDraggableProps {
    onCreate: () => void;
}

const dragSource: DragSourceSpec<IToolbarItemDraggableProps, IDraggableItem> = {
    beginDrag({ onCreate, ...data }) {
        return {
            id: uuid.v1(),
            index: -1,
            data,
            onCreate
        };
    }
};

const collector: DragSourceCollector<IDraggable> = (connect, monitor) => {
    return {
        connectDragSource: connect.dragSource(),
        isDragging: monitor.isDragging()
    };
};

const ToolbarItemDraggable = DragSource<
    IToolbarItemDraggableProps,
    IDraggable,
    IDraggableItem
>("DRAGGABLE_TYPE", dragSource, collector)(props => {
    const { connectDragSource, onCreate, ...data } = props;
    return connectDragSource(
        <div>
            <ToolbarItem {...data} />
        </div>
    );
});
```
Hopefully it makes sense. If there will be interest I can prepare PR or explain bit in depth what is this all about. :)

**Describe alternatives you've considered**
Only one. Cast return as unknown and then to React.ComponentType. But that has to be done in project rather than in library.

**Additional context**
N/A

**Comment by darthtrevino** [comment]
We're going to be releasing an experimental hooks-based API soon (hopefully before lunch). I'd love to get some community feedback on that feature. It should clear up a lot of the issues we have with class decoration, and allow you to use function components entirely for your DnD integration.

**Comment by darthtrevino** [comment]
Please try out 7.2.0, and let me know how the hook-based API works out for you!

**Comment by darthtrevino** [comment]
The typings have been updated in 7.4.x and all the examples have been updated to use function components.
