### ISSUE TITLE
DragDropContext crashes on drop/setState

### ISSUE THREAD

**Issue by CaitlinSweeney** [react-dnd/react-dnd#1236]
This isn't a bug, hoping someone could help me with this. I'm having an crash after I drop my dragSource, in the browser (error in DragDropContext). It's crashing after I'm setting state on the drop, which will populate the dragSource component.
Here is the code : [CodeSandbox.io]( https://codesandbox.io/s/n94y030ryp)
Still new to React, so I'm unsure what in the  docs I'm missing or if it's a general React mistake.
Any direction or input would be greatly appreciated.
Thanks!

**Comment by SuperChocoman7** [comment]
If you take a look at file "Main.js", method "handleDropQuestion".
```
handleDropQuestion = id => {
    const { templateQuestions } = this.state;
    const question = templateQuestions.find(_q => _q.id === id);
    this.setState(
     prevState => (
        { addedQuestions: prevState.addedQuestion.concat([question]) },  //<-- There's a typo here. You forgot the "s" of "prevState.addedQuestions"
        () => console.log("addedQuestions", this.state.addedQuestions)  //<-- Remove this callback
      )
    );
   ...
};
```
If we add the "s" and remove the console.log, it should fix the problems and make our app work as expected.
In short: 
```
this.setState(
  prevState => ({ addedQuestions: prevState.addedQuestions.concat([question]) })
);
```
That'll make it work.

However, it's always good that we make our code more readable, especially when we try to update multiple values in our state.
For example, the code above can be written as the following: 
```
handleDropQuestion = id => {
    const { templateQuestions, addedQuestions } = this.state;
    const question = templateQuestions.find(_q => _q.id === id);
    const updatedQuestions = addedQuestions.concat(question);
    this.setState({ addedQuestions: updatedQuestions });
    ...
};
```

**Comment by CaitlinSweeney** [comment]
@SuperChocoman7  Thank you so much for looking this over. Such a stupid mistake 🙄
