### ISSUE TITLE
drop and hover not triggering on DropTarget, isOver never true

### ISSUE THREAD

**Issue by mbabauer** [react-dnd/react-dnd#1238]
I posted over on [StackOverflow](https://stackoverflow.com/questions/54827598/react-dnd-not-firing-drop-and-hover-on-target) but received no help.  I am trying to setup a simple DnD between a toolbar and a form editor, but when I drag one of the toolbar items (`DropSource`) to the form editor (`DropTarget`), the `drop` and `hover` never fires on the `DropTarget` and the `isOver` never flips to `true`.

My DropSource:
```
import DropTypes from "../../common/DropTypes";

class ToolbarItem extends React.Component {
  render() {
    const { children } = this.props;

    // These two props are injected by React DnD,
    // as defined by your `collect` function above:
    const { isDragging, connectDragSource } = this.props;
    return connectDragSource(<div>{children}</div>);
  }
}

/**
 * Specifies the drag source contract.
 * Only `beginDrag` function is required.
 */
const dragSource = {
  beginDrag(props, monitor, component) {
    return {
      description: props.description
    };
  }
};

/**
 * Specifies which props to inject into your component.
 */
function dragCollect(connect, monitor) {
  return {
    // Call this function inside render()
    // to let React DnD handle the drag events:
    connectDragSource: connect.dragSource(),
    // You can ask the monitor about the current drag state:
    isDragging: monitor.isDragging()
  };
}

console.log("Source DropType: ", DropTypes.TOOLBAR_ITEM);
const DragableToolbarItem = DragSource(
  DropTypes.TOOLBAR_ITEM,
  dragSource,
  dragCollect
)(ToolbarItem);
```

And DropTarget:
```
import DropTypes from "../../common/DropTypes";

class TemplateEditor extends React.Component {
  componentDidMount() {}

  render() {
    console.log("props: ", this.props);
    const { isOver, canDrop } = this.props;
    return (
      <div className="h-100">
        Editor{isOver ? " - OVER!" : ""}
        {canDrop ? " - CAN DROP!" : ""}
      </div>
    );
  }
}

/**
 * Specifies the drag source contract.
 * Only `beginDrag` function is required.
 */
const dropSource = {
  drop(props, monitor, component) {
    console.log("props: ", props);
    console.log("monitor: ", monitor);
    console.log("component: ", component);
  },
  hover(props, monitor, component) {
    console.log("props: ", props);
    console.log("monitor: ", monitor);
    console.log("component: ", component);
  }
};

const dropCollector = (connect, monitor) => ({
  isOver: monitor.isOver(),
  item: monitor.getItem(),
  canDrop: monitor.canDrop()
});

// export default TemplateEditor;
console.log("Target DropType: ", DropTypes.TOOLBAR_ITEM);
export default DropTarget(DropTypes.TOOLBAR_ITEM, dropSource, dropCollector)(
  TemplateEditor
);
```

And the DropTypes is just an object I am using to make sure the source and target types are the same:
```
export default {
  TOOLBAR_ITEM: 'TOOLBAR_ITEM',
};
```

The `div` that makes up the `TemplateEditor` is rendering in the browser > 1000x700, so I don't think it's an issue where the target size is too small.  I am 99% sure this is not a bug, but rather something I am not doing correctly, but I am not sure how to correct it.

**To Reproduce**
1. Use the target and source code
2. Drag source to target
3. target displays "CAN DROP!" but not "OVER!"

**Expected behavior**
I would expect that the target would show "OVER!" when the source was over the target, and `hover` on the target triggered.  When dropped, I would expect `drop` on the target to trigger.

**Screenshots**
<img width="1417" alt="screen shot 2019-03-05 at 7 43 51 am" src="https://user-images.githubusercontent.com/472616/53806431-fb571a80-3f1a-11e9-83ad-4a0a868dcc98.png">
<img width="1303" alt="screen shot 2019-03-05 at 7 44 06 am" src="https://user-images.githubusercontent.com/472616/53806432-fb571a80-3f1a-11e9-83b5-27b2dc0a0925.png">

**Desktop (please complete the following information):**
 - OS: OS X Mojave
 - Browser: Chrome
 - Version 72.0.3626.119

**Additional context**
Using React, Reactstrap, AWS Amplify, reach/router, react-dnd and react-dnd-html5-backend

**Comment by SuperChocoman7** [comment]
I think the problem is that you forgot to use the prop "connectDropTarget" in your DropTarget (which is TemplateEditor in this case).
I hope this will help: 
```
class TemplateEditor extends React.Component {
...
render() {
    console.log("props: ", this.props);
    const { connectDropTarget, isOver, canDrop } = this.props;  //<--add connectDropTarget here
    return connectDropTarget(  //<-- use connectDropTarget here
      <div className="h-100">
        Editor{isOver ? " - OVER!" : ""}
        {canDrop ? " - CAN DROP!" : ""}
      </div>
    );
  }
}
...
const dropCollector = (connect, monitor) => ({
  connectDropTarget: connect.dropTarget(), //<-- andthis line
  isOver: monitor.isOver(),
  item: monitor.getItem(),
  canDrop: monitor.canDrop()
});
```

**Comment by mbabauer** [comment]
That was absolutely it!  Thanks.  I guess I wasn't quite clear on how those got wired together.
