### ISSUE TITLE
Can't resolve 'react-dnd/lib/DragDropContext'

### ISSUE THREAD

**Issue by ravi123shanker** [react-dnd/react-dnd#1247]
/node_modules/frontend-collective-react-dnd-scrollzone/lib/index.js
Module not found: Can't resolve 'react-dnd/lib/DragDropContext' in '/GitRepo/node_modules/frontend-collective-react-dnd-scrollzone/lib'

Please help. My app is crashing.

**Comment by intizarahmad** [comment]
We are also facing the same issue,
Module not found: Error: Can't resolve 'react-dnd/lib/DragDropContext' in '/temp/node_modules/react-sortable-tree/dist', because the output directory path got changed, there is no content on path 'react-dnd/lib/DragDropContext' in the react build directory.

**Comment by Rick83600** [comment]
Same issue here

**Comment by darthtrevino** [comment]
It should be in react-dnd/lib/cjs/DragDRopContext

**Comment by leojh** [comment]
https://github.com/frontend-collective/react-sortable-tree/issues/463

**Comment by Amalanova** [comment]
so what is the solution for that. i want to import that module.

**Comment by wsalazar-peakactivity** [comment]
Why in world did they do this? I've spend forever trying to troubleshoot these issues to no avail.

**Comment by darthtrevino** [comment]
In a major version we removed DragDropContext in favor of the DndProvider react component. The original API was designed when decorators and HOCs were dominant patterns for advanced React.

It became clear when react released their new context API, it became clear that it was the correct way to establish a contextual system, so we deprecated the HOC.
