### ISSUE TITLE
Export Consumer

### ISSUE THREAD

**Issue by dolezel** [react-dnd/react-dnd#1257]
Would you consider also exporting `Consumer` from `DragDropContext`?
`react-sortable-tree` needs access to manager, to get monitor and subscribe to changes, to determine if dragging ended (https://github.com/frontend-collective/react-sortable-tree/blob/master/src/react-sortable-tree.js#L149-L151) and releasing version 7.1 broke our library.
https://github.com/frontend-collective/react-sortable-tree/issues/463

**Comment by darthtrevino** [comment]
It's exported at the module level here (https://github.com/react-dnd/react-dnd/blob/master/packages/react-dnd/src/DragDropContext.tsx#L27)

Do you want it exported at the top level of the library (e.g. https://github.com/react-dnd/react-dnd/blob/master/packages/react-dnd/src/index.ts#L5) as DragDropContextConsumer?

**Comment by dolezel** [comment]
Yes, that what I had in mind - expressing it at top level would be great.

**Comment by darthtrevino** [comment]
Awesome, I'm sorry the cjs/esm stuff threw off your guys' builds - I'll add it to the top level today

**Comment by darthtrevino** [comment]
DragDropConsumer has been added to the top-level react-dnd API in 7.3.0
