### ISSUE TITLE
[Hooks] useDrop receives a DragDropMonitorImpl, not DropTargetMonitor

### ISSUE THREAD

**Issue by jamiewinder** [react-dnd/react-dnd#1258]
According to the typings, the `useDrop` hook spec method receives a `DropTargetMonitor` instance, but it actually currently receives a `DragDropMonitorImpl` instance. For example, you cannot call `isOver()` on it but the typings suggest you can. 

I don't know if this is a fault of the code or the typings?

Conversely, the `useDrag` hook spec methods appears to receive a `DragSourceMonitor` instance.

**Comment by darthtrevino** [comment]
Good catch! Thanks
