### ISSUE TITLE
monitor.isDragging() throws error in collect function

### ISSUE THREAD

**Issue by MikeYermolayev** [react-dnd/react-dnd#1262]
**Describe the bug**
Hello, banging my head around this problem for half of the day already. Any help very appreciated

monitor.isDragging() throws error
![image](https://user-images.githubusercontent.com/8783498/54132250-f1567f80-4424-11e9-9c8d-110794e85055.png)

My DragSource looks like that 
```
const ResizeHandler = DragSource(
    "RESIZE_TYPE",
    {
        beginDrag: ({id}) => ({id}),
        endDrag: (props, monitor) => {
            console.log(props, monitor.getDifferenceFromInitialOffset().x);
        },
    },
    (connectDnd, monitor) => ({
        connectDragSource: connectDnd.dragSource(),
        isDragging: monitor.isDragging(), // fatal here
    }),
)(({isDragging, connectDragSource}: {isDragging: boolean, connectDragSource: Function}) => (
    connectDragSource(
        <div
            className={styles.resizeHandler}
            style={{
                background: isDragging ? `blue` : null,
            }}
        />,
    )
));
```

And at the moment of calling monitor.isDragging() everything fails as it doesn't have sourceId (equals to null).

Context is created by using DragDropContext(backend) and for backend is used some extended version of https://github.com/zyzo/react-dnd-mouse-backend

**Expected behavior**
monitor.isDragging() should work without exceptions

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS 10.14.3
 - Browser: chrome 72.0.3626.121 (Official Build) (64-bit)
 - Version: 7.3.1

**Additional context**

Thanks in advance

**Comment by MikeYermolayev** [comment]
So I have a problem at render of DragDropContainer https://github.com/react-dnd/react-dnd/blob/master/packages/react-dnd/src/decorateHandler.tsx#L197 

It creates monitor with sourceId: null, then it's trying to getCurrentState which leads to calling `collect` function. And by this moment it still doesn't have sourceId

**Comment by MikeYermolayev** [comment]
If I comment monitor.isDragging() in collect function then everything works ok and DragDropContainer receives its' source on componentDidMount

**Comment by darthtrevino** [comment]
@MikeYermolayev can you put together a minimal example demonstrating this in either a GH repo or a codepen or something like that?

**Comment by MikeYermolayev** [comment]
Currently I'm away of my laptop. Will try later
One more thing to note:
Everything works when I use Ref Callbacks. 
But when I pass ref from createRef API or `useRef` - it throws fatal

**Comment by darthtrevino** [comment]
Oh right, that's a known issue. I'll spend some time on that today

**Comment by darthtrevino** [comment]
@MikeYermolayev , I'm seeing useRef and createRef work when I use them in the functional component example. Can you provide a reproduction of the ref issues?

**Comment by MikeYermolayev** [comment]
Oh wait, ref is not the reason. It fails for component where no refs are used at all. Sorry for wrong information. 
I'll try to reproduce it in sandbox

**Comment by MikeYermolayev** [comment]
Well. Looks like it's not that easy. The simplest scenario works for me in sandbox. Need to dig deeper

**Comment by darthtrevino** [comment]
What a PITA, I'm glad you found the issue though. Thanks @MikeYermolayev !
