### ISSUE TITLE
[Hooks] Lazily evaluate drag item in useDrag

### ISSUE THREAD

**Issue by jamiewinder** [react-dnd/react-dnd#1263]
I've been following the releases for experimental hooks. The very latest now requires the drag item to be specified during the hook definition:
```javascript
useDrag({
   item: { type: 'my-drag-item', value: { ... } }
});
```
Would it be possible to allow the item to also be expressed as a function, to be invoked when the drag begins? This is more inline with how the original API worked, and would make some cases easier to upgrade. e.g.:
```javascript
// equivalent to the above
useDrag({
   item: () => ({ type: 'my-drag-item', value: { ... } })
});
```
The typings would basically be `item: DragObject | () => DragObject`, or perhaps passing the monitor as an argument may be useful. Of course, this is very much similar to the current API where `beginDrag` returns the drag object. What is the reason for moving away from this?

**Comment by darthtrevino** [comment]
With the original API, the `beginDrag()` method returns the dragItem. The reason it's wired that way is because this is the point at which we know the props of the thing that's being dragged. In the hooks API, because we use the API in the context of a function component, we already have the props available to us, so there's no need for the indirection. In my mind this makes the API a little clearer to use: "drag this thing here" vs "enable drag, i'll tell you what the thing is when my props are ready"

I'm not morally opposed to a lazy evaluation here, but what use cases would be enabled by this that are not possible or degraded by just defining the object outright?

**Comment by jamiewinder** [comment]
Thanks for your reply. The new API and the `item` property certainly simplified and tidied up a lot of my code when I was playing with it. 

The one situation I had where I wanted it to be evaluated lazily is admitted a bit messy and it could be there is a better way of doing it. I'll describe it for the sake of you deciding whether it's a valid use case that you ought to consider:

It's a list of items where you can click to select, ctrl-click to multiselect, and drag an item to either drag an individual item (without ctrl down) or the item along with the current selection. Basically how you'd expect to be able to drag and drop items in a list.

In order to do this my `beginDrag` had some potential side effects since you'd want to select an item you've started dragging, and you'd also want that item to be part of the drag item. In other words there is some logic involved in determining what the drag item should be based on the drag operation starting (rather than the component being rendered). 

I don't think I can do that the new API. `begin` fires, but I can't use that to affect the drag item as it has already been evaluated at this point.

**Comment by darthtrevino** [comment]
Interesting - could you put together a code sample of this use case? One possible solution may be to allow beginDrag() to return a value that could override the default dragItem.

**Comment by jamiewinder** [comment]
Here's an example: https://codesandbox.io/s/k218kk3z15

This is meant to be a standard multi-selectable / dragging list of items, and behave in the way you'd normally expect it to (with the CTRL key being used to toggle selection).

The behaviour I can't seem to add due to the hooks API change is that the dragged object should be determined based on whether the drag event started with the CTRL key held down. 

For example, in a scenario where 'A' is already selected:

- Dragging A with or without CTRL down will result in [A] being dragged
- Dragging B without CTRL down will result [B] being dragged
- Dragging B with CTRL down will result in [A, B] being dragged

I was able to do with `beginDrag` because I can inspect the drag start event and affect what is being dragged.

Hope that's helpful.

**Comment by darthtrevino** [comment]
@jamiewinder I think this PR should cover your use case. Let me know your thoughts

Thanks!

**Comment by jamiewinder** [comment]
That looks fine for me! As I say, I think I'll be using the `item` property the vast majority of the time, but this will be useful for situations like this and for converting from the non-hooks API.

**Comment by jamiewinder** [comment]
That looks fine for me! As I say, I think I'll be using the `item` property the vast majority of the time, but this will be useful for situations like this and for converting from the non-hooks API.
