### ISSUE TITLE
Implementation in React 360 (Need info)

### ISSUE THREAD

**Issue by lacson17** [react-dnd/react-dnd#1268]
Has anyone tried implementing React DnD on React VR/React 360? I would like to implement a feature that drags element A into element B using a VR controller and raycaster; either via click->drag->click->drop, or click->hold->drag->release->drop. Not sure if anyone has given this a shot, or if it is possible at all.

I've seen a similar question from 3 years ago [#529](https://github.com/react-dnd/react-dnd/issues/529) on whether or not this can be used in React Native, but it seems that it's not possible on native platforms. 

Any insight on this would be greatly appreciated. Thank you!

**Comment by darthtrevino** [comment]
It does not presently work with react-native. The dnd-core does not explicitly depend on the DOM, but the HTML5 backend does.
