### ISSUE TITLE
The example falls at a stage of installation of dependences

### ISSUE THREAD

**Issue by victorpavlenko** [react-dnd/react-dnd#1269]
**Describe the bug**
`macbook:react-dnd Victor$ yarn install
yarn install v0.21.3
[1/4] 🔍  Resolving packages...
success Already up-to-date.
$ npm test
npm WARN invalid config init-author-url="museum.com"
npm WARN invalid config Must be a full url with 'http://'

> react-dnd-parent@ test /Users/Victor/react-dnd
> run-s lint build test_modules jest:cov

> react-dnd-parent@ lint /Users/Victor/react-dnd
> tslint "packages/**/*.{ts,tsx}" -e "**/{lib,node_modules}/**"

> react-dnd-parent@ build /Users/Victor/react-dnd
> lerna run build --stream

lerna notice cli v3.13.1
lerna info Executing command in 6 packages: "yarn run build"
dnd-core: yarn run v0.21.3
dnd-core: $ run-p build:* 
dnd-core: yarn run v0.21.3
dnd-core: yarn run v0.21.3
dnd-core: $ tsc -b tsconfig.cjs.json 
dnd-core: $ tsc -b tsconfig.esm.json 
dnd-core: src/DragDropManagerImpl.ts(1,36): error TS2307: Cannot find module 'redux'.
dnd-core: src/DragDropMonitorImpl.ts(3,23): error TS2307: Cannot find module 'redux'.
dnd-core: src/HandlerRegistryImpl.ts(3,23): error TS2307: Cannot find module 'redux'.
dnd-core: src/interfaces.ts(1,29): error TS2307: Cannot find module 'redux'.
dnd-core: src/DragDropManagerImpl.ts(1,36): error TS2307: Cannot find module 'redux'.
dnd-core: src/DragDropMonitorImpl.ts(3,23): error TS2307: Cannot find module 'redux'.
dnd-core: src/HandlerRegistryImpl.ts(3,23): error TS2307: Cannot find module 'redux'.
dnd-core: src/interfaces.ts(1,29): error TS2307: Cannot find module 'redux'.
dnd-core: error Command failed with exit code 1.
dnd-core: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
dnd-core: error Command failed with exit code 1.
dnd-core: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
dnd-core: ERROR: "build:esm" exited with 1.
dnd-core: error Command failed with exit code 1.
dnd-core: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run build exited 1 in 'dnd-core'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-dnd-parent@ build: `lerna run build --stream`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-dnd-parent@ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Victor/.npm/_logs/2019-03-14T20_26_33_114Z-debug.log
ERROR: "build" exited with 1.
npm ERR! Test failed.  See above for more details.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.`

**To Reproduce**
1. Clone project
2. Run **yarn install**

**Expected behavior**
Start project

**Desktop (please complete the following information):**
 - MacOS 10.14.1

**Comment by MJeorrett** [comment]
+1 getting the same issue

**Comment by darthtrevino** [comment]
The build is passing, and it's just performing these steps. I'll do a clean install&build to see what's up on my end

**Comment by darthtrevino** [comment]
what version of yarn are you guys using?

**Comment by MJeorrett** [comment]
I'm on 1.13.0 also (on windows)

**Comment by gogogous88** [comment]
same issue here, is it because of the node version? node here is 8.15

**Comment by darthtrevino** [comment]
It could be, yeah - I'm using node 11.10
