### ISSUE TITLE
dragSource method and hover occasionally freezing, not defined.

### ISSUE THREAD

**Issue by CaitlinSweeney** [react-dnd/react-dnd#1276]
I’m a bit stuck debugging this issue when removing/moving the dragSource from between targets. It's not happening every time. 

You can view the code here.  https://codesandbox.io/s/82vrzym869. It’s not throwing an error, it's just freezing on the hover (the component stay red) and doesn't call the `removeQuestion` method on it's parent, dropTarget component.  It’s not handling the action after several interactions. It’s occasionally working, which you’ll see. 

In my local environment, the interaction and outcome is the same, but it’s throwing `props.moveQuestion` is not a function or` props.moveQuestion` is not a function  in the console. 
It’s occasionally not hitting these two functions here:
```
QuestionWrapper.js
const questionSource = {
  beginDrag (props){
    const question = props.question
    return {
      index: props.index,
      id: question.id,
      question: question,
      formId: props.formId
    }
  },
  endDrag(props, monitor) {
    const item = monitor.getItem()
    const id = props.id;
    const dropResult = monitor.getDropResult();
  /// check component ID and to remove question from previous list

    if (dropResult && dropResult.formId !== item.formId) {
      console.log('endDrag remove item.index', item.index)
      console.log('endDrag remove props index', props.index)
      props.removeQuestion(props.index)
    }
  }
};
```
I’m trying to figure out whether it’s my code and/or combination of the HTML5Backend that’s buggy. 

I know that I technically shouldn’t be passing props to the initial state, but it’s my only solution since the parent will make the API call to load the initial form data. The docs state, 
> However, it’s not an anti-pattern if you make it clear that the prop is only seed data for the component’s internally-controlled state.

Any help or better debugging advice would be great!
Thanks

**Comment by darthtrevino** [comment]
Hey Caitlin,
It looks like in FormBuilder.js, line 132 you're not setting the `removeQuestion` prop, but you are setting `removeCard`. 

```
removeCard={this.removeCard}
```

if you change this to 

```
removeQuestion={this.removeQuestion}
```
then the function is defined and it appears to work as expected

**Comment by CaitlinSweeney** [comment]
Thanks so much @darthtrevino . That's what I get for not going line-by-line first after renaming my functions 🙄
