### ISSUE TITLE
this is a example about handles,but it don't work

### ISSUE THREAD

**Issue by v5zz** [react-dnd/react-dnd#1299]
import React from 'react'
import {DragSource, DragDropContext, DropTarget} from 'react-dnd'
import ItemTypes from './ItemTypes'
import HTML5Backend from 'react-dnd-html5-backend';

let dragingIndex = -1;

const style = {
  border: '1px dashed gray',
  padding: '0.5rem 1rem',
  marginBottom: '.5rem',
  backgroundColor: 'red',
  width: '20rem',
}
const handleStyle = {
  backgroundColor: 'green',
  width: '1rem',
  height: '1rem',
  display: 'inline-block',
  marginRight: '0.75rem',
  cursor: 'move',
}

class BoxWithHandle extends React.Component {
  render() {
    const {
      isDragging,
      connectDragSource,
      connectDropTarget,
      connectDragPreview,
      item,
    } = this.props;
    console.log('this.props', this.props)
    const opacity = isDragging ? 0.4 : 1;

    return connectDropTarget(connectDragPreview(
      <div style={Object.assign({}, style, {opacity})}>
        {connectDragSource(<div style={handleStyle}/>)}
        Drag me by the handle{item.name}
      </div>,
    ))
  }
}

const CardSource = {
  beginDrag(props, monitor, component) {
    dragingIndex = props.index;
    console.log('dragingIndex', dragingIndex)
    return {
      index: props.index,
    };
  },
  endDrag(props, monitor, component) {
 
  },

  canDrag(props, monitor) {
  

  isDragging(props, monitor) {
   
  }
};

const CardTarget = {
  drop(props, monitor, component) { 
    const dragIndex = monitor.getItem().index;
    const hoverIndex = props.index;
    console.log('adaa', props, component)
    //...
    props.moveRow(dragIndex, hoverIndex);

  },

  canDrop(props, monitor) { 
    //...
  },

  hover(props, monitor, component) {
    //...
  },

};

const DragableBodyRow = DropTarget(
  ItemTypes.BOX,
  CardTarget,
  (connect, monitor) => ({
    connectDropTarget: connect.dropTarget(),
    isOver: monitor.isOver(),
  }),
)(
  DragSource(
    ItemTypes.BOX,
    CardSource,
    (connect, monitor) => ({
      connectDragSource: connect.dragSource(),
      dragRow: monitor.getItem(),
      connectDragPreview: connect.dragPreview(),
    }),
  )(BoxWithHandle),
);

class Container extends React.Component {
  constructor(props) {
    super(props)
    this.state = {
      data: data
    }
  }

  moveRow = (dragIndex, hoverIndex) => {
    const {data} = this.state;
    const dragRow = data[dragIndex];
    console.log('dragIndex, hoverIndex', dragIndex, hoverIndex)
    this.setState(
      update(this.state, {
        data: {
          $splice: [[dragIndex, 1], [hoverIndex, 0, dragRow]],
        },
      }),
    );
  }

  render() {
    return (
      <div>
        {
          data.map((item, i) => {
            return (
              <DragableBodyRow key={i} item={item} moveRow={this.moveRow} index={i}/>
            )
          })
        }
      </div>
    )
  }
}

module.exports = DragDropContext(HTML5Backend)(Container);

const data = [
  {
    name: '1',
  }, {
    name: '2'
  }
]

**Comment by darthtrevino** [comment]
Can you please put this in a code sandbox to demonstrate what issue you're running into?

CodeSandbox.io will let you set up a React Application with `create-react-app`, and you can find react-dnd and react-dnd-html5-backend in their "add dependencies" button.

**Comment by darthtrevino** [comment]
https://codesandbox.io/s/github/react-dnd/react-dnd/tree/gh-pages/examples_js/05-customize/handles-and-previews

**Comment by v5zz** [comment]
> https://codesandbox.io/s/github/react-dnd/react-dnd/tree/gh-pages/examples_js/05-customize/handles-and-previews

hello,this is my demo.https://codesandbox.io/s/vmx385vm4l?fontsize=14
