### ISSUE TITLE
currentOffset and initialOffset null in CustomDragLayer, causing flickering in DragAround: Custom Drag Layer example

### ISSUE THREAD

**Issue by starakaj** [react-dnd/react-dnd#1301]
Hi all, React DnD is great, thanks for all your hard work.

**Describe the bug**
The Drag Around: Custom Drag Layer example says that using a custom drag layer will get rid of the flickering that can happen with a native drag layer. However, the example is still flickering for me, in both Chrome and Firefox. It's hard to see if you don't disable the rotation in the custom drag layer, but if you comment out the rotation you'll see it right away.

**To Reproduce**
1. Go to http://react-dnd.github.io/react-dnd/examples/drag-around/custom-drag-layer
2. Drag around the box that says "Drag me around"
3. See a flicker right when you drop, where the box disappears for a simple frame.
4. If you're having trouble seeing it, add an endDrag method to the implementation in DraggbleBox.tsx and put a breakpoint in it. When that breakpoint gets hit, you'll see the one frame where the box isn't drawn.

**Expected behavior**
Dragging an element around, with a Custom Drag Layer, shouldn't have any flickering.

**Desktop (please complete the following information):**
 - OS X 10.13.3 (High Sierra)
 - Chrome 73.0.3683.86 and Firefox 62.0
 - React Dnd v7.3.2

**Additional context**
Near as I can tell, the flicker is happening when CustomDragLayer renders after a drop occurs. There's a call to render where `initialOffset` and `currentOffset` are both null, and yet `isDragging` is true. This causes the style for the layer item to include `{display: none}`, which is what makes it flicker. You can hack a fix by doing something like this:

```
let cachedInitialOffset: XYCoord | undefined
let cachedCurrentOffset: XYCoord | undefined

const CustomDragLayer: React.SFC<CustomDragLayerProps> = props => {
	const { item, itemType, isDragging } = props

	if (!isDragging || props.currentOffset !== null) {
		cachedInitialOffset = props.initialOffset
		cachedCurrentOffset = props.currentOffset
	}

	const newProps = Object.assign({}, props, {
		currentOffset: cachedCurrentOffset,
		initialOffset: cachedInitialOffset,
	})

	function renderItem() {
		switch (itemType) {
			case ItemTypes.BOX:
				return <BoxDragPreview title={item.title} />
			default:
				return null
		}
	}

	if (!isDragging) {
		return null
	}
	return (
		<div style={layerStyles}>
			<div style={getItemStyles(newProps)}>{renderItem()}</div>
		</div>
	)
}
```

But that's of course not a real solution. Thanks for looking at this!

**Comment by ggeugene** [comment]
Thanks! That solutions did save my day
