### ISSUE TITLE
this is a demo with handles,it don`t  work , could you help me

### ISSUE THREAD

**Issue by v5zz** [react-dnd/react-dnd#1302]
https://codesandbox.io/s/vmx385vm4l?fontsize=14

**Comment by darthtrevino** [comment]
So from the outset, I see that `canDrag` needs to return `true` in your CardSource. This will make the boxes Draggable. 

I don't have the time to edit your example to be a fully functioning one.

I've sent you samples that do exactly what you're trying to do, and these features are described in the documentation.
