### ISSUE TITLE
TS: DragObjectWithType not compatible with NativeTypes

### ISSUE THREAD

**Issue by renchap** [react-dnd/react-dnd#1305]
**Describe the bug**
When using HTML5Backend's NativeTypes, the drag object does not contain a `type` field, which is not compatible with `useDrop`'s typings

**To Reproduce**
```ts
useDrop({
    accept: NativeTypes.FILE,
    drop: (e: { files: File[] }) => {…})
})
```

You get this error: `Property 'files' is missing in type 'DragObjectWithType' but required in type '{ files: File[]; }`

When you add the type field (which does not really exists) it works: `drop(e: { type: typeof NativeTypes.FILE, files: File[] }) => {…})`

**Expected behavior**
`DragObjectWithType` should be compatible with `NativeTypes.FILE` drag objects, which do not contain a `type` key. This `type` key is not currently mandatory in your custom drag objects either, so I dont understand why it is made mandatory here. From what I understand, the correct way to get an item's type is to call `monitor.getItemType()`.

**Comment by renchap** [comment]
I am not sure how it could be modeled in typescript, but it would be great if there was a way to correctly type this function when doing something like this:
```ts
drop: (
      e:
        | { type: "image"; imageId: string }
        | { type: typeof NativeTypes.FILE; files: File[] }, monitor
    ) => {
      switch(monitor.getItemType()) {
        case "image": {
          // here TS does not know that type = "image", so imageId exists
          const image = props.items[e.imageId]
      }
      …
    }
```

**Comment by AO19** [comment]
This needs to be open and adressed!

**Comment by vhcord** [comment]
i need this
