### ISSUE TITLE
endsWith needs to be polyfilled

### ISSUE THREAD

**Issue by renchap** [react-dnd/react-dnd#1309]
**Describe the bug**
The new hooks implementation uses `string.prototype.endsWith`, which is [not supported in every browser](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/endsWith) (for example IE11). This should be polyfilled or replaced with an ES5 alternative.

https://github.com/react-dnd/react-dnd/blob/1d7207e44fb0f424615ede0da079a43dc53b8f14/packages/react-dnd/src/wrapConnectorHooks.ts#L51

**To Reproduce**
Open a page using Hooks in IE11, see error in console

**Expected behavior**
react-dnd should work in IE11

**Desktop (please complete the following information):**
 - OS: Windows 8.1
 - Browser IE
 - Version 11

**Comment by darthtrevino** [comment]
Why not polyfill on the client side? Maybe we can put together a document of required polyfills to work in IE11.

**Comment by renchap** [comment]
Expliciting the browsers `react-dnd` supports as well as the needed polyfills, but it needs to be a major version bump with an explicit message in the changelog.

**Comment by darthtrevino** [comment]
Ahh, that's a fair point

**Comment by darthtrevino** [comment]
@renchap Can you give that PR a quick review?

**Comment by renchap** [comment]
Sorry just saw the notification, and you already released a fix!
Thanks :)
