### ISSUE TITLE
File DropTarget fails after updating to 7.4.0

### ISSUE THREAD

**Issue by rhys-vdw** [react-dnd/react-dnd#1310]
**Describe the bug**
My file dropzone fails on initial mount after upgrading the following:

react-dnd: 7.0.2 -> 7.4.3
react-dnd-html5-backend: 7.0.2 -> 7.4.0

**Code (unchanged)**

```ts
import { ComponentClass, ReactElement, StatelessComponent } from "react"
import {
  ConnectDropTarget,
  DragDropContext,
  DropTarget,
  DropTargetSpec,
} from "react-dnd"
import HTML5Backend, { NativeTypes } from "react-dnd-html5-backend"
import { compose } from "redux"
import validateFiles, { ValidateFilesResult } from "Services/validate-files"
import { Omit } from "Types"

interface ImplProps {
  allowedMimeTypes: ReadonlyArray<string>
  maximumSizeInBytes: number
  maxFiles: number
  onFilesSelected: (validatedFiles: ValidateFilesResult) => void
  children: (isOver: boolean) => ReactElement<any>
  canDrop: boolean
  connectDropTarget: ConnectDropTarget
  isOver: boolean
}

const FileInputDropZoneImpl: StatelessComponent<ImplProps> = props => {
  const { connectDropTarget, isOver, children } = props
  return connectDropTarget(children(isOver))
}

const target: DropTargetSpec<ImplProps> = {
  drop(props, monitor) {
    const { files } = monitor.getItem()
    const {
      allowedMimeTypes,
      maximumSizeInBytes,
      maxFiles,
      onFilesSelected,
    } = props

    onFilesSelected(
      validateFiles(files, { allowedMimeTypes, maximumSizeInBytes, maxFiles })
    )
  },
}

type Props = Omit<ImplProps, "canDrop" | "isOver" | "connectDropTarget">

export const FileInputDropZone: ComponentClass<Props> = compose(
  DragDropContext(HTML5Backend),
  DropTarget(NativeTypes.FILE, target, (connect, monitor) => ({
    connectDropTarget: connect.dropTarget(),
    isOver: monitor.isOver(),
    canDrop: monitor.canDrop(), // <-- ERROR thrown from here!
  }))
)(FileInputDropZoneImpl)
```

**Expected behavior**

Component should mount without error.

**Screenshots**

![image](https://user-images.githubusercontent.com/822105/55379510-3163cc00-54d2-11e9-9deb-1258d1db7e0d.png)

Trace:

```
TypeError: "handlerId is null"
    parseRoleFromHandlerId HandlerRegistryImpl.js:21
    isTargetId HandlerRegistryImpl.js:93
    getTarget HandlerRegistryImpl.js:77
    canDropOnTarget DragDropMonitorImpl.js:59
    canDrop React
```

FileInputDropZone file-input-drop-zone.tsx:53 getCurrentState14React

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.2
 - Browser: Firefox, Chrome
 - Version (see "describe the bug")

**Additional context**

(nothing comes to mind)

**Comment by darthtrevino** [comment]
@rhys-vdw - would you mind putting together a CodeSandbox to reproduce this?

**Comment by rhys-vdw** [comment]
@darthtrevino I'll see what I can do.

**Comment by darthtrevino** [comment]
@rhys-vdw So I checked out the related issue, and cut v7.4.4. If you're still running into issues when using that then let me know

**Comment by rhys-vdw** [comment]
Not reproducing in CodeSandbox. Must be something specific to our setup. I'll try the update, thanks.

**Comment by rhys-vdw** [comment]
> I checked out the related issue

What was the related issue, sorry @darthtrevino?

**Comment by rhys-vdw** [comment]
The stack trace fails when `monitor.canDrop()` is called from the `DropTarget` callback.

![image](https://user-images.githubusercontent.com/822105/55442004-ae8a5200-5561-11e9-9e61-505a013dfc7c.png)

Here `this.targetId` is `null`. I set a breakpoint in `receiveHandlerId` and it is apparently never called.

**Comment by darthtrevino** [comment]
My bad - I mixed this issue up with another one that was cut recently, I don't think this one is related

**Comment by darthtrevino** [comment]
Are you still seeing it in 7.4.4?

**Comment by rhys-vdw** [comment]
I am, yes.

**Comment by darthtrevino** [comment]
Since you've got the debugger open - can you check decorateHandler.tsx and observe receieveProps()? Does it exit because handler is null?

**Comment by rhys-vdw** [comment]
@darthtrevino Yes, that's what's happening.

**Comment by darthtrevino** [comment]
So I'm poking around this trying to make sense of it, when the DropTargetMonitor calls the internalMonitor, the internal monitor should just return false because the handlerId is null

https://github.com/react-dnd/react-dnd/blob/master/packages/dnd-core/src/DragDropMonitorImpl.ts#L89

Can you observe what's happening in canDropOnTarget?

**Comment by rhys-vdw** [comment]
Will do no now. (I pinged you on gitter if you'd prefer chat)

**Comment by rhys-vdw** [comment]
Apologies. This was caused by a locked version of dnd-core in my package.json `"resolutions"` (unfortunately this is necessary due to some upstream issues in other packages). Thanks again for your help @darthtrevino!
