### ISSUE TITLE
react-dnd 7.4.4 breaks build.

### ISSUE THREAD

**Issue by mfklauberg** [react-dnd/react-dnd#1316]
**Describe the bug**

When using the react-dnd library with version 7.4.4, when building the project, it fails to compile due to react-dnd `DragLayer` trying and failing to resolve `lodash/isPlayObject`.

**To Reproduce**

1. Add react-dnd to a project;
2. Build/compile the project;
3. See error

**Expected behavior**

The build should not fail due to react-dnd usage.

**Screenshots**
![Screen Shot 2019-04-03 at 10 48 30](https://user-images.githubusercontent.com/10942649/55484190-72f19580-55fe-11e9-9ae3-c1362adfe2c6.png)

**Desktop (please complete the following information):**
 - OS: OSX 10.14.3
 - Browser Node environment
 - Version 7.4.4

**Additional context**
The problem seems to be the [DragLayler.tsx](https://github.com/react-dnd/react-dnd/blob/master/packages/react-dnd/src/DragLayer.tsx#L14) file, which is requiring `lodash/isPlainObject` even through it was removed in [this](https://github.com/react-dnd/react-dnd/pull/1294) PR.

**Comment by mfklauberg** [comment]
I've open the #1317 Pull Request to solve this issue. Please let me know if there's anything else that I need to do!

**Comment by darthtrevino** [comment]
@mfklauberg thanks for the pr! I've included this in 7.4.5
