### ISSUE TITLE
React component's "key" property is vaporizing.

### ISSUE THREAD

**Issue by drleon** [react-dnd/react-dnd#1327]
**Describe the bug**
Key property from react component is vaporizing.

**To Reproduce**
`<Issue id={issue.id} key={issue.key} />`

"key" property is set but missing in Issue constructor. Im using connectDragSource, DragSource.
Other properties goes without a problem.

"react-dnd": "^7.4.5",
"react-dnd-html5-backend": "^7.4.4",

**Expected behavior**
All properties from component JSX markup are passed to constructor.

**Desktop (please complete the following information):**
Chromium
Version 73.0.3683.86 (Official Build) Built on Ubuntu , running on LinuxMint 18.3 (64-bit)

**Additional context**

**Comment by RobPethick** [comment]
This is a React issue, the key prop is never passed through to a component it is a special prop

https://reactjs.org/docs/lists-and-keys.html#keys

**Comment by drleon** [comment]
OK, thx
