### ISSUE TITLE
Cascading updates on DragSource causing performance issues

### ISSUE THREAD

**Issue by diagramatics** [react-dnd/react-dnd#1332]
**Describe the bug**
https://github.com/react-dnd/react-dnd/blob/5fefffc8c6c1ceced3aa0356fd869354ad74734a/packages/react-dnd/src/decorateHandler.tsx#L100-L105

In `componentDidMount` on `DragDropContainer`, `this.handleChange()` will be called with no initial state (`this.state === null`), this causes `handleChange()` to call `setState()` which causes a cascading update and another React reconciliation process.

**To Reproduce**
1. CodeSandbox has the template for the simplest example provided in this repo: https://codesandbox.io/s/github/react-dnd/react-dnd/tree/gh-pages/examples_js/01-dustbin/copy-or-move. Open the result in a new window and open DevTools to profile the load times. I'm using Chrome DevTools in this case to look at the React Timings output.
1. Profile the load time. You should see this in the React Timing from React warning about cascading updates.
![image](https://user-images.githubusercontent.com/5153378/56561900-8388a080-65eb-11e9-9e00-f6bdf335cc2c.png)

**Expected behavior**
I've skimmed the code and the lifecycles a bit and I think it can be improved fairly easily? I get that `componentDidMount` calls `handleChange` to set state values derived from the context consumer on `DragDropContext`, but it looks like `this.state` is only being used for memoizing the derived values and simultaneously calling it to trigger a new render if any of the dependant values change? Triggering a new render probably shouldn't be done on `componentDidMount` since the evaluation of `handleUpdate` will always trigger another render with the value of `this.state` being `null` from the start? Maybe we can set a default value somehow derived from the context to set to the state initially to avoid rerendering at the start.

I made this issue mainly to discuss whether or not I'm understanding the code wrong and it can't be done, or is it a simple fix (or we all agree this performance bottleneck needs to be solved). Either way let me know if I made a mistake in understanding it.

**Additional context**
FYI cascading updates seem to happen on `DropTarget` as well as the update cycle of these components as well. I'm omitting those issues from this particular one right now. 

For an example of a real world scenario impacted by this bug, my case is on mounting a new `DragSource` for an image loaded dynamically, and this causes the callback to the image being loaded (`onload` or React state updates) taking more than 50ms to process.

Thanks for all the work you've done in this <3

**Comment by gustavohenke** [comment]
There's a PR for it (#1336), shouldn't be marked as wontfix, but the stale bot doesn't know it 😄
