### ISSUE TITLE
Is there some magic way that  i run this project example ?

### ISSUE THREAD

**Issue by OhIAmFine** [react-dnd/react-dnd#1333]
**Describe the bug**
I even can not run this project with your instruction in the docs.
![image](https://user-images.githubusercontent.com/10390004/56563631-c1cb9300-65de-11e9-9cb7-d6a484e74046.png)
 I follow the way to run, but get wrong infomation in the following image.
![image](https://user-images.githubusercontent.com/10390004/56563766-1e2eb280-65df-11e9-9ab3-7ad70144b9e5.png)

**Comment by ShadowMitia** [comment]
I had the same issue. I resolved it by running `yarn build` before `yarn start`

**Comment by OhIAmFine** [comment]
@ShadowMitia  I tried two ways in this documetation ,but get failed.

**Comment by lichchao** [comment]
@ShadowMitia I got the same proplem, and your solution is ok, thx

**Comment by OhIAmFine** [comment]
@lichchao I think it may be these error files that do not contain in this git repository, so got this error

**Comment by OhIAmFine** [comment]
I follow his comment, `rm -rf node_modules` then 
```
yarn install
yarn build
yarn start
```
get success.
I will close this issue , thx all.
