### ISSUE TITLE
the Sortable Simple example works so bad with react hooks

### ISSUE THREAD

**Issue by javahuang** [react-dnd/react-dnd#1340]
**Describe the bug**

https://codesandbox.io/s/w6oq4l7j25

with the [example](https://github.com/react-dnd/react-dnd/blob/master/packages/examples-hooks/src/04-sortable/simple/index.tsx)
the performance is horrible, how can i solve it?

**Comment by darthtrevino** [comment]
The performance issues on these examples are why the hooks are not recommended for production.

**Comment by benjy** [comment]
Are hooks still not supported, reading the docs here (http://react-dnd.github.io/react-dnd/about) it makes it look like hooks are the "Top Level API" and the old way is now considered "Legacy"?

**Comment by darthtrevino** [comment]
They are released now
