### ISSUE TITLE
react-dnd package contains arrow functions after version 7.0.2 which are not working in internet explorer 11

### ISSUE THREAD

**Issue by skottilaine** [react-dnd/react-dnd#1342]
After version 7.0.2 react-dnd stopped working for me in IE 11 (syntax error). I checked my bundled vendor script made with webpack and noticed it containing arrow functions, which are not working in IE11. After I downgraded back to version 7.0.2 the package started working again in IE11. 

I tested the chess game [https://react-dnd.github.io/react-dnd/examples/tutorial](url) with browserstack's IE11 which didn't seem to work either (syntax errors in console).

**Comment by LiamMartens** [comment]
Encountered the same issue. For now what I did is I adjusted the `exclude` in webpack so it would also transpile `react-dnd` even though it is in `node_modules`. Something like this
```
{
  test: /\.(jsx?)$/,
  exclude: /node_modules\/(?!react-dnd)/,
  loaders: [
    ...
  ],
},
```

**Comment by sarcastron** [comment]
This was breaking webpack-uglify-plugin for the same reason. I had to drop to `react-dnd@7.4.5` but dropping to that version alone didn't fix it. I had to also had to manually install the `dnd-core` sub-dependency to get IE 11 working again.

Here are the versions I needed to avoid fat arrow functions getting into the `vendor.bundle.js` file.

```sh
> npm list dnd-core
global-js@0.1.0 C:\Users\agp\repos\am5\AM5\src
+-- dnd-core@7.4.4
+-- react-dnd@7.4.5
| `-- dnd-core@7.4.4  deduped
`-- react-dnd-html5-backend@7.4.4
  `-- dnd-core@7.4.4  deduped
```

**Comment by chrisbutler** [comment]
here's how i used @sarcastron's fix via yarn:

```
  "dependencies": {
    "react-dnd": "7.4.5",
    "react-dnd-html5-backend": "7.4.4",
  },
  "resolutions": {
    "dnd-core": "7.4.4"
  }
```

**Comment by darthtrevino** [comment]
https://github.com/react-dnd/react-dnd/releases/tag/v7.7.0
