### ISSUE TITLE
Can't filter by folder or file an upload action by DnD

### ISSUE THREAD

**Issue by ClementeSerrano** [react-dnd/react-dnd#1345]
**Describe the bug**
It seems there is not a standard way of checking if we're dropping a file or a folder. I was trying with the `type` prop (for folders is an empty str) but there are some files that also have `""` types. See https://github.com/ipfs-shipyard/ipfs-webui/pull/931 for more details of the issue.

**To Reproduce**
1. Select any folder from your OS.
2. Drag and drop it to a droppable component in your React app.
3. If you have any logic behind it, you will not be able to filter by folder or file the upload process.

**Expected behavior**
A clear and safely way to distinguish between files and folders when uploading by DnD.

**Screenshots**
N/A.

**Desktop (please complete the following information):**
 - OS: `macOS Mojave`
 - Browser : `Chrome`.
 - Version `73.0.3683.103 (Official Build) (64-bit)`

**Additional context**
N/A.

**Comment by evshiron** [comment]
I managed to get it working.

It is noting that `DataTransferItemList` and `DataTransferItem` will change between event cycles. To work around this, you need to get `Entries` before jumping into next cycle:

```javascript
drop: (props, monitor, component) => {
  const entries = Array.from(monitor.getItem().items).map(item => item.webkitGetAsEntry());
  component.handleEntries(entries);
},
```
