### ISSUE TITLE
Uncaught Invariant Violation: When clientOffset is provided, getSourceClientOffset must be a function.

### ISSUE THREAD

**Issue by yaswanthsvist** [react-dnd/react-dnd#1348]
**Describe the bug**
I am getting this error at the begin of drag, this is seen in production environment. In development environment drag source just work's fine.
```
Uncaught Invariant Violation: When clientOffset is provided, getSourceClientOffset must be a function.
    at e.exports (http://localhost/ispring/workbench/process/main.js:110:83255)
    at e.<anonymous> (http://localhost/ispring/workbench/process/main.js:120:893928)
    at Object.o.<computed> [as beginDrag] (http://localhost/ispring/workbench/process/main.js:120:891213)
    at handleTopDragStart (http://localhost/ispring/workbench/process/main.js:120:876572)
```

**To Reproduce**
npm install react-dndn and html5-baackend in Project A, and import Project A as a npm module in Project B, 
With Project A there is no problem running it in either production or development.
But with Project B we are facing issue with webpack running in production mode.

**Expected behavior**
If i use react-dnd and html5-backend in Project A and import this Project A library in Project B,and run in webpack production mode the react-dnd should run without errors.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 74

**Additional context**
in `package.json`
```
    "webpack": "^4.17.1",
    "webpack-cli": "^3.1.0",
    "webpack-dev-server": "^3.1.7"
    "react-dnd": "^7.4.5",
    "react-dnd-html5-backend": "^7.4.4"
```
```
"scripts": {
    "dev": "webpack-dev-server --mode production --config webpack/webpack.dev.js --open",
```

**Comment by rmeschian** [comment]
I'm seeing this as well and only in production.  Any ideas regarding how this can be fixed?

**Comment by yaswanthsvist** [comment]
@rmeschian 
Temporary Solution:  I had disabled `minimize` optimization in web-pack to make this issue resolved.
also try this.
```
optimization: {
    minimizer: [
      new UglifyJsPlugin({
        chunkFilter: chunk => {
          if (
            typeof chunk.name === 'string' &&
            chunk.name.indexOf('vendors') !== -1
          ) {
            return false;
          }
          return true;
        }
      })
    ]
  },
```

**Comment by b-j-p** [comment]
I am seeing this error too, and @yaswanthsvist 's solution works 🙏 , but it leaves my `vendors.bundle` exceeding the recommended size limit (all by itself!!!).

**Comment by ViggoV** [comment]
None of the above solutions seem to work for me. Only disabling the minimizer completely:

```javascript
optimization: {
    minimize: false;
}
```
