### ISSUE TITLE
Memory leak for unmounted components

### ISSUE THREAD

**Issue by alexander-dmitriev** [react-dnd/react-dnd#1349]
**Describe the bug**
When the DragSource-component is unmounted, the unsubscribe function (https://github.com/react-dnd/react-dnd/blob/master/packages/react-dnd-html5-backend/src/HTML5Backend.ts#L121) is not called.

**To Reproduce**
1. Open example from link: https://codesandbox.io/s/memory-leak-reactdndhtml5backend-64y8r
or manually execute this code:
```js
import React from "react";
import ReactDOM from "react-dom";
import { DragDropContextProvider, DragSource } from "react-dnd";
import HTML5Backend from "react-dnd-html5-backend";

const Draggable = DragSource(
  "",
  {
    beginDrag() {},
    endDrag() {}
  },
  connect => ({
    connectDragSource: connect.dragSource()
  })
)(({ connectDragSource }) => <div ref={connectDragSource} />);

let backend;

class App extends React.Component {
  constructor(props) {
    super(props);
    this.state = { cnt: 1 };
    setInterval(() => this.setState({ cnt: this.state.cnt + 1 }), 10);
  }

  render() {
    return (
      <>
        sourceNodes in memory: {backend.sourceNodes.size}
        {this.state.cnt % 2 === 0 && <Draggable />}
      </>
    );
  }
}

ReactDOM.render(
  <DragDropContextProvider backend={m => (backend = HTML5Backend(m))}>
    <App />
  </DragDropContextProvider>,
  document.getElementById("root")
);
```
2. The number of sourceNodes in memory strictly increases to infinity.

**Expected behavior**
The number of sourceNodes does not increase above the actual number of components.

**Screenshots**
![test](https://user-images.githubusercontent.com/14834350/57914701-d6c2db80-7897-11e9-866d-d5c02a71ced1.gif)

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 74

**Additional context**
 - react: 16.8.6
 - react-dom: 16.8.6 
 - react-dnd: 7.4.5
 - react-dnd-html5-backend: 7.4.4

**Comment by upsuper** [comment]
FWIW this happens to `react-dnd-touch-backend` as well but for `DropTarget` instead.

A modified testcase: https://codesandbox.io/s/memory-leak-reactdndtouchbackend-85wru

Code below:
<details>

```javascript
import React from "react";
import ReactDOM from "react-dom";
import { DragDropContextProvider, DropTarget } from "react-dnd";
import TouchBackend from "react-dnd-touch-backend";

const Droppable = DropTarget("", {}, connect => ({
  connectDropTarget: connect.dropTarget()
}))(({ connectDropTarget }) => <div ref={connectDropTarget} />);

let backend;

class App extends React.Component {
  constructor(props) {
    super(props);
    this.state = { cnt: 1 };
    setInterval(() => this.setState({ cnt: this.state.cnt + 1 }), 10);
  }

  render() {
    return (
      <>
        targetNodes in memory: {Object.keys(backend.targetNodes).length}
        {this.state.cnt % 2 === 0 && <Droppable />}
      </>
    );
  }
}

ReactDOM.render(
  <DragDropContextProvider backend={m => (backend = TouchBackend()(m))}>
    <App />
  </DragDropContextProvider>,
  document.getElementById("root")
);
```

</details>

And after inspecting the code, we have come up with a solution to this issue. I'll probably submit a PR maybe tomorrow.
