### ISSUE TITLE
Drag-and-drop of text into input field does not work when react-dnd context is rendered

### ISSUE THREAD

**Issue by jseminck** [react-dnd/react-dnd#1351]
**Describe the bug**
Without react-dnd, I am able to drag and drop text from another application into an input field which is outside of ReactDndContext

![drag-drop-text-without-react-dnd](https://user-images.githubusercontent.com/9586897/57965233-337ece80-794a-11e9-993b-d95ef86d6463.gif)

But with react-dnd it doesn't work anymore

![drag-drop-text-with-react-dnd](https://user-images.githubusercontent.com/9586897/57965235-35489200-794a-11e9-981c-9e9dd9edab4e.gif)

**To Reproduce**
https://codesandbox.io/s/8ljmzn88n2

**Expected behaviour**
I'd still expect the drag-and-drop to work with text.

**Screenshots**

**Desktop (please complete the following information):**
- MacOS
- Latest Chrome

**Additional context**
If you have any ideas where the issue would be in the code, let me know. I am happy to dig in myself but some directions would be useful.

**Comment by darthtrevino** [comment]
Try using DndProvider
https://codesandbox.io/embed/react-dnd-example-11-7gdep
