### ISSUE TITLE
Specification methods do not receive stateful component as argument

### ISSUE THREAD

**Issue by smurn** [react-dnd/react-dnd#1353]
**Describe the bug**

`component` argument passed to specification methods, such as `hover`, is `null`. Even if the component is a class component. 

It only happens if the component's `render` method is defined with an arrow function expression.

**To Reproduce**

    class MyComponent extends React.Component {
        render = () => {
            const {connectDropTarget} = this.props;
            return connectDropTarget(<p>hello</p>);
        }
    }
    
    export default DropTarget(MY_TYPE, {
        hover(props, monitor, component){
            // component is null in here
        }
    }, (connect, monitor) => {
        return {
            connectDropTarget: connect.dropTarget(),
        }
    })(MyComponent);

If `render` is instead declared as `render() {...}` everything works as expected.

**Expected behavior**
`hover` should receive a reference to an instance of `MyComponent`.

**Possible cause**
This appears to be caused by `react-dnd/src/utils/isRefable.ts`:  `isClassComponent`. `Component.prototype.render` is undefined when the `render` method is declared with an arrow expression. It comes to the wrong conclusion that the component is state-less, and does not register the `ref` required to get the component reference.

**Desktop (please complete the following information):**
 - OS: win10
 - Browser chrome & firefox
 - react-dnd: 7.4.5
 - react-dnd-html5-backend: 7.4.4

**Comment by xuzhongpeng** [comment]
I also have this situation, how to solve it
