### ISSUE TITLE
Merge in react-dnd-touch-backend

### ISSUE THREAD

**Issue by longlho** [react-dnd/react-dnd#1363]
Hi guys,

I maintain https://github.com/yahoo/react-dnd-touch-backend and am thinking of merging that into this monorepo to further optimize the maintenance cost personally. If you guys are open to that, let me know what needs to be done to fit in your toolchain.

Cheers,

LH

**Comment by longlho** [comment]
ping @darthtrevino

**Comment by darthtrevino** [comment]
Hey @longlho , I would be open to doing this. That being said i'd like to find a new steward or stewardship group of this project who is actively using it it scale. I have not been using this project for a while, and I'm basically just maintaining it as community service.

**Comment by longlho** [comment]
Dropbox is using this for some of our product so I think we can definitely help out.

**Comment by longlho** [comment]
@darthtrevino 	should I just make the PR?

**Comment by darthtrevino** [comment]
Yep, that sounds like a reasonable place to start

**Comment by darthtrevino** [comment]
@longlho, can you grant me publication permissions on npm?

**Comment by longlho** [comment]
done
