### ISSUE TITLE
React.memo is not a function

### ISSUE THREAD

**Issue by lamnt95** [react-dnd/react-dnd#1364]
I am getting a TypeError: React.memo is not a function when trying to add DragDropContextProvider to component. I am using React v16.3.1 and I am wondering if it's required to use React v16.8 to use react-dnd.

Here is my component where I am trying to add DragDropContextProvider.
Please Help Me ! Thanks you very much!!

![image](https://user-images.githubusercontent.com/34705561/58689277-c3902f80-83b0-11e9-9734-d347037491d8.png)

**Comment by darthtrevino** [comment]
I think I see issue. The DragPreviewImage component is using react.memo in its module definition. Unfortunately this means you have to use at least React 16.6
