### ISSUE TITLE
building react-dnd from source and importing into project doesnt seem to work

### ISSUE THREAD

**Issue by mx2323** [react-dnd/react-dnd#1371]
**Describe the bug**
I've cloned the react-dnd git tree locally on my machine and did 'yarn run build', which completes successfully , but when I try to use my locally built packages in my app react-dnd doesn't seem to work at all.

It appears as though all the source files exist and the code is running (i can set breakpoints inside of react-dnd) , but ultimately once I start the page I can't initiate drags. 

The app works correctly if I blow away my node_modules and do an 'npm install' and install react-dnd from the npm registry. 

I noticed that one of the differences is that in my app the dragSource has draggable=true when i use the NPM registry version, but draggable=false when I use the version that I compile from my local react-dnd tree. 

(This is with no changes to my react-dnd source tree)

Does anyone have any insights into why this might be happening?

**Comment by mx2323** [comment]
when i use my locally built version, the following breakpoint hits on load in HTML5Backend.js on line 453: 

```
    return function () {
      _this.sourceNodes.delete(sourceId);

      _this.sourceNodeOptions.delete(sourceId);

      node.removeEventListener('dragstart', handleDragStart);
      node.removeEventListener('selectstart', handleSelectStart);
      **node.setAttribute('draggable', 'false');**
    };
```


when i blow things away and run with the npm registry version of react-dnd, this line never gets triggered on load.

**Comment by mx2323** [comment]
it appears as though this is a regression in master. i reverted back to v7.4.5 and am not having this issue.

**Comment by darthtrevino** [comment]
Were you using connectDragSource() on a ref or a JSX element? There was an issue a couple of days ago on master where it was busted when using it on JSX

**Comment by mx2323** [comment]
`return this.props.connectDragSource(<div><Container /></div>)`

**Comment by darthtrevino** [comment]
Can you check this again with the latest on master?

**Comment by mx2323** [comment]
yeah ill try that later this week and close if appropriate

**Comment by darthtrevino** [comment]
Cool, thanks @mx2323

**Comment by mx2323** [comment]
@darthtrevino that appears to have fixed it! great stuff.
