### ISSUE TITLE
Wrong preview image on chrome app

### ISSUE THREAD

**Issue by Fiorello** [react-dnd/react-dnd#1376]
Hi, i've a problem with the drag preview image.
If i visit my pwa from web the expected behavior is correct, but if i open ma pwa as a [chrome app](https://developers.google.com/web/progressive-web-apps/) preview show only an image.

Maybe it's related to chrome web app on macos, i'll try on windows.

![wrong_preview](https://user-images.githubusercontent.com/3278942/58877882-36abe580-86d2-11e9-86ed-b2fe3a5791cc.gif)

1. Go to pwa url
2. Click to Settings > Other > Create Shortcut
3. Open from chrome app page
4. Reproduce drag action

 - OS: MacOS 10.14.4
 - Chrome  74.0.3729.169
 - Version 7.4.5

**Comment by Yulia-Arkan** [comment]
I have the same issue

**Comment by ShiChenCong** [comment]
same issue
