### ISSUE TITLE
[Uglifyjs Error] The dist file contains ES6 error in version 7.6.0 / 7.5.0

### ISSUE THREAD

**Issue by MickeyMiao7** [react-dnd/react-dnd#1387]
**Describe the bug**
When using uglifyjs to minify the size of the bundle, it failed becaulse the dist of react-dnd includes ES6 syntax. 
I find the problem occurs both in version 7.5.0 and 7.6.0. However, in 7.4.0, there is no problem. 

I checked that the compilation option "target: es5" does exist in tsconfig.json so I have no idea why it seems not work in 7.5.0 and 7.6.0 ...

**To Reproduce**
1.  npm run build 
2. Check the dist/ReactDnD.js and search for ES6 syntax, such as let / const /  () => 

**Expected behavior**
No ES6 syntax in the dist file

**Screenshots**
In ReactDnD.js:
![{968E8DE7-44B4-4E5A-BE5B-B09986DB8A29}_20190613152257](https://user-images.githubusercontent.com/13026247/59412220-85066600-8def-11e9-8780-706606923322.jpg)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 7.6.0, and also in 7.5.0

**Additional context**
No

**Comment by binhpv** [comment]
in Webpack configuration I have to add 

`	
resolve: {
		extensions: [".tsx", ".ts", ".js", ".json"],
		alias: {
 	 	 	"dnd-core": require.resolve("dnd-core/lib/cjs")
		}
	}`
and then it can resolve to ES5 version 

But this is an annoying fix.

**Comment by MickeyMiao7** [comment]
> in Webpack configuration I have to add
> 
> `	resolve: { extensions: [".tsx", ".ts", ".js", ".json"], alias: { "dnd-core": require.resolve("dnd-core/lib/cjs") } }`
> and then it can resolve to ES5 version
> 
> But this is an annoying fix.

thanks! it's kind of annoying but saves the day! 
hope there will be more elegant workaround

**Comment by maoqxxmm** [comment]
I'm facing the same problem.

**Comment by darthtrevino** [comment]
Oh gross - if you can cut a PR of the webpack conf in react-dnd that would be great. If not I'll try to make some time next week.

In the future I'd like to do away with the UMD builds and just publish esm output. I'd love to hear community opinions on that.

**Comment by Punith13** [comment]
Facing same issue

**Comment by binhpv** [comment]
> Oh gross - if you can cut a PR of the webpack conf in react-dnd that would be great. If not I'll try to make some time next week.
> 
> In the future I'd like to do away with the UMD builds and just publish esm output. I'd love to hear community opinions on that.

the issue we are having is webpack try to bundle esm module instead of cjs since the moment you added "module" to package.json. And our site doesn't run on IE anymore. Using a transpiler like babel is not feasible as our code is typescript based and adding it adds huge overhead in compile time :(

**Comment by binhpv** [comment]
Hi @darthtrevino the PR only fixes problem in your example but not problem from other project using react-dnd. Doesn't seems to be a real fix to the real issue don't you agree?

**Comment by darthtrevino** [comment]
How so? We corrected the UMD builds of react-dnd and react-dnd-html5-backend

**Comment by binhpv** [comment]
no the problem is not with UMD build. it's with "module" added to package.json and therefore webpack is bundling ESM version, which doesn't run on IE. This was added in https://github.com/react-dnd/react-dnd/commit/ead0bca30dc8dfebf65e3bb9c1ed02d2352beb2f#diff-d5468382cf3875957a18e720907ffe82 which to me is a breaking change. It should be done in 8.0.0 instead.

**Comment by darthtrevino** [comment]
I see, that's a good point - that probably should have gone in the major version cut. At this point I think it would probably do more hard than good to revert though.

**Comment by binhpv** [comment]
@darthtrevino  Can you be more specific what harm it could do ;)
We are building library with DnD capability, and with many customer using it. This changes cause all project on customer side failing to run on IE. I would really appreciate if you are ok with reverting it :)

I can submit a PR if you agree.

**Comment by darthtrevino** [comment]
Before we cut a 7.x branch for legacy maintenance, can you try out
react-dnd-cjs?

**Comment by binhpv** [comment]
@darthtrevino this require change in our customer code base, to import from new package so it's doesn't really solve the problem.

**Comment by darthtrevino** [comment]
I see - I suppose we can cut a patch 7.x version for this. It would be in a
new v7 branch though

**Comment by chrisbutler** [comment]
@darthtrevino appreciate all the work you're doing on this. just wanted to chime in and say that it would be ideal if the latest version of the packages available for `7.x` weren't broken for IE

this caused a huge headache for us and it's been especially frustrating because of the sub-dependency issue with `dnd-core` resolving to `7.6.0` even when the parent packages are locked at `7.4.5` (see https://github.com/react-dnd/react-dnd/issues/1418)

**Comment by darthtrevino** [comment]
I'll try to make some time tonight to cut a new 7.x patch version that reverts module support.

**Comment by darthtrevino** [comment]
https://github.com/react-dnd/react-dnd/releases/tag/v7.7.0

**Comment by hthomy** [comment]
Same problem exists with v8.0.3
