### ISSUE TITLE
npm run build   error

### ISSUE THREAD

**Issue by zhfzhuhaifeng** [react-dnd/react-dnd#1389]
> react-app-rewired build

Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file:

        ./node_modules/_react-dnd@7.6.0@react-dnd/lib/esm/utils/discount_lodash.
js:17

Read more here: http://bit.ly/2tRViJ9

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! stm-webapp@0.1.0 build: `react-app-rewired build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the stm-webapp@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

**Comment by rdavid369** [comment]
I am getting the same thing.  Trying to figure out why it is failing.

`
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file: 

        ./node_modules/react-dnd/lib/esm/utils/discount_lodash.js:17 

Read more here: http://bit.ly/2tRViJ9

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! land-acquisition-matching-game@0.1.0 build: `react-scripts build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the land-acquisition-matching-game@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
`
