### ISSUE TITLE
There is no version 7.0.2 in NPM packages

### ISSUE THREAD

**Issue by maoqxxmm** [react-dnd/react-dnd#1395]
**Describe the bug**
I found that there is a bug fix about "Fix UMD Builds to use CommonJS-based Libraries" in version 7.6.2. And it's important for my project. But in NPM packages, there is no version 7.6.2. It just jumped from 7.6.1 to 8.0.0.

**Expected behavior**
It will help a lot if you could release version 7.6.2 on NPM. Because it can help users who use `^7.x` in their `package.json`. But if you tell me, just update to version 8.0.0, I will accept this too.

**Screenshots**
![image](https://user-images.githubusercontent.com/18388484/59566050-278f4500-908d-11e9-9f8b-aca6fdd57df6.png)

**Comment by darthtrevino** [comment]
Hey @maoqxxmm , 7.6.1 contains the fix for the `react-dnd` package, and 7.6.2 applies that fix to `react-dnd-html5-backend`. Sorry for the confusion

Starting with 8.0, you can install `react-dnd-umd-builds` to get UMD versions of both.
