### ISSUE TITLE
v8.0 config with jest

### ISSUE THREAD

**Issue by zombieJ** [react-dnd/react-dnd#1396]
Since CommonJS has been removed in v8, it works fine with webpack but hard with jest. 

It makes `transformIgnorePatterns` need to config like `react-dnd`, `dnd-core`...

I'm not sure if its a correct time or little earlier to remove CommonJS version.

ref: https://github.com/facebook/jest/issues/4842

**Comment by darthtrevino** [comment]
Moving from CommonJS to ESModules is going to be a painful shift across the whole JavaScript ecosystem. Since this should improve bundler performance with Webpack, browsers are starting to support ES Modules, and NodeJS 12 is supporting ES Modules, I wanted to tackle this now.

That being said, I'd be open to adding some new packages here that would build out CommonJS.
`dnd-core-cjs`, `react-dnd-cjs`, `react-dnd-html5-backend-cjs`

**Comment by darthtrevino** [comment]
That being said, Jest support for ES Modules truly sucks hard right now. If that's still a major issue with Jest in a few months time I'd be genuinely surprised.

**Comment by wldcordeiro** [comment]
Adding a `transformIgnorePatterns` like this seems to *not* work

```js
    transformIgnorePatterns: [
      '/node_modules/?!(react-dnd)',
    ],
```

**Comment by govizlora** [comment]
@wldcordeiro 
```
transformIgnorePatterns: ['node_modules/(?!(react-dnd|dnd-core|react-dnd-html5-backend)/)']
```
Worked for my case. Hope it helps

**Comment by emgould** [comment]
transformIgnore doesnt help in my case.  Not sure what to try next

**Comment by darthtrevino** [comment]
Have you tried applying a moduleNameMapper? http://react-dnd.github.io/react-dnd/docs/testing

**Comment by emgould** [comment]
That did it.  Thanks!  Do you know why 9.3.3 is not in npm?

**Comment by darthtrevino** [comment]
The way Lerna publishes, not every package is released on every version. Only packages with recorded commits change during patch versions.

**Comment by emgould** [comment]
We use lerna for our monorepos.  We bump the versions in unison across all the packages and publish to npm.  So we don't ever have this situation.  Here is 9.3.3 as latest but only 9.3.2 is published.  We like having them all in sync.

**Comment by jestrickler** [comment]
I know this is an older issue, but I'm working on a library (create-react-library) which uses the react-keyed-file-browser that appears to be dependent on version 8.0 so I'm running into the old issue:
```
({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import HTML5Backend from './HTML5Backend';
                                                                                         ^^^^^^
SyntaxError: Cannot use import statement outside a module
```
The documents no longer contain information regarding this. Is it archived anywhere, or is there a newer solution?

**Comment by darthtrevino** [comment]
It's not necessary on newer versions, but you can find that configuration here
https://github.com/react-dnd/react-dnd/blob/2a50f87553676c770704f059244d1de8c4b5fc83/packages/documentation/docsite/markdown/docs/00%20Quick%20Start/Testing.md#setup

**Comment by pinkbunny1** [comment]
Since jest is not working with esmodules well, you need to add these configurations in jest.config.js

```
moduleNameMapper : {
        '^react-dnd$': 'react-dnd/dist/cjs',
        '^react-dnd-html5-backend$': 'react-dnd-html5-backend/dist/cjs',
        '^dnd-core$': 'dnd-core/dist/cjs',
}
```

**Comment by madhanhere** [comment]
> @wldcordeiro
> 
> ```
> transformIgnorePatterns: ['node_modules/(?!(react-dnd|dnd-core|react-dnd-html5-backend)/)']
> ```
> 
> Worked for my case. Hope it helps

I have added 
```allowJs: true``` in tsconfig.js compilerOptions
I worked for me

**Comment by RyanZhu1024** [comment]
> I know this is an older issue, but I'm working on a library (created with create-react-library) which uses the react-keyed-file-browser that appears to be dependent on version 8.0 so I'm running into the old issue:
> 
> ```
> ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import HTML5Backend from './HTML5Backend';
>                                                                                          ^^^^^^
> SyntaxError: Cannot use import statement outside a module
> ```
> 
> The documents no longer contain information regarding this. Is it archived anywhere, or is there a newer solution?

I'm having the same issue. Can't find any resource online for it. 
```
    "typescript": "^4.3.2",
    "react-dnd": "^16.0.1",
    "react-dnd-html5-backend": "^16.0.1",
    "jest": "^27.5.1",
```
```
node_modules/react-dnd-html5-backend/dist/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import { HTML5BackendImpl } from './HTML5BackendImpl.js';
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      13 |   Skeleton,
      14 | } from 'antd';
    > 15 | import { HTML5Backend } from 'react-dnd-html5-backend';
```
Need some help.
