### ISSUE TITLE
Doesn't compile for no reason

### ISSUE THREAD

**Issue by GriboryBogush** [react-dnd/react-dnd#1397]
**Describe the bug**
Failed to compile.
```
./node_modules/dnd-core/lib/reducers/index.js
Module parse failed: Unexpected token (12:16)
You may need an appropriate loader to handle this file type.
|             type: action.type,
|             payload: {
|                 ...action.payload,
|                 prevTargetIds: get(state, 'dragOperation.targetIds', []),
|             },
```
**Expected behavior**
Compile properly. I just imported DnD and added it like so
```
import { DndProvider } from 'react-dnd';
import HTML5Backend from 'react-dnd-html5-backend';

  <Provider store={store}>
    <DndProvider backend={HTML5Backend}>
      <App />
    </DndProvider>
  </Provider>
```

**Desktop:**
 - OS: IOS
 - Browser - chrome

Version:
`"react-dnd": "^8.0.0",
 "react-dnd-html5-backend": "^8.0.0",`

**Comment by darthtrevino** [comment]
To add some context here: in v8 we changed the default module format to ES Modules. This will be a painful transition across the JavaScript ecosystem. We've realized that this is a pain point for developers who expect CommonJS compatibility. To remedy this we're going to release CJS builds under `dnd-core-cjs`, `react-dnd-cjs`, `react-dnd-html5-backend-cjs`
