### ISSUE TITLE
Make component draggable and droppable at the same time

### ISSUE THREAD

**Issue by alexfrize** [react-dnd/react-dnd#1402]
Current version has bookmarks (top row) and places for them. When used drags bookmark from bookmarks row and drops it to place, everything works fine. But what if user drag one of the places and want to move it somewhere?

I wrapped PlaceForChart component both to DropTarget() and DragSource() and exported wrapped component. But it is not working properly. If a remove any of wrappers, it will work.

Currently when user tries to drag any of PlaceForChart components (orange), the component changes color (as expected), but doesn't move.

How to make it work?

I created a sandbox for better understanding:
https://codesandbox.io/s/quirky-glade-x4h51

**Comment by darthtrevino** [comment]
I'm not sure why the drag-previews are not rendering (I'd have to spend more time on it), but the drop action is occuring with the data you'd expect. If you log out the item in `endDrag`, you'll see that the bookmarks from the lower section are showing up in the logs.

**Comment by darthtrevino** [comment]
![Screen Shot 2019-06-17 at 4 36 35 PM](https://user-images.githubusercontent.com/113544/59643583-193d3980-911e-11e9-9469-b15716e0e184.png)
The actual dnd-objects are different between the two actions, too

**Comment by alexfrize** [comment]
Yes, they are different.
And you're right, drop functionality (DropTarget()) already works as expected.
The main issue is when I wrap DropTarget() to DragSource()  try to apply both of them.

This is the main question.

**Comment by darthtrevino** [comment]
You should be able to compose connectDragSource and connectDropTarget. The sortable example here uses that kind of composition:

https://codesandbox.io/embed/github/react-dnd/react-dnd/tree/gh-pages/examples_decorators_js/04-sortable/simple

**Comment by alexfrize** [comment]
I found a problem.
I changed key={Math.random()} in PlaceForChart.tsx and it started working. There are some other issues, but they are not related to dnd behavior. This was the main one.

Working version: https://codesandbox.io/s/billowing-wave-tjugx
