### ISSUE TITLE
Roolup integration

### ISSUE THREAD

**Issue by morlandi-jss** [react-dnd/react-dnd#1411]
Hi, I am trying to bundle my app using rollup, but I am facing a problem with React-dnd dependency. I've imported the React-dnd like that:

import {DropTarget, DropTargetConnector, DropTargetMonitor, DropTargetSpec} from 'react-dnd'; and when I build everything with rollup I get

[!] Error: 'DropTarget' is not exported by ....\node_modules\react-dnd\lib\index.js

In roolup this is a common error when a lib is not using a default export, but you can define a named export linking the exported name and the library path, something like:

namedExports: { 'node_modules/react-dnd/lib/index.js': ['DropTarget'] }

But yet it doesn't want to work, maybe react-dnd need some changes to works with roolup (or maybe I'm doing something wrong)?

**Comment by darthtrevino** [comment]
What version are you using? React-Dnd v8 ships with ES Modules, so those exports are present, but you may need to configure your bundler.
