### ISSUE TITLE
new-hotness ESModules + nextjs 8 + typescript

### ISSUE THREAD

**Issue by VienNguyen113** [react-dnd/react-dnd#1414]
**Describe the bug**
I have a project build up using nextjs v8 with typescript but I got a problem when importing apis from react-dnd 8.0.2

**Screenshots**
<img width="1228" alt="Screen Shot 2019-06-20 at 11 04 47 AM" src="https://user-images.githubusercontent.com/11764707/59817742-4ae71800-934b-11e9-82c3-e51ed5434fa1.png">

**Desktop (please complete the following information):**
 - MacOS Mojave 10.14.5

**Additional context**
 
<img width="703" alt="Screen Shot 2019-06-20 at 11 13 51 AM" src="https://user-images.githubusercontent.com/11764707/59818053-81716280-934c-11e9-89f4-1bf2705d81d3.png">

.babelrc: 
 ```{
  "presets": [
    "next/babel",
    "@zeit/next-typescript/babel",
  ],
}
```

dependencies: 
```"dependencies": {
    "@weco/next-plugin-transpile-modules": "^2.2.1",
    "next": "^8.1.0",
    "next-transpile-modules": "^2.3.1",
    "react": "^16.8.6",
    "react-dnd": "^8.0.2",
    "react-dnd-html5-backend": "^8.0.2",
    "react-dom": "^16.8.6"
  },
  "devDependencies": {
    "@zeit/next-css": "^1.0.1",
    "@zeit/next-sass": "^1.0.1",
    "@zeit/next-typescript": "^1.1.1",
    "next-compose-plugins": "^2.2.0",
    "webpack-merge": "^4.2.1"
  }
```
component: 
```import React from "react";
import { DndProvider } from "react-dnd";
import HTML5Backend from "react-dnd-html5-backend";

function Home() {
  return (
    <DndProvider backend={HTML5Backend}>
      <div>Welcome to Next.js!</div>
    </DndProvider>
  );
}

export default Home;
```

**Comment by webberwang** [comment]
```
{
"presets": [
"next/babel",
"@zeit/next-typescript/babel",
],
}
```

**Comment by yunstanford** [comment]
+1, having the same issue.

**Comment by webberwang** [comment]
+1 same here

**Comment by yunstanford** [comment]
And it works fine with webpack in my case, but failed with mocha.

**Comment by yunstanford** [comment]
^ @darthtrevino

**Comment by darthtrevino** [comment]
The v8 libraries are using ES Modules by default. It sounds like you need to use the `react-dnd-cjs` library instead
