### ISSUE TITLE
CodeSandbox examples - Problems with react-dnd dependency 8.0.1

### ISSUE THREAD

**Issue by freemagee** [react-dnd/react-dnd#1416]
**Describe the bug**
A number of the examples on CodeSandbox are not working because they are trying to load react-dnd@8.0.1

**To Reproduce**
Visit [The demo for sortable lists](https://codesandbox.io/s/github/react-dnd/react-dnd/tree/gh-pages/examples_hooks_js/04-sortable/simple?from-embed)

**Expected behavior**
For the example on CodeSandbox to load as expected

**Screenshots**
[Screen shot on Imgur](https://imgur.com/C8Y6Yn5)

**Additional context**
Changing the dependency in package.json to 8.0.2 solved the problem

"react-dnd": "8.0.2",
 "react-dnd-html5-backend": "8.0.2",

**Comment by darthtrevino** [comment]
It sounds like this has to do with how lerna publishes packages. If a particular package has not changed since it was last released, lerna won't republish it. But if a package changes and it affects its dowstream dependencies, lerna will publish all affected packages.
