### ISSUE TITLE
Breaking changes released in 7.5.0 minor version update

### ISSUE THREAD

**Issue by chrisbutler** [react-dnd/react-dnd#1418]
**Breaking changes released in minor version update**
Adding `module` in https://github.com/react-dnd/react-dnd/pull/1366 apparently changes how webpack processes the package (see https://github.com/react-dnd/react-dnd/issues/1387#issuecomment-502521443) resulting in ES6 code making it into the production bundle untranspiled.

**To Reproduce**
1. Install version `7.5.0` of this package
2. Build production bundle with webpack
3. Visit site in IE11

**Expected behavior**
Page loads as usual

**Actual behavior**
Blank page with IE script error, because there are hundreds of `const` declarations in the production vendor bundle

**Desktop (please complete the following information):**
 - OS: Windows 7/8/10
 - Browser: IE
 - Version: 11

**Additional context**
Forcing yarn to resolve `dnd-core` down to `7.4.4` (as suggested in https://github.com/react-dnd/react-dnd/issues/1342) in addition to locking the `react-dnd` packages at/below 7.4.5 fixes the immediate issue of `const`, etc in the production bundle

```
  "dependencies": {
    "react-dnd": "7.4.5",
    "react-dnd-html5-backend": "7.4.4",
  },
  "resolutions": {
    "dnd-core": "7.4.4"
  }
```

**Comment by darthtrevino** [comment]
https://github.com/react-dnd/react-dnd/releases/tag/v7.7.0
