### ISSUE TITLE
(react-dnd) and Vega (react-vega) - how to make vega chart draggable?

### ISSUE THREAD

**Issue by alexfrize** [react-dnd/react-dnd#1419]
Not an issue, just need an advice.

I have a draggable component and Vega chart inside it. The Vega part of Bookmark component is not draggable, so user can drag it only by container (dark blue part of bookmark). Yellow part with graph is not draggable.

![image](https://user-images.githubusercontent.com/22485563/59888466-c1503e00-937c-11e9-8f0e-cdbb45859cd7.png)

Here is the code: https://codesandbox.io/s/amazing-zhukovsky-cr7ws

How to make it draggable?

**Comment by darthtrevino** [comment]
It looks like you're really close. What I would do is either use a drag handle (http://react-dnd.github.io/react-dnd/examples/customize/handles-and-previews) or utilize the "outer container" area like you're doing now. 

Your charts appear to be draggable in the example you've given - it looks like you just need to rerender them in the target component.

**Comment by alexfrize** [comment]
Good idea. Thank you.
