### ISSUE TITLE
Cannot have two HTML5 backends at the same time.

### ISSUE THREAD

**Issue by 3110160** [react-dnd/react-dnd#1420]
**Describe the bug**
When I disptch a action in(AppContext) will catch a  error 'Uncaught Error: Cannot have two HTML5 backends at the same time.'

**My code**
`import React ,{createContext,useReducer}from 'react';
import { DndProvider } from 'react-dnd'
import HTML5Backend from 'react-dnd-html5-backend'
import ToolBar from './leftBar';
import Container from './container';
import reducer from './reducer';
import styles from './index.less';
export const AppContext = createContext(null);
function App() {
  const [state, dispatch] = useReducer(reducer, {title:'你好哦'});
  return (
    <DndProvider backend={HTML5Backend}>
      <AppContext.Provider value={{state,dispatch}}>
        <div className={styles.App}>
          <div className={styles.leftBar}><ToolBar /></div>
          <div className={styles.containerBox}><Container /></div>
          <div className={styles.reviewBox} />
        </div>
      </AppContext.Provider>
    </DndProvider>
  )
}
export default App;`

**Comment by 3110160** [comment]
when i use {DragDropContext} No error again ！
`import React ,{createContext,useReducer}from 'react';
import { DragDropContext } from 'react-dnd'
import HTML5Backend from 'react-dnd-html5-backend'
import ToolBar from './leftBar';
import Container from './container';
import reducer from './reducer';
import styles from './index.less';
export const AppContext = createContext(null);
function App() {
  const [state, dispatch] = useReducer(reducer, {title:'你好哦'});
  return (
    <AppContext.Provider value={{state,dispatch}}>
      <div className={styles.App}>
        <div className={styles.leftBar}><ToolBar /></div>
        <div className={styles.containerBox}><Container /></div>
        <div className={styles.reviewBox} />
      </div>
    </AppContext.Provider>
  )
}
export default DragDropContext(HTML5Backend)(App);`

**Comment by Nico142** [comment]
I guess you have the same error like this one [1417](https://github.com/react-dnd/react-dnd/issues/1417), right?

**Comment by darthtrevino** [comment]
Fixed in https://github.com/react-dnd/react-dnd/pull/1422

**Comment by darthtrevino** [comment]
I'll cut a patch release in a few minutes with this change

**Comment by NexxLuo** [comment]
I found still has this problem .Maybe ignore some situation.
Look like this https://nexxluo.github.io/tablex/doc-draggable-index.
I try to click the menu more time, it throw this problem.

I will upload a gif later.

**Comment by NexxLuo** [comment]
It look like this.

![TEST](https://user-images.githubusercontent.com/18549980/65858119-cff4bb00-e397-11e9-9b68-672f5022591c.gif)
