### ISSUE TITLE
After 7.4.5 this.props.connectDragPreview(getEmptyImage() fails intermittently 

### ISSUE THREAD

**Issue by framerate** [react-dnd/react-dnd#1428]
**Describe the bug**
After 7.4.5 `  this.props.connectDragPreview(getEmptyImage())` fails intermittently 

**To Reproduce**
1. Implement a draggable item
2.   `this.props.connectDragPreview(getEmptyImage())`
3. Use 7.4.5, see it works
4. Use any 7.X later than that and see a drag preview that shouldn't be there

**Expected behavior**
If I don't want to see the default "transparent drag image" I shouldn't

**Screenshots**
The "token" is being dragged down and to the left. Large card is my `<CustomDragLayer />` as expected and the transparent "token" is the default react-dnd drag preview I have explicitly turned off
![image](https://user-images.githubusercontent.com/74291/60151657-6d859080-9792-11e9-85da-c8c43ba9e4a4.png)

**Desktop (please complete the following information):**
 - OS: Linux, Windows, macOS
 - Browser electron
 - Version 4.X

**Additional context**
Love the library, looking at upgraded to 8.x so I can't say for sure if it happens in the 8 branch but 7 is DEFINITELY having a regression!

**Comment by SeaOfTea** [comment]
Argh! Yeah, I'm glad you brought this up because I was also having this issue. For what it's worth I've rewritten a whole bunch to use the hooks API and it does not suffer the same problem.
It definitely seems to be from 7.x onwards, but I couldn't see any related breaking changes.

**Comment by framerate** [comment]
@SeaOfTea is your hooks work in this official repo? Is that what the 8.x branch is?

**Comment by SeaOfTea** [comment]
No no, sorry, I'm not a contributor to react-dnd. What I meant is that I was suffering the same issue, but rewrote my component to use the hooks API instead of the 'Legacy Decorator API'. It seems like the bug is specifically contained to the Legacy Decorator API. I had a look in the code changes for 7.0.0 but couldn't see anything that should cause this.
See the docs (http://react-dnd.github.io/react-dnd/about) You will need v7.6.0 or above, but it will possibly resolve your issue.

An example of the difference would be:

Before:
```
componentDidMount() {
  this.props.connectDragPreview(getEmptyImage())
}
```

After:
```
  const [,, preview] = useDrag({
    item: ITEM,
  });

  useEffect(() => {
    preview(getEmptyImage(), { captureDraggingState: true })
  }, [])
```

**Comment by jseminck** [comment]
I have experienced the same issue. It doesn't work at all anymore for us with 7.5.0 but 7.4.5 is fine. I skimmed through the diff but couldn't find anything that seems related.

I tried refactoring to hooks and in this case, my first drag would be correct (empty image) but consecutive drags for the same item would have both the native drag preview plus my custom drag preview.

**Comment by jseminck** [comment]
I found a "fix" by changing the code from: 

```js
React.useEffect(() => {
  connectDragPreview(getEmptyImage());
})

return (
  <div ref={(el) => connectDragSource(el)}>
    ...
```

to

```js
const elementRef = React.useRef(null);
connectDragSource(elementRef);

React.useEffect(() => {
  connectDragPreview(getEmptyImage());
})

return (
  <div ref={connectDragSource}>
    ...
```

I don't understand why 🤷‍♂ but maybe connectDragSource being called before connectDragPreview is now important?

**Comment by darthtrevino** [comment]
useEffect occurs after rendering, which may issues with react-dnd. We've had similar issues with our hooks-based API, and had to migrate some `useEffect` calls to `useLayoutEffect` to make the interaction with the dnd-core synchronous with rendering.

**Comment by framerate** [comment]
@darthtrevino my bug report doesn't use hooks though...

**Comment by darthtrevino** [comment]
I see, I thought there was an issue with useEffect - can you put together a minimal CodeSandbox example demonstrating the issue?

**Comment by framerate** [comment]
I can try. The project is on crunch and nearing the end of funding so I'm super swamped. I know w few others had the issue too so maybe someone in this thread can help out too. 

Currently were locked to 7.45 to make sure our build is good. The repro case SHOULD be as simple as just using the empty image drag image and dragging a Draggable item a bunch until you see the default drag image showing up erroneously

**Comment by jjjjw** [comment]
I had a similar issue. I was calling `connectDragPreview(getEmptyImage())` in `componentDidMount` using the decorators API and React DnD version 7.4. When I upgraded React DnD to 7.7, I started seeing that both the default browser preview and my custom drag layer were being rendered. I think it was upgrading the React DnD HTML5 backend to 7.7 that introduced the regression.

I found a workaround: Calling `connectDragPreview(getEmptyImage())` in `componentDidUpdate` ensures that only the custom drag layer is rendered.

**Comment by jjjjw** [comment]
I think this is an example of the broken behavior: https://codesandbox.io/s/react-dnd-example-6-41jzs

To see it break:
1) Drag one of the elements
2) Stop dragging
3) Start dragging the same element again

I changed the example so that `connectDragSource` is not always called in the render of the draggable item. It must be somehow affecting the `connectDragPreview` call.

**Comment by darthtrevino** [comment]
@jjjjw In your example it looks what's causing the issue is that when the drag source is detached, the drag preview also detaches. (https://github.com/react-dnd/react-dnd/blob/f591828f0ccaf70aa712785a8601017da2df4b45/packages/core/react-dnd/src/common/SourceConnector.ts#L184-L185).

**Comment by darthtrevino** [comment]
@framerate were you conditionally connecting your components using `connectDragSource`?

**Comment by framerate** [comment]
@darthtrevino I don't believe so, but it's a pretty complicated app. The small hexagon draggable in my screenshot has this render (if you see anything I'm doing wrong):

```js
render () {
      return this.props.connectDropTarget(this.props.connectDragSource(
        <div
          className='draggable'
          style={{
            zIndex: this.state.interacting ? 950 : 600
          }}
          onMouseEnter={this.onInteracting}
          onMouseLeave={this.onStopInteractingViaLeave}
          onDrag={this.onStopInteractingViaDrag}
          onMouseUp={this.clickHandler}

        >
          <WidthContext.Consumer>
            {gameplayDimensions =>
              <div
                style={{
                  ...styles.tokenContainer,
                  opacity: this.props.isOverCurrent ? 0.3 : 1.0
                }}
              >
                {this.state.interacting &&
                <SelectedCardPopup
                  mine={this.props.mine}
                  gameplayWidth={gameplayDimensions.width}
                  card={this.props.card}
                  onStopInteracting={this.onStopInteracting}
                />

                }
                <CardToken
                  type={this.props.card.type}
                  flags={this.props.card.flags}
                  affiliation={this.props.card.affiliation}
                  name={this.props.card.name}
                  keywords={this.props.card.keywords}
                  text={this.props.card.text}
                  uid={this.props.card.uid}
                  stats={this.props.card.stats}
                  baseStats={this.props.card.baseStats}
                  equipment={this.props.card.equipment}
                  rarity={this.props.card.rarity}
                  art={`${global.ASSET_LOCATION}/cardart/${this.props.card.img}.png`}
                  card={this.props.card}
                  width={this.props.width ? gameplayDimensions.width * this.props.width : gameplayDimensions.width * 0.14}
                  overlay={this.props.overlay}
                />
              </div>
            }
          </WidthContext.Consumer>
        </div>

      ))
    }
```

**Comment by framerate** [comment]
I do have ALL native dragging turned off, if that helps! Only things with `draggble` class will respond to make it feel more like a game and less like a webpage

**Comment by darthtrevino** [comment]
@framerate Could you do me a favor: go into your node modules for react-dnd, look for SourceConnector.js and apply this change (https://github.com/react-dnd/react-dnd/commit/5e41e1ecf9883d65cbf393a7eb1a20c9a4342280#diff-cacafac45de5a5b9470facf20161ce95R181) to see if that corrects your DragPreview problem?

**Comment by framerate** [comment]
@darthtrevino I'm currently locked to an older version so I don't see it. Should I apply your fix to the latest 7.X?

**Comment by darthtrevino** [comment]
Yes please, that would at least let us know what the real issue is here

**Comment by SeaOfTea** [comment]
> @framerate Could you do me a favor: go into your node modules for react-dnd, look for SourceConnector.js and apply this change ([5e41e1e#diff-cacafac45de5a5b9470facf20161ce95R181](https://github.com/react-dnd/react-dnd/commit/5e41e1ecf9883d65cbf393a7eb1a20c9a4342280#diff-cacafac45de5a5b9470facf20161ce95R181)) to see if that corrects your DragPreview problem?

I've just tried this myself, and can confirm this fixes the issue for me.
