### ISSUE TITLE
[Hooks] useDrag Type Definitions for "end" might be wrong

### ISSUE THREAD

**Issue by 0815Strohhut** [react-dnd/react-dnd#1431]
Hello,

in the hooksApi.ts in DragSourceHookSpec, the type definition for "end" specifies a "dropResult: DropResult | undefined". 

Based on my code, I'm getting the dragged object instead and not the drop result that I am getting when calling monitor.getDropResult(). 

Looking into drag.ts -> useDragHandler -> endDrag, it seems to call monitor.getItem() which confirms that it is rather the dragged object than the actual drop result. 

- As I can get both, the dragged object and the drop result, from the monitor (that is available anyway), I'm not sure what's the point of passing the second parameter? 
- If a parameter is passed, either the parameter (draggedItem) or the corresponding type definition (dropResult) should be changed I guess?

[using version 8.0.3 which is the latest if I am not mistaken]

**Comment by ReasonableDeveloper** [comment]
Although maybe unrelated to your particular problem, please note that the `docs` are wrong for the `useDrag` hook. It should be `end: (props, monitor) => {}` as seen in https://codesandbox.io/s/react-dnd-example-0-z9pxs.
