### ISSUE TITLE
SCRIPT1002: Syntax error - IE11

### ISSUE THREAD

**Issue by 2manoj1** [react-dnd/react-dnd#1433]
**Describe the bug**
- Syntax error - IE11 - class syntax error -'DragDropManagerImpl' app not loading.
- issue in dnd-core

**Expected behavior**
Should support IE11 or babel class property use to avoid error 

**Screenshots**
![image](https://user-images.githubusercontent.com/15128569/60319171-329e7b00-9993-11e9-8077-7193d9770376.png)

Error:

![image](https://user-images.githubusercontent.com/15128569/60319246-6679a080-9993-11e9-920e-d221b4b25171.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] IE11

**Comment by Kadrian** [comment]
Default parameters are ES6 https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/default_parameters#Browser_compatibility

Seems like ES6 isn't compiled to ES5?

**Comment by Kadrian** [comment]
Is it possible that this exists, since `tsconfig`'s `target` is on `es2015` (now even `esnext`)?

**Comment by 2manoj1** [comment]
Yes its not compiled to ES5 when not using babel-polyfill in project. Found solution below - install babel-polyfill as dependency and import in main index file - import '@babel/polyfill'. Now its compile as ES5 and working fine.

**Comment by darthtrevino** [comment]
You can try using `react-dnd-cjs` and `react-dnd-html5-backend-cjs`, which emit ES5 output
