### ISSUE TITLE
[Hooks] Get useDrag DOM ref in useDragLayer

### ISSUE THREAD

**Issue by daviestar** [react-dnd/react-dnd#1434]
I'm looking to get the original DOM ref of a dragged component using `useDrag` passed through to a custom drag layer using `useDragLayer` so I can call `getBoundingClientRect()` on it.

This issue and comment appear to address this for the old API: https://github.com/react-dnd/react-dnd/issues/446#issuecomment-382424350

But I can't figure out how to shoehorn it into the new hooks api.  Any ideas?

My draggable component:
```jsx
export default function DragWrapper({id}) {
  const [drag, preview] = useDrag({
    item: {id, type: 'TRANSACTION'}
  })

  useEffect(() => {
    preview(getEmptyImage(), {captureDraggingState: true})
  }, [preview])

  return (
    <div ref={drag}>
      {...}
    </div>
  )
}
```
My custom drag layer:
```jsx
export default function Ghost({selected}) {
  const props = useDragLayer((monitor) => ({
    offset: monitor.getSourceClientOffset(),
    isDragging: monitor.isDragging(),
    draggedItem: monitor.getItem(),
  }))
  if (!props.isDragging) {
    return null
  }
  const {x, y} = props.offset || {x: 0, y: 0}
  const width = 0 // ??
  const height = 0 // ??
  return (
    <div className="ghost" style={{top: y, left: x, width, height}}>
      {...}
    </div>
  )
}
```

**Comment by darthtrevino** [comment]
How about:

```jsx
const [ drag ] = useDrag(...)
const attach = useCallback((domElement) => {
    drag(domElement)
   // use dom element here for measuring
})
return (
<div ref={attach}>...</div>
)
```

**Comment by stevenkkim** [comment]
@darthtrevino – I'm new to both React Hooks as well as react-dnd, so apologize if I'm a bit slow here.  I'm trying to do the same thing as @daviestar and am confused on a couple points.

First, I tried using your useCallback code, and I'm getting this error in my console:

`React Hook useCallback does nothing when called with only one argument. Did you forget to pass an array of dependencies?  react-hooks/exhaustive-deps`

I'm not sure what I'm supposed to put into the array.

One difference in my code from @daviestar is that my component is both draggable and droppable, so I'm doing the following:

```
function DragAndDropItem({id}) {
  const [dragProps, drag, preview] = useDrag({
    item: {id, type: 'ITEM'},
    ...
  })

  const [dropProps, drop] = useDrop({
    item: {id, type: 'ITEM'},
    ...
  })

  useEffect(() => {
    preview(getEmptyImage(), {captureDraggingState: true})
  }, [preview])

  const ref = useRef(null);
  drag(drop(ref));

  return (
    <div ref={ref}>
      {...}
    </div>
  )
}
```

Second, once I get the useCallback code to work and measure the domElement, how do I get those measurements into my custom drag layer? The documentation says that useDragLayer has a collect function that receives two parameters, `monitor` and `props`. I'm assuming I need to pass the measurements to the custom drag layer via props, but not sure how to do that. I can't find in the documentation how the `props` parameter works for useDragLayer.

Thanks for your help!

**Comment by stevenkkim** [comment]
I just tried doing this:

```
function DragAndDropItem({id}) {
  const [dragProps, drag, preview] = useDrag({
    item: {id, type: 'ITEM'},
    ...
  })

  const [dropProps, drop] = useDrop({
    item: {id, type: 'ITEM'},
    ...
  })

  useEffect(() => {
    preview(getEmptyImage(), {captureDraggingState: true})
  }, [preview])

  // const ref = useRef(null);
  // drag(drop(ref));

  const ref = useCallback(
    domElement => {
      drag(drop(domElement))
    },
    [drag, drop]
  )

  return (
    <div ref={ref}>
      {...}
    </div>
  )
}
```

But sadly, my drag and drop component isn't working anymore. I'm kinda lost here.

**Comment by zhougch5** [comment]
@darthtrevino i get the domElement is null, i could not wonder why it is null.

**Comment by gaurav5430** [comment]
@darthtrevino how is this supposed to be used to get ref of component in useDragLayer in custom drag layer ?

**Comment by hein-j** [comment]
I got this to work by keeping the ref as a state and passing it into the useDrop hook:
- You must put the ref in the dep array of useDrag.

Drag source:
```
const [ref, setRef] = useState(null);

  const [{ isDragging }, drag, dragPreview] = useDrag(
    () => ({
    
      item: {
        draggedComponent: ref,
      },
    }),
    [ref, props],
  );

  return (
      <div
        ref={(div) => {
          drag(div);
          setRef(div);
        }}
      >...</div>
  );

```

Custom drag layer:

```
  const { item, } = useDragLayer((monitor) => ({
    item: monitor.getItem(),
  }));

const offsetWidth = item?.draggedComponent.offsetWidth
```
