### ISSUE TITLE
State changes in `end` fail with React warning

### ISSUE THREAD

**Issue by bartaz** [react-dnd/react-dnd#1435]
**Describe the bug**

If there are any state (via `useState`) changes in `end` callback of `useDrag` they throw a React warning if draggable element gets hidden as result of drop.

**To Reproduce**
This requires quite a specific setup to reproduce:
- draggable elements are visible when dragging starts (obviously), but get hidden as a result of drop on droppable
- draggable elements have `end` callback in `useDrag` that modifies their state
- the first time draggable is dropped a React warning is thrown:

I created a fairly minimal test case here:
https://codesandbox.io/embed/festive-resonance-ftyd1
Just drag the element, drop it on drop target and look at console for the error.

```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    in Draggable (created by App)
```

**Expected behavior**
If draggable component gets removed/unmounted as result of drop, `end` callback should not be called (or should not cause react warnings).

**Screenshots**
<img width="794" alt="Screenshot 2019-06-28 at 13 07 10" src="https://user-images.githubusercontent.com/83575/60338225-aba6ce00-99a5-11e9-8264-dc420c7bcfae.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome, Firefox
 - Version react-dnd 8.0.3

**Additional context**

**Comment by darthtrevino** [comment]
Interesting - a workaround you could do would be to fire dragstart/dragend events up the chain to a parent component that manages that state.

**Comment by darthtrevino** [comment]
I think I like this approach best: https://codesandbox.io/embed/elastic-lake-nnvmx

Instead of conditionally rendering your draggable, render it, but pass the `show` state into it. If the show state is false, it will render out null.

**Comment by darthtrevino** [comment]
I think to a certain degree, this issue intersects with the boundaries of React hooks. We could look into trying to the publication order of events, but that could be really brittle. I think a workaround is your best bet in the short term

**Comment by bartaz** [comment]
@darthtrevino Thanks for feedback. 

I ended up using workaround like that:
```js
  let isRendered = true;
  useEffect(() => {
    isRendered = true;
    return () => {
      isRendered = false;
    };
  });

  const [{ isDragging }, drag, preview] = useDrag({
    item: options.item,
    begin: () => {
      setIsGrabbing(true);
    },
    end: () => {
      if (isRendered) {
        setIsGrabbing(false);
      }
    }
  });
```
This at least keeps the workaround enclosed with `useDrag`, so I can extract it as my own hook (although it is similar in functionality to the deprecated `isMounted` from React, so I'm aware it may not be the best pattern to use)

But I'll give your `show` state a try. Not sure how well it will work in our use case (that is a bit more complicated then the test case I provided).
