### ISSUE TITLE
Writing a DropTarget as a higher order component fails due to Matching<>

### ISSUE THREAD

**Issue by lilymatcha** [react-dnd/react-dnd#1436]
I'm trying to write a higher order component that turns the `WrappedComponent` into a `DropTarget`. (Why? I'm ultimately trying to write a HOC that turns the `WrappedComponent` into a `DropTarget` for the sake of writing autoscroll, and I'm following the suggestion [here](https://react-dnd.github.io/react-dnd/examples/sortable/stress-test) to "parent drop target that compares `component.getBoundingClientRect()` with `monitor.getClientOffset()` inside its hover handler." As a first step though, I'm just trying to write a HOC that turns the wrapped component into a `DropTarget`.)

This is the code I've got right now:

````
interface TargetCollectedProps {
    connectDropTarget: ConnectDropTarget;
}

const withAdditionalFunctionality = <OriginalProps extends {}>(WrappedComponent: React.ComponentClass<OriginalProps>) => {
    const spec: DropTargetSpec<OriginalProps> = {
        hover(targetAreaProps: OriginalProps, monitor: DropTargetMonitor) {
            return;
        }
    };

    function collect(connect: DropTargetConnector, monitor: DropTargetMonitor, props: OriginalProps): TargetCollectedProps {
        return { connectDropTarget: connect.dropTarget() };
    }

    const WrappedComponentAsDropTarget = DropTarget<OriginalProps, TargetCollectedProps>(ITEM_DROP_TYPE, spec, collect)(WrappedComponent);

    class WithAdditionalFunctionality extends React.Component<OriginalProps & TargetCollectedProps> {
        constructor(props: OriginalProps & TargetCollectedProps) {
            super(props);
        }

        public render() {
            return this.props.connectDropTarget(
                <WrappedComponentAsDropTarget {...this.props} />
            );
        }
    }

    return WithAdditionalFunctionality;
};
````

And this is the error it's failing with:

````
Argument of type 'ComponentClass<OriginalProps, any>' is not assignable to parameter of type 'ComponentType<Matching<TargetCollectedProps, OriginalProps>>'.
  Type 'ComponentClass<OriginalProps, any>' is not assignable to type 'ComponentClass<Matching<TargetCollectedProps, OriginalProps>, any>'.
    Types of property 'propTypes' are incompatible.
      Type 'WeakValidationMap<OriginalProps> | undefined' is not assignable to type 'WeakValidationMap<Matching<TargetCollectedProps, OriginalProps>> | undefined'.
        Type 'WeakValidationMap<OriginalProps>' is not assignable to type 'WeakValidationMap<Matching<TargetCollectedProps, OriginalProps>>'.
          Type '(null extends OriginalProps[K] ? Validator<OriginalProps[K] | null | undefined> : undefined extends OriginalProps[K] ? Validator<OriginalProps[K] | null | undefined> : Validator<OriginalProps[K]>) | undefined' is not assignable to type '(null extends Matching<TargetCollectedProps, OriginalProps>[K] ? Validator<Matching<TargetCollectedProps, OriginalProps>[K] | null | undefined> : undefined extends Matching<TargetCollectedProps, OriginalProps>[K] ? Validator<...> : Validator<...>) | undefined'.
            Type 'null extends OriginalProps[K] ? Validator<OriginalProps[K] | null | undefined> : undefined extends OriginalProps[K] ? Validator<OriginalProps[K] | null | undefined> : Validator<OriginalProps[K]>' is not assignable to type '(null extends Matching<TargetCollectedProps, OriginalProps>[K] ? Validator<Matching<TargetCollectedProps, OriginalProps>[K] | null | undefined> : undefined extends Matching<TargetCollectedProps, OriginalProps>[K] ? Validator<...> : Validator<...>) | undefined'.
````

I've looked at the code for `Matching`, but it didn't illuminate anything for me. Does anyone have any idea what could be causing this, and how I might work around it?

**Versions:**
- `react`: 16.8.5
- `react-dnd`: 7.6.0
- `react-dnd-html5-backend`: 7.6.0

**Comment by darthtrevino** [comment]
That's a bit deep-in-the-weeds for me as far as TypeScript goes - we struggled for some time to get the typings for decorators to work ergonomically. Does this work in the JS runtime, or is this just a typings issue?

Ultimately I went and copied some of the typings for how `react-redux` works with decorated components. This section of code basically manages the props interface of the react-component coming out of the decorator. (https://github.com/react-dnd/react-dnd/blob/5069427fc300de818031ad050618d44593170885/packages/core/react-dnd/src/decorators/interfaces.ts#L173-L237)

If you took an approach like this and mark your return type as a "ComponentEnhancer", then you could at least have the option of doing a force cast at the end but keeping your downstream consumer typings clean.
