### ISSUE TITLE
TypeScript types error TS2707: have to change connectors.d.ts manually (ReactElement<P, T> requires between 1 and 2 type arguments)

### ISSUE THREAD

**Issue by alexfrize** [react-dnd/react-dnd#1440]
I added read-dnd to my existing project and have this error:

> TypeScript error in /my_project/node_modules/react-dnd/lib/interfaces/connectors.d.ts(5,5):
> Generic type 'ReactElement<P, T>' requires between 1 and 2 type arguments.  TS2707

Interesting thing that for a new project I don't have this error, only for existing one.

I made some changes to 'connectors.d.ts' file:
![image](https://user-images.githubusercontent.com/22485563/60628602-07f35e80-9da7-11e9-962c-22c9e1499813.png)
I changed `React.ReactElement` to `React.ReactElement<any>` and it solved the issue locally.
But every time I reinstall libraries, the problem will show up again.

Any ideas, how to solve it another way?

Current react-dnd version is: 8.0.3
"@types/react": "^16.7.22",
 "typescript": "^3.2.4",

I had similar problem with another version of react-dnd (7.6.0). But the filename was different: now it is 'connectors.d.ts', but before it was another filename ('classApi.d.ts')

> TypeScript error in /my_project/node_modules/react-dnd/lib/cjs/interfaces/classApi.d.ts(94,65):
> Generic type 'ReactElement<P, T>' requires between 1 and 2 type arguments.  TS2707

**Comment by darthtrevino** [comment]
What version of TypeScript are you using?

**Comment by darthtrevino** [comment]
Hmm, we're using "@types/react" at 16.8, and we have been since 8.x. I think updating that typings package is likely your best bet.

**Comment by alexfrize** [comment]
You're right.
It helped. 
Thank you!

I updated types and also added 
```
"resolutions": {
    "@types/react": "^16.8.4",
    "@types/react-dom": "^16.8.4",
    "@types/react-redux": "^7.1.1"
  }
```
to my package.json file.
