### ISSUE TITLE
Can i get props from React Components?

### ISSUE THREAD

**Issue by popuguytheparrot** [react-dnd/react-dnd#1442]
Can i get props from React Components in events begin, end, canDrop, drop and etc???

**Comment by darthtrevino** [comment]
If you're using the hooks API, then you already have access to the props in your component function. If you're using the decorator-based API, then the props are usually the first argument to your spec functions.

You can read more about it on the docsite http://react-dnd.github.io/react-dnd/docs/api/drag-source
