### ISSUE TITLE
react-dnd v9 uses spread operator, breaks older browsers

### ISSUE THREAD

**Issue by bhollis** [react-dnd/react-dnd#1446]
**Describe the bug**

Typically, consumers of libraries like react-dnd don't run their node_modules through Babel to transform newer syntax. There's a bit of a debate over when and how we should all start doing that, but it's not a great option right now. In v9, the es-modules exported version of react-dnd also started using some newer browser features (specifically, the spread operator) which if not transpiled out will fail to parse in browsers like MS Edge 17 which still don't support that syntax.

**Reproduction**

1. Bundle an app with v9 of react-dnd
2. Open in Edge 17.
3. `SCRIPT1028: Expected identifier, string or number`

**Expected behavior**

It's expected that libraries (even if they are vended as ES modules) do not use newer syntax, or that they include specific instructions in the README that they must be run through babel in order to work.

**Comment by bhollis** [comment]
I'd recommend using `babel-preset-env` to transform the distributed source based on a list of supported browser versions.

**Comment by marvwhere** [comment]
Just noticed that problem too, do you implemented any workaround on your end?

I already use babel-preset-env in my project. But that does not help.

**Comment by kramarmm** [comment]
Have the same issue.

**Comment by darthtrevino** [comment]
This is one of the reasons we ship two variants of the library. Why not use the `react-dnd-cjs` library?

**Comment by darthtrevino** [comment]
So, the alternative would be to ship react-dnd with a folder structure like, which would require a major version cut. The default would be `esm/esnext`, but you could alias out to whatever module/target combo you want.

```
dist/umd/
dist/esm/esnext/
dist/esm/es2017/
dist/esm/es2016/
dist/esm/es2015/
dist/esm/es5/
dist/cjs/es2017/
dist/cjs/es2016/
dist/cjs/es2015/
dist/cjs/es5/
```

**Comment by bhollis** [comment]
What most libraries do is to ship es modules, but use babel-preset-env to translate that source down to the least common denominator among the browsers they support.

**Comment by darthtrevino** [comment]
Right, so we'd just have to decide what our ongoing `preset-env ` support would look like and add a babel step after typescript compilation.

I'd like to avoid endlessly supporting older browsers like IE11, so whatever preset we would ship with would be a live target.

**Comment by darthtrevino** [comment]
I'll look into chaining babel after the tsc compilation. I think some light processing to hit a fixed browsers target ">.25%, not dead", makes sense

**Comment by darthtrevino** [comment]
Actually, using babel directly for all transpilation is pretty great. And this wouldn't necessitate a major version cut
