### ISSUE TITLE
Can't access http://react-dnd.github.io/react-dnd

### ISSUE THREAD

**Issue by TheBegining** [react-dnd/react-dnd#1447]
**Describe the bug**
Can't access http://react-dnd.github.io/react-dnd always redirect to localhost

![image](https://user-images.githubusercontent.com/17702287/60892523-d6d8c980-a291-11e9-9886-b1f70a7e5710.png)

![image](https://user-images.githubusercontent.com/17702287/60892544-dfc99b00-a291-11e9-8e0e-8a94955290d4.png)

**Comment by darthtrevino** [comment]
It looks good to me now, I don’t see any localhost fetches. Can you verify that this is still an issue?

**Comment by TheBegining** [comment]
> It looks good to me now, I don’t see any localhost fetches. Can you verify that this is still an issue?

After I disable the cache.I can access the website.And the request of localhost no longer appear.
