### ISSUE TITLE
Cannot build with v9.1.0

### ISSUE THREAD

**Issue by leantide** [react-dnd/react-dnd#1450]
I get this error when building with react-dnd v9.1.0 but not with react-dnd v9.0.0.

./node_modules/react-dnd/lib/interfaces/index.js
Attempted import error: 'XYCoord' is not exported from 'dnd-core'.

Any thoughts?

**Comment by leantide** [comment]
I cannot see any reference to XYCoord in my code.

**Comment by gogoyqj** [comment]
well, since in `node_modules/react-dnd/lib/interfaces/index.js`

```ts
export { XYCoord } from 'dnd-core';
export * from './monitors';
export * from './hooksApi';
export * from './options';
export * from './connectors';
```

those are typescript interfaces or types


it should export nothing there - just like @9.0.0 

`node_modules/react-dnd/lib/interfaces/index.js`

```ts

```

**Comment by leantide** [comment]
Indeed. After I make node_modules/react-dnd/lib/interfaces/index.js an empty file, I can build and use react-dnd 9.1.0.

Seems index.js is getting the contents intended and available from index.d.ts.

**Comment by wldcordeiro** [comment]
This is because of Babel's TS support you have to do an `export * from 'dnd-core'` if you wish to export that type there.

**Comment by iamchanii** [comment]
Same issue here. any temporary solution there?

**Comment by darthtrevino** [comment]
@wldcordeiro Gah, gotcha - I’ll put out a patch in a minute
