### ISSUE TITLE
DOM node that is draggable and droppable

### ISSUE THREAD

**Issue by CMCDragonkai** [react-dnd/react-dnd#1451]
If you have a React node, and you want to make it a dropzone, but you also want to make it draggable, is there a way to combine the `drag` and `drop` refs on the same dom element?

```
const [{isDragging}, drag] = useDrag({...});
const [{isOver}, drop] = useDrop({...});
return <section ref={drag/drop}></section>;
```

**Comment by darthtrevino** [comment]
You can use the callback version of ref like so: 

```jsx

function attach(node) {
   drag(node)
  drop(node)
}
<section ref={attach} />
```

**Comment by Noa-p** [comment]
Does the node must be a React comonent instead of a React function ?

**Comment by nelsonni** [comment]
(FYI, in case anyone stumbles upon this issue and needs guidance on the solution)

> Does the node must be a React comonent instead of a React function ?

The types for both `drop` and `drag` are inferred to be `DragElementWrapper<any>`. A bit of investigation shows that the relevant typings from [`connectors.d.ts`](https://github.com/react-dnd/react-dnd/blob/75c981c74e2f16b2c3ab752d257f426c72d18eae/packages/react-dnd/src/interfaces/connectors.ts) are fully typed as:
```javascript
export type ConnectableElement =
	| React.RefObject<any>
	| React.ReactElement
	| Element
	| null

export type DragElementWrapper<Options> = (
	elementOrNode: ConnectableElement,
	options?: Options,
) => React.ReactElement | null
```

So any React component or Element can be the node, including React Functional Components.
