### ISSUE TITLE
Duplicate exports DndContext make Meteor Babel minifier sad

### ISSUE THREAD

**Issue by perbergland** [react-dnd/react-dnd#1456]
**Describe the bug**

I attempted an upgrade from 7.4.5 to 9.2.1 and then I needed to move from the deprecated (but still used in quite a few examples in .md files) DragDropContext to the React DndProvider component.
The code compiled fine with Typescript but when trying to run this within a Meteor app which uses some Babel-based minifier I get an error that prevents the build.

**Reproduction**

1. Use react-dnd 9.2.1 in package.json
2. meteor build

**Expected behavior**
Possible to build.
**Desktop (please complete the following information):**

- OS: macOS 10.14.5
- meteor 1.8.1

**Additional context**

```
Errors prevented bundling:
While minifying app code:
packages/minifyStdJS/plugin/minify-js.js:96:26: Babili minification error
within packages/modules.js:
node_modules/react-dnd/lib/common/DndContext.js

`DndContext` has already been exported. Exported identifiers must be unique.:

export var DndContext = React.createContext({

at maybeThrowMinifyErrorBySourceFile
(packages/minifyStdJS/plugin/minify-js.js:96:26)
at files.forEach.file (packages/minifyStdJS/plugin/minify-js.js:135:9)
at Array.forEach (<anonymous>)
at MeteorBabelMinifier.processFilesForBundle
(packages/minifyStdJS/plugin/minify-js.js:118:9)
```

It seems that there is both a const React component AND an interface with the same name exported from [DndContext.ts](https://github.com/react-dnd/react-dnd/blob/master/packages/core/react-dnd/src/common/DndContext.ts)

**Comment by perbergland** [comment]
Verified that this happens also for 8.x so I’m stuck at 7.4.5

**Comment by perbergland** [comment]
Not sure what the problem really is because the app also crashes on startup without minifying involved and cannot load the react-dnd package

**Comment by darthtrevino** [comment]
In 9.1 we switched to using Babel to transpile TypeScript, but babel has some issues with interfaces. What you're seeing is the babel result trying to export the interface DndContext and the instance DndContext.
