### ISSUE TITLE
Cannot test an app which imports useDrag

### ISSUE THREAD

**Issue by threeaster** [react-dnd/react-dnd#1458]
**Describe the bug**

The app which imports `useDrag` can't be tested. 

**Reproduction**

https://github.com/threeaster/react-dnd-test

1. `vagrant init centos/7` and 'vagrant up'
2. `vagrant ssh` and install npm, yarn, and create-react-app
```
curl -sL https://rpm.nodesource.com/setup_12.x | sudo bash -
curl -sL https://dl.yarnpkg.com/rpm/yarn.repo | sudo tee /etc/yum.repos.d/yarn.repo
sudo yum install -y nodejs gcc-c++ make yarn
mkdir ~/.npm-global
npm config set prefix '~/.npm-global'
add "export PATH=~/.npm-global/bin:$PATH" before "export PATH" to ~/.bash_profile
. .bash_profile 
npm install -g create-react-app
```
3. create-react-app test_app
4. cd test_app and yarn add react-dnd react-dnd-html5-backend
5. create ~/test_app/src/test/test.test.js whose content is below:
```
import { useDrop } from 'react-dnd'

it('test', () => {})
```
6. cd ~/test_app and yarn test
7. See error

**Expected behavior**
Tests succeed.

**Screenshots**
Tests fail as below:
``
PASS  src/App.test.js
FAIL  src/test/test.test.js
 ● Test suite failed to run

   Jest encountered an unexpected token

   This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

   By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

   Here's what you can do:
    • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
    • If you need a custom transformation specify a "transform" option in your config.
    • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

   You'll find more details and examples of these config options in the docs:
   https://jestjs.io/docs/en/configuration.html

   Details:

   /home/vagrant/test_app/node_modules/react-dnd/lib/index.js:1
   ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){export * from './common';
                                                                                            ^^^^^^

   SyntaxError: Unexpected token export

   > 1 | import { useDrop } from 'react-dnd'
       | ^
     2 | 
     3 | it('test', () => {})
     4 | 

     at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:471:17)
     at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:513:25)
     at Object.<anonymous> (src/test/test.test.js:1:1)

Test Suites: 1 failed, 1 passed, 2 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        2.235s
Ran all test suites.

Watch Usage
› Press f to run only failed tests.
› Press o to only run tests related to changed files.
› Press q to quit watch mode.
› Press p to filter by a filename regex pattern.
› Press t to filter by a test name regex pattern.
› Press Enter to trigger a test run.
``

**Desktop (please complete the following information):**

- OS: CentOS Linux release 7.6.1810 (Core) 
- Version 
vagrant 2.1.2
npm 6.9.0
yarn 1.16.0
create-react-app 3.0.1

At first, I tried it in my mac. In its environment, same issue happened.
- OS: macOS Mojave 10.14.5
- Version
npm 6.9.0
yarn 1.9.2
create-react-app 1.5.2

**Additional context**
https://github.com/threeaster/react-dnd-test
is made in my mac.
At first, I tried chess tutorial
http://react-dnd.github.io/react-dnd/docs/tutorial
and I cannot test this.

**Comment by darthtrevino** [comment]
We should probably add a page on Jest testing, but one approach would be to use the moduleNameMapper and map out the dnd-libs to their cjs variants for jest

**Comment by davidgilbertson** [comment]
@darthtrevino I don't think you can set `moduleNameMapper` with a create-react-app, without ejecting. Does that mean a component with `react-dnd` can't be tested in that case?

**Comment by pinkbunny1** [comment]
Since jest is not working with esmodules well, you need to add these configurations in jest.config.js

```
moduleNameMapper : {
        '^react-dnd$': 'react-dnd/dist/cjs',
        '^react-dnd-html5-backend$': 'react-dnd-html5-backend/dist/cjs',
        '^dnd-core$': 'dnd-core/dist/cjs',
}
```

**Comment by pinkbunny1** [comment]
Since jest is not working with esmodules well, you need to add these configurations in jest.config.js

```
moduleNameMapper : {
        '^react-dnd$': 'react-dnd/dist/cjs',
        '^react-dnd-html5-backend$': 'react-dnd-html5-backend/dist/cjs',
        '^dnd-core$': 'dnd-core/dist/cjs',
}
```
