### ISSUE TITLE
Build fails on 9.3.1

### ISSUE THREAD

**Issue by androsj** [react-dnd/react-dnd#1461]
**Describe the bug**
```
Failed to compile.

./node_modules/react-dnd/lib/common/index.js
Attempted import error: 'DndContextType' is not exported from './DndContext'.
```

This makes sense since type / interface declarations only exist on .ts files... It is not exported from DndContext.js.

I've manually fixed it by removing DndContextType from the exports on ./node_modules/react-dnd/lib/common/index.js

**Reproduction**

1. Place a DndProvider component in your Render Tree.
2. Run npm start.

**Desktop:**

- OS: Windows
- Browser: Firefox
- Version: 69.0b3 (64-bit)

**Additional context:**

- using create-react-app

**Comment by darthtrevino** [comment]
What a pain - the babel transpiler should cull any interfaces. We may have to output TS and then use babel on that output.

**Comment by darthtrevino** [comment]
I think Gatsby is masking some issues that we’re seeing reported from CRA users as well. This PR will add a CRA app that will fail a build if react-dnd doesn’t work with CRA
