### ISSUE TITLE
CI failed with v9.3.2

### ISSUE THREAD

**Issue by dengfuping** [react-dnd/react-dnd#1463]
**Describe the bug**
![image](https://user-images.githubusercontent.com/14918822/61101590-ec6e0f00-a49c-11e9-8d86-e669ab1011b9.png)

**Reproduction**

[Live Reproduction](https://circleci.com/gh/ant-design/ant-design/94578?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)

1. Go to https://circleci.com/gh/ant-design/ant-design/94578?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
2. Click on terminal
3. Scroll down to bottom of page.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/14918822/61101354-0b1fd600-a49c-11e9-86c6-9e669055dd51.png)

**Desktop (please complete the following information):**

**Additional context**

**Comment by darthtrevino** [comment]
You have to configure the moduleNameMapper for Jest (http://react-dnd.github.io/react-dnd/docs/testing)

**Comment by dengfuping** [comment]
@darthtrevino There are no such module as `html5-backend/dist/cjs` and `touch-backend/dist/cjs`.
![image](https://user-images.githubusercontent.com/14918822/61114983-0bcc6280-a4c4-11e9-8284-5fbe895e5440.png)

- The settings should be like this:
```diff
"moduleNameMapper": {
  "^dnd-core$": "dnd-core/dist/cjs",
  "^react-dnd$": "react-dnd/dist/cjs",
-  "^react-dnd-html5-backend$": "html5-backend/dist/cjs",
-  "^react-dnd-touch-backend$": "touch-backend/dist/cjs",
+  "^react-dnd-html5-backend$": "react-dnd-html5-backend/dist/cjs",
+  "^react-dnd-touch-backend$": "react-dnd-touch-backend/dist/cjs",
  "^react-dnd-test-backend$": "react-dnd-test-backend/dist/cjs",
  "^react-dnd-test-utils$": "react-dnd-test-utils/dist/cjs"
}
```

- I will make a PR for this later.

**Comment by darthtrevino** [comment]
Ahh, correct - I’ll fix the docs
