### ISSUE TITLE
UMD builds missing

### ISSUE THREAD

**Issue by sebastian-lenz** [react-dnd/react-dnd#1472]
**Describe the bug**
The UMD builds are missing in the new versions of React DnD published to npm. The [docs](http://react-dnd.github.io/react-dnd/docs/faq) also state that the builds can be fetched from unpkg, but the links are dead:

https://unpkg.com/react-dnd@9.3.2/dist/ReactDnD.min.js
https://unpkg.com/react-dnd-html5-backend@9.3.2/dist/ReactDnDHTML5Backend.min.js

**Comment by sebastian-lenz** [comment]
For anyone wondering, the builds are no packaged in the module `react-dnd-umd-builds`.

**Comment by jijizz** [comment]
Yes, there are still consumers relying on AMD/requireJs to bundle their apps. Our app was based on dnd@7.6.2 which had AMD release. Now lacking of UMD release is blocking us consuming latest version of dnd. please help

**Comment by sebastian-lenz** [comment]
@jijizz Please see the new package `react-dnd-umd-builds`

**Comment by darthtrevino** [comment]
@sebastian-lenz is correct, check out the react-dnd-umd-builds package
