### ISSUE TITLE
Conditionally dropping

### ISSUE THREAD

**Issue by h182032** [react-dnd/react-dnd#1475]
I have two task lists. The one on the left has all the tasks in the beginning and the right one is empty. In the right list i only want to be able to drop maximum 3 tasks. How can I disable the drop when i have three items (max) in the right list? How do i check if it is 3 items in the right list?

**Comment by IamFonky** [comment]
Hi,
maybe use a function to check if you can drop or not

use the `canDrop: ` method with your own function, checking if 3 tasks were dropped allready

``` typescript
  const incrementDropped = () => {/* Increment the number of dropped tasks */};
  const allowDrop = () => {/* Return if nbDroppedTasks <= 3 */};

  const [dropTabProps, dropTab] = useDrop({
    accept: dndAcceptType,
    canDrop: allowDrop,
    drop: incrementDropped,
    collect: (mon: DropTargetMonitor) => {
      return {
        isOverCurrent: mon.isOver({ shallow: true }),
        canDrop: mon.canDrop(),
        item: mon.getItem()
      };
    }
  });
```

**Comment by IamFonky** [comment]
You're welcome...
Did it help you?
