### ISSUE TITLE
How to combine dnd with resizing

### ISSUE THREAD

**Issue by onokje** [react-dnd/react-dnd#1479]
Hi all, 
I am trying to build a scheduler component (a bit like the meeting scheduler in outlook), and i got the dnd part working fine. But now i want to add the ability to resize my 'draggables' as well. I tried using Resizable (https://github.com/STRML/react-resizable) but I can't get it to work properly (resize does not work). 
I know this is not an issue with dnd, but if anyone has a similar experience, or has any tips to point me in the right direction, it would be appreciated :)

**Comment by IamFonky** [comment]
I may help you if you give me a simple demo of your code on codesandbox :)
