### ISSUE TITLE
Why dnd context is a singleton? 

### ISSUE THREAD

**Issue by MikeYermolayev** [react-dnd/react-dnd#1480]
Hello,

I have a small question regarding DnD Context: why it should be a singleton?

My scenario:

I have a page with a table and use react-dnd to handle resizing of a columns. And I use custom drag layer for that purpose to detect X offset and dragged columnIndex.

Then I want to implement a dashboard page where I want to place few tables. But what I get as a result is that when I drag column resizer on the first table the columns with same column index from other tables are dragged too. Even if they have separate DnDProviders.

Maybe it make sense to make different DnDProviders isolated?

quick silly demo https://codesandbox.io/embed/affectionate-ritchie-b6bvi

**Comment by kyang6** [comment]
Did you ever end up finding a workaround Mike?

**Comment by MikeYermolayev** [comment]
@kyang6 Sorry, I don't remember((

As I can see I switched to react-dnd-touch-backend from html5 backend but not sure if it's related
