### ISSUE TITLE
The copy or move example does not work in the hooks variant

### ISSUE THREAD

**Issue by sgarcialaguna** [react-dnd/react-dnd#1482]
**Describe the bug**
The copy or move example from https://react-dnd.github.io/react-dnd/examples/dustbin/copy-or-move does not work in the hooks variant. No matter where you drop any of the boxes, it will always alert "You moved ${boxName} into ${boxName}". The decorator version works as expected

**Reproduction**

1. Open the copy or move hooks example at https://codesandbox.io/s/github/react-dnd/react-dnd/tree/gh-pages/examples_hooks_js/01-dustbin/copy-or-move?from-embed
2. Drag any of the boxes everywhere
3. The alert will always say "You moved ${boxName} into ${boxName}"

**Expected behavior**
It should behave like the equivalent example with decorators: https://codesandbox.io/s/github/react-dnd/react-dnd/tree/gh-pages/examples_decorators_js/01-dustbin/copy-or-move?from-embed

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Chrome
- Version: 75

**Comment by sgarcialaguna** [comment]
Looked at the both variants side-by-side and the documentation and found the issue.

The end() function passed into useDrag() has a signature of (item, monitor), not (dropResult). Here is a fixed version:

https://codesandbox.io/s/react-dnd-example-1-s3o4c

**Comment by darthtrevino** [comment]
This looks fixed on master, the docs may need to be released though
