### ISSUE TITLE
Use same element as target and source with hooks

### ISSUE THREAD

**Issue by zouxuoz** [react-dnd/react-dnd#1483]
When I use decorators I could use the same element as target and source:

```
let Node = ({ connectDragSource, connectDropTarget }) => {
  return connectDragSource(connectDropTarget(<div/>));
};

Node = compose(
  DropTarget(...),
  DragSource(...),
);
```

Could I implement the same behavior with hooks?

**Comment by zouxuoz** [comment]
Sorry, I got some misunderstanding :)

Solution:
```
const Node = () => {
  const [dragCollectedProps, connectDragSource] = useDrag(...);
  const [dropCollectedProps, connectDropTarget] = useDrop(...);

  return connectDragSource(connectDropTarget(<div/>));
};

```

**Comment by CrocoDillon** [comment]
Wait, this actually works? The examples are like:

```js
import { useDrag } from 'react-dnd'

function DraggableComponent(props) {
  const [collectedProps, drag] = useDrag({
    item: { id, type },
  })
  return <div ref={drag}>...</div>
}
```

Which scared me because I don't know how to add two refs to a single element. So how does this work if not with refs? Can I use a custom component like `return connectDragSource(connectDropTarget(<Tab />))`?

**Comment by CrocoDillon** [comment]
> Uncaught Error: Only native element nodes can now be passed to React DnD connectors.

So that's a no on custom components.

**Comment by mx2323** [comment]
can confirm, you can do drag(drop(<div>))

**Comment by mib32** [comment]
A nice working solution for custom component

```js
import { useDrag, useDrop } from 'react-dnd'

function DraggableComponent(props) {
  /* ... */
 function attachRef(el) {
    drag(el)
    drop(el)
  }
  return <Grid ref={attachRef}>...</Grid>
}
```

**Comment by johnfrades** [comment]
> A nice working solution for custom component
> 
> ```js
> import { useDrag, useDrop } from 'react-dnd'
> 
> function DraggableComponent(props) {
>   /* ... */
>  function attachRef(el) {
>     drag(el)
>     drop(el)
>   }
>   return <Grid ref={attachRef}>...</Grid>
> }
> ```

Thank you man! You saved me
