### ISSUE TITLE
Error on fresh installation

### ISSUE THREAD

**Issue by jairusd** [react-dnd/react-dnd#1485]
**Describe the bug**
after clean installation, i'm getting error with export default from inside the package

**Expected behavior**
should run without problem

**Screenshots**
![image](https://user-images.githubusercontent.com/36670564/61556692-fa232600-aa94-11e9-8488-42b30c2f339f.png)

**Desktop (please complete the following information):**

- OS: windows 10
- Browser chrome
- Version 75.0.3770.142 (Official Build) (64-bit)

**Additional context**

**Comment by coodysk8er** [comment]
the same here. even wtih webpack 'js' babel loader including /node_modules/

**Comment by rajbits** [comment]
Facing the same issue here.. Tried couple of earlier versions too, seeing the same behavior.
Using create-react-app with hooks

**Comment by jairusd** [comment]
> Facing the same issue here.. Tried couple of earlier versions too, seeing the same behavior.
> Using create-react-app with hooks.
> 
> Upgrade to the latest node and create react app 2 and the error is gone.
> @jairusd - what's your node environment?

I just upgraded to 12.6.0 and refreshed my deps to test it out, unfortunately, I'm still getting the same error :(

**Comment by Topppy** [comment]
same problem +1. and when I try to use react-dnd-cjs,  got another [problem](https://github.com/react-dnd/react-dnd/issues/1468).

- os: mac
- electron

**Comment by Skylsmoi** [comment]
I'm having the same issue.
I just upgraded Babel to 7.4+ with the switch from `@babel/polyfill` to `core-js` so I'm yet not entirely sure where my error comes from.
I'll look closely at this thread though.

**Comment by jairusd** [comment]
> I'm having the same issue.
> I just upgraded Babel to 7.4+ with the switch from `@babel/polyfill` to `core-js` so I'm yet not entirely sure where my error comes from.
> I'll look closely at this thread though.

same man.. i'm on core-js 3

**Comment by rajbits** [comment]
fwiw, with due respect to react-dnd, it did not work well with react-virtualized (which is a must have for me). I moved on to use react-sortable-hoc and the combo works best for me.

**Comment by tom-james-watson** [comment]
I had the same problem - they're directly exporting ES6 on `react-dnd`. Instead, just use the drop-in-replacement `react-dnd-cjs` and it should work fine.
