### ISSUE TITLE
Set source type dynamically in hooks API

### ISSUE THREAD

**Issue by Atralbus** [react-dnd/react-dnd#1486]
**Is your feature request related to a problem? Please describe.**

I'm not able set item type dynamically based on a condition. In the legacy API it's possible to set it conditionally by passing a function to source type e.g.
```typescript
DragSource((props: Props) => (props.condition ? 'TYPE1' : 'TYPE2'), ...)
```

In the hooks API, I tried to pass the item based on a condition, but it just takes the initial type and never updates it.

```typescript
useDrag({
  item: props.condition
    ? { type: 'TYPE1', ...}
    : { type: 'TYPE2', ...}
  ,...
})

```

I also tried to use `begin` callback but it didn't update the type, either.

Am I doing something wrong? Normally, should it update the type or is it the expected behavior? Since hooks are part of the component lifecycle, I thought it would automatically update its state based on the passed props. I checked the docs but couldn't find an alternative or description how it would behave in the hooks API.

**Describe the solution you'd like**

I would like to be able to set source type dynamically.

**Describe alternatives you've considered**

**Additional context**
react: v16.8.2
react-dnd: v8.0.3
typescript: v3.5.2

**Comment by waynevanson** [comment]
You're returning an expression. Have you tried returning a function?

``` tsx
useDrag({
  item: () => props.condition
    ? { type: 'TYPE1', ...}
    : { type: 'TYPE2', ...}
  ,
// ...
})

// OR

useDrag({
  item: { type: props.condition ? 'TYPE1' : 'TYPE2' }
// ...
})
```


I'm no expert but throwing possible workarounds out there.

**Comment by Atralbus** [comment]
@waynevanson Thanks for the suggestion but `item` only accepts [object](https://github.com/react-dnd/react-dnd/blob/383f51ee13293c29fead83e73ef4dd0511542a9f/packages/core/react-dnd/src/interfaces/hooksApi.ts#L124) with `string | symbol` typed `type` prop.

**Comment by jjant** [comment]
Having the same problem here

**Comment by tyio** [comment]
Please, consider this feature in your roadmap.

**Comment by tyio** [comment]
Type can be set dynamically by using begin() method

> begin(monitor): Optional. Fired when a drag operation begins. Nothing needs to be returned, but if an object is returned it will override the default item property of the spec.

**Comment by elliempatten** [comment]
I'm also having this same problem. Unfortunately using the `begin()` method doesn't seem to solve it. 
If I take an action which should update the type of an item, from some investigation I've found the following:
After the event that should update the type occurs, if I try to access `monitor.getItem().type`, it returns the correct (the new, updated) drag type, but if I try and access `monitor.getItemType()` this returns an incorrect drag type and seems to still be using the previous drag type, from before the change.

I would be interested to know the difference in the implementation of these two different ways of accessing the item's type, and why the result of `monitor.getItemType()` doesn't seem to get updated after a re-render.

**Comment by RomanChumakov** [comment]
useDrag works like a useCallback. Thus, you can pass a dependency array as the second argument to useDrag like this:
useDrag(() => {/*your object*/}, [/*your props enfluencing the result*/]).

P.S. It works in at least v14.0.2, but maybe in earlier ones too
