### ISSUE TITLE
Example's behavior is not correct

### ISSUE THREAD

**Issue by sakopqiu** [react-dnd/react-dnd#1487]
**Describe the bug**
In the simplest example, if I drag "Box" into "Dustbin", the alert message keeps printing "The glass is dropped into glass" instead of "into dustbin".

After some debugging, I found that the example code is wrong(Might attribute to the API interface change recently, I guess?)

The code
```
end: (dropResult?: { name: string }) => {
      if (dropResult) {
        alert(`You dropped ${name} into ${dropResult.name}!`)
      }
    },
```
should be turned into
```
end: (item: { name: string }, monitor: DragSourceMonitor) => {
    const dropResult = monitor.getDropResult();
      if (dropResult) {
        alert(`You dropped ${name} into ${dropResult.name}!`)
      }
    },
```

In addition, I found several discrepancies between the newest version and the document, which is quite unfriendly to the new users.
I hope that someone would come and update the docs, thanks

**Reproduction**

[Live Reproduction](codesandbox.io/....)

1. Just open the first example
https://react-dnd.github.io/react-dnd/examples/dustbin/single-target

**Screenshots**

**Desktop (please complete the following information):**

- OS: MacOs Mojava
- Browser chrome
- Version 75.0.3770.142

**Comment by darthtrevino** [comment]
Thanks for the report! I've corrected the example you pointed out. I'll try to take a pass through the docs later in the month - if you could help us by identifying which pieces of documentation you found particularly confusing or wrong, that will help.
