### ISSUE TITLE
Can not import DragDropContext in v9.3.2

### ISSUE THREAD

**Issue by shenghou** [react-dnd/react-dnd#1489]
**Describe the bug**
I upgraded dnd  from 7.4.5 to 9.3.2, but the browser throw an error:

Attempted import error: 'DragDropContext' is not exported from 'react-dnd'. in 9.3.2

**Reproduction**

[DEMON](https://codesandbox.io/s/youthful-benz-j9uvu)

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/24260845/61765350-4c56a500-ae0f-11e9-9f08-24802482f805.png)

**Desktop (please complete the following information):**

- Browser [ chrome last version]

**Additional context**

**Comment by ekaradon** [comment]
Well, it may have been fixed with the 9.3.3 version but not yet released as npm package. I don't know why?

**Comment by adiosneo** [comment]
Hi, `DragDropContext` was removed since version 9 [https://github.com/react-dnd/react-dnd/pull/1439](https://github.com/react-dnd/react-dnd/pull/1439)

**Comment by shenghou** [comment]
> Hi, `DragDropContext` was removed since version 9 #1439

oh thx

**Comment by hisuwh** [comment]
Whats the migration path now that this has been removed?

**Comment by alencarlucas** [comment]
Guys, is there any migration guide for the breaking changes in the 9.x version?

**Comment by shenghou** [comment]
> Guys, is there any migration guide for the breaking changes in the 9.x version?

No, You can remind the author to update the document.

**Comment by hisuwh** [comment]
This is what I ended up doing

```diff
- import { DragDropContext } from "react-dnd";	
- import HTML5Backend from "react-dnd-html5-backend";	
-
- export const withDragDropContext = DragDropContext(HTML5Backend);
+ import * as React from "react";
+ import HTML5Backend from "react-dnd-html5-backend";
+ import { DndProvider } from "react-dnd";
+ 
+ export const withDragDropContext = <TProps extends {}>(Component:  React.ComponentClass<TProps> | React.StatelessComponent<TProps>) =>
+ {
+     return (props: TProps) => (
+         <DndProvider backend={HTML5Backend}>
+             <Component {...props} />
+         </DndProvider>
+     );
+ };
```

**Comment by ldd** [comment]
For those out there googling, this might help:

```jsx
import { createDndContext, DndProvider } from "react-dnd";
import Backend from "react-dnd-html5-backend";
// ...

const DndContext = createDndContext(Backend);

  <DndProvider backend={Backend} context={DndContext}>
    ....
  </DndProvider>
```

sources: [Dnd code](https://github.com/react-dnd/react-dnd/blob/master/packages/core/react-dnd/src/common/DndProvider.tsx)

**Comment by Liruimin2** [comment]
how to solve

**Comment by 1Jesper1** [comment]
As decorator component:

```
import * as React from 'react';
import { HTML5Backend } from 'react-dnd-html5-backend';
import { DndProvider } from 'react-dnd';

const DragDropContext = (WrappedComponent) => (props) => {
	return  (<DndProvider backend={HTML5Backend}>
		<WrappedComponent {...props} />
	</DndProvider>);
};

export default DragDropContext;
```
