### ISSUE TITLE
Drag Preview and size are incorrect when contains position: absolute elements

### ISSUE THREAD

**Issue by drpicox** [react-dnd/react-dnd#1492]
**Describe the bug**
Given a draggable item that contains an absolute positioned elements.
When the user drags it.
Then the preview is larger than the component itself and also shows elements below.

It gives the sensation that you are dragging more than one element simultaneously.

**Reproduction**

Code: https://codesandbox.io/s/react-dnd-example-13-87ot4

1. Start dragging the element "Create some examples"
2. Look that the drag preview contains some following elements.
3. Try move it again from any other position to see how preview changes.

**Expected behavior**
The drag preview size should not exceed the draggable element size.

**Screenshots**

![DnD-Bug](https://user-images.githubusercontent.com/2758345/62116682-e2c91180-b2ba-11e9-9a59-adb7d6e59130.gif)

**Desktop (please complete the following information):**

- OS: Windows 10 & Mac OS 10.14
- Browser Chrome
- Version 75

**Additional context**
The same problem arises when the draggable component hides the overflow.
A good practical example for this problem is the drag and drop of virtual-lists.

**Comment by GuillermoBlanco** [comment]
Seen same behaivour. 
It's a very bad user experience.

Can we reopen as it's a non fixed issue?

**Comment by tyler-ray** [comment]
Agreed. having the same problem

**Comment by vdesdoigts** [comment]
You can use `transform: 'translate3d(0, 0, 0)',` on your element.

**Comment by drpicox** [comment]
Still failing :/

https://codesandbox.io/s/peaceful-rubin-5q9gft?file=/src/Card.js
I am sorry that I couldn't allocate time to debug the library and contribute a PR with the fix :/

![StillFailing3](https://github.com/react-dnd/react-dnd/assets/2758345/7914f2de-88f1-49e6-a823-e88636533328)

**Comment by orange-groove** [comment]
This is still an issue in 2024. Fix of adding `transform: 'translate3d(0, 0, 0)'` works, but very unintuitive and should be in the docs or put up a fix to allow for absolute positioned elements within the drag zone without visual anomalies to the preview.
