### ISSUE TITLE
useDrop: hover(item, monitor) - item is dragged item, not hovered item

### ISSUE THREAD

**Issue by butchmarshall** [react-dnd/react-dnd#1493]
I'm attempting to port to the [useDrop](https://react-dnd.github.io/react-dnd/docs/api/use-drop) hook from [DropTarget](https://react-dnd.github.io/react-dnd/docs/api/drop-target).

In DropTarget the `hover(props, monitor, component)` `props` argument is the item properties of the item being hovered.

In `useDrop: hover(item, monitor)` both the `item` and `monitor` arguments are the dragged item?

Is there any way to get the properties of the item being hovered?
Additionally, is there any way to get the component of the item being hovered?  I need to calculate its position/dimensions.

**Comment by liamhubers** [comment]
When you use `useDrop` you're already in the component that is being hovered. You can just use the properties received from the component

**Comment by butchmarshall** [comment]
Thanks for the response @liamhubers  - are these properties available in the hover() function?

Or do you mean use the properties in the render function?

I don't believe the render function is possible, since I use the `hover` function to determine whether a swap is possible.

In `hover` I calculate the position of the dragged item and the hovered item.  I only do a swap operation based on your drag position above/below the hovered component (more than 50% above or more than 50% below)

**Comment by liamhubers** [comment]
Example from my code:
```
const SectionComponent = ({ section, ...props }: Props) => {
  const [, dropRef] = useDrop({
    accept: ['section', 'module_item'],
    hover: (item, monitor) => {
      // Can use section object here like this:
      const shouldDoAction = item.id === section.id;
    },
  });
}
```

**Comment by butchmarshall** [comment]
This is my current code to determine "should I swap these two items" using the older behaviour. 

From your code above, I don't know how to calculate `shouldDoAction` without access to both components?


    hover(props, monitor, component) {
      const monitorItem = monitor.getItem();

      // Get size and position of the hovered page
      const domNode = ReactDOM.findDOMNode(component);
      if (!domNode) {
        return;
      }
      const hoverBoundingRect = domNode.getBoundingClientRect(),
      // Get vertical middle
      hoverMiddleY = (hoverBoundingRect.bottom - hoverBoundingRect.top) / 2,
      // Determine mouse position
      clientOffset = monitor.getClientOffset(),
      // Get pixels to the top
      hoverClientY = clientOffset.y - hoverBoundingRect.top;

      const direction = (dragIndex < hoverIndex)? "down" : "up";
      // Dragging downwards
      if (direction === "down" && hoverClientY < hoverMiddleY) {
          return;
      }

      // Dragging upwards
      if (direction === "up" && hoverClientY > hoverMiddleY) {
          return;
      }

      if (direction === "down") {
          movedTo = monitorItem.onDragSwap(...);
      }
      if (direction === "up") {
          movedTo = monitorItem.onDragSwap(...);
      }
    }

**Comment by liamhubers** [comment]
Have a look at their sortable example, it also uses the useDrop hook: https://codesandbox.io/s/github/react-dnd/react-dnd/tree/gh-pages/examples_hooks_js/04-sortable/simple?from-embed

**Comment by butchmarshall** [comment]
`ref.current` was the key!  Thank you!
