### ISSUE TITLE
While dragging an item in a list inside an overflow scroll, auto-scroll doesn't work in IE11, Edge 12 and Safari

### ISSUE THREAD

**Issue by zeerorg** [react-dnd/react-dnd#1495]
**Describe the bug**
While dragging as item in a list inside an overflow scroll, auto-scroll doesn't work in IE11, Edge 12 and Safari
In the live example if you try to drag an item to the end of the view the scrolling starts in newer browsers, but doesn't work in IE11, Edge 12 and Safari.

**Reproduction**

[Live Reproduction](https://codesandbox.io/s/react-dnd-example-13-ywcjs)

1. Scroll to the middle
2. Hold down a "Number x" in the middle
3. Try to drag that to the top or bottom

Try these steps in Chrome/firefox/edge chromium and then try them in Safari/IE11/Edge 12

**Expected behavior**
The expected behavior is that the scrolling starts in browsers.

**Desktop (please complete the following information):**

- OS: Windows, Mac OSX
- Browser IE11, Edge 12 and Safari

**Additional context**
This issue has been reported before at https://github.com/react-dnd/react-dnd/issues/553 but the reported solution react-scrollzone hasn't been updated and since the functionality exists with react-dnd the behavior should be consistent across browsers.

**Comment by andrefox333** [comment]
Running into the same issue.

**Comment by XiaoBieThree** [comment]
如果有鼠标，鼠标有中键滚轮，在拖动时滚动鼠标滚轮，可以实现预期效果么
