### ISSUE TITLE
import error: 'DragDropContextProvider' is not exported from 'react-dnd'

### ISSUE THREAD

**Issue by palakvc** [react-dnd/react-dnd#1510]
I just switch form `"react-dnd": "^7.4.5"` to `"react-dnd": "^9.3.4"` and now I'm getting this erorr `'DragDropContextProvider' is not exported from 'react-dnd'`

**Comment by palakvc** [comment]
Just try to make the context of HTML5Backend a singleton. You can check the codes at:
- https://github.com/react-dnd/react-dnd/issues/186
- https://github.com/react-dnd/react-dnd/issues/708

**Comment by manthan-patel-digitattva** [comment]
i Am still getting error... for can't getting import from react-dnd  for **DragDropContextProvider**,,
can you give solution....

**Comment by OlgaKostiuk** [comment]
for 14.0.2 react-dnd version I wrote
```
    <div ref={wrapperRef} >
        <DndProvider
          backend={HTML5Backend}
          context={
            wrapperRef.current
              ? wrapperRef.current.ownerDocument.defaultView
              : window
          }
        >
   </div>
```
so I assume DndProvider should be used instead of DragDropContextProvider
