### ISSUE TITLE
How does the `props` argument in the collecting function work?

### ISSUE THREAD

**Issue by stevenkkim** [react-dnd/react-dnd#1515]
In the documentation for useDrag, useDrop, and useDragLayer, it says under `collect`: 

"It receives two parameters, `monitor` and `props`"

I understand the `monitor` parameter, but I don't understand the `props` parameter. What is it, and how is it used? I also cannot find an example that explains it.

I tried the following:
```
function DraggableComponent(props) {
  const [collectedProps, drag] = useDrag({
    item: { id: '1', type: 'test' },
    collect: (monitor, props) => {
      console.log('DraggableComponent monitor', monitor);
      console.log('DraggableComponent props', props);
      return { isDragging: monitor.isDragging() };
    }
  })
  console.log('collectedProps', collectedProps);
  
  return <div ref={drag}>DraggableComponent</div>
}
```

`monitor` works fine, but `props` is undefined. What am I missing? Thanks!

**Comment by Fled8617** [comment]
+1

**Comment by stevenkkim** [comment]
Has anyone figured this out? I still don't understand what the `props` argument is for in the collect function.

**Comment by metart43** [comment]
I am also not sure if I can use `connect` argument in the collect function. 
As well as `monitor.isOver` returns `undefined`. 
I couldn't find reference in docs regarding what functions can be called for `monitor` argument in `collect` function
