### ISSUE TITLE
How to get continuously updated client offset {x, y} position

### ISSUE THREAD

**Issue by stevenkkim** [react-dnd/react-dnd#1523]
While dragging an item, I need to continuously get client offset {x, y} coordinates so I can call a function or fire a redux action when the item is dragged to certain coordinates on the screen (but before the item is dropped).

I'm currently doing this by using useDragLayer and monitor.getSourceClientOffset().

Is this the right/best way to do this?

I looked at useDrag methods, and methods like begin, end, canDrag and isDragging do not seem to be continuously called. useDragLayer was the only thing I could get working, but not sure if that's the right way to do it.

Thanks!

**Comment by waynevanson** [comment]
We can use the `hover()` method in `useDrop()`. http://react-dnd.github.io/react-dnd/docs/api/use-drop#specification-object-members

It has a monitor where you can do what you need to do.

**Comment by stevenkkim** [comment]
Thanks @waynevanson, that works for me. The mistake I made was that since I wanted properties of the drag item I assumed the method should be in useDrag or useDragLayer. I didn't think to try the useDrop hover method. Thanks for helping me out! Much appreciated.
