### ISSUE TITLE
Drag Preview cuts off with a fixed width on parent container.

### ISSUE THREAD

**Issue by NaviMarella** [react-dnd/react-dnd#1530]
**Describe the bug**
Drag Preview is calculated based on what is shown in the active window. If we have a fixed width for parent container and add horizontal scroll to elements, drag preview is being cut off from the screen.

Here is the sandbox link.
https://codesandbox.io/s/react-dnd-example-13-3cot2

**Expected behavior**
Offset calculation for drag preview should be modified, to solve preview being cut off.

**Desktop (please complete the following information):**
Happens on all environments with latest version.

**Comment by anmlkh** [comment]
You can try to implement your own DragLayer. In this layer you can specify how you drag item should look like. 

Very raw example
https://codesandbox.io/s/react-dnd-example-13-cnrr9
