### ISSUE TITLE
Support for Drag & Drop across browser windows

### ISSUE THREAD

**Issue by meticoeus** [react-dnd/react-dnd#1533]
The HTML5 Drag and Drop API supports dragging data between browser windows.
Is there interest in adding support for this to the HTML5 Backend implementation?
Currently it doesn't work since it doesn't use the setData and getData functions of event.dataTransfer (as mentioned in other issues).

I think this can be made to work by partially extending the existing NativeSource handling.
Update the begin drag to set the stringified item with dataTransfer.setData, then work as normal in the same window.
If the dataTransfer.types array contains the json type and the local window is not already handling the event, then handle similarly to the NativeSource code pathway.
Add a source handler specifically for JSON and parse the payload on the drop event.
One change is that I think instead of white-listing certain properties, it would probably be simpler to assign the parsed object's props into the item so that consumers receive the same data object shape whether it came from the same window or a different window.

**Comment by reinvanleirsberghe** [comment]
Would love to have this support as well...

**Comment by Falkyouall** [comment]
this feature would bring a very big improvement to our app at work. please re-activate <3

**Comment by AlexandreExtier** [comment]
Hello, I use DnD for dragging TreeItem inside a TreeView. And it would be very usefull if I could drag TreeItems between Treeview from different browser windows. Thanks guys !
