### ISSUE TITLE
Module won't import in typescript - browerify errors ( 'import' and 'export' may appear only with 'sourceType: module'`)

### ISSUE THREAD

**Issue by pierznj** [react-dnd/react-dnd#1536]
**Describe the bug**
The app will not build due to errors thrown by gulp/browserify:

`.../node_modules/react-dnd/dist/esm/index.js:1
export * from './common';
^
ParseError: 'import' and 'export' may appear only with 'sourceType: module'`

This is the first time I've ever seen this with any module, and I have imported many external libraries in my React app. I am following the implementation in the examples.
**Reproduction**

Sorry, I can't provide reproduction steps as the setup is too complex.

**Additional context**
The build step is as follows:

 ```const compileScript = (done) => {
    return browserify({
      basedir: '.',
      debug: mode === 'dev',
      entries: [`${paths.src}/app/${buildConfig.appFolder}/${buildConfig.appSrc}`],
      cache: {},
      packageCache: {},
    })
      .plugin(tsify)
      .transform('babelify', {
        presets: ['es2015'],
        extensions: ['.ts'],
      })
      .bundle()
      .pipe(source('app.js'))
      .pipe(gulp.dest(`${paths.dist}/app/${buildConfig.appFolder}`))
      .on('error', err => {
        console.error(err.toString()); // eslint-disable-line
        done(err);
      });
```
I also tried importing from `/dist/cjs`, but I still get the same error.

**Comment by RecaMedia** [comment]
I'm also getting this error after a fresh install via npm.

```
..\node_modules\react-dnd\dist\esm\index.js:1
export * from './common';
```

Any idea on how to resolve this issue? Other repos such as react-sortable-tree and react-sortly that depend on this code base, are also giving the same warning.

**Comment by darthtrevino** [comment]
You can try using `react-dnd-cjs` and `react-dnd-html5-backend-cjs` for commonjs modules, which may be the use case you're looking for.

**Comment by RecaMedia** [comment]
@darthtrevino that does work. However, I was try to use ‘react-sortly’, which searches for ‘react-dnd’.

After more research, I found out by updating babel to the latest version, I no longer got this error. Instead, I have totally new one related to babel presets.

I guess if I just revert my dependencies, and modify ‘react-sortly’ within the node_modules folder to use ‘react-dnd-cjs’, that may work just not ideal.
