### ISSUE TITLE
Cannot hide Source element behind Drag Layer

### ISSUE THREAD

**Issue by KosGrillis** [react-dnd/react-dnd#1549]
I'm implementing a multi-select drag and drop feature and one of my requirements is to show all selected items in the drag preview.

I understand this can be done using a custom `DragLayer`, so I implemented the following with help from the examples:

```
const styles = ({ palette, spacing }: Theme) =>
  createStyles({
    layer: {
      position: 'fixed',
      pointerEvents: 'none',
      zIndex: 100,
      left: 0,
      top: 0,
      width: '100%',
      height: '100%',
    },
  })

function getItemStyles(props: CustomDragLayerProps) {
  const { initialOffset, currentOffset } = props
  if (!initialOffset || !currentOffset) {
    return {
      display: 'none',
    }
  }

  const { x, y } = currentOffset

  const transform = `translate(${x}px, ${y}px)`
  return {
    transform,
    WebkitTransform: transform,
  }
}

export interface CustomDragLayerProps extends WithStyles<typeof styles> {
  item?: any
  itemType?: Identifier | null
  initialOffset?: XYCoord | null
  currentOffset?: XYCoord | null
  isDragging?: boolean
}

const CustomDragLayer: React.FC<CustomDragLayerProps> = (props) => {
  const { item, itemType, isDragging, classes } = props

  if (!isDragging) {
    return null
  }
  return (
    <div className={classes.layer}>
      <div style={getItemStyles(props)}>
        <React.Fragment>
          {item.items.map((item: any) => (
            <div>
              { item }
            </div>
          ))}
        </React.Fragment>
      </div>
    </div>
  )
}

export default DragLayer((monitor) => ({
  item: monitor.getItem(),
  itemType: monitor.getItemType(),
  initialOffset: monitor.getInitialSourceClientOffset(),
  currentOffset: monitor.getSourceClientOffset(),
  isDragging: monitor.isDragging(),
}))(withStyles(styles)(CustomDragLayer))
```

The above works, to a point, in that it displays all the selected items which I manually inject into `item` elsewhere in the code. The problem is, the default drag preview (one item) is still shown above my custom drag previews.

How can I disable the default drag preview behaviour?

**Comment by dawidaksamski** [comment]
Have you override the default preview with empty image in your drag source?

`useEffect(() => {
    preview(getEmptyImage(), { captureDraggingState: true })
  }, [])`

**Comment by KosGrillis** [comment]
> Have you override the default preview with empty image in your drag source?
> 
> `useEffect(() => { preview(getEmptyImage(), { captureDraggingState: true }) }, [])`

I've just tried to implement this. But it doesn't seem to hide the _preview_ image of the drag (i.e, the element at the mouse cursor as you're dragging). It only hides the original element.
