### ISSUE TITLE
How to customize the size of DragPreviewImage

### ISSUE THREAD

**Issue by vdtn359** [react-dnd/react-dnd#1555]
**Describe the bug**
I need a way to customize the size of DragPreviewImage. Currently what I am trying to do is to create a new canvas and use it as a preview image but it doesn't work

```
const [{ isDragging }, drag, preview] = useDrag({
		item: { type: PLAYER, player, zone: PLAYER_ITEM_ZONE },
});

useEffect(() => {
      const img = new Image();
      img.src = src;
      const ctx = document.createElement('canvas').getContext('2d');
      ctx.canvas.width = 50;
      ctx.canvas.height = 50;

      img.onload = () => {
	    ctx.drawImage(img, 0, 0, ctx.canvas.width, ctx.canvas.height);
	    preview(ctx.canvas);
      };
}, []);

```
**Expected behavior**
The preview image could be resized

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Chrome
- Version: react-dnd 9.4.0

**Comment by AaronPorts** [comment]
You can replace image src by data URI from canvas and use it in preview.
```
useEffect(() => {
      const img = new Image();
      img.src = src;
      const ctx = document.createElement('canvas').getContext('2d');
      ctx.canvas.width = 50;
      ctx.canvas.height = 50;

      img.onload = () => {
	    ctx.drawImage(img, 0, 0, ctx.canvas.width, ctx.canvas.height);
            img.src = c.toDataURL();
	    preview(img);
      };
}, []);
```

**Comment by OctoD** [comment]
For everybody reading this, bear in mind that creating an image with canvas could lead to problems with the *Tainted canvases may not be exported* security error.

[read here](https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_enabled_image)

It would not be a bad idea to provide a way to render a new component while dragging.

**Comment by AnthonySgro** [comment]
@AaronPorts where did the "c" variable in this line come from?
`img.src = c.toDataURL();`

**Comment by AaronPorts** [comment]
I guess `img.src = ctx.toDataURL();` should be.

**Comment by prashantDigimonk** [comment]
also this is not working
