### ISSUE TITLE
Resizing the drag source before dragging?

### ISSUE THREAD

**Issue by skrawn** [react-dnd/react-dnd#1556]
I have a very large form that needs to use drag and drop to re-order items in it. Each of these sub-forms can take up roughly 3/4 of a page so trying to re-order these at their normal size is clunky. I want to collapse all the sub-forms and show a smaller form for dragging (that would also be the drag preview) but when I trigger this in a begin() event or a onMouseDown() event, the grab handle's position on the page changes when the subforms collapse, which immediately calls the onBlur() handler for the handle and cancels the drag. Does react-dnd support some sort of work-around to this problem?

**Comment by metafoo** [comment]
Did u find a solution for this?
