### ISSUE TITLE
UMD build in IE 11 gives syntax error

### ISSUE THREAD

**Issue by ntrahan** [react-dnd/react-dnd#1557]
**Describe the bug**
Running the UMD builds of react-dnd and react-dnd-html5-backend (both v. 9.4.0) in IE 11 gives a syntax error.

**Reproduction**
Create a blank HTML document with script tags that include the following: react.development.js & react-dom.development.js (both v. 16.8.0) and ReactDnd.js & ReactDndHTML5Backend.js (both v. 9.4.0, from the dist/umd folders of the react-dnd and react-dnd-html5-backend node_modules folders).

**Expected behavior**
No syntax error (since the README page claims a Browserlist Target of ">0.25%, not dead", which would include IE 11).

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/3845815/65924102-3807c900-e3b9-11e9-8147-9e65a17b2473.jpg)

**Additional context**
Note that the first syntax error occurs at an eval statement that tries to execute some code that contains the object spread syntax, which IE 11 doesn't support. The minified versions of the scripts also include unsupported syntax. I also tried to use Babel to transpile the scripts to ES5 myself, but it still leaves a single error where IE will complain about 'Symbol' being undefined.

**Comment by jai1331** [comment]
Facing the same  problem, Are you managed to get this work ? I'm getting error in IE edge like : 'Symbol' is undefined File: DataProvider.js

**Comment by ntrahan** [comment]
Unfortunately no, in the end I gave up and just implemented what I needed using the HTML 5 drag and drop APIs directly.

**Comment by darthtrevino** [comment]
I suspect that this is because the webpack configuration is bundling the code code that's directly outputted from tsc, not the babel-processed env-compatible result. I'll dig into this today, I may switch up the bundler to rollup as well.
