### ISSUE TITLE
Collect monitor on useDrag

### ISSUE THREAD

**Issue by fantgeass** [react-dnd/react-dnd#1559]
**Describe the bug**
Is it normal behaviour that collect monitor does not track `monitor.getClientOffset` properly? It only takes initial value.

**Reproduction**
https://codesandbox.io/s/react-dnd-example-3-k1zcj

**Steps to reproduce the behavior:**
Drag any draggable and check console to see that offset is not tracked.

**Comment by anmlkh** [comment]
You can check it in custom drag layer. https://codesandbox.io/s/react-dnd-example-3-uteou

**Comment by MinJieLiu** [comment]
Bad advice

**Comment by BigWeather** [comment]
I agree with @MinJieLiu, creating a custom drag layer shouldn't be the answer. Why are the values returned from getClientOffset and getSourceClientOffset the same as getInitialClientOffset and getInitialSourceClientOffset (and of course then getDiffenceFromInitialOffset is always x=0, y=0 as a result)? It is in the documentation and it is extremely inconvenient to have to create a custom drag layer to track them (and, in my case, get them back to the drag source for processing).
