### ISSUE TITLE
getEmptyImage() from HTML5 backend sets cursor to default?

### ISSUE THREAD

**Issue by KosGrillis** [react-dnd/react-dnd#1563]
Using a combination of

``` 
React.useEffect(() => {
    preview(getEmptyImage(), { captureDraggingState: true })
  }, [])
```

And a custom drag layer in order to render customized preview objects overrides custom cursor styles I have set on my drag targets.

Is there any way to prevent this behaviour?

**Comment by orlandovallejos** [comment]
@KosGrillis how did you fix this issue?
