### ISSUE TITLE
V9.4.0  Error: Cannot have two HTML5 backends at the same time.

### ISSUE THREAD

**Issue by NexxLuo** [react-dnd/react-dnd#1571]
**Describe the bug**

Although the new version has been fixed this issue in #1422 .
But I still  found has this problem .Maybe ignore some situation?
Look like this https://nexxluo.github.io/tablex/doc-draggable-index.
I try to click the menu more time, it throw this problem.

There is a gif image below, maybe it is slow, wait patiently...
 
![TEST](https://user-images.githubusercontent.com/18549980/66379736-9ef43600-e9e8-11e9-95db-5a3ce90f691b.gif)

- OS: windows 10
- Browser : chrome 77.0
- Version : 9.4.0

**Comment by Enigma10** [comment]
I am also having same issue.

**Comment by NexxLuo** [comment]
I solved it with this way.

`
     <DndProvider backend={HTML5Backend} context={window}></DndProvider>
`

**Comment by NexxLuo** [comment]
I solved it with using  window context.

**Comment by NexxLuo** [comment]
> I am also having same issue.

I solved it with using window context.

**Comment by WizardWang94** [comment]
Thanks! Why it can works? Are there any documents about this?

我遇到了相同的问题，用这个方法解决了，但是为什么它能生效呢？有相关文档吗？
