### ISSUE TITLE
CommonJS build: error in module's path in "Testing" doc for Jest.

### ISSUE THREAD

**Issue by Colmea** [react-dnd/react-dnd#1592]
**Describe the bug**

After hours of debugging, I realised that in the "Setup Testing for Jest" doc (https://react-dnd.github.io/react-dnd/docs/testing#setup),
CommonJS build points to `react-dnd/dist/cjs`, which doesn't seem to exist anymore.

Shouldn't it be `react-dnd-cjs` ?

Furthermore, after digging in the react-dnd package, we still have a `react-dnd/dist/ReactDnD.js` file, which looks like an UMD module.
I first decided to try this UMD module for my Jest config, but it doesn't work: the `DndProvider` is not properly exported (see error below when running in my app or in Jest tests). Everything's working well with the new `react-dnd-umd-builds/dist/ReactDnd.js` UMD build, though.

```
 console.error ../../node_modules/react/cjs/react.development.js:175
    Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
    
    Check the render method of `WrapperComponent`.
        in WrapperComponent
```

Is the `react-dnd/dist/ReactDnD.js` not up-to-date anymore ?

**Reproduction**

See the doc: http://react-dnd.github.io/react-dnd/docs/testing

![image](https://user-images.githubusercontent.com/974918/68230684-cd6e2c80-fff9-11e9-8567-abcdb1da9fcd.png)

EDIT: I would be happy to create a PR to fix, at least, the typo in the Documentation. I'm just waiting for your feedback to know if it's a real issue or if I'm missing something :)

**Comment by darthtrevino** [comment]
The dist/ folder for react-dnd libraries

`dist/esm` (module main)
`dist/cjs` (for testing/webpack aliasing purposes)
`dist/umd` for libraries with UMD exports. 

with `react-dnd-cjs`, the package `main` field is the CommonJS variant of the library, and the package dependencies have been rewritten to their `-cjs` variants (e.g. `dnd-core-cjs`) to allow these libraries to be used as a system without goofy config.

With Node 13.2, the harmony module system is enabled by default (thank God), so there's a light at the end of the tunnel WRT the JS ecosystem's module hell when it drops in Node 14 LTS. What you'll see is more and more libraries moving towards ESM as the default module format, and CJS being a deprecated relic of the past.
