### ISSUE TITLE
endDrag is not triggered

### ISSUE THREAD

**Issue by lorekadam** [react-dnd/react-dnd#1594]
I have a problem with endDrag. It is not triggered when DragSource component has been unmounted while dragging. Has anyone run into the same problem?

**Comment by bplok20010** [comment]
I solved it. 
eg:
```
componentWillUnmount(){
...

if(isDragging) {
dragDOM.style.display = "none";
document.body.appendChild(dragDOM);
}
...
}
```

```
DragOptions = {
 end(){
   ...
   dragDOM.parentNode.removeChild(dragDOM);
   ...
 }
}
```

**Comment by lorekadam** [comment]
I figured out that if you create copy of dragged element somewhere in DOM endDrag event will be triggered even if original dragged element will be unmounted :) (kinda weird but it is working)

**Comment by ArcaneDiver** [comment]
hey may you provide me and example of  how get the DOM ref of the drag obj.

**Comment by lorekadam** [comment]
Hey you can create ref eg: 
`  
const DragSourceComponentFunctions = {
  beginDrag(props, monitor, component) {
   // here is DOM ref of drag object
    const dragSourceDOM = component.bookingRef.current;
  }
}
class DragSourceComponent extends Component {
    constructor(props) {
    super(props);
    this.dragSourceRef = React.createRef();
  }
  render() {
    return (
       <div ref={this.dragSourceRef} />
    )
  }
}
`

**Comment by ArcaneDiver** [comment]
Thanks
