### ISSUE TITLE
ReactDnD plugin is not working in IE Edge browser?

### ISSUE THREAD

**Issue by learnToCode02** [react-dnd/react-dnd#1623]
I'm using ReactDnd for my drag and drop functionality in my new project which works perfectly.

It works perfectly in Chrome and firefox, things turned worse when I've checked it in IE. It throws error while opening page/while page loading.

Errors :

    Symbol is not defined.

    *Symbol is undefined*
    *File: DndProvider.js, Line: 77, Column: 1*

    Even the demo codesandbox is not working in IE which is listed in official React DnD page.

Almost, i have finished the functionality with React Dnd, now I struggled to put it in production since it throws errors in IE. Anyone, please help me on this, What I have to do to get this work on IE.

Raised a question on Stackoverflow too : https://stackoverflow.com/questions/59027926/why-reactdnd-plugin-is-not-working-in-ie-edge-browser

**Comment by darthtrevino** [comment]
With the current React-DnD, you have to bring your own polyfills. I would recommend looking at core-js for a Symbol polyfill.

**Comment by learnToCode02** [comment]
Thanks, but where I can find this core-js file ? and I hope bringing polyfills will solve my problem, will surely check now.

**Comment by darthtrevino** [comment]
https://github.com/zloirock/core-js

You install it as a dependency with `yarn add core-js` and then `import 'core-js'` or `require('core-js')` at the top of your application to have it polyfill your environment.
