### ISSUE TITLE
Typescript incorrect import in types file

### ISSUE THREAD

**Issue by jdemeuse1204** [react-dnd/react-dnd#1628]
**Describe the bug**
`DndProvider.d.ts` imports react differently than all other type files.  `import React from 'react'` is not valid unless `"allowSyntheticDefaultImports": true` is set in the tsconfig.json.  All other type files import react correctly `import * as React from 'react'`.

**File Location**
react-dnd/lib/common/DndProvider.d.ts

**Expected behavior**
All type files should import react in the same manner

**Screenshots**
![image](https://user-images.githubusercontent.com/5512999/69552301-d781ac00-0f63-11ea-89f2-5c675b9b61a3.png)

**Desktop (please complete the following information):**

- OS: All
- Browser All
- Version 9.5.0

**Comment by darthtrevino** [comment]
It looks like we depend on allowSyntheticDefaultImports across the libraries (it's used in dnd-core to import asap and invariant). I'll see what we can do turn, but this will be a more involved that changing that specific file.

**Comment by sandersn** [comment]
Breaks the following `@types` packages that depend on react-dnd:

* react-dnd-multi-backend
* react-sortable-tree
* react-sortable-tree-theme-file-explorer

See [the test run on Definitely Typed](https://dev.azure.com/definitelytyped/DefinitelyTyped/_build/results?buildId=25055&view=logs&j=b2dd9be2-fb32-52f8-c4c9-7dc0bc384587&t=f2dea62c-b696-5a51-78ad-206032e0a320&l=14799).

**Comment by sandersn** [comment]
The smallest fix is just to change the imports:

```ts
import * as React from 'react';
import { memo } from 'react';
```

But I think you should remove allowSyntheticDefaultImports in order to have the highest compatibility across Typescript users. asap and invariant themselves have `@types` packages, so they are tested to work without allowSyntheticDefaultImports.

**Comment by darthtrevino** [comment]
I can cut a patch tonight that will fix this import, and possibly synthetic imports with a couple of utility libraries. The one gotcha here is the 'hoist-non-react-statics' library which uses 'react-is', which is part of react, which is not published in ESM. 

The options with that library will either be:
1) `@ts-ignore` it, and depend on bundlers to load the dependency correctly
2) `require('hoist-non-react-statics')`, which breaks ESM purity and depends on bundlers to resolve the require correctly.
3) Convince React to publish ESM modules
4) Find a replacement library
