### ISSUE TITLE
Migration from Redux in the kernel

### ISSUE THREAD

**Issue by popuguytheparrot** [react-dnd/react-dnd#1720]
Hey.
Are there plans for migration from Redux to self solution or react-state, or something else?

Why am I asking this?
Not all projects use Redux. It just turns out to be redundant and increases bundle size.

**Comment by darthtrevino** [comment]
dnd-core is not react specific, so using react-state is out of the question. At it's heart it's a state engine designed around the redux pattern. If there was a compelling argument that expressed how many bytes redux is costing in a final tree-shaken bundle size it may be worth a small DIY replacement, but it's not something I'm very eager to do.

**Comment by clawoflight** [comment]
You could have a look at https://github.com/react-spring/zustand - it's much smaller than redux while covering most of the same use-cases, making it a better fit for use in a library.

**Comment by msdrigg** [comment]
Redux is 18% of the final bundle.

https://bundlephobia.com/package/react-dnd@16.0.1

Not as much as I expected honestly
