### ISSUE TITLE
When change ratio screen down 85%, copy item still keep init size (in 100% screen)?

### ISSUE THREAD

**Issue by cuongdevjs** [react-dnd/react-dnd#1855]
**Describe the bug**

**Reproduction**

[Live Reproduction](https://codesandbox.io/....)

1. Turn on Devtool and open mode screen smaller
2. Drag item
3. Item copy still keeps its initial size

**Expected behavior**

**Screenshots**
<img width="1677" alt="Screen Shot 2020-01-17 at 16 14 32" src="https://user-images.githubusercontent.com/33604446/72599524-74e5d480-3944-11ea-8586-dbe35b229dcd.png">

**Comment by IamFonky** [comment]
Sadly the link you gave is not working.

**Comment by cuongdevjs** [comment]
you can use any example in this repo. Just turn on devtools mode and select screen smaller then drag. This is my case.

**Comment by IamFonky** [comment]
Yes but when I click on the link "live reproduction" that you wrote in the previous comment it sends me to a 404 not found page.

**Comment by IamFonky** [comment]
Yes but the link to the repo (Your Live Reproduction link) points me to "https://codesandbox.io/...."
