### ISSUE TITLE
Sandbox nested example not found

### ISSUE THREAD

**Issue by saschahofmann** [react-dnd/react-dnd#2060]
**Describe the bug**
Trying to see the code for the nested target example for either Javascript or Typescript gives the 
`Not Found
We could not find the sandbox you're looking for.` error. 

**Reproduction**
Go to https://react-dnd.github.io/react-dnd/examples/nesting/drop-targets, click Javascript or Typescript.

**Comment by saschahofmann** [comment]
In fact, this happens for all examples I have tried.

**Comment by IvanFon** [comment]
Seems like a duplicate of #1963

**Comment by saschahofmann** [comment]
indeed
