### ISSUE TITLE
Resizing

### ISSUE THREAD

**Issue by joejavacavalier2001** [react-dnd/react-dnd#2162]
I know this is a lot to ask, but...
Is it possible to add resizing to the useDrag and useDrop hooks?

**Comment by timoleinio** [comment]
I'm also interested in this. Is this currently possible somehow? Could not find anything on docs.

**Comment by joejavacavalier2001** [comment]
TBH: I used a different library for my application. "react-rnd"
I found it too awkward to combine resizing with the react-dnd.
The react-dnd library supports several backends such as ones that support touch events.
That means for now, I don't support mobile devices for my particular application right now.
