### ISSUE TITLE
react-window issue: Invariant Violation

### ISSUE THREAD

**Issue by radulle** [react-dnd/react-dnd#2181]
**Describe the bug**
When using react-window getting the following issue that happens as soon as the state is updated.
```
Invariant Violation
Expected to find a valid target.
at invariant (https://itdrm.csb.app/node_modules/
react-dnd/invariant/dist/invariant.cjs.development.js:31:15
DragDropMonitorImpl.canDropOnTarget
https://itdrm.csb.app/node_modules/dnd-core/dist/cjs/DragDropMonitorImpl.js:111:32
eval
https://itdrm.csb.app/node_modules/react-dnd-html5-backend/dist/cjs/HTML5Backend.js:296:30
HTML5Backend.handleTopDragOver
https://itdrm.csb.app/node_modules/react-dnd-html5-backend/dist/cjs/HTML5Backend.js:295:47
```

**Comment by radulle** [comment]
This issue happens because react-window destroys items on list change so there are no valid drop targets. It is solved by adding a drop ref on a container too as it is done in [simple sample](https://react-dnd.github.io/react-dnd/examples/sortable/simple) which is something I forgot to do.

**Comment by tuanddd** [comment]
@radulle, how can you manage to do that with the `key` props? Once I pass the `key` props to the item it caused the error, if it is not passed then everything works but React is not updating the list which caused the `isDragging` to be incorrect.

To reproduce, just comment out the `key={card.id}` and try dragging around.
