### ISSUE TITLE
How to customize the preview effect when dragging the drag source

### ISSUE THREAD

**Issue by VirgoArt** [react-dnd/react-dnd#2382]
I want to customize the blurred content area that the mouse pulls while dragging. Can you tell me how to do it?
![image](https://user-images.githubusercontent.com/41778222/81388218-90225d00-914a-11ea-9322-e8d43a3e1d22.png)

**Comment by tannerbaum** [comment]
import DragPreviewImage 
https://react-dnd.github.io/react-dnd/docs/api/drag-preview-image

**Comment by VirgoArt** [comment]
> import DragPreviewImage
> https://react-dnd.github.io/react-dnd/docs/api/drag-preview-image

This program needs to create a picture, I need to display a div area directly.
I see that in Image Drag, perview is triggered in img load, but how do I use div to operate

**Comment by tannerbaum** [comment]
Could you maybe style the div by setting a class onHover (or preferably onDrag if the library would catch that change for the preview) and then remove the class after drop?

**Comment by VirgoArt** [comment]
I can get the dragging and draged event, set the marker for the creation and destruction of mousemove, but this is how to guarantee performance in react

> Could you maybe style the div by setting a class onHover (or preferably onDrag if the library would catch that change for the preview) and then remove the class after drop?

I can get the dragging and draged event, set the marker for the creation and destruction of mousemove, but this is how to guarantee performance in react

My current way is to draw an image via canvas and then use toDataURL() to get the img url, it works fine, but I do n’t like it

**Comment by zalelion** [comment]
@VirgoArt  

I use `position:relative` drag itself. 

![pagegif](https://user-images.githubusercontent.com/8503065/83201505-31b03380-a178-11ea-9253-d53cdec794f5.gif)

```ts
const [{ isDragging }, drag] = useDrag({
    collect(monitor) {
      const isDragging = monitor.isDragging();
      if (isDragging) {
        const offset = monitor.getDifferenceFromInitialOffset() || {
          x: 0,
          y: 0,
        };
        setOffsetDebounce(offset);
      }

      return {
        isDragging,
      };
    },
```

```html
<div
      ref={ref}
      style={{
        position: "relative",
        top: isDragging ? top + "px" : "0px",
        left: isDragging ? left + "px" : "0px",
        zIndex: isDragging ? 100000 : 0,
      }}
    >
      {children}
</div>
```

**Comment by VirgoArt** [comment]
got it , thanks
