### ISSUE TITLE
'react-dnd-html5-backend' does not contain a default export

### ISSUE THREAD

**Issue by Epsilon-Rashmi** [react-dnd/react-dnd#2487]
**Describe the bug**
Getting the below error when trying to include the module in my React App

Attempted import error: 'react-dnd-html5-backend' does not contain a default export (imported as 'HTML5Backend').

**Code **

`import React, { useCallback, useState } from "react";
import { DndProvider } from "react-dnd";
import HTML5Backend from "react-dnd-html5-backend";
import TouchBackend from "react-dnd-touch-backend";
const backendForDND = isTouchDevice() ? TouchBackend : HTML5Backend;

function App() {
return (
   

      <DndProvider backend={HTML5Backend}>
        <ImageList images={images} moveImage={moveImage} />
      </DndProvider>

  );
}
export default App;
`

**Desktop (please complete the following information):**

- IOS
- Chrome
- 81.0

**Comment by darthtrevino** [comment]
In v11 the backends were changed to named exports:
`import { HTML5Backend } from 'react-dnd-html5-backend`
