### ISSUE TITLE
Drop event on `useDrop` not triggering

### ISSUE THREAD

**Issue by hafeez1042** [react-dnd/react-dnd#2493]
**Describe the bug**
I'm trying to implement `react-dnd` with `HTML5Backend` in my project, first I tried to implement it manually and then used exact same code from the `react-dnd` example [link](https://react-dnd.github.io/react-dnd/examples/dustbin/single-target). but `drop` event is not triggering, even `hover` is triggering and consoled `monitor.canDrop()` it returned `true`.

**Desktop:**

- OS: Windows 10
- Browser Edge Chromium
- Version 83.0.478.37
- React DND Version 11.0.0

Edit: Also tried it on Google Chrome V 81.0.4044.138

**Comment by dbushell** [comment]
I'm experiencing the same issue after updating to `v11.0.0`.

**Comment by hafeez1042** [comment]
My project is running on a sharepoint environment, the issue was related to its parent container preventing the drop event, i couldn't solve the issue on the development environment, but no issue on production.

**Comment by dbushell** [comment]
hi @hafeez1042 are you expand on why the parent container prevented the drop event?

I've had no luck fixing my code. Any general insight would be be very helpful.

**Comment by hafeez1042** [comment]
The parent container already have some drag n drop functionality, So the parent container is stopping the event propagation.

**Comment by hafeez1042** [comment]
FYI: I was using Microsoft Sharepoint workbench for development

**Comment by dbushell** [comment]
ok thanks! That's given me something to investigate.
