### ISSUE TITLE
Expected drag drop context

### ISSUE THREAD

**Issue by guchengjie** [react-dnd/react-dnd#2526]
**Describe the bug**
invariant
./node_modules/@react-dnd/invariant/dist/invariant.esm.js:29
useDragDropManager
./node_modules/react-dnd/dist/esm/hooks/useDragDropManager.js:12
useDropTargetMonitor
./node_modules/react-dnd/dist/esm/hooks/internal/drop.js:20
useDrop
./node_modules/react-dnd/dist/esm/hooks/useDrop.js:28

**Reproduction**

[Live Reproduction](codesandbox.io/....)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- Browser [e.g. chrome]

**Additional context**

**Comment by zhaowei-plus** [comment]
大腿，问下你这个问题是怎么解决的，我也报这个错误

**Comment by o-faro** [comment]
Struggeling with same error and did a lot of research but couldn't solve it yet - could you?

**Comment by wozhaodiaodiao** [comment]
if you won`t use DndProvider to wraper your component that has processed by useDrop or useDrap,you will never get the context........so try it!

**Comment by o-faro** [comment]
Loosing dnd drag and drop context can even happen if you wrap it by DndProvider as it did in my case. I am tending to split large files into smaller pieces and if you do so with files containing dnd logic, chances are high to get this error. Try to write it down in one file and split afterwards.
In former versions splitting files was no problem, I refactored an existing dnd project and got this problem.

**Comment by HUGY1** [comment]
Don't use <DndProvider> and useDrop in the same file. it may cause 'Expected drag drop context'. and that s the way i solve .
