### ISSUE TITLE
Incorrect position when using a drag preview image

### ISSUE THREAD

**Issue by SebastianStehle** [react-dnd/react-dnd#2649]
**Describe the bug**
When I use a drag preview image that is bigger or smaller than the original image or element the position is wrong.

**Reproduction**

https://codesandbox.io/s/gallant-sea-h0evc

1. Drag and drop the green element to top left top corner of the blue target. Position should be around 0/0
2. Drag and drop the red element to the blue target so that the top left corners match. Position depends a lot on the initial position when you started dragging.

**Expected behavior**
Positions should be the same.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows
- Browser Chrome
- Version latest

**Comment by SebastianStehle** [comment]
Has anybody an idea how to solve this? Perhaps there is an hack how to retrieve the initial position?

**Comment by zach-clark** [comment]
Hey @SebastianStehle. I'm coming across this same issue, and was wondering if you have found a fix/workaround for this issue.

I can provide a little bit more information on affected platforms, as well: The issue is present only on Chrome under Windows. Firefox/Windows has no issues, nor do Chromium/Ubuntu or Firefox/Ubuntu. The issue only presents itself on Chrome/Windows.

**Comment by SebastianStehle** [comment]
Unfortunenalty not. But I have this issue on all browsers. I think it is not a browser bug.

**Comment by zach-clark** [comment]
Hmm, interesting that it's showing up for you everywhere, but for me only on Chrome. I just found that for me at least, disabling resolution scaling fixes the issue - so perhaps this could be related to #1583?

**Comment by SebastianStehle** [comment]
For me the problem only exists with the red box. Therefore I think it has something to do with the size of the element.

**Comment by SebastianStehle** [comment]
Has someone a solution or workaround for this?

**Comment by SebastianStehle** [comment]
I got it working with a custom image:

```
  const [, drag, connectDragPreview] = useDrag({
    item: { type: "thing" }
  });

  React.useEffect(() => {
    const img = new Image();
    img.src =
      "https://mydraft.cc/assets/image.c8817f2e29c599ae489e6a849cb270c7.png";
    connectDragPreview(img, {
      anchorX: 0,
      anchorY: 0
    });
  }, [connectDragPreview]);
  ```

**Comment by znacloud** [comment]
for those who want a solution, there's a workaround for this:
```ts
....
const siOffset = monitor.getInitialSourceClientOffset();
const piOffset = monitor.getInitialClientOffset();
const idx = (piOffset?.x ?? 0) - (siOffset?.x ?? 0);
const idy = (piOffset?.y ?? 0) - (siOffset?.y ?? 0);

const offset = monitor.getClientOffset();
let targetRect = tagContainer.current?.getBoundingClientRect();
//Below is the position relative to parent container
let left = (offset?.x ?? 0) - (targetRect?.left ?? 0) - idx * 0.5;
let top = (offset?.y ?? 0) - (targetRect?.top ?? 0) - idy * 0.5;
...
```

`idx*05` and `idy*0.5` is the key to fix position offset. 
The reason behind this is that the  cursor position of drag preview relative to drag source is scaled by 50%.

**Comment by MuhammadFadhil10** [comment]
> for those who want a solution, there's a workaround for this:
> 
> ```ts
> ....
> const siOffset = monitor.getInitialSourceClientOffset();
> const piOffset = monitor.getInitialClientOffset();
> const idx = (piOffset?.x ?? 0) - (siOffset?.x ?? 0);
> const idy = (piOffset?.y ?? 0) - (siOffset?.y ?? 0);
> 
> const offset = monitor.getClientOffset();
> let targetRect = tagContainer.current?.getBoundingClientRect();
> //Below is the position relative to parent container
> let left = (offset?.x ?? 0) - (targetRect?.left ?? 0) - idx * 0.5;
> let top = (offset?.y ?? 0) - (targetRect?.top ?? 0) - idy * 0.5;
> ...
> ```
> 
> `idx*05` and `idy*0.5` is the key to fix position offset. The reason behind this is that the cursor position of drag preview relative to drag source is scaled by 50%.

i don't know what to say, but it works. Many thanks bro!
