### ISSUE TITLE
npm install 404 error

### ISSUE THREAD

**Issue by luxuze** [react-dnd/react-dnd#2710]
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@react-dnd%2finvariant - Not found
npm ERR! 404
npm ERR! 404  '@react-dnd/invariant@^2.0.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'dnd-core'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by sujatha97714** [comment]
try this 'yarn add react-dnd' if the one that you have already tried is using npm

**Comment by luxuze** [comment]
fixd with taobao registry. Thanks @sujatha97714
