### ISSUE TITLE
Website example code has exception

### ISSUE THREAD

**Issue by hiyangguo** [react-dnd/react-dnd#2722]
**Describe the bug**
![image](https://user-images.githubusercontent.com/15609339/90006078-cf70c480-dcca-11ea-8299-5fbc922acae8.png)

**Reproduction**

[Live Reproduction](codesandbox.io/....)

1. Go to https://react-dnd.github.io/react-dnd/examples/sortable/cancel-on-drop-outside
2. Click on `Using Hooks` button.
3. Switch to `Typescript` tab.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/15609339/90006179-0050f980-dccb-11ea-9679-6253294c7b9b.png)

**Desktop (please complete the following information):**

- OS: [e.g. iOS] MAC
- Browser [e.g. chrome, safari] chrome 
- Version [e.g. 22]  83

**Comment by mburakeker** [comment]
Desktop:
OS: Windows
Browser: Chrome
Version: 85

And can confirm this.
