### ISSUE TITLE
monitor.getItem is not a function

### ISSUE THREAD

**Issue by alexandrebouttier** [react-dnd/react-dnd#2776]
hello i have a problem i have this error monitor.getItem is not a function
here is what my file looks like, reacts dnd work before without migration to hooks
https://pastebin.com/WBqAQjun

**Comment by elliott-king** [comment]
What did you see, alexandrebouttier???

![What did you see, alexandrebouttier???](https://imgs.xkcd.com/comics/wisdom_of_the_ancients.png)

Anyone else who may come here with a similar problem, make sure you double check the expected method arguments. For example, I had:
```javascript

  const [{ isOver }, drop] = useDrop(
    () => ({
      accept: reviewItemType.CARD,
      drop: (monitor) => {
        const projectId = monitor.getItem().uuid;
        updateProjectState({ projectId });
      },
    }),
  );
```

But checking the [docs](https://react-dnd.github.io/react-dnd/docs/api/use-drop#specification-object-members), the correct signature is `drop(item, monitor)`. So I changed to:
```javascript
      drop: (item) => {
        const projectId = item.uuid;
        updateProjectState({ projectId });
      },
```

**Comment by moderndayNeo** [comment]
@elliott-king  very helpful, thanks!
