### ISSUE TITLE
Html5 backend should support 'text/html' type

### ISSUE THREAD

**Issue by maxired** [react-dnd/react-dnd#2928]
**Is your feature request related to a problem? Please describe.**
I am using react-dnd to handle file dropping inside my app.
Some people are trying to drag and drog image from other tab form this browser. we currently receive the event with the data type corresponding to NativeTypes.URL. But the data transfer object I receive also has some data with type  `text/html`. I would like to be able to retrieve it.

**Describe the solution you'd like**
I want to be able to retrieve data with type `text/html`

**Comment by darthtrevino** [comment]
Thanks for the PR!
