### ISSUE TITLE
wrapInTestContext: Warning: Stateless function components cannot be given refs

### ISSUE THREAD

**Issue by borys-kupar** [react-dnd/react-dnd#2966]
**Describe the bug**
I am following the instruction to test component that uses react-dnd - https://react-dnd.github.io/react-dnd/docs/testing.

```
import { wrapInTestContext } from 'react-dnd-test-utils';
import { render } from '@testing-library/react';

const MyComponentWithDnD = wrapInTestContext(MyComponent);

render(<MyComponentWithDnD/>);
```

Once I wrap my component in test provider, I see the following warning:
```
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?
      
      Check the render method of `ForwardRef(TestContextWrapper)`.
          in MyComponent (created by ForwardRef(TestContextWrapper))
          in Unknown (created by ForwardRef(TestContextWrapper))
          in ForwardRef(TestContextWrapper) (at MyComponent.spec.tsx:67)
```

I am using react resting library.

**Desktop (please complete the following information):**

- OS: macOS
- Browser js-dom

**Additional context**
Using latest versions of package:
"react-dnd": "^11.1.3",
"react-dnd-html5-backend": "^11.1.3",
"react-dnd-test-backend": "^11.1.3",
"react-dnd-test-utils": "^11.1.3",

**Comment by darthtrevino** [comment]
The testing utilities have been reworked and now accept function components. You can also wrap your components with a live backend for more end-to-end testing with JSDOM. Check out the chess example in the repo. I hope that helps!
