### ISSUE TITLE
HTML5Backend overwrite other module's drag and drop event

### ISSUE THREAD

**Issue by xinmeipublic** [react-dnd/react-dnd#2995]
HTML5Backend --> setup() --> this.addEventListeners(this.window);  
-->  target.addEventListener('dragstart', this.handleTopDragStart);
-->  this.handleTopDragStart
-->  overwrite  by the last ELSE statement ：
{
    // If by this time no drag source reacted, tell browser not to drag.
    e.preventDefault();
}

**Comment by Lyndon-Wu** [comment]
I meet the same issue, is there a way to define the context and then bind the listeners?

**Comment by Lyndon-Wu** [comment]
> I've meet the same issue. Is there a way to define the context range and then bind the drag events? Please help if we have any solution. Thanks！

I've resolved it by apply dnd provider.

**Comment by darthtrevino** [comment]
In the latest version of HTML5Backend, you can pass a `rootElement` config option, which will localize the eventing of the HTML5Backend.
