### ISSUE TITLE
Applying options to a backend when using DragDropContext

### ISSUE THREAD

**Issue by JacksonGariety** [react-dnd/react-dnd#2997]
Hello. I'm using an old version of `react-dnd`. I'd like to be able to pass the `scrollAngleRanges` option to the `TouchBackend`, but I don't see how `DragDropContext` lets me do that.

For my purposes, upgrading to the newer version of `react-dnd` is not worth the trouble. Do I have to patch the touch backend to manually set the scroll angle ranges? Or is there a way to set it when using  `DragDropContext`

**Comment by darthtrevino** [comment]
`<DndProvider backend={TouchBackend} options={options}>`
