### ISSUE TITLE
all example codesandbox's broken

### ISSUE THREAD

**Issue by trebor** [react-dnd/react-dnd#3036]
**Describe the bug**

clicking through to the codesandbox for any example results in an:

~~~
ReferenceError React is not defined
~~~
**Reproduction**

1. browse to:

  https://react-dnd.github.io/react-dnd/examples/tutorial

2. click on the `JavaScript` tag.

**Expected behavior**

the examples to work.

**Screenshots**

![image](https://user-images.githubusercontent.com/12802394/108119353-81ab8f00-7054-11eb-9f65-a96bbedd8585.png)

**Desktop (please complete the following information):**

- OS: mac os: 10.15.7 (19H114)
- chrome: Version 88.0.4324.150 (Official Build) (x86_64)

**Comment by darthtrevino** [comment]
Fixed earlier today - updated react-scripts to use React 17 idioms

**Comment by trebor** [comment]
@darthtrevino thanks!
