### ISSUE TITLE
Cannot call endDrag while not dragging

### ISSUE THREAD

**Issue by ctiller15** [react-dnd/react-dnd#3051]
**Describe the bug**
It looks like in the tutorial and the examples whenever you run drag and drop, it will error out whenever you finish dropping.

**Reproduction**
[Example on the react-dnd project site](https://zr7ly.csb.app/)

[My repo with some small mods to the tutorial.](https://github.com/ctiller15/react-dnd-chess) (using `useState` instead of observers)

1. grab the knight
2. drag it to a valid square
3. drop the knight
4. See error, `cannot call enddrag while not dragging`

**Expected behavior**
Dragging would be successful, error would not occur.

- OS: ubuntu 20.04
- Browser: Firefox
- Version 85.0.1 (64-bit)

**Additional context**
This seems to be at least similar to #1481 . The solution seemed to be to upgrade to the latest version of react-dnd. That did not seem to solve the issue in this case.

**Comment by gpaslari** [comment]
I've got the same issue

**Comment by darthtrevino** [comment]
I can repro; investigating on my end

**Comment by ziaenroutech** [comment]
I've got the same issue

![image](https://user-images.githubusercontent.com/67310941/108692769-d94b6e00-751e-11eb-8345-ce4a0b8cf137.png)
