### ISSUE TITLE
useDrop({ hover }) not working properly on v13

### ISSUE THREAD

**Issue by otaciliolacerda** [react-dnd/react-dnd#3085]
**Describe the bug**
After upgrade from v11.1.3 to v13.1.1 when I have:
```js
const [, drop] = useDrop({
    accept: type,
    hover(item) {
      if (!ref.current) {
        return;
      }
      const dragIndex = item.index;
      const hoverIndex = index;
      if (dragIndex === hoverIndex) {
        return;
      }
      console.log(dragIndex, hoverIndex)
      // ...
}
```

When I start dragging a cards, the hovered card does not move (to change order) as in the previous version. 

EDIT: I am going to try to get a running example. I am not that familiar with react-dnd.

**Reproduction**

Suppose I have 2 cards that I can drag&drop to change the order. If I drag the card in position 1 to position 0 I have:

**For v11.1.3**: Card 1 switches place with card 0. The console in the code snippet above logs "1 0"

**For v13.1.1**: Card 1 stays on top of card 0 and place 1 stays blank. The console in the code snippet above logs:
```
1 0
0 1
1 0
0 1
// keeps logging non-stop
```

**Expected behavior**
To behave as previous version

**Desktop (please complete the following information):**

- OS: OSX 11.2.1
- Browser Chrome 
- Version 88.0.4324.182

**Comment by darthtrevino** [comment]
Does this behavior change if you use the memo pattern in useDrop? e.g. `useDrop(() => {*spec*}, [...deps])`

There is an example on the docsite of reordering cards, and that's the main test case we use for scenarios like this.

**Comment by otaciliolacerda** [comment]
Hi @darthtrevino, thanks for the quick reply. I got the same behaviour using the memo pattern. The example is quite interesting. I will play with this the next days and post updates here.

**Comment by darthtrevino** [comment]
Sounds good, let me know what you find. I'll be backpacking until Sunday

**Comment by otaciliolacerda** [comment]
Hi again, I've noticed my previous implementation is similar to the [simple sortable example](https://react-dnd.github.io/react-dnd/examples/sortable/simple), which is also not working with the new version on CodeSandbox.

Unfortunately I still did not have time to change my implementation to be similar to the working example you shared (dependency upgrade is a low priority task on my side).

**Comment by otaciliolacerda** [comment]
@darthtrevino I've managed to make it work using the example you gave. Thanks for the help.
