### ISSUE TITLE
Support for Custom DragHandles

### ISSUE THREAD

**Issue by shahlav** [react-dnd/react-dnd#3101]
**Problem:**
I have been using react-dnd in multiple projects, and I see to drag and drop item we can use the flags, but it would be great if we can create our own drag handles so that we do not need to add drag props to whole item in a list.
 
**Purposed Solution:**
Something like this, which react-beautiful-dnd supports out of the box here: https://codesandbox.io/s/vertical-list-dgy2q

We are using hooks approach and usage of react-dnd has been little complex, so would love to see this if possible.
If any one have reference for this using react-dnd, It would be great you can provide an example.

PS: I am requesting this feature as this is the second time I am facing this, for first use case we switched to react-beautiful-dnd as it was not major work over there, but as of now it is not possible for us to switch to react-beautiful-dnd, so will appreciate if some can help on this.

Thanks!

**Comment by darthtrevino** [comment]
There is a drag handle example in the doc site. Basically you attach the drag ref to the handle and the preview ref to the item. Does this do what you're looking for?

**Comment by darthtrevino** [comment]
Here's a link to that example:

https://react-dnd.github.io/react-dnd/examples/customize/handles-and-previews

**Comment by shahlav** [comment]
Hey @darthtrevino!
Sorry for the late reply, I checked the example and that is somewhat what I was looking for.

I am looking for a drag handle + drag to the original component both highlighted in the following image:
(Our use-case is a little different and we have a handle and the element little bit differently placed, the item inside iframe and handle is outside positioned on that with absolute positioning)
![image](https://user-images.githubusercontent.com/45399472/109881888-01fe0100-7c9f-11eb-9969-5a59dd8fb3f4.png)

Again thanks for the example, I'll play around on that weekend and see if I can get it working.

**Comment by darthtrevino** [comment]
Are they adjacent in the UI? One idea may be to have a container component that provides the spatial context between the handle and the item, and that container component would tie into the useDrag() hook
