### ISSUE TITLE
monitor.getItem() always returning null

### ISSUE THREAD

**Issue by lukevella** [react-dnd/react-dnd#3110]
**Describe the bug**
When I call `monitor.getItem()` inside `canDrag()` it always returns `null`. 

**Reproduction**

[Live Reproduction](https://codesandbox.io/s/blue-feather-413m0?file=/src/Box.tsx)

1. Drag around one of the boxes
2. Check the console to see the value of `monitor.getItem()` (it's always `null`)

**Expected behavior**
I expect the result to be either the value of `item` or whatever is returned by `begin()`. This is particularly useful in combination with `begin()` as some drag events need to be suppressed based on its result. 

**Desktop (please complete the following information):**

- OS: macOS
- Browser: chrome
- Version: 88.0.4324.192 (Official Build) (x86_64)

**Comment by darthtrevino** [comment]
The `monitors` in DnD are observers of DnD state. In this case, the dnd-core doesn't have an active drag-item because the system is still performing pre-drag work. 

I think this is more of an ergonomics issue. You can get the drag Item by using the same object as `item` in your spec. 
e.g. 
```js
const item = useMemo(() => ({type: 'box', id: 'banana'}), [])
const [...] = useDrag({item, ...})
```
We could pass it along as a separate argument, but then the API would feel wonky between functions in the useDrag spec. (e.g. end has dragObject as the first arg, canDrag would have it as the second arg) unless we cut a major semver, of course.

**Comment by lukevella** [comment]
Thanks for the reply. The real issue here is when we use `begin()` which makes the drag item dynamic. Take the following example:

```tsx
const [...] = useDrag({
   item: defaultItem,
   canDrag: (monitor) => {
        return monitor.getItem() !== defaultItem
   },
   begin: (monitor) => {
          // dynamically generate drag item
          return dynamicallyCreatedDragItem(monitor) // may return undefined
   }
})
```

In this case, my drag item is generated dynamically and I would like `canDrag()` to be `true` only if I was able to dynamically generate my drag item. A concrete use case for this is when working with `<canvas />` elements where the drag item needs to be generated based on the cursor position where the drag event was generated.

I have managed to work around this limitation by using a ref to store the dynamically generated drag item but this seems less than ideal.

```ts
const dragItem = React.useRef()

const [...] = useDrag({
   item: defaultItem,
   canDrag: () => {
        dragItem.current = dynamicallyCreatedDragItem(monitor)
        return dragItem.current !== undefined
   },
   begin: (monitor) => {
          return dragItem.current
   }
})
```

**Comment by darthtrevino** [comment]
I'm playing around with this a bit: in the way the sequencing works out , canDrag() is fired before begin(), so you don't have that item handy yet.

**Comment by lukevella** [comment]
Assuming that can be changed, would it make sense perhaps to change `begin()` so that it allows you to cancel a drag event? Currently if `begin()` does not return an object we default to `item` but if not returning anything canceled the event it would satisfy the use case that I am describing and the current behaviour can still be reproduce by defaulting to `item` explicitly.

```ts
const [...] = useDrag({
   item: defaultItem,
   begin: (monitor) => {
        // this mimics the current behaviour but if we want to cancel the drag event we can
        // choose to not default to a value
        return createDragItem(monitor) || defaultItem
   }
})

```

**Comment by darthtrevino** [comment]
Yeah, I think we could do that - perhaps by returning `null`?

**Comment by darthtrevino** [comment]
The PR goes a little deeper than the problem stated here, but I think this issue brought to light some usability issues with the useDrag() api.
