### ISSUE TITLE
Unable to use the useDrop - Error: accept must be defined

### ISSUE THREAD

**Issue by meeshh** [react-dnd/react-dnd#3121]
**Describe the bug**
I am simply using the useDrop hook but i am getting a strange Error in the console that `accept must be defined`

here's my code

```
const draggableTypes = {
  LAYOUT: 'LAYOUT',
  ELEMENT: 'ELEMENT',
};
```

```
  const [{ isOver }, drop] = useDrop(() => ({
    accept:  [draggableTypes.ELEMENT, draggableTypes.LAYOUT],
  }));

  return (
    <div className={classes.root}>
      <div
        ref={drop}
      >
         ...
      </div>
    </div>
```

- OS: macOS
- Browser chrome
- Version latest

**Comment by huaibaomengxiang** [comment]
i have same question, How did you solve it

**Comment by meeshh** [comment]
> i have same question, How did you solve it

There was something strange in my node server. I restarted the dev server and it worked fine after that

**Comment by CaaioSB** [comment]
> > eu tenho a mesma pergunta, como você resolveu isso
> 
> Havia algo estranho em meu servidor de nó. Eu reiniciei o servidor de desenvolvimento e funcionou bem depois disso

Works, thanks my friend :rocket:
