### ISSUE TITLE
Website example codesandboxes are not loading

### ISSUE THREAD

**Issue by wuweiweiwu** [react-dnd/react-dnd#3130]
**Describe the bug**

Codesandbox examples on the website are not loading (js + ts)

**Reproduction**

1. Go to https://react-dnd.github.io/react-dnd/examples/dustbin/multiple-targets
2. Click on `JS` or `TS`
3. See not found error

**Expected behavior**

codesandbox to load

**Screenshots**

<img width="823" alt="Screen Shot 2021-03-09 at 9 31 34 AM" src="https://user-images.githubusercontent.com/35270620/110512641-3ff18f80-80ba-11eb-83e3-2bf7282f7bd7.png">

**Comment by darthtrevino** [comment]
Hmm, it seems alright now, at least on my end
