### ISSUE TITLE
Console Error: Uncaught TypeError: this._drop is not a function

### ISSUE THREAD

**Issue by XiaTian-Dreamarts** [react-dnd/react-dnd#3132]
**Describe the bug**
Hello. I'm trying to make a sortable list following the example.
Every time when I do the dropping this following error is shown in console.
It only happens in Chrome and DnD itself work well.

<img width="541" alt="スクリーンショット 2021-03-11 16 19 14" src="https://user-images.githubusercontent.com/70364918/110750500-eb9b0b00-8285-11eb-98b6-2fc9f2cbcc5d.png">

**Reproduction**

It also happens in all the [examples](https://react-dnd.github.io/react-dnd/examples/drag-around/naive)
 in the document if I open the devTool.

**Expected behavior**

No exception.

**Screenshots**

**Desktop (please complete the following information):**

- OS: [MacOS 10.14]
- Browser [chrome]
- Version [89.0.4389.82]

**Additional context**

**Comment by darthtrevino** [comment]
I don't see any errors in the console or the examples, and a quick search for `_drop` in the repository yielded no code results. I'm not sure where your error is coming from

**Comment by XiaTian-Dreamarts** [comment]
Thank you for your reply.
I checked plugins in my Chrome again and finally I found it is came from a Gesture Add-on(crxMouse Gestures).

Sorry for troubling.
