### ISSUE TITLE
[DOCUMENTATION] useDrag call shows wrong params in docs

### ISSUE THREAD

**Issue by itay-moav** [react-dnd/react-dnd#3135]
**Describe the bug**
I am following the docs at https://react-dnd.github.io/react-dnd/docs/tutorial.
The structure you send to useDrag in the doc is `{type:'xxxx',collect....}`
This erred in my code. I found out it should be :
**{item:{type:'xxx'},collect....}**
**Desktop (please complete the following information):**

- OS: Centos7
- Browser Chrome
- Version 
dnd-core:  12.0.1
react-dnd: 13.1.1
react-dnd-html5-backend: 12.1.1

**Comment by darthtrevino** [comment]
In the latest version the type property is at the top-level.

**Comment by darthtrevino** [comment]
For reference: https://github.com/react-dnd/react-dnd/releases/tag/v14.0.0
