### ISSUE TITLE
Invariant Violation: Expected drag drop context find when deploy to server in minimal CodeSandbox

### ISSUE THREAD

**Issue by Pet3ris** [react-dnd/react-dnd#3149]
**Describe the bug**
I'm running the following code in a sandbox

```jsx
import { useDrag, useDrop, DndProvider } from "react-dnd";
import { HTML5Backend } from "react-dnd-html5-backend";

export default function App() {
  var matchDrag = useDrag({
    type: "FILE"
  });
  var matchDrop = useDrop({
    accept: "FILE",
    drop: function (item, monitor) {
      console.log("dropped");
    }
  });

  return (
    <div className="App">
      <h1>Hello CodeSandbox</h1>
      <DndProvider backend={HTML5Backend}>
        <div ref={matchDrag[1]}>Drag</div>
      </DndProvider>
      <DndProvider backend={HTML5Backend}>
        <div ref={matchDrop[1]}>Drop</div>
      </DndProvider>
      <h2>Start editing to see some magic happen!</h2>
    </div>
  );
}

```

When I run it, it triggers this issue: `Uncaught Invariant Violation: Expected drag drop context`.

**Reproduction**

[Live Reproduction](https://codesandbox.io/s/long-rgb-c4i69?file=/src/App.js)

**Expected behavior**
It should allow the drag item to be dropped into the drop div.

**Screenshots**

![image](https://user-images.githubusercontent.com/224585/111628010-a1ff7280-87e7-11eb-9f2f-838f6d934a58.png)

**Desktop (please complete the following information):**

- OSX
- firefox

![image](https://user-images.githubusercontent.com/224585/111628179-d5420180-87e7-11eb-8f3f-f4826e75311d.png)

**Comment by Pet3ris** [comment]
Found it!

`DndProvider` has to be external of the component in which `useDrag` / `useDrop` hooks are used. It should be factored out of the `App` component like so:

```jsx
<DndProvider backend={HTML5Backend}>
  <App />
</DndProvider>
```

**Comment by kireet3213** [comment]
If you have recently updated react or any other packages, sometimes there is a version mismatches in lock file. Its best to regenerate lock file(watch out for peer dependencies) and see if that fixes the issue.
