### ISSUE TITLE
DragSourceOptions type is not aligned with the docs?

### ISSUE THREAD

**Issue by KatFishSnake** [react-dnd/react-dnd#3158]
**Describe the bug**

useDrag DragSourceOptions type is not aligned with the docs

Docs on useDrag mention `options:` "specifying a custom `arePropsEqual(props, otherProps)` function"

But the actual type contains only `dropEffect`
https://github.com/react-dnd/react-dnd/blob/80733610ef7fb6104112697686cc7e4bd857105b/packages/react-dnd/src/hooks/types.ts#L40
https://github.com/react-dnd/react-dnd/blob/80733610ef7fb6104112697686cc7e4bd857105b/packages/react-dnd/src/types/options.ts#L1-L8

**Reproduction**
[codepen](https://codesandbox.io/s/trusting-snow-gdk27?file=/src/Example.tsx)

1. have useDrag
2. populate it with options dict
3. add arePropsEqual
4. see that typescript complains about the type

**Expected behavior**
Please either update the docs or populate the type with valid keys

**Screenshots**
<img width="602" alt="Screen Shot 2021-03-24 at 12 51 47 PM" src="https://user-images.githubusercontent.com/12003520/112374805-c6ec5d80-8c9f-11eb-92ed-083d669eb9c6.png">
<img width="564" alt="Screen Shot 2021-03-24 at 12 51 55 PM" src="https://user-images.githubusercontent.com/12003520/112374808-c81d8a80-8c9f-11eb-8a0e-966d6a971242.png">

**Desktop (please complete the following information):**

- OS: Mac
- Browser Chrome latest

Tried to fix it myself, but have no branch permisssions

cc @darthtrevino sorry a typescript types guy here, I would be happy to contribute if you can give me permissions, we are using react-dnd extensively in our codebase

**Comment by darthtrevino** [comment]
Sure, you can write PRs now. This looks like a documentation issue. What you probably want is to use index in the deps array (it acts like useMemo).

e.g. `useDrag(() => {...spec}, [id, index])`

**Comment by darthtrevino** [comment]
Smashed a change in main

**Comment by KatFishSnake** [comment]
Thanks @darthtrevino lemme craft a PR
