### ISSUE TITLE
Combination of react-dnd and html drag&drop api not work

### ISSUE THREAD

**Issue by xchunzhao** [react-dnd/react-dnd#3163]
**Describe the bug**
When combination of react-dnd and html drag&drop api, the drop&drag event defined in drop target which use html drag&drop api cannot be called

**Reproduction**

[Live Reproduction](https://codesandbox.io/s/exciting-sunset-mm52l?file=/src/index.js)

1. Drag the element  text `Drag` to `Drop` container

**Expected behavior**
the drop&drag event defined in drop target which use html drag&drop api work normally

**Desktop (please complete the following information):**

- OS: [Mac]
- Browser chrome]
- Version [14]

**Comment by vdesdoigts** [comment]
Hello @xchunzhao, Did you find a solution? Thanks
