### ISSUE TITLE
Error in documentation (react hooks)

### ISSUE THREAD

**Issue by Avivhdr** [react-dnd/react-dnd#3197]
Missing closing tag:
https://react-dnd.github.io/react-dnd/docs/api/hooks-overview

![image](https://user-images.githubusercontent.com/23265867/117550350-2fb94a80-b040-11eb-83a3-a85e1079a144.png)

**Comment by joshpetit** [comment]
Whenever you find a mistake in any open source project always feel free to send a PR 😄. I went ahead and did it.

**Comment by Avivhdr** [comment]
Thanks :)
Didn't know it was possible 🤷‍♂️

**Comment by Avivhdr** [comment]
👇🏼
[PR 3269](https://github.com/react-dnd/react-dnd/pull/3269)
