### ISSUE TITLE
[Hooks API] Spec as function causes stale closure for drop function

### ISSUE THREAD

**Issue by valtism** [react-dnd/react-dnd#3223]
**Describe the bug**
When specifying the spec in useDrop, using a function vs. using a plain object function differently. If any of the functions within the spec are capturing state from outside their function scope, they can have stale state if the spec is defined using a function.

**Reproduction**

[Live Reproduction](https://codesandbox.io/s/dazzling-chatterjee-t5hb6?file=/src/App.js)

1. Open the console
2. Drag the drag me box over the **function** spec box. Take note of the hover state.
3. Drop the box and see in the console that the hoverState that the `drop()` function in the spec sees is the old hover state of "None"
4. Drag the drag me box over the **object** spec box. Take note of the hover state.
5. Drop the box and this time see in the console that the correct hoverState is logged.

**Expected behavior**
I would expect that the the behaviours be consistent. I understand that there may be tradeoffs here, but if that is the case, I would expect the docs to cover the difference because it's quite a gotcha.

**Desktop (please complete the following information):**

- OS: macOS
- Browser: Safari
- Version: 14.0.2

**Comment by domarmstrong** [comment]
You need to add the hoverState as a dependency:
```javascript
  const [{ isOver }, drop] = useDrop(() => ({
    accept: "box",
    hover: (item, monitor) => {
      if (!ref.current) {
        return;
      }
      const clientRect = ref.current.getBoundingClientRect();
      const clientOffset = monitor.getClientOffset();
      const hoverState = getHoverState(clientRect, clientOffset);
      setHoverState(hoverState);
    },
    drop: () => {
      console.log(hoverState);
    },
    collect: (monitor) => ({
      isOver: monitor.isOver()
    })
  }), [hoverState]); // <---
```

**Comment by valtism** [comment]
Ah, that's it! I think I just never really noticed the **deps** property in the documentation. Thanks for clearing this up 😊

**Comment by anakreon** [comment]
I've just spent about two hours trying to figure this out. Thanks for the good question @valtism.
