### ISSUE TITLE
Invariant Violation: Expected targetIds to be registered

### ISSUE THREAD

**Issue by valtism** [react-dnd/react-dnd#3224]
**Describe the bug**
When using create-react-app, every time a hot reload occurs an invariant exception is thrown.

**Reproduction**

[Live Reproduction](https://codesandbox.io/s/dazzling-chatterjee-t5hb6?file=/src/App.js)

1. Change the colour of a drag or drop box
2. Try to drag
3. Error occurs

**Expected behavior**
No error thrown, somehow handle hot-reloading properly.

**Desktop (please complete the following information):**

- OS: macOS 11.3
- Browser Safari 14.1
- Version 14.0.2

**Comment by valtism** [comment]
Related discussion (marked as stale) https://github.com/react-dnd/react-dnd/issues/763

**Comment by dreamyguy** [comment]
Just wanted to mention that I get this error with a stripped-down example from DnD itself, on a NextJS app. https://react-dnd.github.io/react-dnd/examples/sortable/simple

**Comment by hlz** [comment]
I'm also having this issue with a fairly simple Next.js app. Dragging after a hot reload throws the error.

**Comment by valtism** [comment]
This seems to be fixed in v14.0.4 🎉
