### ISSUE TITLE
Can I use two DropTargets simualteneously?

### ISSUE THREAD

**Issue by deser** [react-dnd/react-dnd#330]
``` js
@DropTarget(DndTypes.AVATAR_ITEM, avatarSource, (connect, monitor) => ({
    connectDropTargetAvatar: connect.dropTarget(),
    isOverCurrentAvatar: monitor.isOver({ shallow: true })
}))
@DropTarget(DndTypes.EDITOR_ITEM, editorSource, (connect, monitor) => ({
    connectDropTargetEditorItem: connect.dropTarget(),
    isOverCurrentEditorItem: monitor.isOver({ shallow: true })
}))
export default class SomeClass extends React.Component {
   render() {
         return connectDropTargetEditorItem(connectDropTargetAvatar(<div></div>));
    }
}
```

It worked in react-dnd of static times but it now doesn't work. To be more presice monitor.isOver works unaccepable to my mind.

``` js
canDrop(props, monitor) {
       // IF I DRAG EDITOR_ITEM IT ALWAYS RETURNS FALSE
        if(!monitor.isOver({ shallow: true })) {
            return false;
        }
}
```

**Comment by gaearon** [comment]
I don't think we support two `connect*` calls of the same type on the same DOM node. This is where the abstraction leaks unfortunately. (Is it a bug? Maybe.)

However in this case I'd suggest you to register a single target for multiple types.

```js
@DropTarget([DndTypes.AVATAR_ITEM, DndTypes.EDITOR_ITEM], avatarSource, (connect, monitor) => ({
    connectTarget: connect.dropTarget(),
    isOver: monitor.isOver()
}))
```

Then inside your target you can switch on `monitor.getItemType()` to specify different behavior.

**Comment by gaearon** [comment]
Whoops, didn't mean to close. I agree it's a valid issue, even though the workaround is easy.

**Comment by FoxxMD** [comment]
It might be worth changing the wording of the section **How do I combine several drag sources and drop targets in a single component?** in the FAQ. Even though the example only shows one `DragSource` and one `DropTarget` the question implies one could stack an arbitrary number of each.

**Comment by agilgur5** [comment]
Just found this issue after looking at the exact same section in the FAQ and wondering the same thing. This workaround should really be documented in the FAQ
