### ISSUE TITLE
Using react-dnd as part of a component for a UI library

### ISSUE THREAD

**Issue by robaguilera** [react-dnd/react-dnd#3303]
**Describe the bug**
Trying to use the react-dnd library as part of a UI library and I get the error `Expected drag and drop context` when attempting to consume that component in a host application.

**Reproduction**
A little tough to reproduce this publicly as this very well might be an issue with our UI library but I created a component that more or less functions like so:
```
export function DraggableTable() {
  const [{ canDrop, isOver }, drop] = useDrop(() => ({}));
  const [collected, drag, dragPreview] = useDrag(() => ({}));
  return (<table>// all the appropriate code</table>);
}
```
It is then consumed like so:
```
// index.js
<DndProvider backend={HTML5Backend}>
   <App />
</DndProvider>
// app.js
import {DraggableTable} from "my-react-ui-library"
<DraggableTable />
```

**Expected behavior**
Since my host app is wrapping itself with the DndProvider the context should be considered as provided.

**Additional context**
If I move the `DraggableTable` to my host app everything works fine. It's only when trying to consume it as a UI component from my company library that it fails with the `Expected drag and drop context`. If it helps I'm using rollup to build the UI library.

**Comment by onuralpbicer** [comment]
You need to have react-dnd as a peer dependency of your library instead of a dependency

**Comment by zzg-forward** [comment]
you should install react-dnd and react-dnd-html5-backend in your `my-react-ui-library`, and then hava react-dnd and react-dnd-html5-backend as `peerDependencies` in your library's package.json.

**Comment by robaguilera** [comment]
Jeez, sorry should have closed this a long time ago. I ended up doing exactly what zzg-forward suggested and it worked out. Thanks all for the help!

**Comment by azgorov** [comment]
Sorry to open this again but I have similar problem with next app + 2 ui lib packages. Moving react-dnd between dependencies and peerDependencies does not seem to fix the issue.
