### ISSUE TITLE
Docs are outdated, how to run the examples?

### ISSUE THREAD

**Issue by marktoman** [react-dnd/react-dnd#3308]
**Describe the bug**
[The Examples page](https://react-dnd.github.io/react-dnd/examples), Run Locally, does not work.

**Reproduction**
```
yarn install
yarn build
yarn start
```
This does not work in the root or the `examples-hooks` directory. 

Other scripts don't seem to host anything at http://localhost:8000 either.

**Comment by darthtrevino** [comment]
What version of yarn do you have locally? This should work at the root

**Comment by darthtrevino** [comment]
Oh, derp, it's `build:` and `start:` - with yarn 2, tasks with `:` in them are available from any directory in the monorepo
