### ISSUE TITLE
Integrating with react-data-table-component

### ISSUE THREAD

**Issue by sergecheban** [react-dnd/react-dnd#3334]
Has anyone been able to get this library to work with https://github.com/jbetancur/react-data-table-component? 

Trying to see how to make them talk to each other, but haven't found any examples or anything that would point me in the right direction. Appreciate any help!

**Comment by irehmanullah** [comment]
Have you found any solution for this?

**Comment by sergecheban** [comment]
No, don't think it's possible. I ended up using https://github.com/tannerlinsley/react-table
