### ISSUE TITLE
DnD not working on Chrome 97 / linux

### ISSUE THREAD

**Issue by vaurat** [react-dnd/react-dnd#3354]
On linux/ubuntu (gnome), our feature of reordering things in a form, does not work anymore.
Works on Firefox 95 on Linux, and Chrome 97 on Windows.

**Reproduction**
It is reproductable here :
https://codesandbox.io/s/github/react-dnd/react-dnd/tree/gh-pages/examples_hooks_js/04-sortable/simple?file=/src/index.js

1. Go to rendered panel
2. Click on 'Write README'
3. Drag down to 'Create some examples'
4. reordering is not happening.

**Expected behavior**
Reordering should happen like in Firefox 95

**Screenshots**

**Desktop (please complete the following information):**

- OS: Ubuntu 21.10 
- Gnome 40.4.0
- Browser Chrome only
- Version 97

**Comment by d-vorobyov** [comment]
macos chrome 97.0.4692.71 arm64 - works too

**Comment by vaurat** [comment]
It seems this has been fixed in Version 97.0.4692.99 (Build officiel) (64 bits)
Good news.

**Comment by ibarrick** [comment]
For those who arrive from Google, the issue re-surfaced in 102.0.5005.61 but was fixed in a later release.
