### ISSUE TITLE
Error Compile

### ISSUE THREAD

**Issue by matheuscamarques** [react-dnd/react-dnd#3367]
Compiled with problems:X

ERROR in ./src/pages/Board/Board.tsx 18:35-46

export 'DndProvider' (imported as 'DndProvider') was not found in 'react-dnd' (module has no exports)

ERROR in ./node_modules/react-icons/all.js 4:0-22

The requested module './io5' contains conflicting star exports for the names 'IoLogoAndroid', 'IoLogoAngular', 'IoLogoApple', 'IoLogoBitbucket', 'IoLogoBitcoin', 'IoLogoBuffer', 'IoLogoChrome', 'IoLogoClosedCaptioning', 'IoLogoCodepen', 'IoLogoCss3', 'IoLogoDesignernews', 'IoLogoDribbble', 'IoLogoDropbox', 'IoLogoEuro', 'IoLogoFacebook', 'IoLogoFlickr', 'IoLogoFoursquare', 'IoLogoGithub', 'IoLogoGoogle', 'IoLogoHackernews', 'IoLogoHtml5', 'IoLogoInstagram', 'IoLogoIonic', 'IoLogoIonitron', 'IoLogoJavascript', 'IoLogoLinkedin', 'IoLogoMarkdown', 'IoLogoNoSmoking', 'IoLogoNodejs', 'IoLogoNpm', 'IoLogoOctocat', 'IoLogoPinterest', 'IoLogoPlaystation', 'IoLogoPython', 'IoLogoReddit', 'IoLogoRss', 'IoLogoSass', 'IoLogoSkype', 'IoLogoSlack', 'IoLogoSnapchat', 'IoLogoSteam', 'IoLogoTumblr', 'IoLogoTux', 'IoLogoTwitch', 'IoLogoTwitter', 'IoLogoUsd', 'IoLogoVimeo', 'IoLogoVk', 'IoLogoWhatsapp', 'IoLogoWindows', 'IoLogoWordpress', 'IoLogoXbox', 'IoLogoXing', 'IoLogoYahoo', 'IoLogoYen', 'IoLogoYoutube' with the previous requested module './io'

ERROR in ./node_modules/react-dnd/lib/index.js 1:0-24

Module not found: Error: Can't resolve './types' in '/home/sanonichan/projetos/emendas/emendas-frontend/node_modules/react-dnd/lib'
Did you mean 'index.js'?
BREAKING CHANGE: The request './types' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/react-dnd/lib/index.js 2:0-23

Module not found: Error: Can't resolve './core' in '/home/sanonichan/projetos/emendas/emendas-frontend/node_modules/react-dnd/lib'
Did you mean 'index.js'?
BREAKING CHANGE: The request './core' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/react-dnd/lib/index.js 3:0-24

Module not found: Error: Can't resolve './hooks' in '/home/sanonichan/projetos/emendas/emendas-frontend/node_modules/react-dnd/lib'
Did you mean 'index.js'?
BREAKING CHANGE: The request './hooks' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

**Comment by darthtrevino** [comment]
WIP: https://github.com/react-dnd/react-dnd/pull/3369
