### ISSUE TITLE
ERR_UNSUPPORTED_DIR_IMPORT when trying to use react-dnd with Next.js app. 

### ISSUE THREAD

**Issue by tombburnell** [react-dnd/react-dnd#3368]
**Describe the bug**
When adding react-dnd to a next.js app I get error:

Error: Directory import '/.../node_modules/react-dnd/lib/types' is not supported resolving ES modules imported from .../node_modules/react-dnd/lib/index.js

error - Error [ERR_UNSUPPORTED_DIR_IMPORT]: Directory import '/.../node_modules/react-dnd/lib/types' is not supported resolving ES modules imported from /..../node_modules/react-dnd/lib/index.js

**Reproduction**
I just try to add the example code to an existing page in my next.js app.

import { useDrag } from 'react-dnd';

function MyComponent() {
    let [{isDragging}, dragRef] = [{isDragging: undefined}, undefined];

         [{isDragging}, dragRef] = useDrag({
             type: 'Irrelevant, for now',
             item: {name: 'Any custom name',},
             collect: (monitor) => ({
                 isDragging: monitor.isDragging(),
             }),
         });

    return ()
 }

I suspect this has to do with it loading on the server side when it's only required on the client but not sure how to resolve this. Is there an example of how to integrate with Next.js?

Thanks

[Live Reproduction](codesandbox.io/....)

**Expected behavior**
No error..

- OS: OSX Mojave
- Browser Chrome

**Additional context**

**Comment by darthtrevino** [comment]
WIP: https://github.com/react-dnd/react-dnd/pull/3369

**Comment by tombburnell** [comment]
Thanks - it's working now!

**Comment by softmarshmallow** [comment]
having this issue again with `react-dnd@16.0.1` and nextjs 12, react18

**Comment by Wimmind** [comment]
@softmarshmallow did you manage to solve the problem?

**Comment by llGaetanll** [comment]
I am also currently facing this issue on `next@12.3.4`, `react@18.2.0`, and `react-dnd@16.0.1`. Any guidance would be greatly appreciated.
