### ISSUE TITLE
Will there be support soon for react 18

### ISSUE THREAD

**Issue by laclance** [react-dnd/react-dnd#3401]
Hi, I need features from react 18 but it seems it is not supported yet?

```
yarn create react-app my-app
yarn add react@rc react-dom@rc react-dnd react-dnd-html5-backend
yarn install
yarn start
```

```
Compiled with problems:X

ERROR in ./node_modules/react-dnd/dist/esm/core/DndProvider.mjs 1:0-51

Module not found: Error: Package path ./jsx-runtime.js is not exported from package 
node_modules/react (see exports field in node_modules/react/package.json)
```

**Comment by Himself65** [comment]
workaround: https://github.com/facebook/create-react-app/issues/11769#issuecomment-997152888

**Comment by Himself65** [comment]
workaround 1: add this into `webapck.config.js`

```ts
alias: {
  'react/jsx-dev-runtime.js': projectRoot('node_modules', 'react', 'jsx-dev-runtime.js'),
  'react/jsx-runtime.js': projectRoot('node_modules', 'react', 'jsx-runtime.js')
}
```

workaround 2: use [`patch-package`](https://github.com/ds300/patch-package) then edit the `./node_modules/react-dnd/dist/esm/core/DndProvider.mjs` by yourself

**Comment by laclance** [comment]
thank you

**Comment by rileyjshaw** [comment]
This issue is being tracked in https://github.com/react-dnd/react-dnd/issues/3416
