### ISSUE TITLE
Is there a way to drop a draggable item if it is near to the drop zone? 

### ISSUE THREAD

**Issue by eugeneZolotarenko** [react-dnd/react-dnd#3413]
**Is your feature request related to a problem? Please describe.**
I have multiple drop zones in my app, so I'd like to suggest to users which drop zone is the nearest to the cursor and allow drop draggable item without hovering drop zone.

**Describe the solution you'd like**
I don't see the ability to manually activate dropping functionality. I'd like to activate it based on the cursor position.

**Comment by hlynurstef** [comment]
You should be able to simply create a wrapping div that is slightly larger than your drop zone that acts as the drop target, then render the drop zone UI component inside.

Something like this:
```
  <div
    ref={drop}
    style={{
      width: "100%",
      height: "10px",
      display: "flex",
      alignItems: "center",
      opacity: isHovering ? 1 : 0,
    }}
  >
    // Actual drop zone UI rendered here:
    <div style={{ width: "100%", height: "2px", backgroundColor: "blue" }} />
  </div>
```

**Comment by eugeneZolotarenko** [comment]
> You should be able to simply create a wrapping div that is slightly larger than your drop zone that acts as the drop target, then render the drop zone UI component inside.
> 
> Something like this:
> 
> ```
>   <div
>     ref={drop}
>     style={{
>       width: "100%",
>       height: "10px",
>       display: "flex",
>       alignItems: "center",
>       opacity: isHovering ? 1 : 0,
>     }}
>   >
>     // Actual drop zone UI rendered here:
>     <div style={{ width: "100%", height: "2px", backgroundColor: "blue" }} />
>   </div>
> ```

Make sense, thank you!
