### ISSUE TITLE
Cannot import DndProvider after upgradation of react to 18.0.0

### ISSUE THREAD

**Issue by duyhcmut** [react-dnd/react-dnd#3416]
**Describe the bug**
After upgradation react to 18.0.0, it is impossible to launch react application due to error message:
ERROR in ./node_modules/react-dnd/dist/esm/core/DndProvider.mjs 1:0-51
Module not found: Error: Package path ./jsx-runtime.js is not exported from package ./node_modules/react

**Reproduction**
1. prepare a codebase with simple importation of DndProvider (e.g. import { DndProvider } from "react-dnd").
2. npm install react@18.0.0 react-dom@18.0.0 react-is@18.0.0
3. see error message

**Expected behavior**
The application should work properly as it is with react 17.0.2 or earlier.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome
- Version: 99.0.4844.82

**Additional context**

**Comment by Azerothian** [comment]
It seems that with the latest release they have dropped the js extension on the jsx-runtime import

webpack config (temp) fix 
```
    alias: {
      "react/jsx-runtime.js": "react/jsx-runtime",
      "react/jsx-dev-runtime.js": "react/jsx-dev-runtime",
    },
```

**Comment by duyhcmut** [comment]
@Azerothian Thanks. It works like a charm.

**Comment by macrozone** [comment]
anyone knows a fix for nextjs?

**Comment by uipoet** [comment]
Temporary workaround for `vitejs`:

```typescript
export default defineConfig({
  resolve: {
    alias: {
      "react/jsx-dev-runtime.js": resolve(
        __dirname,
        "node_modules/react/jsx-dev-runtime.js"
      ),
      "react/jsx-runtime.js": resolve(
        __dirname,
        "node_modules/react/jsx-runtime.js"
      ),
    },
  },
});
```

**Comment by paulkuhle** [comment]
Adding this to my `next.config.js` seems to have fixed it (Next 12.0.3):

```js
const withTM = require('next-transpile-modules')(['react-dnd'])
module.exports = withTM({
  reactStrictMode: true,
  // ...
})
```

**Comment by fahadashiq12** [comment]
Facing the same issue, it has been fixed or not?

**Comment by mikaelrss** [comment]
For anyone using create react app #3433
