### ISSUE TITLE
The value of isOver is not as expected

### ISSUE THREAD

**Issue by tobemaster56** [react-dnd/react-dnd#3489]
**Describe the bug**

I want to implement an onEnter onLeave effect for a Drop Target based on the change of isOver.

In most cases, when I drag elements into and out of the Drop Target multiple times, it is normal, entering the Drop Target, isOver becomes true, leaving the Drop Target, isOver becomes false, but sometimes, entering the Drop Target, isOver changes multiple times in a very short period of time.
true->false->true.

**Reproduction**

[Live Reproduction](https://codesandbox.io/s/hidden-monad-s0pct2)

1.  drag elements into and out of the Drop Target multiple times，watch out the console

**Expected behavior**

Drag an element into the Drop Target, isOver becomes true and the value of isOver does not change unless you leave the Drop Target.

**Screenshots**

**Desktop (please complete the following information):**

- OS: [macos Monterey12.5]
- Browser [edge ]

<img width="436" alt="image" src="https://user-images.githubusercontent.com/8998761/185051157-6a78a920-91e0-4d4a-a5e8-91841b6907ec.png">

**Additional context**

**Comment by D-kylin** [comment]
I try to drag elements slowly into the Drop Target, console is output one message "isOver true".
If I drag elements fastly into Drop Target, console is output three message "isOver true"、"isOver false"、"isOver true" in sequence.
Is that the issue in browser ?

**Comment by tobemaster56** [comment]
> I try to drag elements slowly into the Drop Target, console is output one message "isOver true". If I drag elements fastly into Drop Target, console is output three message "isOver true"、"isOver false"、"isOver true" in sequence. Is that the issue in browser ?

yes, repeat many times and it will appear, there is a certain chance

**Comment by D-kylin** [comment]
Actually, It is different define of the "hover" event between react-dnd and html native drag API.
In react-dnd, the monitor.isOver is changing by dragenter and dragout, maybe dragover.
In html native drag API, hover status is changing by dragover and this event has 100 millisecond interval.
This is why different result slow into the target and fastly into the target.

**Comment by D-kylin** [comment]
In my opinion, the monitor.isOver is work well in most times. How is your sence need precise value of monitor.isOver ?

**Comment by tobemaster56** [comment]
> In my opinion, the monitor.isOver is work well in most times. How is your sence need precise value of monitor.isOver ?

I want to implement an onEnter and onLeave callback  of a Drop Target,  my idea is based on the change of isOver，Is there a better way to do this?

**Comment by D-kylin** [comment]
The drop.collect attribute could set "isOverCurrent: monitor.isOver({ shallow: true })" and then watching isOverCurrent status?
If that can resolve your problem?

**Comment by tobemaster56** [comment]
> The drop.collect attribute could set "isOverCurrent: monitor.isOver({ shallow: true })" and then watching isOverCurrent status? If that can resolve your problem?

isOverCurrent behaves the same as isOver

**Comment by tobemaster56** [comment]
@D-kylin 
thanks for your reply，
at last，i found a way to solve my problem，While isOver may change multiple times and onEnter may be executed multiple times, I designed onEnter to change the temporary data . The data in the store is updated only after the drag and drop is finished.

so i will close this issue

**Comment by andylwelch** [comment]
This is still a real issue with the monitor.isOver(). The changing value from `true -> false -> true` in rapid succession causes flickering in the UI. This should be handled by react-dnd

For anyone else that encounters this, forget using the collect function with monitor.isOver(). Add your own `onDragEnter` and `onDragLeave` listeners which set an `isOver` state. For example:

```
  const [, drop] = useDrop({ ... });
  const ref = useRef();
  drop(ref);
  const [isOver, setOver] = useState(false);
  
  return (
    <div
      ref={ref}
      onDragEnter={() => setOver(true)}
      onDragLeave={() => setOver(false)}
    >
    ...
    </div>
  );
  ```

**Comment by bigjimhere** [comment]
Here is a fix- you can used isOverDebounced instead:

`    const [isOverDebounced, setIsOverDebounced] = useState(false)
    const [lastOver, setLastOver] = useState(0)
    const [lastLeave, setLastLeave] = useState(0)

    useEffect(() => {
        let inTimer: NodeJS.Timeout | undefined
        let outTimer: NodeJS.Timeout | undefined
        if (!isOver) {
            if (lastOver && Date.now() - lastOver < 100) {
                inTimer = setTimeout(() => {
                    clearTimeout(outTimer)
                    setIsOverDebounced(isOver)
                    setLastLeave(Date.now())
                }, 100)
            } else {
                clearTimeout(outTimer)
                setIsOverDebounced(isOver)
                setLastLeave(Date.now())
            }
        } else {
            if (!(lastLeave && Date.now() - lastLeave < 100)) {
                clearTimeout(inTimer)
                setIsOverDebounced(isOver)
                setLastOver(Date.now())
            } else {
                outTimer = setTimeout(() => {
                    if (isOver) {
                        clearTimeout(inTimer)
                        setIsOverDebounced(isOver)
                        setLastLeave(Date.now())
                    }
                }, 100)
            }
        }
        return () => {
            clearTimeout(inTimer)
            clearTimeout(outTimer)
        }
    }, [isOver])`
