### ISSUE TITLE
Getting ERR_REQUIRE_ESM error when trying to implement React-DND inside a Remix app

### ISSUE THREAD

**Issue by fahadahmed** [react-dnd/react-dnd#3518]
**Describe the bug**
Getting an error (ERR_REQUIRE_ESM) when trying to implement React-DND inside a remix app.

**Reproduction**

[Live Reproduction](https://codesandbox.io/s/lucid-surf-7huedz?file=/app/routes/index.jsx)

**Expected behavior**
React DND should work inside a remix app without any issues. There is a codesandbox which implements it however the same steps cannot be replicated
[Working Example](https://codesandbox.io/s/ezel1d?file=/package.json)

**Screenshots**
<img width="1727" alt="Screen Shot 2022-11-18 at 7 42 30 am" src="https://user-images.githubusercontent.com/1190340/202568894-e4278c0e-4156-4896-a493-783c17ccbcb9.png">

**Desktop (please complete the following information):**
- NA

**Comment by alex-udisc** [comment]
@fahadahmed What changed? I'm getting build errors similar to the error you described.

**Comment by fahadahmed** [comment]
So I had to change the way I was including the ReactDND component. In remix we can make the component be rendered client only as well using the `remix-utils` package. So to resolve the above issue, this is what I did:

```tsx
// parent component
import { ClientOnly} from 'remix-utils';
...

function Index() {
  ...
  return(
    <ClientOnly fallback={<p>Loading ...</p>}>
      {() => (
        <Canvas
          tenancyId={location?.state?.tenancyId}
          workspaceId={location?.state?.workspaceId}
          insightId={insightId}
          data={widgets}
        />
      )}
    </ClientOnly>
}
```

Also place the `Canvas` component inside a `components` folder inside `app` and save the component as `Canvas.client.tsx`.

**Comment by flyon** [comment]
for anyone else coming here, I had the same error but not with Remix. This thread made me realise that it's only a problem on the server though. So I've put a dynamic import in a useEffect hook in my react component. The component will only become draggable after that dynamic import has resolved, but it works
