### ISSUE TITLE
Does not display the element while dragging in Safari

### ISSUE THREAD

**Issue by Roman-H91** [react-dnd/react-dnd#3538]
**Describe the bug**
When I drag an item, the selected item is not displayed. When dropped - it's fine, the item is in the needed place.
Or I have an SVG file inside a div and when I drag it, it shows the Chrome logo.

**Screenshots**
![image](https://user-images.githubusercontent.com/70602437/214638223-303d7c29-c60c-45cf-b83a-90f4a026baac.png)

**Desktop:**
- OS: macOS Monterey 12.6
- Browser: Safari 16.0
- Version: react-dnd **15.1.2** and react-dnd-html-5-backend **15.1.3**. Also tried on **16.0.1**

**Additional context**
I also added CSS styles:
```
   -webkit-touch-callout: none;
    -webkit-user-select: none;
    -khtml-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
```

**Comment by Roman-H91** [comment]
I had 2 bugs:
1) When I drag an item, the selected item is not displayed. Solution: 
Adding `transform: 'unset'` to `overlayClass`. I use 'react-modal'. But the modal would be crushed. In this case, you need to change the styles to center the modal.
2) I have an SVG file inside a div and when I drag it, it shows the Chrome logo. Solution:
Adding attribute `draggable="false"` to tag `img `.

**Comment by XiaoBieThree** [comment]
我使用了一个hacking方案，在这里
https://github.com/react-dnd/react-dnd/issues/2708
