### ISSUE TITLE
Not working in parent with modal styling { top: 50%, left: 50%, transform: translate(-50%, -50%) }

### ISSUE THREAD

**Issue by johnschatner** [react-dnd/react-dnd#3604]
**Describe the bug**
Not working in parent with modal styling { top: 50%, left: 50%, transform: translate(-50%, -50%) }. The SortableItem jumps away from the mouse cursor when starting the onDrag event.

**Reproduction**

[CodeSandbox](https://codesandbox.io/s/magical-oskar-j37djj?file=/src/App.tsx)

**Expected behavior**
The drag handle should be positioned underneath the cursor and not jump somehwere. In the above example the element seems to jump down, in my instance it jumps to the right.

**Comment by volodymyrdn** [comment]
In the example you provided you are using dnd-kit. But this is react-dnd.

**Comment by johnschatner** [comment]
This is embarrassing. Sorry!
