### ISSUE TITLE
Error: (0 , react__WEBPACK_IMPORTED_MODULE_0__.createContext) is not a function

### ISSUE THREAD

**Issue by Boby900** [react-dnd/react-dnd#3642]
**Describe the bug**
I am getting an error that `Error: (0 , react__WEBPACK_IMPORTED_MODULE_0__.createContext) is not a function`

**Reproduction**

just add this code in root layout in Next.js app router
```tsx
 <SessionProvider>
        <Navbar />
        <DndProvider backend={HTML5Backend}>
        {children}
        </DndProvider>
        </SessionProvider>
```

**Desktop (please complete the following information):**

- OS Name:                   Microsoft Windows 10 Pro
- OS Version:                10.0.19045 N/A Build 19045
- Browser:                     Chrome
- Version:                      129.0.6668.60 (Official Build) (64-bit)

**Additional context**
```json
 "dependencies": {
    "lucide-react": "^0.445.0",
    "next": "14.2.3",
    "next-auth": "^5.0.0-beta.22",
    "react": "^18",
    "react-dnd": "^16.0.1",
    "react-dnd-html5-backend": "^16.0.1",
    "react-dom": "^18"
  },
  "devDependencies": {
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "eslint": "^8",
    "eslint-config-next": "14.2.3",
    "postcss": "^8",
    "prettier": "3.3.3",
    "tailwindcss": "^3.4.1",
    "typescript": "^5"
  }
```

![Screenshot (646)](https://github.com/user-attachments/assets/456bad14-91b4-4371-9d36-da8f6b5f7564)

![Screenshot (645)](https://github.com/user-attachments/assets/97116fc1-2fa6-479f-a77b-b80d58a8c5bc)

**Comment by Boby900** [comment]
hi @elliotcw 
I have added `'use client'` directive in almost every file instead of `src/app/layout.tsx` file, but still getting this error.
https://github.com/Boby900/test-app-v0

**Comment by antho1jp** [comment]
@Boby900 create a Providers.tsx file like below:

```jsx
'use client';

import { DndProvider } from 'react-dnd';
import { HTML5Backend } from 'react-dnd-html5-backend';
import { ReactNode } from 'react';

interface ProvidersProps {
	children: ReactNode;
}

export function Providers({ children }: ProvidersProps) {
	return (
		<DndProvider backend={HTML5Backend}>
			{children}
		</DndProvider>
	);
}
```

and then include it in your layout.tsx file like:

```jsx
import './globals.css';
import { Providers } from './providers';

export const metadata = {
	title: 'Page Builder',
	description: 'A Next.js app with drag-and-drop page builder features.',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body>
				<Providers>
					{children}
				</Providers>
			</body>
		</html>
	);
}

```

**Comment by Boby900** [comment]
thanks @antho1jp  it's working now.
silly mistake, I did not think of creating another module and adding a `'use client'` directive on  that and then importing that module
