### ISSUE TITLE
cannot drag after dropping on a target that is not drop-able

### ISSUE THREAD

**Issue by bibodha** [react-dnd/react-dnd#386]
After dragging to a non-dropable area, you cannot drag the dragSource again until you click somewhere. 

![dnd-bug](https://cloud.githubusercontent.com/assets/2340572/13225765/80b4f8f2-d94b-11e5-881e-c2b5739f5924.gif)

I looked into dnd-core, wrote a test there and it passed.
I thought it was because it wasn't calling endDrag but it is. When I put a breakpoint in the end drag, it behaves like it should. Causes me to believe this is a race condition.

**Comment by gaearon** [comment]
Can’t reproduce.
Can you please check your console for errors and report your browser and OS versions?

**Comment by bibodha** [comment]
no errors on the console. I'm on Mac OS X 10.11.3 Yosemite. Chrome Version 48.0.2564.109 (64-bit)

**Comment by gaearon** [comment]
I think 10.11 is El Capitan, not Yosemite.

**Comment by gaearon** [comment]
I tested:

* Chrome 48.0.2564.97 (64-bit) on OS X 10.11 (15A284)
* Chrome 48.0.2564.116 (64-bit) on OS X 10.11 Beta (15A279b)

Both of them worked fine. Do any other examples have similar problems? Do you have any unusual configuration (multiple monitors, special input devices, etc)?

**Comment by nihaux** [comment]
Hello, experiencing the same problem here.  
My config: OS X El Capitan 10.11.4 + chrome Version 59.0.3071.115 (Build officiel) (64 bits).  
Macbook pro 13'' 2013 + Mac screen.  
Glad I found this issue, thought it was side-effect problem in my project.  
Will try to investigate further on the chess example.

**Comment by werg27** [comment]
I'm working with nihaux, and i cannot reproduce the same problem with this configuration : 
OS X El Capitan 10.11.4 + chrome Version 59.0.3071.115 (Build officiel) (64 bits)
macbook pro 13" 2015,  3,1 GHz Intel Core i7 (Intel Iris Graphics 6100 1536 Mo) + Dell screen.
Strange ...

**Comment by nihaux** [comment]
So nobody else was able to reproduce. I upgraded to macOS Sierra 10.12.5 and cannot reproduce since...
