### ISSUE TITLE
How to manage position:relative drag source

### ISSUE THREAD

**Issue by koliyo** [react-dnd/react-dnd#404]
I'm using a ListGroupItem from react-bootstrap as a drag source, but it can not be dragged because of the `position:relative` style. If I remove this styling it is ok to drag, but only if I change it _before_ the drag start.

I tried to change the style when `isDragging` prop is true, but this is too late, the drag is already denied (dnd thinks the drag is active though), so I need to change the style before this, but I dont want it changed permanently.

Any suggestions on how to handle this?

**Comment by eeh** [comment]
+1

Using material-ui trying to let the user drag around list items, drag preview is way off.

**Comment by AndrewTHuang** [comment]
Can you change the style on `beginDrag`, then change it back on `endDrag`?

**Comment by kolis** [comment]
Nope same problem with `beginDrag/endDrag` I'm afraid.

**Comment by eeh** [comment]
Didn't work for me either. Currently looking into creating some special dragPreview, which I would assume can help me here.

**Comment by globexdesigns** [comment]
Can you wrap the ListGroupItem in another container element which is used for dragging instead?

**Comment by yinchonging** [comment]
@eeh  +1

**Comment by yinchonging** [comment]
@eeh drag preview is work

          <div style={{width:200,height:200,background:'red',paddingTop:1}}>
            <div style={{marginLeft:10,marginTop:10}}>test</div>
          </div>
