### ISSUE TITLE
Dragging Preview of Component inside Cell in Safari

### ISSUE THREAD

**Issue by BugsBunny338** [react-dnd/react-dnd#417]
Not sure whether this is an issue of [`fixed-data-table`](https://facebook.github.io/fixed-data-table/), `react-dnd` or Safari, but when I insert a draggable ([`export default DragSource(type, spec, collect)(MyComponent);`](http://gaearon.github.io/react-dnd/docs-drag-source.html)) component inside a `Cell` (inside `Column` inside `Table`) and start dragging, there is no preview in Safari 9 on OS X 10.11. Dropping on defined dropzones work, but no thumbnail midflight :-(

If I use the same [`DragSource`](http://gaearon.github.io/react-dnd/docs-drag-source.html) component outside `fixed-data-table`, dragging preview works normally.

Any ideas?

**Comment by globexdesigns** [comment]
Can you provide a code sample to reproduce this?

**Comment by BugsBunny338** [comment]
Here it is: http://output.jsbin.com/qawiye. Make sure you use **Safari**, try dragging the first item, then scroll randomly, drag different one, scroll randomly, drag yet another one. Sometimes you get no preview, sometimes you get preview of another item (not the one you're dragging), sometimes you get preview _cut in half_, etc.

**Comment by kiya69** [comment]
I recently came across this issue too - when the draggable is not an image, the whole div won't show as dragPreview (aka ghost image) on dragging. After some digging, I think it's because the **transform: translate** CSS attributes on the draggable's parent elements. After I clear all those transform: translate attributes, the ghost images seem to be showing fine, tho all the layout is messed up.
Hope there will be a better solution here than me re-writing the site's layout.

**Comment by ggentzke** [comment]
The example @BugsBunny338 gave is still broken. Is it going to be addressed?

**Comment by DavidVorac** [comment]
> I recently came across this issue too - when the draggable is not an image, the whole div won't show as dragPreview (aka ghost image) on dragging. After some digging, I think it's because the **transform: translate** CSS attributes on the draggable's parent elements. After I clear all those transform: translate attributes, the ghost images seem to be showing fine, tho all the layout is messed up.
> Hope there will be a better solution here than me re-writing the site's layout.

Can confirm that drag preview is still not working if parent element has **transform: translate** CSS attribute, but only on Safari. Chrome, Opera and Firefox is working fine.
