### ISSUE TITLE
DragPreview not working on MS Edge

### ISSUE THREAD

**Issue by yonaichin** [react-dnd/react-dnd#420]
Hi

DragPreview [example](https://gaearon.github.io/react-dnd/examples-customize-handles-and-previews.html) seems not working on MS Edge.

Currently on a project needs to build custom text preview while dragging. 

Is there any workaround to achieve it on MS Edge?

Thanks

**Comment by rfogar2** [comment]
I was having trouble with this in my app and the only workaround I could find was to make the entire preview the drag source for IE.

`export function usingIE (windowOverride = window) {
  const ua = windowOverride.navigator.userAgent

  const edge = ua.indexOf('Edge/')
  const ie11 = ua.indexOf('Trident/')
  const ie10 = ua.indexOf('MSIE ')

  return edge > -1 || ie11 > -1 || ie10 > -1
}`

**Comment by thienanle** [comment]
+1

**Comment by bluespore** [comment]
Any update on this?

**Comment by derrikcurran** [comment]
Take a look at http://gaearon.github.io/react-dnd/docs-drag-source-connector.html at the "captureDraggingState" option.

Try something like this:
```javascript
class Whatever extends Component {
    componentDidMount() {
        this.props.connectDragPreview(getEmptyImage(), {
            // IE fallback: specify that we'd rather screenshot the node
            // when it already knows it's being dragged so we can hide it with CSS.
            captureDraggingState: true,
        });
    }

    componentWillUpdate(nextProps) {
        this.aboutToDrag = nextProps.isDragging && !this.props.isDragging;
    }

    render() {
        const isUsingEdgeOrIE = ???; // @rfogar2's method is a good way to figure this out
        const style = this.aboutToDrag && isUsingEdgeOrIE && { display: 'none' };
        return <div style={style}>Drag me</div>;
    }
}
```
As a side note, the function @rfogar2 posted is good but probably shouldn't be called "usingIE". Treating Edge and IE the same is a bad idea because they're totally different browsers. IE uses the (terrible) Trident layout engine and Edge uses EdgeHTML. EdgeHTML _is_ a fork of Trident, but with all legacy IE code removed and the majority of its source code rewritten. It complies with modern standards quite well and mostly behaves the same as Gecko and Blink. Of course, this particular case is a poor example of that.

**Comment by edgesoft** [comment]
Still getting this issue even when using connectDragPreview.

**Comment by konradcieslukowski** [comment]
Hi, there is easy workaround, if you mean to change the draggable node and treat a parent like DragPreview. 

```
const DndContainer = ({connectDragSource}) => {
  return connectDragSource(
    <div className="my-drag-preview" onMouseDown={e => e.preventDefault()}>
      <div className="my-drag-source" onMouseDown={e => e.stopPropagation()}>
        Drag Me Here!
      </div>
    </div>
  )
}
```
It's all about handling mouseDown properly.

**Comment by edgesoft** [comment]
This does not work. I'm using a custom DragLayer and Edge simple does not handle this. Any workaround. Spent at least 16 hours on this.

**Comment by cmsmachado** [comment]
Having the same issue.  Using connectDragPreview with getEmptyImage.
Is there any news on this?

**Comment by Justin-ZS** [comment]
Here is my solution, if you only want to hide the native preview image. (same as getEmptyImage)
```js
// previous code (only work in chrome)
@DragSource(DragType, dragSpec, cnt => ({
  cntDragSource: cnt.dragSource(),
  cntDragPreview: cnt.dragPreview(),
}))
class Whatever extends Component {
    componentDidMount() {
      this.props.cntDragPreview(getEmptyImage());
    }
    render() {
        const { cntDragSource } = this.props;
        return cntDragSource(<div>Drag me</div>);
    }
}

// solution
@DragSource(DragType, dragSpec, cnt => ({
  cntDragSource: cnt.dragSource(),
  cntDragPreview: cnt.dragPreview(),
}))
class Whatever extends Component {
    componentDidMount() {
      this.props.cntDragPreview(getEmptyImage());
    }
    render() {
        const { cntDragSource } = this.props;
        return (<div style={{ position: "relative" }} >}>
            Drag me
            {connectDragSource(<div className="drag-trigger" />)}
          </div>);
    }
}
```
add css to make `.drag-tigger` fill the container node.
```css
/* The `.drag-tigger` node has't any UI style, just a transparent mask. so the preview image is transparent too */
.drag-trigger {
  position: absolute;
  pointer-events: all;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
}
```
Hope this help.:smile:

**Comment by grinbuck** [comment]
> Here is my solution, if you only want to hide the native preview image. (same as getEmptyImage)
> 
> ```js
> // previous code (only work in chrome)
> @DragSource(DragType, dragSpec, cnt => ({
>   cntDragSource: cnt.dragSource(),
>   cntDragPreview: cnt.dragPreview(),
> }))
> class Whatever extends Component {
>     componentDidMount() {
>       this.props.cntDragPreview(getEmptyImage());
>     }
>     render() {
>         const { cntDragSource } = this.props;
>         return cntDragSource(<div>Drag me</div>);
>     }
> }
> 
> // solution
> @DragSource(DragType, dragSpec, cnt => ({
>   cntDragSource: cnt.dragSource(),
>   cntDragPreview: cnt.dragPreview(),
> }))
> class Whatever extends Component {
>     componentDidMount() {
>       this.props.cntDragPreview(getEmptyImage());
>     }
>     render() {
>         const { cntDragSource } = this.props;
>         return (<div style={{ position: "relative" }} >}>
>             Drag me
>             {connectDragSource(<div className="drag-trigger" />)}
>           </div>);
>     }
> }
> ```
> 
> add css to make `.drag-tigger` fill the container node.
> 
> ```css
> /* The `.drag-tigger` node has't any UI style, just a transparent mask. so the preview image is transparent too */
> .drag-trigger {
>   position: absolute;
>   pointer-events: all;
>   top: 0;
>   left: 0;
>   right: 0;
>   bottom: 0;
> }
> ```
> 
> Hope this help.😄

This is the only solution that has worked for me consistently on Edge so far.
