### ISSUE TITLE
Reposition mouse cursor to be over top left corner of component

### ISSUE THREAD

**Issue by brianluong** [react-dnd/react-dnd#425]
I'm pretty new to JS / web app building, so please bear with me:

OnDrag, I want to reposition the dragged DOM element's top left corner to be under the drag cursor, no matter where I start the drag from on that DOM element. For example, if I start a drag an element's middle, the cursor will be over the  DOM element's upper left corner, instead of the initial place where the drag started.

How can I achieve this? I tried using absolute position on the beginDrag event in the Drag Source spec, but that seems to end the drag event. Should I use Drag Layer? 

Thanks

**Comment by dusterbed** [comment]
I would also like this feature! Any word on progress? I see this has been triaged...

**Comment by pyssion** [comment]
Found `getClientOffset` from #142 and it should suffice.

**Comment by szeryf** [comment]
I'd like to center the component under the pointer while dragging, but it's essentially the same feature. Any progress?

**Comment by sorawee** [comment]
No need to use drag layer. There's an option in http://react-dnd.github.io/react-dnd/docs/api/drag-source-connector to do this. In particular, pass in an option for `dragPreview` with `offsetX` and `offsetY` being some offset, like `1`.

For example, make changes as follows:

```diff
    return {
      connectDragSource: connect.dragSource(),
      isDragging: monitor.isDragging(),
+     connectDragPreview: connect.dragPreview(),
    };
  }
```

and

```diff
*** 1,7 ****
  class Foo extends Component {
    render() {
!     const {connectDragSource} = this.props;
!     return connectDragSource(<Bar>);
    }
  }
  
--- 1,10 ----
  class Foo extends Component {
    render() {
!     const {connectDragSource, connectDragPreview} = this.props;
!     return connectDragPreview(
!       connectDragSource(<Bar>),
!       {offsetX: 1, offsetY: 1}
!     );
    }
  }
  

```

**Comment by eden-lane** [comment]
Is it possible to do with new API on hooks?

**Comment by anthonysgro** [comment]
Also interested in knowing if this solution can be used with the hooks api

**Comment by 7mioda** [comment]
This is already closed. But is there news how to implement this 🤔
