### ISSUE TITLE
DropTarget that accepts all types

### ISSUE THREAD

**Issue by simshaun** [react-dnd/react-dnd#432]
I'm trying to globally implement window scrolling when any DragSource is dragged close to the window's edge.

Going off of http://gaearon.github.io/react-dnd/examples-sortable-stress.html, I'm making my entire App a DropTarget whose sole purpose is to handle scrolling via the `hover` specification method.

What I can't figure out is how to have that DropTarget accept _any_ type. I don't want to have to explicitly list/register every possible type at the App root. Is that currently possible? or am I going about it all wrong?

**Comment by froatsnook** [comment]
I'm not an expert, but as far as I know, this isn't possible.  Even if you get the `DragDropManager`, you'll only find types in `manager.registry.types` for rendered components (the `DragSource` type can be a function, and this function isn't called until it's needed).  One thing you could do would be to use your own `DragSource` that keeps track of types.

```diff
// YourComponents.js
- import { DragSource } from "react-dnd";
+ import { DragSource } from "./DragSource";
```

```javascript
// DragSource.js
import { DragSource as ReactDnDDragSource } from "react-dnd";
var types = new Set();
export function DragSource(type, ...args) {
  types.add(type); // hopefully you're not using (props) => type
  return ReactDnDDragSource(type, ...args);
}

export function allTypes() {
  return Array.from(types);
}
```

**Comment by simshaun** [comment]
I'm wondering if it would be better to modify `DropTarget` to accept a wildcard (`true`, `*`, something like that) for acceptable types.

**Comment by froatsnook** [comment]
Yeah I think that would be the right solution!  `true` would make sense and not break anyone's code who happened to use "*" as their source/target ID :).

**Comment by froatsnook** [comment]
Hey @simshaun,

I implemented this in dnd-core and it seems to be working.  Before merging it in I need to update the tests some more, and then work on react-dnd.

@gaearon: what do you think of this change?  (`true` acting as wildcard for DropTargets)

**Comment by simshaun** [comment]
Cool!

**Comment by gaearon** [comment]
Yep, `true` sounds good to me. We’ll need to document this if we add this.

**Comment by froatsnook** [comment]
Cool, I'll finish this up then.

**Comment by crispy-invention** [comment]
@simshaun since we have canDrop() would you please see if this issue is still valid?

**Comment by simshaun** [comment]
Sorry, it's been so long I don't remember what codebase I was working in.

Looking at [the docs](http://react-dnd.github.io/react-dnd/docs/api/drop-target), I'm not sure if `canDrop` is what's needed or not. Does that override `DropTarget`'s `types` parameter?

**Comment by crispy-invention** [comment]
@simshaun you can have type = ["common"] (or all types) on DropTarget so any source can be dropped on that target. Now if canDrop() is available DnD will use it for all sources. So you can precisely control what source can be dropped and when.

**Comment by m0onspell** [comment]
> Sorry, it's been so long I don't remember what codebase I was working in.
> 
> Looking at [the docs](http://react-dnd.github.io/react-dnd/docs/api/drop-target), I'm not sure if `canDrop` is what's needed or not. Does that override `DropTarget`'s `types` parameter?

Looking at the docs, it doesn't seem so.

So is there any solution to that problem? I don't understand @crispy-invention suggestion.

**Comment by paztis** [comment]
accept is mandatory.
if it didn't fit the the type f the dragged item, we never enter in the canDrop function
It is still a missing feature since 5 years.
There's really no way to accept all the possible types ?
