### ISSUE TITLE
Disable dragging when there are no drop targets

### ISSUE THREAD

**Issue by davidsharff** [react-dnd/react-dnd#436]
Is it possible to disable dragging based on there being no drop targets? Do we have access to information about the drop targets in the drag source that I could use to disable dragging?

**Comment by froatsnook** [comment]
This is undocumented, so it might break in future versions.  But if you like to live dangerously:

Let's say you have some DragSources of type "foo" and some DropTargets of type "bar".

```javascript
const fooSource = {
  // Can drag if there's anything that accepts my type, i.e. "foo".
  canDrag(props, monitor) {
    // Looks like { S8: "foo", S10: "foo", S12: "foo", T9: "bar", T11: "bar" }
    const { types } = monitor.internalMonitor.registry;

    for (const key in types) {
      if (key[0] === "T" && types[key] === "foo") {
        return true;
      }
    }

    return false;
  },
  ...
};
```

BTW, I haven't tested this, but it should point you in the right direction!
