### ISSUE TITLE
Can't select input text in Chrome

### ISSUE THREAD

**Issue by maxsalven** [react-dnd/react-dnd#438]
I believe this is still an issue for `<input />`. See screen grab:

https://github.com/gaearon/react-dnd/issues/358#issuecomment-194106893

**Comment by mondaychen** [comment]
+1 for this. It's pretty annoying and I can't find a good way to do it.
I found this workaround https://github.com/gaearon/react-dnd/issues/335 but my `<input>` is in a grandchild component. It's hard to add event listeners from drag source level.

**Comment by ngoctigerstyle** [comment]
Had this issue been fixed?

**Comment by tention** [comment]
Encountered the same problem here.

**Comment by tcosentino** [comment]
I am also looking for a good solution to this. 

Here is a collection of issues that have been created for this, for reference:
- #335
- #358
- #260
- #178

Per @mondaychen, here is @gaearon's suggestion from #335:
```javascript
render() {
  let element = (
    <div>
      <input
        onMouseEnter={() => this.setState({ overInput: true }) }
        onMouseLeave={() => this.setState({ overInput: false }) }
      />
    </div>
  );

  if (this.state.overInput) {
    return element;
  }

  return this.props.connectDragSource(element);
}
```

The reason this doesn't work for me is that I have somewhat "unknown" children. The children are always forms but can be nested and used in other (non-draggable) situations. In my application, we could add `onMouseEnter` and `onMouseLeave` to each input, and keep `overInput` in our redux store to always know if an input is being hovered - but this will be overkill in any situation other than the sorting page.

@cscleison added this suggestion 11/11/16:
```javascript
class RowDraggable extends React.Component {
    node = undefined;
    constructor(props, ctx) {
      super(props, ctx);

      this.onHoverOverInput = this.onHoverOverInput.bind(this);
      this.onHoverOutOfInput = this.onHoverOutOfInput.bind(this);

      this.state = {overInput: false};
    }
    componentWillUnmount() {
      this.detachEventListeners(this.node);
      this.node = undefined;
    }
    getInputElements(node) {
      return node
        ? Array.prototype.slice
            .call(node.getElementsByTagName('input'))
            .filter(e => !e.readOnly)
        : [];
    }
    onHoverOverInput() {
      this.setState({overInput: true});
    }
    onHoverOutOfInput() {
      this.setState({overInput: false});
    }
    detachEventListeners(node) {
      this.getInputElements(node).map(e => {
        e.removeEventListener('mouseleave', this.onHoverOutOfInput);
        e.removeEventListener('mouseenter', this.onHoverOverInput);
      });
    }
    render() {
      const { rowProps, isOver, connectDropTarget, connectDragSource
        } = this.props;
      const { overInput } = this.state;

      return <YourRow
            isOver={isOver}
            ref={instance => {
              this.detachEventListeners(this.node);
              this.node = findDOMNode(instance);

              if (!overInput) {
                connectDragSource(this.node);
                connectDropTarget(this.node);
                this.getInputElements(this.node).map(e => {
                  e.addEventListener('mouseenter', this.onHoverOverInput);
                });
              } else {
                this.getInputElements(this.node).map(e => {
                  e.addEventListener('mouseleave', this.onHoverOutOfInput);
                });
              }
            }}
          />;
    }
}
```

This seems like my best option so far. It seems very hacky but like it would work. Any other ideas?

**Comment by tention** [comment]
Solved mine with the use of Redux store instead of React state. Assign connectDropTarget() only when editing is true. 

Seems to be the only way to temporary remove DnD when my <input> is in a child component.

**Comment by tcosentino** [comment]
@tention yes, sounds like this might be best. I wish I didn't have to remind form makers to include these events on each input going forward, but probably not much else to do!

**Comment by lulupy** [comment]
my solution is:
```js
<input
  onDragStart={(event) => {
     event.stopPropagation();
      event.preventDefault();
   }}
   draggable
/>
```

**Comment by harekuer** [comment]
> my solution is:
> 
> ```js
> <input
>   onDragStart={(event) => {
>      event.stopPropagation();
>       event.preventDefault();
>    }}
>    draggable
> />
> ```

it works for me,great
