### ISSUE TITLE
Tutorial - width: 100% and height: 100% has no effect

### ISSUE THREAD

**Issue by keithyong** [react-dnd/react-dnd#443]
I am going through the tutorial for the chessboard, at the part where flexbox is introduced and seems like the Board's `width: 100%;` and `height: 100%;` has no effect, because `<div id="root">` has no preset width or height.

![screen shot 2016-04-19 at 12 09 01 pm](https://cloud.githubusercontent.com/assets/6934989/14646585/00e595aa-0628-11e6-997d-65a152ff53c6.png)

Proposed fix: change the board's style from 

```
width: '100%',
height: '100%'
```

to

```
width: '400px',
height: '400px'
```

This still works with the flexbox implementation, and makes it less confusing for beginners who might run into the same trouble (like me).

 Here's what it looks like:

![screen shot 2016-04-19 at 12 11 38 pm](https://cloud.githubusercontent.com/assets/6934989/14646616/2420d296-0628-11e6-842f-efba4b744e52.png)

**Comment by billyjanitsch** [comment]
See #422. PR welcome.

**Comment by keithyong** [comment]
Cool, I'll see if I can make a PR after I finish the tutorial. The main grunt of the work would be to refresh the images I think.

**Comment by mdramos** [comment]
still an issue

**Comment by billyjanitsch** [comment]
@mdramos PR still welcome.

**Comment by velobuff** [comment]
This is a common issue with code that may or may not assume you're using quirks-mode. The issue is that with `<DOCTYPE html>`, the height of the 'html' and 'body' aren't 100% so 'div' heights end up being 0. You can fix it by removing the code or explicitly setting 'html' and 'body' to 100% height.
