### ISSUE TITLE
How to customize Drag Effect based on the target ?

### ISSUE THREAD

**Issue by theTechie** [react-dnd/react-dnd#448]
How do we go about customising the DragPreview using a custom DragLayer based on the Drop Target ?

i.e. To show a visual cue about a target not accepting a drag source, on the drag preview.

I guess right now we only have browser supported drop effect like one mentioned here : https://gaearon.github.io/react-dnd/examples-customize-drop-effects.html

**Comment by msonip** [comment]
For now you can loop over all targetIds -

```
canDrop: () => {
      const targetIds = monitor.isDragging() ? monitor.getTargetIds() : [];

      for (let i = targetIds.length - 1; i >= 0; i--) {
        if (monitor.isOverTarget(targetIds[i])) {
          return monitor.canDropOnTarget(targetIds[i])
        }
      }

      return false;
    }()
```

But it's not performant.

It would be awesome if the monitor also let us know what is the drop target being hovered on.

@gaearon any suggestions?

**Comment by Venryx** [comment]
This would be useful for me as well.

In the meantime, though, @msonip's approach works for me.

**Comment by lsem** [comment]
@msonip  Please could you explain in a bit more details how to inject this canDrop to drag layer? I didn't get you here.

**Comment by hakubo** [comment]
Is there a better way now to do this?

**Comment by fridaystreet** [comment]
I know this is old thread, but had this issue and solved it using a ref which seemed much easier so thought post it for anyone else.

So we pass our preview component to the drag layer view the item. obviously you need to hookup your preview component to forwardRef to something inside it you want to style

```
const dragPreviewRef = useRef()

const [{ isDragging }, drag, preview] = useDrag({
		item: {
			props,
			type: 'taskCard',
			Preview: <TaskCardDragPreview ref={dragPreviewRef} {...props} />,
      dragRef,
      dragPreviewRef
		},
...
})
```

then in your droppable you can just reference the ref and set the style directly

```
const [{ isOver, canDrop }, drop] = useDrop({
		accept: [ 'taskCard'],
		canDrop({ dragPreviewRef }, monitor) {

      if (dragRef?.current?.style && <some other thing is true>) dragRef.current.style.opacity = 0.3

})
```
