### ISSUE TITLE
Stale link to dist in website

### ISSUE THREAD

**Issue by beeb** [react-dnd/react-dnd#449]
The link provided on the website (https://github.com/gaearon/react-dnd/tree/latest/dist) is stale. I see from the changelogs that it's not provided since 2.1.0 but the website still mentions it.
Thanks.

**Comment by kesne** [comment]
I found it here: https://github.com/gaearon/react-dnd/blob/0f1b5d8731caeacad5474e09976b963d7462e796/docs/04%20Backends/HTML5.md
and here: https://github.com/gaearon/react-dnd/blob/1345c19eabbc92c4396c30e24da115edc835cd4e/docs/00%20Quick%20Start/FAQ.md
