### ISSUE TITLE
Huge performance regression when updating from 2.0.2 to 2.1.4.

### ISSUE THREAD

**Issue by jhgg** [react-dnd/react-dnd#458]
We recently tried to upgrade react-dnd from 2.0.4 to 2.1.4 and noticed a huge performance hit when mounting/unmounting many elements. In our case, we have lots of drag and drop targets (each channel, user in voice channel, etc...)

Take a look at these recordings, this one is on a build with react-dnd upgraded to 2.1.4: 
https://cdn.discordapp.com/attachments/180419911636615168/180419950039662594/Screen_Recording.mov

This one is with react-dnd at 2.0.2:
https://cdn.discordapp.com/attachments/180419911636615168/180420571639578625/Untitled_2.mov

**Comment by jhgg** [comment]
Looks like one of my co-workers reported this too on #441 when we tried to upgrade to 2.1.2. 

We'll work on getting a minimal repro. I think it just has to do with mounting and umounting a bunch of elements.

**Comment by marbemac** [comment]
+1 we are seeing this as well, but don't know exactly why it is happening other than the version bump - it's very noticeable.

**Comment by gferreri** [comment]
I started with 2.1.4, and never used 2.0.4, but I'm also seeing this in my project when I have a couple hundred components in play as drop targets.

**Comment by keithrobichaud** [comment]
+1 also noticing these issues after upgrading to 2.1.4. Anyone able to resolve these issues?
