### ISSUE TITLE
Error in production mode: Uncaught Invariant Violation: Expected targetIds to be unique in the passed array.

### ISSUE THREAD

**Issue by davidmilo** [react-dnd/react-dnd#464]
Hi,

I am getting `edit:24 Uncaught Invariant Violation: Expected targetIds to be unique in the passed array.` error when I start dragging my component. However this issue only occurs in my production app. Surprisingly our staging which is using same process of deployment works ... 

Any idea what could be wrong?

**Comment by froatsnook** [comment]
That's an interesting one!  Did you ever figure it out?  I recommend setting a breakpoint and checking what the `targetIds` array has when you create your `DropTarget`.

**Comment by kesne** [comment]
@davidmilo Let me know if you're still having problems with React DnD!

**Comment by PorterNan** [comment]
I am facing that problem, Expected targetIds to be registered. it is very hard to repro, cause it is in production, just 1% percentage of users met that crash, is there anyone have a idea about that?

**Comment by kotsolesya** [comment]
@kesne Hi. I having same problems only in IE and Edge. 
Any idea what could be wrong?

**Comment by drFabio** [comment]
I'm having that as well on chrome and only on a few environments. Didn't find the root cause yet

**Comment by AndrewMorsillo** [comment]
This just randomly started happening to me as well.

**Comment by mtetlow** [comment]
Has anyone figured this out? I am also seeing some inconsistent behavior around this

**Comment by meisammirkahromi** [comment]
Anyone managed to figure this our?

**Comment by zeevl** [comment]
I'm getting this as well, happens randomly and unexpectedly.   I patched it to include the ids in the error: 
```
Invariant Violation: Expected targetIds to be unique in the passed array.["T2","T38","T38","T18","T18"]
```
and
```
Invariant Violation: Expected targetIds to be unique in the passed array.["T6","T6","T341","T416"]
```

In case it helps anyone.   

Not having any idea of what this means, but can we just make this array unique?  Remove the assertion and let them be duplicated?   I can help fix if someone can suggest a direction.. 

Oh, and please reopen this!

**Comment by meisammirkahromi** [comment]
I found the root of mine, and it was a conflict with the **track.js**. So it is worth to check if you have any dependency that is available only on production and could cause such strange behaviour.

**Comment by zeevl** [comment]
@meisammirkahromi are you referring to https://trackjs.com?   I'm not familiar with that and I don't think we have any references to it (`yarn why track.js` has no results??) If you have any other details I'd appreciate it!
