### ISSUE TITLE
How would one only allow dragging on a certain direction?

### ISSUE THREAD

**Issue by ckknight** [react-dnd/react-dnd#467]
What I would like to enable is a list of items (on the top of the screen, for this example) where if they are dragged down, then the regular drag-and-drop mechanism works, but if the user drags left/right, then that list can scroll left or right (via overflow-x: scroll or similar).

What I have done previously (not in React, mind you) is wait for the touch to move 30px, calculate the direction, and then allow for the drag events to propagate based on the angle.

Is this possible with `react-dnd`?

**Comment by tthomas7** [comment]
The [FAQ](https://gaearon.github.io/react-dnd/docs-faq.html) mentions implementing a custom drag layer to constrain the movement rendered. That's easy but I think it's mostly a rendering layer, scrolling the list left and right would be a separate thing. 

Check out [this issue](https://github.com/gaearon/react-dnd/issues/324) for ideas. It sounds like the list is both a drag source and a drop target and implements logic on hover.
