### ISSUE TITLE
Drag is immediately ended when source node change position on screen (by CSS)

### ISSUE THREAD

**Issue by kodl** [react-dnd/react-dnd#477]
For example - I have a list of nodes on screen.

```
[Node1]
[Node2]
..
[Node20]
```

When starts Drag on [Node20], all possible targets (Node1..19) gets CSS style with {border: 3px}, which cause that [Node20] moves down (for 19_3_2 pixels).

This "move" cause immediate endDrag event very often (not all the times) - depends on mouse move.

When I removed CSS border, then problem stops.

**Comment by psachs21** [comment]
I ran into a similar issue. I was able to work around it by putting whatever side effect that causes the style change on a timeout like so:

```js
beginDrag: (props) => {
  setTimeout(() => props.setComponentIsBeingDragged(true), 0);
}
```

In my case, I fired an action (setComponentIsBeingDragged) that caused the component to be pushed down but the idea should still hold when adding classes or whatever

It's not an ideal solution but it works.

**Comment by mdenchev** [comment]
@psachs21 Could you elaborate what you mean by "that caused the component to be pushed down"?

**Comment by mdenchev** [comment]
Ah, I see. Turns out it's a chrome bug(?) where you modifying the dom during dragstart will immediately trigger dragend (http://stackoverflow.com/questions/19639969/html5-dragend-event-firing-immediately), hence the use of a timeout.

**Comment by psachs21** [comment]
Ah I see. If it's just a chrome bug, I'm fine with putting it on a timeout. It's just setting it on the next tick, so it's not such a large deal. Thanks!
