### ISSUE TITLE
Nested DropTargets Don't Work

### ISSUE THREAD

**Issue by cbachich** [react-dnd/react-dnd#483]
I'm working on a react tree that has nested components. I was hoping to use react-dnd with it but have hit a stumbling point. It seems that when a DropTarget is nested within another DropTarget, things fail. I get an Uncaught TypeError: connectDragSource is not a function. Am I missing something or is this something that isn't supported yet?

I've created a simple example of the problem I'm running into. Let me know if there is anything else I can provide.

``` javascript
const Types = {
    ASSET: 'asset'
};

@DragDropContext(HTML5Backend)
export class NestedDndExample extends React.Component {

    render() {
        return (
            <div>
                <h1>Draggables</h1>
                <ul>
                    <DragItem name="Bob" children={[ 'child 1', 'child 2' ]} />
                    <DragItem name="Jane" />
                    <DragItem name="Chris" />
                </ul>
                <h1>Droppables</h1>
                <DropBox name="Box 1" />
                <DropBox name="Box 2" />
                <DropBox name="Box 3" />
            </div>
        )
    }
}

const assetSource = {
    beginDrag(props) {
        console.log('beginDrag', props);
        return props;
    }
};

@DragSource(Types.ASSET, assetSource, (connect, monitor) => ({
    connectDragSource: connect.dragSource()
}))
class DragItem extends React.Component {

    render() {
        const { connectDragSource, name, children } = this.props;

        return connectDragSource(
            <li>
                {name}
                {
                    children == undefined ?
                        '' : (
                        <ul>
                            {children.map(function(name) {
                                return (<DragItem name={name} />);
                            })}
                        </ul>
                    )
                }
            </li>
        );
    }
}

const weirwoodTarget = {
    drop(props, monitor) {
        console.log('dropped', props);
        console.log('monitor', monitor.getItem())
    }
};

@DropTarget(Types.ASSET, weirwoodTarget, (connect, monitor) => ({
    connectDropTarget: connect.dropTarget(),
    isOver: monitor.isOver()
}))
class DropBox extends React.Component {

    render() {
        const { connectDropTarget } = this.props;

        var style = {
            width: 50,
            height: 50,
            margin: 20,
            border: '1px black solid'
        };

        return connectDropTarget(
            <div>
                <h3>{this.props.name}</h3>
                <div style={style}>
                </div>
            </div>
        )
    }
}
```

**Comment by chalda** [comment]
Interesting literally in the middle of implementing something extremely similar.
a droptarget panel that has tree structure of elements that are both dragsources and drop targets. didnt get to the point of compiling my code yet but i think i am about hit this as well. 

let me know if you figure anything out.

**Comment by jugimaster** [comment]
It might be related to React's event handling. IIRC, if you have nested handlers for the same event, then the "outer" one will fire before the "inner" one, because React handles all events on the document, and stuff.

**Comment by dant00ine** [comment]
Anyone find a good workaround for this? Might have to move to another library T_T

**Comment by jugimaster** [comment]
The latest React version might help.

**Comment by Ravalika24** [comment]
Need solution for this using React library itself. Can anyone please help ?

**Comment by wouter-vdb** [comment]
I had similar objectives and the same kinds or issues, and it turned out that for my nested elements I was using the undecorated class. Using the decorated class solved it all.

**Comment by georgejdanforth** [comment]
I know this issue is super old, but I figured out a solution to this when rendering components recursively. The trick is to define and export the `DragSource` component separately from the component that renders itself.

So, in the above example it would be changed to:
```js
class DragItem extends React.Component {
/* ... */
                        <ul>
                            {children.map(function(name) {
                                return (<DragItemContainer name={name} />);
                            })}
                        </ul>
/* ... */
}

const DragItemContainer = DragSource(Types.ASSET, assetSource, (connect, monitor) => ({
    connectDragSource: connect.dragSource()
}))(DragItem)
```

**Comment by peterpme** [comment]
Hey @georgejdanforth are you able to share a more complete example? This has been a great step forward but I can't figure it out 😄

**Comment by georgejdanforth** [comment]
@peterpme Sure, I used this method here: https://github.com/georgejdanforth/record-bin/blob/master/app/src/containers/Folder.js

Apologies for the lack of documentation 😅

**Comment by peterpme** [comment]
Thank you @georgejdanforth 😘

Is this live by the way? Interested in giving it a shot :)

**Comment by georgejdanforth** [comment]
@peterpme There are a couple loose ends I've still been meaning to tie up, but it's in stealth mode on the chrome web store

https://chrome.google.com/webstore/detail/record-bin/epmfcbngjhcniippplhikdcgfkkimbgl

Feedback and PRs always welcome :]

**Comment by willh33** [comment]
How would this look in the latest version where you have a ref to a useDrag variable?
