### ISSUE TITLE
Connect to Draft.JS

### ISSUE THREAD

**Issue by GuyHovav** [react-dnd/react-dnd#485]
Is there a way to use React DnD with Draft.js?
I would like to use Draft.js as drop target.
I saw that Draft has [handleDrop](https://facebook.github.io/draft-js/docs/api-reference-editor.html#handledrop) prop but I don't know how to use it with React DnD.

Thanks

**Comment by kesne** [comment]
I'm not sure how clean the integration would be. Draft manages it's own drop system, whereas react-dnd really expects that it owns the whole world, so-to-speak. You could maybe try using the html5 backend and just a dragSource and then make your draftJS client a dropTarget and see if things get forwarded correctly. I'm guessing they won't be, so you might have to wire things up yourself.
