### ISSUE TITLE
drop function never called on DropTarget

### ISSUE THREAD

**Issue by tbohlen** [react-dnd/react-dnd#487]
I'm trying to use ReactDnD to allow someone to move items around on a large canvas. The canvas is a single large dropTarget, and each item on it is a single DragSource.

I can click and drag the node around the canvas without any trouble, and as I do so the canDrop action is called correctly on the DropTarget. The drop function I specified, though, is never called. In addition, if I check monitor.didDrop() in the endDrag function of the DragSource, it returns false even if canDrop was returning true and did drop the element.

So it seems like there is some eventing issue here or perhaps drop is only fired when dragging into a new target. Is that the case, or any other recommendations about where to look for an issue?

**Comment by mcrawshaw** [comment]
ReactDnd is most powerful when there is a clear mapping between drag/drag source-target and HTML/SVG elements (or React Components).  As you only really have one drop target, I would suggest writing something to manage the drag & drop yourself.  Often when writing code to manage a drawing canvas there are lots of things to consider, e.g. zoom in/out and panning.  For such functionality you really need a global input handler that manages a range of concerns (including drag and drop against the current viewport transform).

BTW. Using a design similar to ReactDnd for the components you drag around is a great idea.  For example, when your global input handler detects a drag you can trigger an event with the component you are dragging.

**Comment by tbohlen** [comment]
Thanks for the response. We had actually had our own handler and were exploring using ReactDND instead. Sounds like we'll stick with our handler for this.

**Comment by siemiatj** [comment]
In my case my drop function is called but `monitor.didDrop()` always returns false. No fancy setup, just a simple list of elements where everything is both dropTarget and dropSource. It sucks that I can't force-call `didDrop` on monitor.
