### ISSUE TITLE
How to fix typescript error for NativeTypes on DropTarget

### ISSUE THREAD

**Issue by davidl63** [react-dnd/react-dnd#491]
If I try and use NativeTypes.FILE on a DropTarget as a type I get the typescript error
Argument of type 'NativeTypes' is not assignable to parameter of type 'string | string[] | ((props: any) => string | string[])'.

I have not been able to figure out a cast or a different way of specifying NativeTypes that works.
How can I fix this error?

**Comment by DarkSnowy** [comment]
The typings file needs to be updated from:
```
    // The React DnD docs say that this can also be the ES6 Symbol.
    type Identifier = string;
```
To something like:
```
    // Accepts string, Symbol or Enum.
    type Identifier = string | Object;
```
