### ISSUE TITLE
no click event if canDrag() returns false due to "draggable" atribute

### ISSUE THREAD

**Issue by HermanBovens** [react-dnd/react-dnd#498]
I have a component for which some instances have to be draggable, others don't.
Those that don't need to be draggable need to receive click events.

Normally if you don't add the HTML5 `draggable` attribute to an element, you can press a mouse button while on the element, move the mouse a few pixels and release the button, and it would be registered as a click event.
However, when you add the `draggable` attribute, it seems clicks are only registered if you don't move the mouse.

Normally if you use the HTML5 Drag and Drop API, you only add the `draggable` attribute to elements that actually need to be draggable so this would be no issue.  However with react-dnd it seems the attribute is added even if `canDrag()` returns `false`.  Therefore users need to make sure they don't move the mouse even a single pixel while clicking, which is annoying.

Is there a way to remove the `draggable` attribute when `canDrag` returns false?

**Comment by Niryo** [comment]
Im also facing that problem, I need to be able to select text on the node if it is not draggable, and currently I can't because of the same problem that you have mention.

**Comment by philraj** [comment]
Having the same issue. It'd be very helpful if the draggable attribute could be set to false when drag behavior is unneeded. Unless there's a workaround for this? I've seen people suggest making a separate drag handle that's the same size as the component instead of making the component itself draggable, but that feels like a bit of a hack.

**Comment by tysonnero** [comment]
Has anyone figured out how to remove or toggle `draggable=true`?
