### ISSUE TITLE
Modify custom drag layer if it's over DropTarget

### ISSUE THREAD

**Issue by anrw** [react-dnd/react-dnd#505]
Hi all,

Is there a way to check if custom DragLayer is over DropTarget?

Thanks

**Comment by Venryx** [comment]
See here: https://github.com/gaearon/react-dnd/issues/448

It's not the best solution, but gets the job done for now.

**Comment by mindtricksdev** [comment]
That will help me too.
I have an item which should have different previews based on which DropTarget is over.
When I am over a DeleteDropTarget I want the preview to scale(.5).

**Comment by tageecc** [comment]
@mindtricksdev hi mindtricksdev，any updates? im also looking for the solution

**Comment by mindtricksdev** [comment]
I worked around that. I made the drop target react to custom drag layer hover. This was acceptable as UX for my DeleteDropTarget as I changed the drop background to red instead of scaling down the dragged item.
