### ISSUE TITLE
react dnd isssue

### ISSUE THREAD

**Issue by ashutoshjha1409** [react-dnd/react-dnd#508]
./scripts/startSiteDevServer.sh

I am getting this issue while running npm

**Comment by kesne** [comment]
@ashutoshjha1409 Can you provide more details to reproduce the issue, and can you describe exactly what problems you're having?

**Comment by yuanzx** [comment]
## File not found when running npm start

lerna ERR! execute callback with error
lerna ERR! Error: Command failed: yarn run start
lerna ERR! sh: ./scripts/startSiteDevServer.sh: /bin/bash^M: bad interpreter: No such file or directory
