### ISSUE TITLE
Cannot get mouse position when dragging out of browser window

### ISSUE THREAD

**Issue by Lyrillind** [react-dnd/react-dnd#509]
Hi, I'm implementing an application that allow user to drag an element all around. I need to update the element's position when user is dragging it. 
I used `monitor.subscribeToOffsetChange()` to continuously get mouse position.
But when dragging it, and the mouse is out of window, I can't get mouse position so I can't update the element's position. Is there any solution or any way to get mouse position even it's out of window?
Thanks.

**Comment by kesne** [comment]
I don't think that you can capture the mouse position in a drag event once it's out of the window.

**Comment by Murriouz** [comment]
I know if binding ```onmousemove``` can get mouse position even mouse is out of the window. I want to know is there a way to obtain mouse position in react-DnD.
Thanks.

**Comment by kesne** [comment]
Really? I can't recreate that with this:

```js
window.addEventListener('mousemove', () => console.log('mouse moved'));
```

**Comment by Murriouz** [comment]
You have to hold mouse button down, then you can receive ```mousemove``` event.

**Comment by kesne** [comment]
Ah interesting! I'll take a look at this and see. I think we hide all of the mouse events and data from the consumers so it might not be possible.
