### ISSUE TITLE
[RFC] Remove decorators from documentation.

### ISSUE THREAD

**Issue by kesne** [react-dnd/react-dnd#510]
Right now the documentation includes decorators, which are a stage-2 TC39 proposal. The implementation in babel has issues, and requires a legacy transformer. Should we pull decorators from the docs until the spec is finalized and babel is updated?

**Comment by tonilaukka** [comment]
I would leave them there with a notion about stage-2. If you use ES7 you probably also know about decorators and their current issues.

**Comment by kesne** [comment]
@tonilaukka The problem is that people set them up based on outdated blog posts and try to get help via random stackoverflow findings. The experience is far from seamless and I know that a lot of projects promoting the use of decorators get bug reports from people mis-configuring babel (which makes sense because it's extremely brittle and error prone to set up decorators).

**Comment by kesne** [comment]
Also, the official `create-react-app` setup doesn't include decorators. So out of the box people might get confused and try to use features that are not available to them.

**Comment by gaearon** [comment]
Totally agree with this. Happy to add them back when Babel officially supports them and configuration doesn't break due to plugin order.

**Comment by tonilaukka** [comment]
@kesne you make valid point there with `create-react-app` and I agree with you and @gaearon on the other issues too. ;) When everything is working for you, it easy to forget how hard it was to get working in the first place.
