### ISSUE TITLE
react - dnd unit testing  Invariant Violation: Expected a valid target ID.

### ISSUE THREAD

**Issue by potapovDim** [react-dnd/react-dnd#520]
```
describe.only('Drag drop test', () => {
  class Wrapper extends Component {
    render() {
      return <div>{this.props.children}</div>
    }
  }
  let renderedCmpt = null
  let WrapperContext = null
  beforeEach('set up', () => {
    const setFocusedElement = sinon.spy()
    WrapperContext = wrapInTestContext(Wrapper)
    renderedCmpt = TestUtils.renderIntoDocument(
      <WrapperContext>
        <Block uid={'test'} setFocusedElement={setFocusedElement}/>
        <ButtonThumbnail />
      </WrapperContext>
    )
  })

  it('--------------------- ', () => {
    const wrapperContext = TestUtils.findRenderedComponentWithType(renderedCmpt, WrapperContext)

    const dropZone = TestUtils.findRenderedComponentWithType(renderedCmpt, Block)
    const dropId = dropZone.getHandlerId()

    const dragComponent = TestUtils.findRenderedComponentWithType(renderedCmpt, ButtonThumbnail)
    const dragId = dragComponent.getHandlerId()

    const backend = wrapperContext.getManager().getBackend()
    const monitor = wrapperContext.getManager().getMonitor()

    console.log(dragId, dropId) //S29 S28
    backend.simulateBeginDrag([dragId])
    backend.simulateHover([dropId])
    backend.simulateDrop()
  })
})
```

dragId = dropId ,how can it be?

stack : 
Invariant Violation: Expected a valid target ID.
      at Object.invariant [as default](node_modules/invariant/invariant.js:42:15)
      at HandlerRegistry.getTarget (node_modules/dnd-core/lib/HandlerRegistry.js:137:27)
      at DragDropManager.hover (node_modules/dnd-core/lib/actions/dragDrop.js:124:27)
      at Object.hover (node_modules/dnd-core/lib/DragDropManager.js:74:36)
      at TestBackend.simulateHover (node_modules/dnd-core/lib/backends/createTestBackend.js:50:18)

**Comment by HorseBinky** [comment]
I have a similar problem. I use enzyme and mounted two components (one source and one target) seperatly. Like you I tried to drop source on the target.

**Comment by MomchilGorchev** [comment]
Same here, using enzyme with jest and getting 
```
Invariant Violation: Could not find the drag and drop manager in the context of DropTarget(WidgetContainer). Make sure to wrap the top-level component of your app with DragDropContext. Read more: http://gaearon.github.io/react-dnd/docs-troubleshooting.html#could-not-find-the-drag-and-drop-manager-in-the-context
```
when trying to render component that is `DragSource`

**Comment by jca41** [comment]
This is a big issue, you need to wrap the component in drag drop context in order to not throw the above violation. But then you can't manipulate state and use other enzyme functionalities because it's not a Root Component.

**Comment by Larkenx** [comment]
@jca41 is exactly right. This is breaking all of our pre-existing unit tests and we can't find a way to unit test them without exporting the original component without the `DragDropContext`, but that defeats the purpose...

**Comment by darthtrevino** [comment]
With react-dnd 3 and below, can you use enzyme's context API to set the Backend? http://airbnb.io/enzyme/docs/api/ShallowWrapper/setContext.html

The context value you need to set is `dragDropManager`: https://github.com/react-dnd/react-dnd/blob/6d0b0e302e980e01fd91c09003f9a78ebc78fedf/packages/react-dnd/src/DragDropContext.js#L12

With react-dnd 4+, we're using the new Context API, and I don't see any indication that enzyme supports it yet.

I'll make a note that we should improve our testing docs.

**Comment by Larkenx** [comment]
I found my solution by using the [React DnD docs testing section](http://react-dnd.github.io/react-dnd/docs-testing.html). I was able to unit test original component functionality with `const OriginalBox = Box.DecoratedComponent;`
