### ISSUE TITLE
Possible to programatically cancel a drag?

### ISSUE THREAD

**Issue by BrennanRoberts** [react-dnd/react-dnd#528]
Hi folks, thanks for your work on this library. Is it possible to programmatically cancel an in-progress drag?  If not, what's the best way to determine if the component has been unmounted at drop-time so we don't try to trigger an action on a (say) deleted item?

**Comment by charlesoconor** [comment]
bump

**Comment by brianh20** [comment]
bump

**Comment by Johnrobmiller** [comment]
This feature is still missing, it's appearing in search results, and this issue should not have been closed. I seriously hate these bots that automatically close issues.
