### ISSUE TITLE
Unit testing with native types?

### ISSUE THREAD

**Issue by emilecantin** [react-dnd/react-dnd#534]
My app has some behaviour around dropping files and URLs on some components.

How can I test this? There doesn't seem to be a DragSource involved in this, but when I try calling `simulateHover` with my drop target, I get this:

```
 Invariant Violation: Cannot call hover while not dragging
```

It looks like I need to call `simulateBeginDrag`, but with what? Is there something I'm missing?

**Comment by HorseBinky** [comment]
Yes, you have to simulate the complete Dragging cycle. And you need performe it with a dragSource. Here is a very nice example writen with enzyme which helped me a lot!
[https://github.com/gaearon/react-dnd/issues/453](url)
