### ISSUE TITLE
Uncaught invariant violation with React-router

### ISSUE THREAD

**Issue by vshia** [react-dnd/react-dnd#535]
Hi all,

I've running React-router with React-dnd and am running into the following Invariant error when I try to use react-router's HOC (`Router.withRouter`) with `DragDropContext(HTML5Backend)`:
<img width="528" alt="screen shot 2016-09-08 at 11 13 12" src="https://cloud.githubusercontent.com/assets/401047/18408229/ca7f7742-76de-11e6-815e-e418193f88de.png">

I'm running react 15.1.0, react-router 2.7.0, react-dnd 2.1.4, and react-dnd-html5-backend 2.1.2 and I'm certain I don't have 2 versions of React running.

After looking around the code base and React documentation on refs (https://facebook.github.io/react/docs/more-about-refs.html), I think it has to do with making the ref a callback function instead of a string in line 76 of `DragDropContext.js`.  (There are variants of this found in line 185 of `decorateHandler.js`

If I change line 76-80 of DragDropContext:

```
      DragDropContextContainer.prototype.render = function render() {
        return _react2['default'].createElement(DecoratedComponent, _extends({}, this.props, {
          ref: 'child'
        }));
      };
```

to this:

```
      DragDropContextContainer.prototype.render = function render() {
        return _react2['default'].createElement(DecoratedComponent, _extends({}, this.props, {
          ref: this.getDecoratedComponentInstance
        }));
      };
```

the Invariant warning disappears.

While the Invariant warning disappears and my React components render completely fine, I'm not sure if this is entirely correct or if this will introduce unforeseen errors somewhere else. 

Any thoughts?
Thank you!

**Comment by withintheruins14** [comment]
Hello @vshia, I am experiencing the same issue. After reviewing similar issues and solutions online, I am still stuck. Have you resolved this? I have updated my dependencies, removed node_modules and reinstalled, and greped my entire repo for duplicate versions of React. My React lives in components.js as `global.React = require('react');` and my react-dom as well. I am using browserify-rails (3.4.0), react-router (^5.0.2), and React(^15.4.2). Any help is greatly appreciated. Thanks

Here is my root.js: http://pastebin.com/raw/HDPFgYQR
Here is my app.js: http://pastebin.com/raw/cmT4BJdk
Here is my package.json: http://pastebin.com/raw/hJXCLy1N
