### ISSUE TITLE
Strange issue in chrome (53) only

### ISSUE THREAD

**Issue by kingsurf** [react-dnd/react-dnd#537]
I have a very strange issue which I have narrowed down to the method "monitor.getDifferenceFromInitialOffset" I have console logged the coordinates of this method in chrome and right before releasing the mouse the coordinates suddenly jump to a completely different area of the screen. This does not occur in Edge/Firefox and only occurs in chrome. I am not running any extensions apart from ad blocker... any ideas?

![dragndrop bug](https://cloud.githubusercontent.com/assets/8368812/18534015/d3d745ae-7b2a-11e6-8880-fe8c326d2059.gif)

**Comment by kingsurf** [comment]
To reproduce this set zoom to 150% - 200% (sign out/sign in) must be on chrome 53

**Comment by kesne** [comment]
Seems related to #430.
