### ISSUE TITLE
File drop in Firefox doesn't always work

### ISSUE THREAD

**Issue by Devilly** [react-dnd/react-dnd#539]
While working on a project it was noted that the native file drop didn't always work in Firefox. I didn't see any error or whatsoever but I did see the file drop was not handled by the function I had made therefore. While trying to create a testcase I made https://jsfiddle.net/r2mudx7a/ and there quite often the following error is thrown:

Error: Cannot call hover while not dragging.

When trying the fiddle please drag on a text file on the dashed square. In my latest test run I got the error nine times before it finally worked (the file was read and outputted to the console).

![image](https://cloud.githubusercontent.com/assets/603645/18576595/3a6337a2-7be3-11e6-9c1b-44bbcbe346ca.png)

**Comment by bouwwouw** [comment]
When you drop a file, Firefox will fire the `mousemove` event before the `drop` event. In HTML5Backend.js this causes `endDragNativeItem` to be fired before `handleDrop`.

Removing the firefox specific event handler makes dropping files work. But then if you drag a file to a new tab, react-dnd gets stuck in dragging state, and you cannot start dragging any items on the page. You can get out of this state by dragging another file around.

Another possible solution is by using setTimeout on the Firefox specific event handler. I haven't found any new bugs, but I'm not sure if it's a good solution. Any ideas?
