### ISSUE TITLE
Drag and Drop between two different containers with different elements

### ISSUE THREAD

**Issue by romanmuska** [react-dnd/react-dnd#542]
Hello,

is there any way to do drag and drop between two different lists with two different containers (every container contains different elements). I have found solution here http://rafaelquintanilha.com/sortable-targets-with-react-dnd/ but the problem is that i can just a push element into another container not drag and dropping there.

**Comment by romanmuska** [comment]
I can do it by adding container in every element in first list and then i can drag there what i want but the problem is that i need to hide it and when i drag the element on it, it shows

**Comment by kesne** [comment]
This example shows how you can hide the element while dragging it: http://gaearon.github.io/react-dnd/examples-sortable-simple.html

**Comment by crapthings** [comment]
@kesne 

but how to drag sortable item to another container ?

**Comment by Carmezim** [comment]
Any updates?

**Comment by denvist** [comment]
@Carmezim 
tutorial & example - [http://rafaelquintanilha.com/sortable-targets-with-react-dnd/](http://rafaelquintanilha.com/sortable-targets-with-react-dnd/)

**Comment by xTaz1** [comment]
Any updates here?

**Comment by harrysolovay** [comment]
^ updates?
