### ISSUE TITLE
Accommodating DragDropContext in Dependency

### ISSUE THREAD

**Issue by gabergg** [react-dnd/react-dnd#544]
I'm building a webapp that uses react-dnd, and the top level is wrapped in DragDropContext. I'm also bringing in a package that also uses react-dnd, and that package is wrapped at its top level with DragDropContext. 

I ended up with drag issues (without any explicit warnings) until I removed one of the DragDropContext. Should an app work with multiple DragDropContext like this? If not, what's the best way to handle the issue?

**Comment by kesne** [comment]
The context is designed to be app-level. I'm guessing the best approach for your package would be removing the top-level context provider wrapping. The benefit of doing this is that you allow the consumer to set the backend of dnd (i.e. touch or html5).

**Comment by aurels** [comment]
So if I need several different sortable lists in the same page, I need to put only one `DragDropContext` as a common ancestor ?

**Comment by qborreda** [comment]
While the context can be set up in the top level, say App, it really makes much more sense to have it in the parent component of the ones using d&d capabilities. 

In fact, in my case, I have to wrap it around a container connected with Redux, and works like:
```
export default DragDropContext(HTML5Backend)(connect(
  mapStateToProps,
  mapDispatchToProps
)(ProposalsPage));
```
