### ISSUE TITLE
Update Babel and disposables

### ISSUE THREAD

**Issue by jakubzitny** [react-dnd/react-dnd#546]
Would you be open for PRs updating some of the outdated dependencies? Good candidates could be e.g. Babel 5 or `disposables` that's not maintained anymore?

Maybe alse adding a [david](https://david-dm.org) badge.

**Comment by kesne** [comment]
Yes definitely! I'm a little behind on this repo, but I have plans in the next few weeks to pump some life into it!

**Comment by patchygreen** [comment]
Hi. Just wondering if there was any update on removing the `disposables` dependency?
