### ISSUE TITLE
When drag starts, preview is offset

### ISSUE THREAD

**Issue by mvanlonden** [react-dnd/react-dnd#552]
<img width="383" alt="screenshot 2016-10-09 09 37 41" src="https://cloud.githubusercontent.com/assets/1718791/19227042/c563e6de-8e68-11e6-97ff-732ce8b2fc6e.png">

The preview generated is offset from the click position

**Comment by mvanlonden** [comment]
The original node is under the cursor and the preview is in the bottom right

**Comment by mvanlonden** [comment]
This only happens on chrome, works fine on firefox

**Comment by brakon** [comment]
its going to be a year with this not working :s any idea on when it will be fixed?

**Comment by project707** [comment]
I'm actually seeing this exact thing in other browsers as well, but quite the opposite positioning. I used the initial preview style settings used in the examples: ` left: 0, top: 0` and the layer always starts at the top left corner of the parent container even if dragging an element at the bottom of the viewport. If I remove those initial coordinates  then it drags from somewhere relative to the dragged element but varying distances depending on where dragging started.

**Comment by mcamdenwm** [comment]
Just ran into the same issue as you @project707  For me, the issue presents when the item I am dragging is larger than the viewport, the preview will start at 0,0 whereas the item being dragged is -100, 0.

**Comment by Hatcher** [comment]
This is also malfunctioning on chrome for osx (El Capitan 10.11.6, Chrome Version 65.0.3325.181)

**Comment by nrkroeker** [comment]
I've been attempting to resolve this issue for several days with the same results as above, does anyone know if its going to be looked at eventually? It's been 2 years since the initial issue, just want to keep it active.

**Comment by eliucs** [comment]
Any updates on this issue? This is still a problem

**Comment by Hatcher** [comment]
I think this is an issue related to how chrome handles preview during drag and drop. Not necessarily an issue with React DnD.

**Comment by nrkroeker** [comment]
@Hatcher is this an issue you've encountered/handled before? I can't seem to find anyone with even a hacky fix for it, and I use Chrome primarily so I'd like to avoid it in my projects if possible.

**Comment by coltontravers** [comment]
Getting this issue, too, with Chrome on osx.

**Comment by closertb** [comment]
different browser, differnt performance; wtf...
