### ISSUE TITLE
i've tried to make example 4 to work with multiple decks but getting 3 errors

### ISSUE THREAD

**Issue by crapthings** [react-dnd/react-dnd#555]
```
https://github.com/gaearon/react-dnd/tree/master/examples/04%20Sortable
```

Warning: Failed prop type: Required prop `connectDragSource` was not specified in `DropTarget(DragSource(Card))`.

Warning: Failed prop type: Required prop `connectDropTarget` was not specified in `DropTarget(DragSource(Card))`.

Warning: Failed prop type: Required prop `isDragging` was not specified in `DropTarget(DragSource(Card))`.

the deck works fine with its only column, but i cant drag and drop it to another deck

reproduce repo

https://github.com/crapthings/try-react-dnd

require meteor 1.4.1.2

```
meteor npm install

meteor
```

https://github.com/crapthings/try-react-dnd/tree/master/client/templates/projects

**Comment by mattblackdev** [comment]
@crapthings I just ran into this working on an old meteor project using react inside blaze. Did you happen to figure out a solution?

**Comment by crapthings** [comment]
i've change to another lib, because that already has a working example and its good as react-dnd too

https://react-beautiful-dnd.netlify.com/?selectedKind=board&selectedStory=task%20board&full=0&down=1&left=1&panelRight=0&downPanel=storybook%2Factions%2Factions-panel

**Comment by mattblackdev** [comment]
@crapthings thanks. this is a weird bug, I can reproduce it by including my component in CRA app too. So it's not meteor related.
