### ISSUE TITLE
Drag Around Container.js file i don't change es6

### ISSUE THREAD

**Issue by yoonjaepark** [react-dnd/react-dnd#559]
@DragDropContext(HTML5Backend)
@DropTarget(ItemTypes.BOX, boxTarget, connect => ({
  connectDropTarget: connect.dropTarget()
}))

together use i don't know

this code change es6?

---

sorry help me

 I can not switch to a grammar es6

**Comment by kesne** [comment]
I'm not 100% sure what you're asking here. Can you clarify?

**Comment by YoonJaePark** [comment]
I can not switch to a grammar es6

These syntax @ and   static propTypes = {
    connectDragSource: PropTypes.func.isRequired,
    isDragging: PropTypes.bool.isRequired,
    id: PropTypes.any.isRequired,
    left: PropTypes.number.isRequired,
    top: PropTypes.number.isRequired,
    hideSourceOnDrag: PropTypes.bool.isRequired,
    children: PropTypes.node
  };

**Comment by kesne** [comment]
Is the ES version selector broken? If so, on what page are you seeing this?

Those are experimental proposals, not yet part of the standard language. On the site, you should be able to click the ES5/ES6 version of the code previews to see what the equivalent is.
