### ISSUE TITLE
Can't access handlerId of a Drag Source

### ISSUE THREAD

**Issue by taichatha** [react-dnd/react-dnd#563]
Component

``` jsx
const resultSource = {
    beginDrag(props) {
        return props.result;
    },
    canDrag(props) {
        return hasPermission(props.workspacePermission, [roles.ADMIN, roles.WRITE]);
    }
};

function collect(connect, monitor) {
    return {
        connectDragSource: connect.dragSource(),
        isDragging: monitor.isDragging()
    };
}

@connect((state) => ({workspacePermission: currentWorkspacePermission(state)}), {})
@DragSource(ItemTypes.SEARCH_RESULT, resultSource, collect)
export default class SearchResult extends React.Component {

    render() {
        const {connectDragSource, isDragging, result, onClick, selected} = this.props;
        // console.log(result);
        var style = {
            'opacity': isDragging ? 0.5 : 1
        };

        return connectDragSource(
            <div className={'searchResult draggable ' + (selected ? 'highlighted' : '')}>
                <DisplayVertex vertex={result} style={style} onClick={onClick} isSearchResult={true}/>
            </div>,
            {dropEffect: 'copy'}
        );
    }
}
```

Test

``` jsx
it('can be tested with the testing backend', () => {
         // Render with the test context that uses the test backend
         const vertex = {'attributes': []};
         const SearchResultContext = wrapInTestContext(SearchResult);
         const GraphContext = wrapInTestContext(Graph);
         const graphRoot = TestUtils.renderIntoDocument(<GraphContext name="graphtest" />);
         const searchRoot = TestUtils.renderIntoDocument(<SearchResultContext result={vertex} isSearchResult={true} name="searchtest"/>);
         const backend = searchRoot.getManager().getBackend();
         const searchResult = TestUtils.findRenderedComponentWithType(searchRoot, SearchResult);
         const graphResult = TestUtils.findRenderedComponentWithType(graphRoot, Graph);
         console.log(searchResult.getHandlerId());
         // backend.simulateBeginDrag([searchResult]);
         // See other backend.simulate* methods for more!
     });
```

TypeError: undefined is not a constructor (evaluating 'searchResult.getHandlerId()') 

Graph gets the handlerId. 
When I console.log searchResult I get a Connect, whereas when I do Graph, I get a DragDropContainer.

Here's SearchResult:
`
Connect{props: Object{result: Object{attributes: ...}, isSearchResult: true, name: 'searchtest'}, context: Object{store: Object{dispatch: ..., subscribe: ..., getState: ..., replaceReducer: ..., Symbol(Symbol.observable)_l.9xmp3zbp7a: ...}}, refs: Object{}, updater: Object{isMounted: function (publicInstance) { ... }, enqueueCallback: function (publicInstance, callback, callerName) { ... }, enqueueCallbackInternal: function (internalInstance, callback) { ... }, enqueueForceUpdate: function (publicInstance) { ... }, enqueueReplaceState: function (publicInstance, completeState) { ... }, enqueueSetState: function (publicInstance, partialState) { ... }, enqueueElementInternal: function (internalInstance, nextElement, nextContext) { ... }, validateCallback: function (callback, callerName) { ... }}, version: 12, store: Object{dispatch: function (action) { ... }, subscribe: function subscribe(listener) { ... }, getState: function getState() { ... }, replaceReducer: function replaceReducer(nextReducer) { ... }, Symbol(Symbol.observable)_l.9xmp3zbp7a: function observable() { ... }}, state: Object{storeState: Object{api: ..., diffs: ..., display: ..., search: ..., user: ..., workspace: ..., files: ..., system: ..., queries: ..., userworkspaces: ..., notifications: ...}}, dispatchProps: Object{}, stateProps: Object{workspacePermission: undefined}, mergedProps: Object{result: Object{attributes: ...}, isSearchResult: true, name: 'searchtest', workspacePermission: undefined}, haveOwnPropsChanged: false, hasStoreStateChanged: false, haveStatePropsBeenPrecalculated: false, statePropsPrecalculationError: null, renderedElement: Object{$$typeof: Symbol{_k: ...}, type: function DragDropContainer(props, context) { ... }, key: null, ref: null, props: Object{result: ..., isSearchResult: ..., name: ..., workspacePermission: ...}, _owner: {_currentElement: ..., _rootNodeID: ..., _compositeType: ..., _instance: ..., _hostParent: ..., _hostContainerInfo: ..., _updateBatchNumber: ..., _pendingElement: ..., _pendingStateQueue: ..., _pendingReplaceState: ..., _pendingForceUpdate: ..., _renderedNodeType: ..., _renderedComponent: ..., _context: ..., _mountOrder: ..., _topLevelWrapper: ..., _pendingCallbacks: ..., _calledComponentWillUnmount: ..., _warnedAboutRefsInRender: ..., _mountIndex: ..., _mountImage: ..., _debugID: ...}, _store: Object{}}, finalMapDispatchToProps: function (dispatch) { ... }, finalMapStateToProps: function (state) { ... }, _reactInternalInstance: {_currentElement: Object{$$typeof: ..., type: ..., key: ..., ref: ..., props: ..., _owner: ..., _store: ...}, _rootNodeID: 0, _compositeType: 0, _instance: Connect{props: ..., context: ..., refs: ..., updater: ..., version: ..., store: ..., state: ..., dispatchProps: ..., stateProps: ..., mergedProps: ..., haveOwnPropsChanged: ..., hasStoreStateChanged: ..., haveStatePropsBeenPrecalculated: ..., statePropsPrecalculationError: ..., renderedElement: ..., finalMapDispatchToProps: ..., finalMapStateToProps: ..., _reactInternalInstance: ..., doStatePropsDependOnOwnProps: ..., doDispatchPropsDependOnOwnProps: ..., unsubscribe: ...}, _hostParent: null, _hostContainerInfo: Object{_topLevelWrapper: ..., _idCounter: ..., _ownerDocument: ..., _node: ..., _tag: ..., _namespaceURI: ..., _ancestorInfo: ...}, _updateBatchNumber: null, _pendingElement: null, _pendingStateQueue: null, _pendingReplaceState: false, _pendingForceUpdate: false, _renderedNodeType: 1, _renderedComponent: {_currentElement: ..., _rootNodeID: ..., _compositeType: ..., _instance: ..., _hostParent: ..., _hostContainerInfo: ..., _updateBatchNumber: ..., _pendingElement: ..., _pendingStateQueue: ..., _pendingReplaceState: ..., _pendingForceUpdate: ..., _renderedNodeType: ..., _renderedComponent: ..., _context: ..., _mountOrder: ..., _topLevelWrapper: ..., _pendingCallbacks: ..., _calledComponentWillUnmount: ..., _warnedAboutRefsInRender: ..., _mountIndex: ..., _mountImage: ..., _debugID: ...}, _context: Object{dragDropManager: ..., store: ...}, _mountOrder: 12, _topLevelWrapper: null, _pendingCallbacks: null, _calledComponentWillUnmount: false, _warnedAboutRefsInRender: false, _mountIndex: 0, _mountImage: null, _debugID: 15}, doStatePropsDependOnOwnProps: false, doDispatchPropsDependOnOwnProps: false, unsubscribe: function unsubscribe() { ... }}`
`

**Comment by kesne** [comment]
I would first try to simplify the test down to just the search result test and see what happens when doing that:

```js
it('can be tested with the testing backend', () => {
  // Render with the test context that uses the test backend
  const vertex = {'attributes': []};
  const SearchResultContext = wrapInTestContext(SearchResult);
  const searchRoot = TestUtils.renderIntoDocument(<SearchResultContext result={vertex} isSearchResult={true} name="searchtest"/>);
  const backend = searchRoot.getManager().getBackend();
  const searchResult = TestUtils.findRenderedComponentWithType(searchRoot, SearchResult);
  console.log(searchResult.getHandlerId());
});
```
