### ISSUE TITLE
how to write multiple drop target with es6?

### ISSUE THREAD

**Issue by the1sky** [react-dnd/react-dnd#565]

**Comment by anilreddykatta** [comment]
@the1sky Any particular use cases? 
```
import { compose } from 'ramda'
compose(
 DropTarget('CARD', spec, collect),
 DropTarget('STACK', spec, collect),
)
```
I guess this should work without issues

**Comment by towfiqi** [comment]
You can pass in an array as types parameter in DropTarget, try this: 

`DropTarget(['CARD', 'SONG'], spec, collect),`

**Comment by KhgDwb** [comment]
It didn"t work for me when passing a table of strings as the first argument : Uncaught Invariant Violation: Expected "type" provided as the first argument to DragSource to be a string, or a function that returns a string given the current props. Instead, received form-elements,table-elements
