### ISSUE TITLE
Documentation mistake

### ISSUE THREAD

**Issue by rosko** [react-dnd/react-dnd#566]
There is a mistake on the page http://gaearon.github.io/react-dnd/docs-overview.html, part "Connectors"

> In fact, a connector is passed as a **second** argument to the collecting function

and after that there is an example:

``` javascript
function collect(connect, monitor) {
```

Connector here is the first argument. The same with others examples in the documentation.

**Comment by theirishpenguin** [comment]
This threw me as well when I first read the docs. Simple PR added to fix.
