### ISSUE TITLE
Do react-dnd support working with babel presets 'react-hmr'?

### ISSUE THREAD

**Issue by sheweichun** [react-dnd/react-dnd#567]
I use babel-preset-react-hmre in react project,when I change something in DropTarget'spec or DragSource'spec,it will trigger hot module replace,but after that,it didn't work,code like beblow:
```javascript
const chessSquareTarget = {
    ...
    drop(props,monitor,component){
       console.log('hello')
    }
}
...
export default DropTarget(Types.CHESSPIECE, chessSquareTarget, collect)(ChessSquare);
```
If I change `console.log('hello')` to `console.log('hello1')`,after HMR,when I drop a dargSource,it will still output 'hello',not 'hello1'

**Comment by alvaro-cuesta** [comment]
Works for me with React Hot Loader 3, but my CustomDragLayer stops working as soon as HMR happens.
