### ISSUE TITLE
react dnd with ag-grid

### ISSUE THREAD

**Issue by Miteshdv** [react-dnd/react-dnd#569]
Hi ,
 I need to create a grid with drag and drop reorder feature.
Can I use react dnd with ag-grid ? any example you can provide me please

Thanks

**Comment by jithinolickal** [comment]
Hi Mitesh, 
I know it's not okay to ask, but did you find any solution for the above? React Dnd with ag-grid.
I too want to drag items from ag-grid and drop in other container.

Thanks and Regards,
Jithin

**Comment by vladbicu** [comment]
Hello,

I'm also interested in a solution. I have an application where I want to drag a custom column header in other container. 

I created a drag source inside the custom header and I get `Expected drag drop context` error.

Thanks,
Vlad

**Comment by jithinolickal** [comment]
@vladbicu, you able to create drag source inside a column name? Do you have that code sample in any online editors?
