### ISSUE TITLE
Simple Card example no longer works in React 15

### ISSUE THREAD

**Issue by ncphillips** [react-dnd/react-dnd#571]
I implemented the [simple card](https://github.com/gaearon/react-dnd/blob/master/examples/04%20Sortable/Simple/Card.js) example.

It worked for a while, but suddenly I've started having a very annoying error.

`TypeError: Cannot assign to read only property 'index' of object '#<Object>`

This is caused by here: https://github.com/gaearon/react-dnd/blob/master/examples/04%20Sortable/Simple/Card.js#L66

Is there a work around?

**Comment by joyt** [comment]
Removing the offending [`monitor.getItem().index = hoverIndex` line](https://github.com/gaearon/react-dnd/blob/master/examples/04%20Sortable/Simple/Card.js#L66) in the [Sortable Simple Card](http://gaearon.github.io/react-dnd/examples-sortable-simple.html) example causes thrashing (`moveCard` is called repeatedly and causes the items to switch back and forth).

**Comment by im-sven** [comment]
This issue can be caused by setting up your `beginDrag` function in your source not correctly. 

```
const mySource = {
  beginDrag(props) {
    return {
			id: props.id,
			index: props.index,
		};
  },
};
```

Hope this helps.

**Comment by larrybotha** [comment]
I had 
```js
...
  beginDrag(props) {
    return props;
  },
...
```
@im-sven's [suggestion](https://github.com/react-dnd/react-dnd/issues/571#issuecomment-278951626) resolved the issue.

**Comment by PaulBrunache** [comment]
to make the object not read only you can either use object.assign or ES6 spread operator like so 
```javascript
beginDrag(props) {
    return {...props}
  },
```
