### ISSUE TITLE
HOWTO: Detect drag cancellation?

### ISSUE THREAD

**Issue by inactivist** [react-dnd/react-dnd#572]
It's not obvious (to me) how to detect a cancelled drag action (as when the user presses the ESC key while dragging).   

The HTML5Backend simply calls `.endDrag()` on `dragend` event, with no event context.  

If detection is possible, are there any examples demonstrating techniques for detecting cancellation?

**Comment by knuterik91** [comment]
Have you checked out this example ? 
[http://gaearon.github.io/react-dnd/examples-sortable-cancel-on-drop-outside.html](http://gaearon.github.io/react-dnd/examples-sortable-cancel-on-drop-outside.html)

**Comment by sangmokh** [comment]
+1 on the issue. The framework does not provide a way to tell whether the user has dropped the item outside or has cancelled DnD operation by hitting the ESC key. In both cases,  monitor.getDropResult() in endDrag() returns null.
e.g. Chrome, Firefox and Sublime Text implement a different behavior on the two conditions.

**Comment by inactivist** [comment]
See also #600

**Comment by alexanderby** [comment]
It is a common practice, you can press ESC when dragging files in Windows, moving cards in Trello etc.

During Drag & Drop in Trello app:
1. If you hit Escape a card will return to it's initial position.
2. If you release mouse button a card will be dropped to the latest highlighted position.

So, normally you need to detect drag cancellation when user starts D&D, don't remember the initial position and wants to prevent data modification. Currently you there is no way in `react-dnd` to separate drag end outside a target and drag end when hitting escape.
