### ISSUE TITLE
beginDrag not called when holding down shift key

### ISSUE THREAD

**Issue by edgesoft** [react-dnd/react-dnd#573]
I'm trying to make drag and drop work by enabling multiple items to be dragged when holding down shift key. The beginDrag is never called when holding shift. Works without the shift key.

**Comment by WiaczeslawP** [comment]
Same problem. @gaearon, is it possible to solve it?

**Comment by smiple** [comment]
Could this just be a Chrome bug? [Chrome bug 646339](https://bugs.chromium.org/p/chromium/issues/detail?id=646339)

**Comment by WiaczeslawP** [comment]
No, it works fine on w3school page https://www.w3schools.com/html/html5_draganddrop.asp
And there is also a bug with alt-key pressed, too
https://react-dnd.github.io/react-dnd/examples-drag-around-naive.html
