### ISSUE TITLE
React app freezes and crashes when dragging on Ultrawide monitor

### ISSUE THREAD

**Issue by duffbuster** [react-dnd/react-dnd#575]
I've got two people reporting the the dnd function freezes our react application when dragging on an ultrawide (2560x1080) monitor. I initially thought this could be a resolution issue, but the dragging works just fine on my 4k (normal aspect ratio) monitor. Has this issue been reported anywhere else? Is there an easy fix that I'm missing? Help me Obi-wan-@gaearon, you're my only hope...

**Comment by pietromaj** [comment]
The same problem is happening to me here! But just in chrome. Works on firefox.

**Comment by pietromaj** [comment]
Just for reference. I fixed this problem by removing the react tooltip that I was using inside the draggable component.

**Comment by ImmRanneft** [comment]
@gaearon same issue that @pietromaj had. Disabling react-tooltip makes it work fine.

**Comment by sevikon** [comment]
@ImmRanneft same issue - fixed when I removed react-tooltip from dragged element, thanks!

**Comment by kaiomagalhaes** [comment]
Thanks for these answers guys, but I need to have the react tooltip in my component, did anyone make it work with it?

**Comment by ImmRanneft** [comment]
@kaiomagalhaes yes, if you will use only one instance of react-tooltip somewhere outside of drag-n-drop context.
