### ISSUE TITLE
Drag Preview doesn't work when child props are rendered in component

### ISSUE THREAD

**Issue by duffbuster** [react-dnd/react-dnd#577]
I have a Card component that wraps some child elements. The whole card needs to be the drag preview, but it doesn't work with the children present.

```
return connectDragPreview(connectDragSource(connectDropTarget(
      <div
        {...this.props}
        className="Card"
        style={{
          ...this.props.style
        }}
      >
        {children} {/* Interior card elements */}
      </div>
)));
```
If I comment out `{children}`, the dragPreview shows normally. With the children rendered, I get the drag file icon (in Chrome), but no preview.

**Comment by duffbuster** [comment]
I've found the issue I was happening. Apparently this component doesn't play nice with React Tooltip. https://github.com/wwayne/react-tooltip

**Comment by lvwrence** [comment]
Ran into this too. @duffbuster did you find a way to work around this?

**Comment by Andruschenko** [comment]
It seems to be a general incompatibility between dragPreviews and tooltips.

We use material-ui and their Tooltip implementation https://github.com/callemall/material-ui/blob/master/src/internal/Tooltip.js caused weird/disappearing dragPreview behavior..

Any solutions to this issue are very welcome!

**Comment by theTechie** [comment]
You will have to use the DragLayer; then you can render the entire component as a preview

**Comment by Andruschenko** [comment]
@theTechie Thanks, I'll give it a try soon! Could you in the meantime rename the issue to better reflect the real issue here, i.e. "dragPreview behaves weird with Tooltip inside component" or similar, so that it's easier to find?!

**Comment by theTechie** [comment]
@darthtrevino - could you help us rename this issue to "DragPreview behaves weird for components with child elements"

**Comment by Andruschenko** [comment]
@theTechie the name should be "DragPreview behaves weird for components which use tooltips".

Tooltips are the main issue, not child components as such, right?!

**Comment by TomMahle** [comment]
Also seeing this issue with Material-UI tooltips. removing the tooltip did resolve it, but it would be nice to not have to remove them.

Thank you @Andruschenko for pointing out that tooltips cause this issue!

**Comment by forrestbice** [comment]
Any progress on this issue? @pelhage and I are still experiencing this issue; really hoping we don't need to fully remove the tooltip...

**Comment by grimunit** [comment]
This also became a problem with material-ui's ripple effect on buttons. If you wait to drag until the ripple has started it behaves very strangely. Had to not use a material-ui buttons to avoid the problem.

**Comment by JEkedorff** [comment]
I confirm what @grimunit stated here above, the ripple effect on Material UI buttons is resulting in over-sized and/or offset previews. Adding prop disableRipple={true} should fix it though.
