### ISSUE TITLE
Is it possible to set custom threshold before actual dragging begins?

### ISSUE THREAD

**Issue by alyrik** [react-dnd/react-dnd#580]
I want dragging to start only when cursor moved 20px after mouseDown. Is it possible in any way?

**Comment by jan4984** [comment]
👍 I want dragging to start only cursor down and hold 400ms.

**Comment by JoaoMosmann** [comment]
With the current API, it's not possible.  

The code responsible for managing the drag and drop is the backend [gaearon/react-dnd-html5-backend](https://github.com/gaearon/react-dnd-html5-backend)

You could write your own, implementing the features you require.
