### ISSUE TITLE
Typescript 2.0 Support

### ISSUE THREAD

**Issue by amygl** [react-dnd/react-dnd#581]
After upgrading to typescript 2.0 builds failed with the following error:
error TS2600: JSX element attributes type '(Column<any, any> & { children?: ReactNode; }) | (Column<any, any> & { chil...' may not be a union type.

Someone else hit this too:
http://stackoverflow.com/questions/40269415/typescript-2-0-with-react-dnd-gives-error-jsx-element-attributes-may-not-be-a-u

**Comment by darthtrevino** [comment]
The types aren't defined here, I would check out the DefinitelyTyped project and look at the typings they are providing. At some point, it would make sense to manage the types here.
