### ISSUE TITLE
ERROR in ./site/components/CodeBlock.js

### ISSUE THREAD

**Issue by abnerlinan** [react-dnd/react-dnd#587]
ERROR in ./site/components/CodeBlock.js
Module not found: Error: Cannot resolve module 'react/lib/ReactUpdates' in /Users/ksana/Workspace/react-dnd/site/components
 @ ./site/components/CodeBlock.js 19:28-61

npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/Cellar/node5/5.11.0/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v5.11.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! react-dnd@2.1.4 start: `./scripts/startSiteDevServer.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-dnd@2.1.4 start script './scripts/startSiteDevServer.sh'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-dnd package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./scripts/startSiteDevServer.sh
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-dnd
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-dnd
npm ERR! There is likely additional logging output above.

**Comment by pupadupa** [comment]
I comment these two lines in  ./site/components/CodeBlock.js

`//import ReactUpdates from 'react/lib/ReactUpdates';`
and
`//ReactUpdates.flushBatchedUpdates();`

After that `npm install && npm start` worked
