### ISSUE TITLE
Have an example in the docs that illustrates dragging multiple elements.

### ISSUE THREAD

**Issue by nikhilbaradwaj** [react-dnd/react-dnd#590]
While the thread https://github.com/gaearon/react-dnd/issues/14 started by @gaearon might not be implemented anytime soon, I feel like a workaround approach can be illustrated in the docs if someone wants to use react-dnd for dragging multiple elements.

**Comment by nikhilbaradwaj** [comment]
If this is something worth doing, I would love to write the example and submit a PR.

**Comment by ishantoberoi** [comment]
@nikhilbaradwaj If you have a working example of selecting multiple elements for drag n drop, can you share it?

**Comment by dangreenisrael** [comment]
@nikhilbaradwaj That would be amazing

**Comment by GreGGus** [comment]
@nikhilbaradawj Please mate <3

**Comment by GreGGus** [comment]
@nikhilbaradwaj

**Comment by pavel06081991** [comment]
Yeah, we would appreciate it

**Comment by nikhilbaradwaj** [comment]
@pavel06081991 @dangreenisrael @ishantoberoi @GreGGus

Sorry for the late response. The code example for multi-select drag and drop is here - https://github.com/nikhilbaradwaj/ReactMultiDnD  

You can test the app here - https://nikhilbaradwaj.github.io/ReactMultiDnD/

**Comment by ishantoberoi** [comment]
@nikhilbaradwaj  Thank You.

**Comment by melvynhills** [comment]
If anyone's interested, I implemented a multiple drag / grid view: https://codesandbox.io/s/rwrly0yxnp.
You can use cmd/ctrl and shift keys to select multiple items, then drag them around the grid and insert them anywhere.

*This is still a demo, but I might package it in a component later.*

**Comment by Raduuu** [comment]
> If anyone's interested, I implemented a multiple drag / grid view: https://codesandbox.io/s/9j897k0mwy.
> You can use cmd/ctrl and shift keys to select multiple items, then drag them around the grid and insert them anywhere.
> 
> _This is still a demo, but I might package it in a component later._

Any progress on this? :D

**Comment by znwang25** [comment]
In case anyone is looking for an example using the new API. Here is my [current solution](https://github.com/znwang25/react-dnd-multiple-selection) with `react-dnd` based on @melvynhills's codesandbox. I rewrote the code using new APIs and react hooks.

You can try the live demo [here](https://www.zenan-wang.com/react-dnd-multiple-selection/). 

I also implemented @nikhilbaradwaj's solution using new APIs and react hooks, you can check out the [codesandbox here](https://codesandbox.io/s/react-dnd-multi-select-list-8oqrl).

**Comment by hanalice** [comment]
@melvynhills you are so great!
