### ISSUE TITLE
Which files need to be host?

### ISSUE THREAD

**Issue by kennynaoh** [react-dnd/react-dnd#599]
Hello @gaearon , I am the member of cdnjs project. We want to host this library. There is a question want to ask. Could you help me mention the files you want to host in some of old versions? I found that the main file `ReactDnD.min.js` is under `dist/` on npm, but it doesn't exist in version `v0.0.0` ~ `v0.1.5`, `v1.0.0` ~ `v1.1.2`. Thanks for your help!

https://github.com/cdnjs/cdnjs/issues/9320

**Comment by vsiao** [comment]
It looks like @darthtrevino is the primary maintainer now?
