### ISSUE TITLE
How to cancel and stop dragging upon escape key?

### ISSUE THREAD

**Issue by oyshan** [react-dnd/react-dnd#600]
I have a list which is pretty similar to the "sortable -> cancel on drop outside" example in your documentation (https://gaearon.github.io/react-dnd/examples-sortable-cancel-on-drop-outside.html)

I want to be able to stop the dragging altogether upon hitting the Escape key. Where is it sensible to add (and remove) the keydown event listener? And how can I cancel/stop the actual dragging?

I was able to add an escape key listener in the beginDrag-method, and call the endDrag-method from it, returning  the dragged item to its initial position. But since the actual dragging is not cancelled/stopped until I release the mouse button, I can continue to drag the item around.
So I want to trigger a "drop"-like event upon hitting Escape, so that the dragging is cancelled/stopped completely. Is there a recommended way of approaching this?

**Comment by akuji1993** [comment]
Are you sure that this isn't more of a mistake design-wise? Why do you need to cancel on ESC?

**Comment by oyshan** [comment]
@akuji1993 I'm definitely not sure about that;) 

But I've now figured out that HTML5 Drag and Drop supports it (it works in the example I pointed to), so it's actually not an issue with react-dnd (sorry about that), but the backend I use. I'm not using the officially supported HTML5 backend, but I'm using react-dnd-touch-backend (https://github.com/yahoo/react-dnd-touch-backend) to support touch devices, and this backend doesn't respond to the escape key.

So, sorry about that! Any tips on how to make it work with react-dnd-touch-backend would be greatly appreciated though ;)

**Comment by akuji1993** [comment]
Thing is, how I understand your issue, that there's (imo) no real good reason to NEED the escape key at all. And touch backends should not support this, as there is no ESC key to press^^ 

Could you maybe describe why you specifically need the ESC key interaction? Maybe I can point you in the right direction.

**Comment by oyshan** [comment]
I fully agree with you, but it's my clients who want this feature, and I can't seem to convince them otherwise.

The reason for why we "need" ESC key interaction on touch backend is because we're not really using touch devices. We embed a chromium browser in .NET, and this browser, for some reason, is touch enabled..don't ask me why. So the users are using devices with keyboards, and they want to be able to cancel by hitting ESC..

**Comment by akuji1993** [comment]
Alright, that's a reasonable explanation for needing that. Hm, not sure that the touch frameworks are able to do something like this. My approach would be to swap the touch framework for something more fitting that supports normal keyboard interaction.

**Comment by oyshan** [comment]
I was able to add a keydown event listener on the touch-backend framework. This will cancel the drag if the Escape key was pushed. My pull request is here, if you're interested: https://github.com/yahoo/react-dnd-touch-backend/pull/48

**Comment by alexanderby** [comment]
It is a common practice, you can press ESC when dragging files in Windows, moving cards in Trello etc.

During Drag & Drop in Trello app:
1. If you hit Escape a card will return to it's initial position.
2. If you release mouse button a card will be dropped to the latest highlighted position.

So, normally you need to detect drag cancellation when user starts D&D, don't remember the initial position and wants to prevent data modification. Currently you there is no way in `react-dnd` to separate drag end outside a target and drag end when hitting escape.
