### ISSUE TITLE
Animate target while dragging over

### ISSUE THREAD

**Issue by hillarycohen** [react-dnd/react-dnd#607]
Hi there :)

I'm new to React - and React-DnD itself - and picked this lib to make an app for a school work.

I followed the [sortable simple](http://gaearon.github.io/react-dnd/examples-sortable-simple.html) example, and basically copy/pasted/adapted for my needs, and it's working fine. However, I'd like to make some animations when the drag hits the target, like creating a smoother movement. I found a comment [here](https://github.com/gaearon/react-dnd/issues/384#issuecomment-185264824), that illustrate what I'm trying to do:

![eee3d763fe-d548-11e5-8759-9d51f382181b](https://cloud.githubusercontent.com/assets/24801135/21706378/d2057198-d3ad-11e6-8d22-a3ee47ec0e57.gif)

Is there any example outside on how can I make such animations? Most similar I could found was [this one](http://gaearon.github.io/react-dnd/examples-drag-around-custom-drag-layer.html), but couldn't make much of it. If there's nothing, could someone guide me on which methods should I work on, to make it happen? Any help very appreciated. 

Thanks for such a cool lib!

**Comment by onsta** [comment]
I am using react-motion library and my code looks similar to this
```

    const springSetting2 = { stiffness: 130, damping: 18 };
        const motionStyle = {
          translateX: spring(
            this.width,
            springSetting2
          ),
          translateY: spring(
            this.height
            springSetting2
          )
        };
        return (
          <Motion key={`KEY_${name}`} style={motionStyle}>
            {({ translateX, translateY }) =>
              <div
                style={{
                  position: "absolute",
                  transform: `translate(${translateX}px, ${translateY}px)`
                }}
              >
                <AnimatedComponent  />
              </div>}
          </Motion>
```

**Comment by hungle88** [comment]
Could you please explain what does `this` stand for in the `motionStyle` constant? What would `this.width` would return?

**Comment by hillarycohen** [comment]
I wonder if there's a way to animate it without using external libraries?

**Comment by hugetiny** [comment]
@hillarycohen 'react-beautiful-dnd' can solve your problem
