### ISSUE TITLE
Scroll disabled for long lists

### ISSUE THREAD

**Issue by AlexanderKozhevin** [react-dnd/react-dnd#608]
So I checked out an example:
http://gaearon.github.io/react-dnd/examples-sortable-stress.html
It contains a long list. What if I have an item at the end of list and wanna drag it to the beginning of it. 
I picked the item, but I can't scroll the page at the same time (at least on mac).
Is there easy workaround or some hack to solve this problem?

**Comment by craigjackson** [comment]
The scroll is not working on drag because of the fixed header at the top of the page. You can drag from the top of the list to the bottom of the list. Also, if you deleted the header element on that example, you could drag from the bottom of the list to the top of the list.

**Comment by yankopetrov** [comment]
I have fixed position div container with `overflow: auto` and when drag the list do not scroll as the `examples-sortable-stress` above. Do i miss something?
