### ISSUE TITLE
'dnd-core' and 'disposables' '.babelrc' file incompatibility issue with babel 6

### ISSUE THREAD

**Issue by brunoprela** [react-dnd/react-dnd#612]
I was having an issue using webpack with babel 6 in a react/redux project and using react-dnd. The only solution I had was to actually go into node_modules and delete the '.babelrc' file from both 'dnd-core' and 'disposables'. Webpack now works and the drag and drop components function as desired but this issue took quite a while to realize where it was going wrong because it was in the node_modules.

**Comment by amccloud** [comment]
@darthtrevino I think this is still an issue.

**Comment by nanjixiong218** [comment]
please update this `.npmignore` of the project of disposables at the same time.

**Comment by gaearon** [comment]
The real issue is you’re running Babel on `node_modules`. You shouldn’t try to do that: it can cause other issues and is not always safe.

**Comment by gaearon** [comment]
I published `disposables@1.0.2` to mitigate the problem on our end though.
