### ISSUE TITLE
Update Gitter Chatroom with Org-Specific one

### ISSUE THREAD

**Issue by darthtrevino** [react-dnd/react-dnd#627]
We may need a transition period, or it may make sense to just leave the chat as-is at @gaearon 's gitter site.

**Comment by gaearon** [comment]
I'm not using Gitter, so happy with whatever you folks prefer.

**Comment by darthtrevino** [comment]
Cool, if that's the case I'll ping the guys who run the reactiflux discord server and see if we can set up a room there
