### ISSUE TITLE
Creating my own backend

### ISSUE THREAD

**Issue by alexreardon** [react-dnd/react-dnd#633]
Hi there!

I am looking to create my own backend but I am a little lost as to how to do this. I am not sure what the contract of a backend is. I am trying to piece it together from the implementation of the html5 and touch backends but it is a little hard going.

Is there any place that explains what the contract is for a custom backend?

Cheers

**Comment by darthtrevino** [comment]
There's not much in the way of documentation there. Reverse engineering the HTML5 backend and touch backend is probably your best bet.

**Comment by alexreardon** [comment]
Ouch. Okay
