### ISSUE TITLE
Access the dataTransfer on drop event

### ISSUE THREAD

**Issue by darren128** [react-dnd/react-dnd#635]
One of the quirks regarding our use case of React DnD is that we have some markup that is not handled by react, but instead uses javascript for creating / manipulating / removing from the DOM. In one case, we want to hook into the HTML drag drop api by adding a drop event listener on a node, but I noticed that React DnD does not attach any information to the event.dataTransfer during the onDrag logic. Is there any way to add data to that object via connectToDragSource so that it's available on the dataTransfer object on the native event handler?

Thanks for any help!

**Comment by Jeffy2012** [comment]
I also want to get event object

**Comment by Colmea** [comment]
I'm also a little bit confused on how html5 backend store data from drag object. It seems that dataTransfer from html5 drag&drop api is not used at all (except an empty object for Firefox, but it's only there to avoid a bug).

I'd though (instinctively) that the object returned by beginDrag() would be stored in a dataTransfer item.
This allows interactions between react apps and "vanilla html5" ones (we actually have the same use case than @darren128: we have to deal with non-react elements from outside the app).

Is there a reason this dataTransfer is empty ? What's your suggestion to populate this dataTransfer with object returned by beginDrag() ?

**Comment by quentez** [comment]
This would be great if available.

**Comment by sorawee** [comment]
For me, I want to access the cursor location in CodeMirror on drop event. I believe that if I have the event, I can use `e.pageX` and `e.pageY` to accomplish that, but without the event object, I'm not sure how I could do that.

**Comment by aebabis** [comment]
I'd also like to see this feature. I have a need to drag to a drop target that's not using `react-dnd`

**Comment by ravernkoh** [comment]
Just ran into a need for this use-case. I need to support:

* Drag `react-dnd` drag source to native drop target (doesn't work)
* Drag native drag source (`draggable="true"`) to `react-dnd` drop target (works)
* Drag both `react-dnd` and native drag source to native apps (e.g. Microsoft Word/Pages) (works, but no support for adding data in `dataTransfer`)
* Drag `react-dnd` drag source between windows (doesn't work)
