### ISSUE TITLE
Square effect when dragging in Chrome

### ISSUE THREAD

**Issue by maZahaca** [react-dnd/react-dnd#637]
Hello guys,

We used your example http://react-dnd.github.io/react-dnd/examples-sortable-simple.html to implement our solution for dnd.
We experienced an issue with card, which inside contains another DOM element with rounded angles.

![dragging](https://s24.postimg.org/732v072cl/i42_pimgpsh_fullsize_distr.png)

Can you see this square around the circle, it appears when you dragging element in Chrome.
Can you navigate us, how we can solve this issue?

Thanks

**Comment by darthtrevino** [comment]
Are you using a custom drag layer? https://react-dnd.github.io/react-dnd/docs-drag-layer.html

**Comment by maZahaca** [comment]
No, will it help?
