### ISSUE TITLE
Looking for Interested Maintainers

### ISSUE THREAD

**Issue by darthtrevino** [react-dnd/react-dnd#638]
Dan has stepped away from maintaining react-dnd, and has left it to the community at large. I've set up this Github organization, and I've been working on modernizing the code-base a bit, but this is not something I'm interested in doing alone. I'd like for this to be a community effort, and reap the benefits of having things like code reviews. Let me know if you're interested in helping to maintain these libraries.

**Comment by john-ziegler** [comment]
I'm happy to lend a hand - we've benefited a ton from this library at MSKCC. I'd love to learn more about the implementation and help out wherever possible

**Comment by darthtrevino** [comment]
Sweet, thanks @john-ziegler. I'll add you to the group

**Comment by theTechie** [comment]
@darthtrevino i have been working with this since sometime now. I will be happy to help in whatever way possible.

**Comment by DetweilerRyan** [comment]
@darthtrevino At [Retrium](https://www.retrium.com/demo), We have been using react-dnd in production for some time now and it has become core to our front end tech stack.  React-dnd is reliable and its abstractions are spot on!  The developers at Retrium would like to do our part to ensure that react-dnd continues to be reliable and modern.

**Comment by cezaraugusto** [comment]
hey there, we use React-DnD at Brave [browser-laptop](https://github.com/brave/browser-laptop/) for new tab page, and long term we plan to replace most of our DnD with this library. I'm very interested in improving this lib and ensure it's always at its best, so more than happy to assist as well 👍 .

**Comment by rcdexta** [comment]
@darthtrevino Have been using react-dnd extensively in many projects including a oss library that I built recently: [react-trello](https://github.com/rcdexta/react-trello). Would be more than happy to learn more and help with contributions..

**Comment by anilreddykatta** [comment]
@darthtrevino Can you also add me to as contributors. I have been using react-dnd in my projects, want to contribute to this awesome project.

**Comment by BenChand** [comment]
@darthtrevino Not sure if you're looking for more people but react-dnd has been a fantastic help in my dissertation project and I'd love to help where possible

**Comment by darkowic** [comment]
Hello there! Is anyone working on the library today? There are many open issues and pull requests.
