### ISSUE TITLE
looking for a boilerplate project to run the latest dustbin example

### ISSUE THREAD

**Issue by azadbolour** [react-dnd/react-dnd#640]
I am trying to start a new react dnd project that uses as its starting point the dustbin single target example.

I tried to use the react-hot-boilerplate as my starting point and copy the .js source files of dustbin example to its src directory and then add an appropriate index.js file to render the container (plus a few other minor tweaks to the package.json and .babelrc files to eliminate some initial errors).

But I am getting the following error in the browser when I try to access the example:

Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. Check the render method of `Container`.

Since I just copied the source of Container from the examples directory, I am not sure what to make of this error. I also tried googling for the error, and looked at several hits, without success.

Is there documentation on how to build and run such an example independently of the rest of the react dnd source?

The react-hot-boilerplate README seems to discourage its use. But as a  beginner in this area, I am not sure how to proceed to get a consistent set of boilerplate files to run the dustbin example stand-alone.

Thanks in advance for your help.

Azad

**Comment by rparjun** [comment]
@azadbolour  i can take a look into it if you can share the code.

**Comment by azadbolour** [comment]
Thanks so much for offering to help. I put the code on the github repository:

https://github.com/azadbolour/issues/

under the folder: react-dnd-boilerplate. See the README.md file in that folder for details.

Thanks again.

Azad

**Comment by matttk** [comment]
@azadbolour did you ever find a solution? I have the exact error as you and am wondering if I have a similar problem. I can't find anybody talking about this issue...
