### ISSUE TITLE
[2.2.0] window is not defined on server-side rendering

### ISSUE THREAD

**Issue by GGAlanSmithee** [react-dnd/react-dnd#645]
Just updated to v2.2.0 and am now getting `window is not defined` when doing server-side rendering.

stack

```javascript
window is not defined
ReferenceError: window is not defined 
at HTML5Backend.get (/home/node/node_modules/react-dnd-html5-backend/lib/HTML5Backend.js:615:53) 
at HTML5Backend.setup (/home/node/node_modules/react-dnd-html5-backend/lib/HTML5Backend.js:71:22) 
at DragDropManager.handleRefCountChange (/home/node/node_modules/dnd-core/lib/DragDropManager.js:52:22) 
at Object.dispatch (/home/node/node_modules/redux/lib/createStore.js:186:19) 
at HandlerRegistry.addSource (/home/node/node_modules/dnd-core/lib/HandlerRegistry.js:104:18) 
at registerSource (/home/node/node_modules/react-dnd/lib/registerSource.js:9:27) 
at DragDropContainer.receiveType (/home/node/node_modules/react-dnd/lib/decorateHandler.js:146:32) 
at DragDropContainer.receiveProps (/home/node/node_modules/react-dnd/lib/decorateHandler.js:135:14) 
at new DragDropContainer (/home/node/node_modules/react-dnd/lib/decorateHandler.js:102:13) 
at /home/node/node_modules/react-dom/lib/ReactCompositeComponent.js:295:18
```

in the [realeases page](https://github.com/react-dnd/react-dnd/releases) I can see there were some updates which might affect ssr, namely

> Add DragContextProvider class, use updated dnd-core with support for injectable global context.

But the [docs]( http://react-dnd.github.io/react-dnd/) does not mention anything about it (as far as I can see), so not quite sure how to apply the new changes, if that's what's required for ssr to work.

**Comment by GGAlanSmithee** [comment]
Seems like I might have spoken too soon, because the error persists when I downgrade to earlier versions.

I really thought it was related to your latest realease because this was the first deploy I made since react-dnd was updated (not locked version in stage environment) and the stack trace pointed to it. Will investigate, sorry for the noise.

**Comment by GGAlanSmithee** [comment]
So, just saw the deprecation notice in https://github.com/react-dnd/react-dnd-html5-backend and realised the stack-trace is for that package (which is now a part of this package) *facepalm*. This is most def. related to this. Sorry again for the noise, closing.

**Comment by ninoperin** [comment]
Same problem on my side. Also investigating.

**Comment by GGAlanSmithee** [comment]
@ninoperin ok, then I guess it's better to re-open this until something is confirmed.

**Comment by darthtrevino** [comment]
@ninoperin @GGAlanSmithee The new DragContextProvider is optional, and it's only really necessary when you need to inject a window global that's different from what the browser provides.  It looks like previously when the setup was invoked, if `window` was not defined, then it would just abort. I haven't worked with SSR before, but I'm guessing this is how it should behave under SSR?

**Comment by darthtrevino** [comment]
I see, the previous version was using a `typeof window` to check to see if the window was valid. I'll have something up shortly.

**Comment by darthtrevino** [comment]
@GGAlanSmithee @ninoperin Can you try react-dnd-html5-backend@2.2.1?

**Comment by ninoperin** [comment]
Works. Thanks for that quick fix!

**Comment by GGAlanSmithee** [comment]
Yes, thank you very much @darthtrevino

**Comment by m4rk3r** [comment]
It looks like this issue has resurfaced in v7.0.0, perhaps: https://github.com/react-dnd/react-dnd/commit/572955bf3a6a572ad938ff90637731ede286ec22#diff-5177492c6e40a1abfcb33fc0dc4bc3c3R20
