### ISSUE TITLE
Funny preview when I have overlapping items.

### ISSUE THREAD

**Issue by AlexanderKozhevin** [react-dnd/react-dnd#649]
I got a strange behavior. 
So when I got two items close to each other, I got this weird effect. 
If they overlap, I got a preview of overlapped area as also, which is no cool.
How can I fix that? I guess, it's html5backend problem.  

![screen shot 2017-02-07 at 23 17 08](https://cloud.githubusercontent.com/assets/4464561/22709800/266b1dc6-ed8c-11e6-9f43-616b8de2d26f.png)

**Comment by darthtrevino** [comment]
I don't have any suggestions off-hand, but I'll gladly review a PR if you want to dig into this further.

**Comment by hawkrives** [comment]
I think it has to do with the default rendering the browser provides? You might need to write your own custom DragLayer: http://react-dnd.github.io/react-dnd/docs-drag-layer.html

Or, and I'm not sure about this, check if the element you're dragging has a white background, and try changing it to a transparent one.

**Comment by AlexanderKozhevin** [comment]
@hawkrives Ok, yea. I think drag layer is gonna be fine solution.
The background is already transparent if you talking about root element.
