### ISSUE TITLE
Can we make our Component as DropTarget ?

### ISSUE THREAD

**Issue by pbpraveen1988** [react-dnd/react-dnd#655]
Hello ,

I want to make my component as DropTarget where other components will be drag on.
Can you help me on this.

Note ; I am using Typescript,

Thank You

**Comment by darthtrevino** [comment]
https://react-dnd.github.io/react-dnd/docs-drop-target.html

**Comment by pbpraveen1988** [comment]
Hello @darthtrevino  ,
Thanks for the help , One more question , I was able to drag the component in Droptarget , now i want to make the dragged component as dropTarget at runtime , where other components will dragged on.

**Comment by abelkbil** [comment]
@pbpraveen1988 Did this work in typescript. For it is working in jsx but not in typescript. Can you please share your dorp method code. I dont get the component method in drop. https://github.com/react-dnd/react-dnd/issues/785#issuecomment-368897599

Thank you
