### ISSUE TITLE
Support native html5 dropEffect

### ISSUE THREAD

**Issue by hpurmann** [react-dnd/react-dnd#657]
Since this is a monorepo now, it probably makes sense to raise awareness of my issue here.

Please see https://github.com/react-dnd/react-dnd-html5-backend/issues/58

**Comment by darthtrevino** [comment]
@hpurmann Feel free to cut a PR on this, I'll give it a fair review. The documentation examples also act as a kind of test-bed for different kinds of scenarios. In your PR, could you include an example that does what you're trying to pull off?  Dnd-core is pretty well tested, the rest of the project is so-so, as much as possible, please try to write unit tests to capture your desired behavioral changes.
