### ISSUE TITLE
Unable to reference HTML5Backend in react-dnd 2.2.3 

### ISSUE THREAD

**Issue by charlesgreen** [react-dnd/react-dnd#658]
Unable to reference HTML5Backend in react-dnd 2.2.3

Previously I was using the following react-dnd* packages however, after they were merged with the react-dnd repo I am now receiving the following error. 

```
UNMET PEER DEPENDENCY react-dnd@2.0.2

# package.json
"react-dnd-html5-backend": "^2.0.0",
"react-dnd-test-backend": "^1.0.2",
"react-dnd": "~2.0.2",
```

I have updated my project and references to HTML5Backend and TestBackend to use react-dnd 2.2.3 however,  the HTML5Backend import statement is now throwing and error and is unassigned. 

I have searched the ReactDnD.js file in the node_module however, I cannot find a reference to HTML5Backend but I am able to find one for TestBackend. 

```
# HTML5Backend example
import { DragDropContext, HTML5Backend} from 'react-dnd';
class YourApp {
  /* ... */
}
export default DragDropContext(HTML5Backend)(YourApp);


# TestBackend Example
import { DragDropContext, TestBackend} from 'react-dnd';
```

Could you please tell me if this is an error or if I am going about this incorrectly?

**Comment by darthtrevino** [comment]
Try using all of those deps @2.2.3. The monorepo now has a single version for all of those libraries.

**Comment by charlesgreen** [comment]
@darthtrevino thank you for your quick reply. I misunderstood monorepo and through it included merging the different packages together rather than hosting multiple packages with a single version. Thanks for the clarification.
