### ISSUE TITLE
Dragging shows the entire list with Material UI

### ISSUE THREAD

**Issue by yanickrochon** [react-dnd/react-dnd#662]
I'm trying to integrate this using the `List` and `ListItem` of Material UI and, while dragging, the entire list is shown as dragged element. I have tried to follow to the best of my understanding the examples, and here is what I have 

```jsx
import React, { Component, PropTypes } from 'react';
import { Random } from 'meteor/random';
import LocalizedComponent from '/client/components/LocalizedComponent';
// MUI
import { List, ListItem } from 'material-ui/List';
// ---
import { DragDropContext, DragSource, DropTarget } from 'react-dnd';
import { findDOMNode } from 'react-dom';

import HTML5Backend from 'react-dnd-html5-backend';


const itemSource = {
  beginDrag(props) {
    return {
      id: props.id,
      index: props.index
    };
  },
};

const itemTarget = {
  hover(props, monitor, component) {
    const dragIndex = monitor.getItem().index;
    const hoverIndex = props.index;

    // Don't replace items with themselves
    if (dragIndex === hoverIndex) {
      return;
    }

    // Determine rectangle on screen
    const hoverBoundingRect = findDOMNode(component).getBoundingClientRect();

    // Get vertical middle
    const hoverMiddleY = (hoverBoundingRect.bottom - hoverBoundingRect.top) / 2;

    // Determine mouse position
    const clientOffset = monitor.getClientOffset();

    // Get pixels to the top
    const hoverClientY = clientOffset.y - hoverBoundingRect.top;

    // Only perform the move when the mouse has crossed half of the items height
    // When dragging downwards, only move when the cursor is below 50%
    // When dragging upwards, only move when the cursor is above 50%

    // Dragging downwards
    if (dragIndex < hoverIndex && hoverClientY < hoverMiddleY) {
      return;
    }

    // Dragging upwards
    if (dragIndex > hoverIndex && hoverClientY > hoverMiddleY) {
      return;
    }

    // Time to actually perform the action
    props.onMoveItem(dragIndex, hoverIndex);

    // Note: we're mutating the monitor item here!
    // Generally it's better to avoid mutations,
    // but it's good here for the sake of performance
    // to avoid expensive index searches.
    monitor.getItem().index = hoverIndex;
  },
};


class SortableListComponent extends Component {

  render() {
    const { children, onMoveItem } = this.props;
    let index = 0;

    return (
      <List>
        { React.Children.map(children, child => React.cloneElement(child, {
          id: Random.id(),
          index: index++,
          onMoveItem: onMoveItem
        })) }
      </List>
    );
  }
}

SortableListComponent.propTypes = {
  onMoveItem: PropTypes.func.isRequired
};


class SortableListItemComponent extends Component {

  render() {
    const {
      id,
      index,
      isDragging,
      connectDragSource,
      connectDropTarget,
      onMoveItem,
      ...other
    } = this.props;
    const opacity = 1; // isDragging ? 0 : 1;

    return connectDragSource(connectDropTarget(
      <div style={{ opacity }}>
        <ListItem { ...other } disabled={ isDragging } />
      </div>
    ));
  }
}
SortableListItemComponent.propTypes = {
  connectDragSource: PropTypes.func.isRequired,
  connectDropTarget: PropTypes.func.isRequired,
  id: PropTypes.any.isRequired,
  index: PropTypes.number.isRequired,
  isDragging: PropTypes.bool.isRequired,
  onMoveItem: PropTypes.func.isRequired,
};


export const SortableList = DragDropContext(HTML5Backend)(SortableListComponent);

export const SortableListItem = DropTarget('SortableListItem', itemTarget, connect => ({
  connectDropTarget: connect.dropTarget(),
}))(DragSource('SortableListItem', itemSource, (connect, monitor) => ({
  connectDragSource: connect.dragSource(),
  isDragging: monitor.isDragging(),
}))(SortableListItemComponent));
```

What am I doing wrong?

**Comment by thebetterjort** [comment]
Looks like a Materialize css issue

**Comment by yanickrochon** [comment]
@thebetterjort not Materialize, but Material UI. The two frameworks are quite different. Also, how can it be Material UI's fault? The resulting HTML are composed of pretty much only DIVs and the styling is all inline?

**Comment by scrambled2k3** [comment]
@yanickrochon, did you figure out what was causing this?  I am seeing this happen in my project as well.

**Comment by yanickrochon** [comment]
@scrambled2k3 unfortunately, no. Since this is an Ethernet app, and the feature is only being used by a handful of users (thus far), I simply told my users about the flaw and to simply ignore it. I would assume that it is either a fault of the browser, or how Material UI style the components. And since it "works" despite the entire UI artifact... I wish I'd have time to create a simple mock-up to reproduce this, and help debug, but I'm alone managing an entire warehouse + HQ and am overflowed with supporting other projects and other responsibilities already :smile:

**Comment by scrambled2k3** [comment]
No worries, I may have just figured out a workaround for the issue.

If I set the ListItem to 'disabled', it seems to work correctly.  However, this means I have to move my 'onTouchTap' functionality to a context menu on that list item....or just not have the fancy ripple effect when someone clicks on it  😄 Hopefully that will help you as well.

Not sure exactly what (within MUI) causes this behavior....but that might be a project for another day.

**Comment by yanickrochon** [comment]
I have figured a workaround! It does not explain what causes this, but it actually works. I figured that there must be a problem with this part :

```
return connectDragSource(connectDropTarget(
  <div style={{ opacity }}>
    <ListItem { ...other } disabled={ isDragging } />
    </div>
  ));
```

So I changed it to 

```
return connectDropTarget(
  <div style={ listItemStyle }>
    <ListItem
      leftIcon={ connectDragSource(<div><ActionSwapVert /></div>) }
      disabled={ isDragging } { ...other }
    />
  </div>
);
```

and it surely works as expected. It seems that the drag source cannot also be the drop target. I'd like to know if this solves everyone's problem as it does to me?

**Comment by dedan** [comment]
I have the same problem. The `disabled` workaround works, but I'm not happy with not understanding the solution. Does anybody have an explanation?

**Comment by maksimkurb** [comment]
I have the same issue with ButtonBase with ripple. If I disable a ripple, all works perfectly. When a ripple is created, ReactDND copying an element with invisible part of a ripple (IMHO), so nearby elements are also seems like being dragged

_without ripple:_
![chrome_2018-10-11_21-00-29](https://user-images.githubusercontent.com/1351924/46821293-4c624880-cd99-11e8-82ff-6123829b2430.png)

_with ripple:_
![chrome_2018-10-11_21-00-55](https://user-images.githubusercontent.com/1351924/46821292-4c624880-cd99-11e8-97eb-3edf58265e40.png)

.
