### ISSUE TITLE
Minor breaking change when upgrading to 2.2.3

### ISSUE THREAD

**Issue by mockdeep** [react-dnd/react-dnd#665]
I don't know if this needs to be documented somewhere, but when I upgraded from `2.0.1` to `2.2.3`, I ran into a breaking change in my tests when trying to call a method on my wrapped react component. I'm using `enzyme` to render in my tests, and ended up needing to change:

```js
wrapper.instance().refs.child.updateTimeframes(input);
```

to:

```js
wrapper.instance().child.updateTimeframes(input);
```

Not a big deal, just wanted to throw it out there as something to be aware of. Feel free to close this issue if deemed unimportant. I can also provide more context if useful.

**Comment by darthtrevino** [comment]
The reference mechanism in React changed at some point, I think with v15, and we're using the newer ref mechanism. If there's misleading documentation, we'd welcome a PR to address it.
