### ISSUE TITLE
Errored while running command 'yarn' with arguments '' in 'dnd-core'

### ISSUE THREAD

**Issue by phping1** [react-dnd/react-dnd#669]
hi:
1. clone git clone https://github.com/react-dnd/react-dnd.git
2. cd react-dnd
3. when npm install ,there is error:
Errored while running command 'yarn' with arguments '' in 'dnd-core'
Errored while running ExecCommand.execute
Command exited with status 1: yarn
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
......
......

The reason for this error is version?

**Comment by darthtrevino** [comment]
We're using yarn now. `yarn install`

**Comment by phping1** [comment]
thk you!

**Comment by youngwind** [comment]
The REAME.md in folder example is out of date.  @darthtrevino 

> To run them locally, clone the repo, and run `npm install && npm start`.
