### ISSUE TITLE
Make gh-page/docs locale ready

### ISSUE THREAD

**Issue by cezaraugusto** [react-dnd/react-dnd#679]
I think making RDND docs localized would help not only spreading the word but making it more accessible for non-English speakers.

There's a PR #676 addressing l10n for Chinese and I'm sure there are other people willing to translate into their own language. Making it's in on our own repo will make maintenance/contributions easier.

There's a library for that https://github.com/l20n/l20n.js/ and if we accept going this way I can help implementing. 

/cc @darthtrevino @DetweilerRyan @gaearon @john-ziegler @kesne @theTechie

**Comment by theTechie** [comment]
It's definitely a good idea to add localization support for docs. Anyone of you interested in taking this forward? @darthtrevino @john-ziegler @kesne @DetweilerRyan 

I glanced at https://github.com/l20n/l20n.js/, but seems complicated to use. Have you used this before? @cezaraugusto  

I also looked into alternative solutions about doing this and found https://github.com/untra/polyglot. This would also require us to convert our gh-pages to use Jekyll.
This seems like a simple solution where we can maintain separate docs per language and use Jekyll to redirect to appropriate ones based on locale. (But, it might be tricky to maintain different versions and ensuring they are in sync when we update our docs; we will have to think about the workflow for updating across languages)

**Comment by darthtrevino** [comment]
I'd prefer an approach like l20n over jekyll, it seems like it would probably be less intrusive to the existing structure.

**Comment by ChenCyl** [comment]
@darthtrevino Is there any way to contribute localization now?

**Comment by darthtrevino** [comment]
We still need a good approach for this. It's not something I've dealt with before. Any suggestions?
