### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by theTechie** [react-dnd/react-dnd#680]
@react-dnd/gatekeepers - Should we start discussing on the road ahead?

- Review and close issues which are just `how-to / help-me` types and prioritize on the ones which really needs to be fixed
- Look into the PR's
- Any feature improvements planned we want to take up
- Also, an ongoing discussion about adding localization support for docs #679

**Comment by darthtrevino** [comment]
Sure, maybe sometime in the next week we can have a discussion on Discord. We can set up some milestones and work through bugs; I don't think we need to big feature development, but i18n of the docs is something that would be compelling
