### ISSUE TITLE
Dragstart event won't fire while holding one of the modifier keys

### ISSUE THREAD

**Issue by makstheimba** [react-dnd/react-dnd#683]
In Chrome dragstart and dragover events won't fire while holding Shift key. In Firefox same behavior happens while holding Alt key. It seems like the issue is with react-dnd, since native html5 drag and drop works fine with any modifier key.
What is a reason for that and is it possible to fix?

**Comment by dhruvparmar372** [comment]
this still seems to be an issue, @darthtrevino any ideas on if/when it will be fixed? 
I'd be happy to dig into this if it's something that be considered merging in once fixed.

**Comment by lsem** [comment]
So what should we do? Any ideas how to work around this?

**Comment by lsem** [comment]
I've behaviour that locks horizontally dragged item when shift is pressed. While this itself is issue for react-dnd I've found a workaround by subscribing to drag event. But this issue looks like showstopper for this particular interaction.  People always first press shift and then start dragging.

**Comment by lsem** [comment]
I've tested on latest Chromium and can confirm everything except Custom Drag Layer (which is the case for me :-/ )works now with this fix:
https://bugs.chromium.org/p/chromium/issues/detail?id=646339&can=2&start=0&num=100&q=&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified&groupby=&sort=
