### ISSUE TITLE
Fire a function on drop

### ISSUE THREAD

**Issue by martinnov92** [react-dnd/react-dnd#699]
Hello,

is it ok to fire a function from drop method?

I need to fire an action when I drop an item into drop zone and I would like to use it like this:

```
    drop(props, monitor) {
        return props.onDropTarget(monitor.getItem());
    }
```

Thank you

**Comment by anilreddykatta** [comment]
@martinnov92 Are you planning to dispatch a `redux` action? Calling a handler from `drop` has already been used in examples.

**Comment by martinnov92** [comment]
@anilreddykatta Not a redux action, just a function from a parent component

**Comment by martinnov92** [comment]
Ahh, it should be ok, I just found it in the examples, thanks @anilreddykatta .
