### ISSUE TITLE
No file during spec when dragging an image from the same page

### ISSUE THREAD

**Issue by ArnaudRinquin** [react-dnd/react-dnd#700]
**Using:** 

* react-dnd: `2.2.4`
* react-dnd-html5-backend: `2.2.4`
* Chrome: `56.0.2924.87 (64-bit)`
* Apple OS X: `10.12.3 (16D32)`

**How it is now:**

When dragging an image displayed in the same page to a drop zone, `monitor.getItemType() === NativeTypes.FILE` during `collect` but `monitor.getItems().files` is an empty array during `spec`.

**How it should be:**

Either:

* not have the item type to `NativeTypes.FILE` during `collect` so we are aware that there will be no file
* have the files actually accessible during `spec`

**Comment by anilreddykatta** [comment]
@ArnaudRinquin Is the issue reproducible in other browser? I have seen similar kind of issue, when trying to break in drop. If I don't break it seems work. Can you provide `console.log` inside drop of `monito.getItems()`?

**Comment by ArnaudRinquin** [comment]
Yes I can

<img width="181" alt="screen shot 2017-03-17 at 11 07 17" src="https://cloud.githubusercontent.com/assets/228886/24050750/27ae4160-0b30-11e7-95f0-b576fedc98f0.png">

**Comment by anilreddykatta** [comment]
@ArnaudRinquin Can you provide some sample code for `DragSource, DropTarget, DragDropContext` ? I will try to reproduce this locally in the meantime, any sample code from your side will be really helpful.

**Comment by anilreddykatta** [comment]
@ArnaudRinquin It seems issue is with `react-dnd-html5-backend`. It goes back to browser `dragEvent`, which has this `["text/uri-list", "text/html", "Files"]` as `event.dataTransfer`. Which is pretty interesting. I will dig more and keep you posted.

**Comment by theTechie** [comment]
@ArnaudRinquin - how does your `types` look on your `DropTarget` (drop zone) ?

**Comment by yoavniran** [comment]
hi @anilreddykatta did you get to look into this one? 

We're seeing this issue as well and although its not critical it would be good to be able to prevent showing an hover drag effect when the user drags an image from the app's page.

Currently I dont see a way to do this as there is no information in the spec's canDrop() pars that will differentiate it from another file or url being dragged

**Comment by daldridge-cs** [comment]
I'm seeing similar behavior when dragging a file from the Finder on macOS onto my drop target.  `monitor.getItems().files` does become defined/non-null when the drop begins, but it is null up until that point.  (I expected it to be non-null essentially at dragenter time for the drop zone).
