### ISSUE TITLE
Dropping element into input field resets it to the empty value

### ISSUE THREAD

**Issue by igorarkhipenko** [react-dnd/react-dnd#701]
![out](https://cloud.githubusercontent.com/assets/24496348/24152481/71ae3c12-0e54-11e7-85ad-abad4723d99c.gif)

How to prevent this kind of unexpected actions? 
onDrop event handler with `e.preventDefault(); return false;` doesn't make any difference here for some reason.

**Comment by anilreddykatta** [comment]
@igorarkhipenko Can you provide some sample code? How you are structuring `DragSrouce` & `DropTarget` and how you handle them?

**Comment by igorarkhipenko** [comment]
@anilreddykatta `renderField()` contains jsx code of drag-n-drop element 

`const` fieldSource = {
  canDrag(props) {
    return props.isDraggable
  },

  beginDrag(props) {
    return {
      index: props.index,
      mapIndex: props.mapIndex,
      fieldName: props.fieldName,
      isDraggable: props.isDraggable
    }
  }
};

@DropTarget('field', fieldTarget, connect => ({
  connectDropTarget: connect.dropTarget(),
}))
@DragSource('field', fieldSource, (connect, monitor) => ({
  connectDragSource: connect.dragSource(),
  connectDragPreview: connect.dragPreview(),
  isDragging: monitor.isDragging(),
}))
export default class DraggablePrize extends Component {
  render() {
    const { index, field, renderField, isDragging, connectDragSource, connectDropTarget, connectDragPreview } = this.props;

    return connectDragPreview(
      <div}>

        {connectDropTarget(
          <div 
            id={index}
            {renderField(field)}
          </div>
        )}

      </div>
    );
  }
}`

**Comment by anilreddykatta** [comment]
@igorarkhipenko Where are persisting any changes to the fields (`DragSource/DropTarget`), are you storing them on state or always reading from props. Is it possible to share renderField too? From what I see now there is no `connectDragSource`.  More information about how you are dealing with `value` changes in the field would really help.

**Comment by MHerszak** [comment]
I got the same issue. @anilreddykatta my values are reset when I drop it into the field as well. And the field is a redux-form field. I have basically almost the same code as above. @igorarkhipenko did you resolve your issue?

**Comment by tcosentino** [comment]
Same here, @anilreddykatta & @MHerszak. Any resolution? Will dig in further so I can see what would be causing this but want to make sure you didn't do that already :)

**Comment by igorarkhipenko** [comment]
@MHerszak No, I didn't. Left it as it is after a few hours of headscratching.

**Comment by MHerszak** [comment]
@tcosentino `onDrop={e => { e.preventDefault(); }}` is what I used to solve it.

**Comment by evserykh** [comment]
@tcosentino your solution works like a charm 👍
