### ISSUE TITLE
Check if at least one drop target can drop from monitor

### ISSUE THREAD

**Issue by fritz-c** [react-dnd/react-dnd#702]
Is there any way to use the `DropTargetMonitor` from the `DropTarget` `collect()` function to determine if there is a single drop target with `monitor.canDrop() === true`?

To give a simple example, you have three dog pictures. You drag a steak to one of them and hover without dropping. The dog that is under the steak takes on a `.happy` class. The dogs that aren't get a `.sad` class. As far as I can tell with the current API, you can judge when to add `.happy` by using `monitor.isOver()` and `monitor.canDrop()`, but there's no way to judge when to add the `.sad` class.

**Comment by gaearon** [comment]
Looking at (private) `monitor.internalMonitor.getTargetIds()` will probably tell you that we're over something, and you can use `monitor.isOver()` to check that we're not over current item.

We should probably expose this somehow.

**Comment by theTechie** [comment]
This should help - #448
