### ISSUE TITLE
A hover() func that doesn't update data

### ISSUE THREAD

**Issue by malcolmredheron** [react-dnd/react-dnd#705]
I would like to make a reorderable list with react-dnd. Unlike the example, I want to just indicate where an item will go until the item is dropped, at which point I'll update the underlying data.

After hover() has figured out whether the mouse is in the top or bottom of the row, I'd like to update state or props to reflect this so that I can render appropriately. However,
  - I can't update props because hover() doesn't get return new props.
  - https://github.com/react-dnd/react-dnd/issues/265 suggests that I shouldn't call setState from hover().
  - I also can't do this work in the collector because it doesn't get the component.

As far as I can tell I'm meant to make a second component that wraps my component, put my drop state on there and then plumb a setter through my props so that the real component can update the drag state.

Given that there's already a DropTarget element keeping track of drop state from my collector, I don't understand why it can't store props returned by hover() as well.

If I'm missing something, great. If not, I'd love to understand the reasons for this.

**Comment by anilreddykatta** [comment]
@malcolmredheron Correct me if I am missing something. I am trying to answer from what I know, Calling setState from hover is not desirable, as in general practice you don't want to leak your state to outside world unless it is through props. It will create whole class of bugs which are difficult to track.  

Showing where it can be dragged I hope this helps [http://react-trello-board.web-pal.com/](http://react-trello-board.web-pal.com/)

**Comment by malcolmredheron** [comment]
@anilreddykatta: I don't think that I'm leaking state by using setState. The hover function is provided by my component so it all seems pretty well encapsulated to me. That said, I'd love to update my props from hover -- I just can't, as I noted in my earlier post.

I haven't looked through your example closely but it looks as if hover() calls moveList(), which I think updates the model. Am I mistaken? I'm looking to display a black line where the item would go but not update the model until the drop.

**Comment by anilreddykatta** [comment]
@malcolmredheron I am trying to understand

```
DragSource('CARD', spec, collect)(CustomComponent)

// This will create components like this
DragSource (HOC)
    - CustomComponent
```
`hover` is a handler provided by `DragSource`, so when we call `setState` of `CustomComponent` in `hover` which is from `DragSource`, is well encapsulated? Let me know if this makes sense

Coming back to displaying line when we are about to cross a boundary.
[https://react-dnd.github.io/react-dnd/docs-drag-source-monitor.html]https://react-dnd.github.io/react-dnd/docs-drag-source-monitor.html. It has methods which provide us with coordinates of current drag operation and getting `source` `height, width` and some basic maths we should be able to do this. Looking for more simple way to do it

**Comment by malcolmredheron** [comment]
My code has the hover handler and CustomComponent in the same file. CustomComponent is wrapped into a compound component that includes the drag source and I view them as one logical piece of code. Given this, yes, I believe that it's perfectly reasonable to have the handler set state on the component.

I know about DragSourceMonitor. It's helpful for figuring out where to render my line. But I want the component itself to render the line, and that means updating its props or state. As I noted in my first message, there are some technical problems with that.
