### ISSUE TITLE
How to implement async funcs in drop() func ?

### ISSUE THREAD

**Issue by Ron-Yu** [react-dnd/react-dnd#706]
I had been using redux as data flow in my react application. I would like to add some drag and drop functionality in my project. What I have done is as follow,

* when drop is activated
* call `reorderWaitListPeople`, a function sending new index info to server
* call `fetchWaitLists`, a function getting all data

but I got the error message `Uncaught Error: drop() must either return undefined, or an object that represents the drop result. Instead received [object Promise]`

The simple code example

```javascript
const target = {
	async drop(props, monitor, component) {
		const {
			index,
			reorderWaitListPeople,
			fakeFetchWaitLists
		} = props

		if (monitor.didDrop) {
			await reorderWaitListPeople(index)
			fetchWaitLists()
		}
	}
}
```

**Comment by Ron-Yu** [comment]
oh, I modified my code as below. Because `reorderWaitListPeople` and `fetchWaitLists` are declared by `async`, both of them will return promise after been invoked. I use promise to fulfill my goal.

```javascript
const target = {
	drop(props, monitor, component) {
		const {
			index,
			reorderWaitListPeople,
			fakeFetchWaitLists
		} = props

		if (monitor.didDrop) {
			reorderWaitListPeople(index).then(() => fetchWaitLists())
		}
	}
}
```

**Comment by theTechie** [comment]
@Ron-Yu - is this still an issue? otherwise, could you please close this
