### ISSUE TITLE
Delegate to existing backend instead of throwing new Error('Cannot have two HTML5 backends at the same time.');

### ISSUE THREAD

**Issue by nomcopter** [react-dnd/react-dnd#708]
I have an app that uses the HTML5 backend for drop and drop internally. I want to use a sub-component that also uses it independently, but in the same app. Currently this is only possible if I can actually make changes to this sub-component to remove it's DragContext or export one without which seems unnecessary.

**Comment by theTechie** [comment]
You can create a HOC to pass the DnDContext created as a singleton to childContext and wrap your components using DnD with this HOC.

**Comment by anilreddykatta** [comment]
@nomcopter [https://github.com/react-dnd/react-dnd/blob/1153d82395b336d3cc0ad647625d8adad9887bde/examples/01%20Dustbin/Single%20Target/Container.js](https://github.com/react-dnd/react-dnd/blob/1153d82395b336d3cc0ad647625d8adad9887bde/examples/01%20Dustbin/Single%20Target/Container.js).

Above component use `DragDropContextProvider` which you can use with `HTML5Backend` injected from outside

**Comment by c9s** [comment]
Hi @anilreddykatta,

I'm still not quite sure the internal mechanism.  I replaced the decorator with the `DragDropContextProvider` in my two different views (actually two app instances), but I still get this error.

I traced the code a little bit and found DragDropContext creates the backend instance from the given html5 factory callback in each decorator instance, what should I do to share the backend instance for my different views?

**Comment by c9s** [comment]
The code below seems to check if there are two backend instances instantiated under the same window global:

```
if (this.window === undefined) {
	        return;
	      }

	      if (this.window.__isReactDndBackendSetUp) {
	        // eslint-disable-line no-underscore-dangle
	        throw new Error('Cannot have two HTML5 backends at the same time.');
	      }
	      this.window.__isReactDndBackendSetUp = true; // eslint-disable-line no-underscore-dangle
	      this.addEventListeners(this.window);
```

**Comment by theTechie** [comment]
Check this out [#186](https://github.com/react-dnd/react-dnd/issues/186#issuecomment-110333064)

**Comment by c9s** [comment]
Hi @theTechie, Thanks,

I just found the solution to solve this, I used three lines of code:

```
import HTML5 from 'react-dnd-html5-backend';
import {DragDropContext} from 'react-dnd';
export default DragDropContext(HTML5);
```

**Comment by zz-james** [comment]
Hi @c9s 
So let me get this straight, this is a 3 line component that you share instead of each component setting up their own DragDropContext?

**Comment by c9s** [comment]
Yes

**Comment by duidae** [comment]
> Hi @theTechie, Thanks,
> 
> I just found the solution to solve this, I used three lines of code:
> 
> ```
> import HTML5 from 'react-dnd-html5-backend';
> import {DragDropContext} from 'react-dnd';
> export default DragDropContext(HTML5);
> ```

@theTechie @c9s thanks for the solution, really fixed my urgent pain in the ass, really appreciated. :bowing_man:
BTW, would you mind explain this a little bit, I still don't quite understand it after googled some articles of HOC :thinking:
