### ISSUE TITLE
HTML5 backend: access to DataTransfer.items when dropping files

### ISSUE THREAD

**Issue by renchap** [react-dnd/react-dnd#712]
This is needed to be able to drop directories and get their content (using `DataTransferItem#webkitGetAsEntry`, cf https://developers.google.com/web/updates/2012/07/Drag-and-drop-a-folder-onto-Chrome-now-available)

Currently `dataTransfer.files` is exposed, and by looking at the code (https://github.com/react-dnd/react-dnd/blob/master/packages/react-dnd-html5-backend/src/NativeDragSources.js#L16) I dont see how to expose multiple attributes.

I can give a try at implementing it if you tell me the preferred way to do so.

**Comment by anilreddykatta** [comment]
@renchap You are planning to implement how to expose items ?

**Comment by renchap** [comment]
I can have a try at it, but I am not sure how to do so without big changes to the existing code to handle exposing multiple props.

**Comment by mickael-kerjean** [comment]
I would also use this. Any plan to implement it or would you accept a pull request for it?

**Comment by Andarist** [comment]
I'm planning to make a PR for this soon, would suggest adding `DIRECTORY` as new native type.

**Comment by jwbay** [comment]
Would a new separate native type preclude accepting both files and directories on a drop target?

**Comment by Andarist** [comment]
why would it? I would say it should be possible to combine both as accepted targets, I had no time to implement this as we've dropped the idea of uploading directories at my work (for now), but also it got me thinking - should we allow it in this lib while the spec for `DataTransferItem#webkitGetAsEntry` is not settled and this is Chrome-only for now?

OTOH easier would be to just expose `event` to the user and make it possible to implement this in userland, also this would be helpful for other use cases when people need such access to the event

**Comment by yoavniran** [comment]
hi,
I currently have the requirement of uploading files from a dropped dir.
I have written this little package: https://www.npmjs.com/package/html-dir-content
that does the extraction of File objects from the given dir.

Now I came to the blocker of not being able to influence how the HTML5 backend handles the dropped (transfer)data

@Andarist is this something youre already working on?

**Comment by yoavniran** [comment]
also @Andarist - 👍 for exposing the raw event :)

**Comment by Andarist** [comment]
@yoavniran unfortunately not, I hadn't much need for it and decided not to implement it without direct encouragement from the react-dnd team, as this feature in browsers is kinda experimental and not standardized properly yet

**Comment by yoavniran** [comment]
@Andarist true that its not standardized in a spec yet but it works consistently on chrome/firefox/edge. And its can be graceful about browsers without support (no errors).

Would a PR with the Directory type be accepted? 

More urgently, can we get the underlying event exposed to "user land" so i can implement my solution without waiting on a bigger change? I'd be happy to PR it.

**Comment by tomfairbs** [comment]
@yoavniran did you have any luck finding a solution for this? I'm stuck on the same issue of needing to access the raw event.

**Comment by yoavniran** [comment]
hi @tomfairbs - i did find a workaround although im not happy with it because it requires a hacky solution:

``` javascript

import HTML5Backend from 'react-dnd-html5-backend';
import { getFilesFromDragEvent } from 'html-dir-content';

const overrideDropCaptureHandler = (manager) => {
  
    const backend = HTML5Backend(manager),
        orgTopDropCapture = backend.handleTopDropCapture;

    backend.handleTopDropCapture = (e) => {
        orgTopDropCapture.call(backend, e);
        backend.currentNativeSource.item.dirContent = getFilesFromDragEvent(e); //adding my custom information here
    };

    return backend;
};


// now you can use it :

const MyDndComponent = DragDropContext(overrideDropCaptureHandler)(
    DropTarget(
        [NativeTypes.FILE, NativeTypes.URL], //support drop of files and url strings
        dndSpec,
        dndCollect
    )(MyComponent)
);

```

**Comment by mickael-kerjean** [comment]
One year after opening this issue, it doesn't seem the author of the library is interested in contributing to the discussion. As such, I've publish a fork of this backend to [npm](https://www.npmjs.com/package/react-dnd-html5-backend-filedrop) that expose the dataTransfer object directly

**Comment by renchap** [comment]
@darthtrevino Do you have any opinion on the API for this? The change by itself is not huge, but I am not sure how to expose `dataTransfer` without a breaking API change.

**Comment by renchap** [comment]
@darthtrevino Could you please reopen this issue, as #1120 has been reverted?
Thanks!

**Comment by renchap** [comment]
I just posted a PR implementing `getItem().items`, feel free to test it and send any feedback: #1225

**Comment by darthtrevino** [comment]
Yep, taking a look, sorry for the wait
