### ISSUE TITLE
Update Container state when parent props changed

### ISSUE THREAD

**Issue by dmarczydlo** [react-dnd/react-dnd#722]
I'm trying to use DND for 2 containers.

1) container have static data form axios => tasks list. 
2) container have only tasks which were set to user.

```
<Container id={1} list={this.props.tasks}/>
<Container id={2} list={this.state.userTasks}/>
```
When I change user (by select) X => Y I have to refresh data for **Container(2).**

My **this.state.userTasks** are refreshing but child component **Container(2)** still have the same elements.

This is because I use constructor to pass data. Constructor is call once. I know it.

```
constructor(props) {
        super(props);
        this.state = {cards: props.list};
    }
```
I can't use **`componentWillReceiveProps(nextProps)`** into Container (child) because I have to update only **Container(2)** and this method is calling when I moving element from **Container(1)** to **Container(2)**

How to update **Container(2)** cards when I change user? Do you have any ideas?

**Comment by anilreddykatta** [comment]
@dmarczydlo One alternative will be to pass `unique user information` to the `Container` and checking it in the `Container` when it changes reset lists by calling handler. 

Better approach will be to use `componentWillReceiveProps` in the component where you are declaring 
```
<Container id={1} list={this.props.tasks}/>
<Container id={2} list={this.state.userTasks}/>
```
This components. 

Let me know if it helps!

**Comment by dmarczydlo** [comment]
@anilreddykatta 

> Better approach will be to use componentWillReceiveProps in the component where you are declaring



but I using `this.state.userTasks` as data which are pass. So this data where changing. 

But in the `Container(2)` I have to change props but I don't know how.

Information about users tasks are updated only when I changed select. At the begining tasks are empty.

**Comment by anilreddykatta** [comment]
@dmarczydlo When `user` changes reset the `this.state.userTasks`. `Container2` requires this from the state, I understand it. But for `Container` `list` is a prop. 


```
componentWillReceiveProps(nextProps) {
 if (nextProps.userId !== this.props.userId) {
    this.setState({
      userTasks: [],
    })
 }
}
```

Somewhere in the `render`

```
render() {
 return (
   <Container id={1} list={this.props.tasks}/>
   <Container id={2} list={this.state.userTasks}/>
 )
}
```

**Comment by dmarczydlo** [comment]
OK thnx. Your answer gave me idea how to do that. 
And now is working fine. So this issue could be close.

**Comment by anilreddykatta** [comment]
@dmarczydlo Can you close the issue?
