### ISSUE TITLE
"Browse the Source" 404 for native files example

### ISSUE THREAD

**Issue by corysimmons** [react-dnd/react-dnd#723]
https://react-dnd.github.io/react-dnd/examples-other-native-files.html
https://github.com/react-dnd/react-dnd/tree/master/examples/05%20Customize/Native%20Files

**Comment by anilreddykatta** [comment]
@corysimmons Thank you very much! For pointing this out.

**Comment by corysimmons** [comment]
Thanks for the fix. =)
