### ISSUE TITLE
what can i do to wait endDrag function for some value ?

### ISSUE THREAD

**Issue by nilaybrahmbhatt** [react-dnd/react-dnd#726]
i want to call function to get value from db and then i want to complete endDrag after receiving value from db.
what can i do?

i am tried but endDrag already completes before getting value;

**Comment by anilreddykatta** [comment]
@nilaybrahmbhatt Any specific case you are trying to address. `endDrag` is called when we receive `dragend` from browser if you are using `HTML5 backend`. Provide any specific use case?

**Comment by nilaybrahmbhatt** [comment]
@anilreddykatta  can u please share code of your example you explained ?

**Comment by anilreddykatta** [comment]
@nilaybrahmbhatt You can find example how to create a `CustomPreview` for you component like this. [example](https://github.com/react-dnd/react-dnd/tree/master/examples/02%20Drag%20Around/Custom%20Drag%20Layer). 

```
// DRAG SOURCE
const DynamicCard = (props) => props.connectToDragSource(
 <div className="card">
 {/* content */}
</div>
)
```
When you are handling `drop` on `DropTarget`
```
class TargetLot extends Component {
 state = { isProgress: false }
 handleDrop = () => {
   this.setState({isProgress: true})
  fetch(url).then(() => {
   this.setState({isProgress: false})
   // Actually drop element logic here
  })
 }
}

 render(){
  return (
    <div>
      {this.state.isProgress ? (
        <Loader />
      ): (
        <div />
      )}
    </div>
   )
 }
```

Let me know if it helps.

**Comment by nilaybrahmbhatt** [comment]
I create same thing. 
my Redux State is changed but not page render again.
i also tried to re-Render but setState and this.forceUpdate but not affect anything.

**Comment by anilreddykatta** [comment]
That's interesting. Can you please strip down version of your code how you are handling state changes? Maybe I can help?
