### ISSUE TITLE
how to initialize state in components rendered with the test context that uses the test backend?

### ISSUE THREAD

**Issue by thecristen** [react-dnd/react-dnd#730]
Hi, thanks for all your work towards this great project! I wanted to check in and verify whether what I'm trying to do is supposed to be possible or not.

I'm following the example from https://react-dnd.github.io/react-dnd/docs-testing.html and it's working well but I have a component that has state. I wanted to test if my component initializes with the correct state but as far as I can tell the state for my component ends up being null.

```javascript
beforeEach(() => {
  ElementComponent = wrapInDragDropContext(Element.DecoratedComponent);
});

test('renders Element with name and initial state', () => {
  const element = mount(
    <ElementComponent
      connectDragSource={el => el}
      connectDragPreview={el => el}
      name='test' />
  );

  /* ... */
  expect(element.state('isActive')).toBe(false); // TypeError: Cannot read property 'isActive' of null
});
```
Note - this is regular React (no Redux/Flux/etc). Should state be already initialized here or is it something I'm expected to handle on my own?

**Comment by anilreddykatta** [comment]
@thecristen `Element.DecoratedComponent` gives you the original class, which you don't need to wrap in any context. 

Sample code where you are initializing state really helps in resolving this quickly.

**Comment by thecristen** [comment]
@anilreddykatta you're right, I should be just using the Element class. Thanks for the quick response.
On further investigation, the issue seems to be more in the domain of my testing tool enzyme rather than with react-dnd, so I'm going to close this. Cheers!
