### ISSUE TITLE
delete event after drop

### ISSUE THREAD

**Issue by song-forever** [react-dnd/react-dnd#732]
how to delete event after drop?I dont find some info in doc,with enddrag event?

**Comment by anilreddykatta** [comment]
@song-forever Why you want to delete event. Once you receive `endDrag` you already have the event, you can chose to ignore or you can handle it.

**Comment by song-forever** [comment]
i dont use `endDrag` ,but you remind me use the `canDrag` and the problem is resolved ,thanks a lot :)
