### ISSUE TITLE
Re-render component while dragging (Cannot read property 'nodeName' of undefined)

### ISSUE THREAD

**Issue by spiritix** [react-dnd/react-dnd#733]
Roughly summarized, I am using the following structure (using Redux):

```
<Provider store=..>
  <MyApp>
    <Connect(DragDropContext)>
      <DragDropContext>
        <div id=main>
          <DragLayer></DragLayer>
          <MyComponent props={draggingElement:store.draggingElement}>
            <div class=container> 
              <DropTarget props={draggingElement:this.props.draggingElement}>
                <div id=indicator>
                  Currently dragging #2 which can be dropped here
                </div>
              </DropTarget>
              <div id=elements>
                <DragSource key=1></DragSource>
                <DragSource key=2></DragSource>
                <DragSource key=3></DragSource>
              </div>
            </div>
            <div class=container> 
              <DropTarget props={draggingElement:this.props.draggingElement}>
                <div id=indicator>
                  Currently dragging #2 which can not be dropped here.
                </div>
              </DropTarget>
              <div id=elements>
                <DragSource key=1></DragSource>
                <DragSource key=2></DragSource>
                <DragSource key=3></DragSource>
              </div>
            </div>
          </MyComponent>
        </div>
      </DragDropContext>
    </Connect(DragDropContext)>
  </App>
</Provider>
```

Now in an all DragSources, I am listening to the `beginDrag` event and firing an action which updates the store with some information about the item being dragged at the moment (`draggingElement`).
`MyComponent` gets this information passed as a property but doesn't use it in any way other than passing it down to all DropTargets, still as a property.
Now in all DropTargets, I render a message depending on whether the element being dragged can be dropped there or not.

So far so good, unfortunately, as soon as I start dragging an element I get the following error message:
```
Uncaught TypeError: Cannot read property 'nodeName' of undefined
    at Object.a [as getDragPreviewOffset] (core-2fc0801472.js:31485)
    at t.handleTopDragStart (core-2fc0801472.js:31485)
```
It seems that `MyComponent` gets replaced entirely in the DOM as soon as it receives the property with the information about the dragging element.
And since the dragging element is also a child of `MyComponent`, it gets replaced as well and the drag operation fails.
If I put the following code in `MyComponent` everything works:

```
        shouldComponentUpdate: function(nextProps) {
            if (nextProps.draggingElement !== this.props.draggingElement) {
                return false;
            }

            return true;
        },
```

But now the DropTargets are not re-rendered anymore as well (since they are children of `MyComponent`) and don't display the required information.

What can I do about this? And specifically, why is the DOM of `MyComponent` being replaced entirely if the new property only affects a small part of it?

**Comment by spiritix** [comment]
Solved the problem using a workaround. Still, this should not happen.

**Comment by serle** [comment]
I'm getting the same problem, could you elaborate on the workaround

**Comment by spiritix** [comment]
Well, I refactored the components to not get 'draggingElement' passed as property anymore. Instead, I am now using the monitors 'getItem' method to get information about the currently dragging element inside the component.

**Comment by serle** [comment]
I found that by rendering the component once drag starts, the DragPreview still needs access to the component to create the DragPreview "snapshot" image. To prevent this I modified the display style to none, although I think this is out of keeping with react design principles. 

I would suggest that react-dnd library supply a dag behavior flag to take care of this common case where the component should disappear from its source container for the duration of the drag operation, until the drop event is successful.

**Comment by spiritix** [comment]
I will open this issue again to allow further discussion. Would be nice to get the opinion of a contributor.

**Comment by Carmezim** [comment]
Any updates on this?

**Comment by mannycolon** [comment]
I have the same issue

**Comment by tyewang** [comment]
Same issue here as well.

**Comment by klappy** [comment]
I've got the same problem. 

I've got a word bank with multiple drop zones. When dragging from the word bank to the drop zone, I have no issues. But when dragging from one drop zone to another, I get the issue referenced here.

I've even created a new component that gets rendered in the drop-zone so it's fresh with a different name. Initiating the drag from within the drop-zone is where I am getting the error.

**Comment by stellarhoof** [comment]
@serle In my case, the drag preview has already been rendered when this happens. The reason I encounter this error is because https://github.com/react-dnd/react-dnd/blob/dbba380960d408014b8a6c4d7dfc508078a1a3f3/packages/react-dnd-html5-backend/src/HTML5Backend.ts#L407 (which is in `handleTopDragStart`) doesn't encounter the original drag node. However, I suspect this happens only when dragging starts, because I see no reason why the drag source should need to be available after the drag preview has already been rendered.

**Comment by leantide** [comment]
I have a multi-level tree structure with draggable nodes. Depending on the node being dragged, I collapse some branches in the tree. Since I re-walk the tree it gets re-rendered, and my dragSources change and I get this same error. Since I am in a virtualized list container, hiding instead of re-walking isn't presently viable.
