### ISSUE TITLE
Dragging Functionality Not working in Windows 10: Chrome

### ISSUE THREAD

**Issue by zargold** [react-dnd/react-dnd#743]
Facts about my Drag N Drop implementation:
1. I did this: 
```javascript
const touchDevice = ('ontouchstart' in document.documentElement)
let ConnectedRoot
if(touchDevice){
  ConnectedRoot = DragDropContext(TouchBackend)(Root)
}
else{
  ConnectedRoot = DragDropContext(HTML5Backend)(Root)
}
export default ConnectedRoot
```
2. This *did work* in allowing drag n drop to work on iPad, iPhone, MacBook Pro (Chrome, Safari, Firefox) on various versions.
3. Even on Windows 7 Chrome, Firefox, etc: Drag N'Drop worked... and windows 8 touchscreen--it worked in all browsers with fingers but not with mouse. 

Problem is with a specific Windows 10 laptop (we'll call Win10) *without* Touchscreen in Chrome. Particular problem is with the initial Grab functionality where `onDragStart` never fires.

4. Win10's Firefox: DragN'Drop *works fine* with custom drag layer and `canDrag` etc.
5. Win 10 is not touchscreen--its a lenovo that looks like a thinkpad with a glossy screen.

After seeing this post: [on super user: google chrome drag-drop](https://superuser.com/questions/994283/google-chromes-drag-drop-feature-stopped-working)
Assumed that may just be a chrome settings/flags issue.

However, this did not appear to be the case:

1. Win10 was able to use Drag N Drop on Chrome within Gmail--needed no flag changes etc.
2. Tried to follow instructions provided in above article => But...
 - did not seem to be the case that chrome was being run as an administrator because I tried to re-run using Window key+R and it worked)
 - Doesn't look like a flag issue because it worked in Gmail.
3. Instead of Drag N Drop it selects text... (only in Win10's chrome and in all other devices listed it just grabs something).

Any help or work around would be appreciated.

**Comment by diiq** [comment]
Does it work in Windows 10 Chrome if you *force* it to use HTML5Backend? This seems like it might be a problem with your feature sniffing.

**Comment by zargold** [comment]
Yes, unfortunately you were correct... Firefox was not picking up that Windows 10 considers itself to have `'ontouchstart'` even when no touchscreen device is connected (ie. a windows touchscreen monitor) or if a laptop its built in touchscreen... it makes no distinction and thus my app would allow drag but only on a touch connected device. This is sad, but I'll figure out a way to make both work eventually.

**Comment by Ronnyrr** [comment]
How did you manage to solve this?

**Comment by tauren** [comment]
@zargold @Ronnyrr I'm seeing the same issue. Any insights on how to solve it?

**Comment by diiq** [comment]
After fighting with react-dnd on the Surface (and other all-in-one devices), I ended up writing a react drag and drop library specifically to handle the touch-and-also-mouse case. It's not as mature or as well-supported as react-dnd, but if touch-and-mouse support is a major blocker,  https://github.com/diiq/esdragon might help.
