### ISSUE TITLE
Is it possible to determine if an item can be dropped

### ISSUE THREAD

**Issue by aeneasr** [react-dnd/react-dnd#744]
Is there a way to determine if an item can be dropped at it's current location? For example, I want to detect if an item is being dragged outside of `<DragDropContext>`.

To clarify, I want this while the item is being dragged, not after it was dropped.

**Comment by ericp96** [comment]
You can check the isOver function on the drop target monitor.

Please see the example here:
https://react-dnd.github.io/react-dnd/docs-drop-target.html

**Comment by arekkas** [comment]
If I have multiple drop targets I would need to check isOver for all of them, right? I don't see this working well :/
