### ISSUE TITLE
requestIdleCallback() 

### ISSUE THREAD

**Issue by justinjzs** [react-dnd/react-dnd#746]
I use ReactDnd in such scenario:
Some items in a container, you can DnD any item to any where in container. 
in`hover()` I calculate the real-time position of  all items in the container. And I pass the position to the `Item`Component so that it can be rendered at correct position.
But, I occur a problem that when you drag a item, item move slow and even stop some times. After a while it will appear at the correct position.
below are the output in `console`, 
````
[Violation] 'requestIdleCallback' handler took 537ms
[Violation] 'requestIdleCallback' handler took 323ms
[Violation] 'requestIdleCallback' handler took 446ms
[Violation] 'requestIdleCallback' handler took 83ms
[Violation] 'requestIdleCallback' handler took 56ms
[Violation] 'requestIdleCallback' handler took 55ms
[Violation] 'requestIdleCallback' handler took 53ms
````
did any one meet the same problem?

**Comment by bernatfortet** [comment]
Same here

**Comment by justinjzs** [comment]
@bernatfortet I solve this problem by adding a `throttle` function to reduce the frequency of the `hover()`.
````javascript
function throttle(fn, threshhold = 250, scope) {
	let last;
	let deferTimer;
	return function (...args) {
		const context = scope || this;

		const now = +new Date;
		if (last && now < last + threshhold) {
			// hold on to it
			clearTimeout(deferTimer);
			deferTimer = setTimeout(() => {
				last = now;
				fn.apply(context, args);
			}, threshhold);
		}
		else {
			last = now;
			fn.apply(context, args);
		}
	};
}
````
but I still don't know the source of the problem

**Comment by Windstalker** [comment]
In my case it was caused by some extension in Chrome. Possibly, React Dev Tools
