### ISSUE TITLE
Chrome redraw bug

### ISSUE THREAD

**Issue by ruben1** [react-dnd/react-dnd#747]
Demo: http://recordit.co/RaQvk3XER0

It seems it has trouble rendering the background in the above element, the problem goes away when triggering a repaint manually. I can't locate that element in the DOM, and there's not any unwanted element in the DOM or any change in the CSS that could cause that either. So my guess is that the bug isn't actually from react-dnd but from Chrome? Opening this here just to make sure that's right.

Could be similar to http://stackoverflow.com/questions/14187703/chrome-flexbox-drag-and-drop-redraw-bug, since I'm using flexbox

**Comment by ruben1** [comment]
This did the work http://ilee.co.uk/css-translate3d-performance-hack/

**Comment by amakhrov** [comment]
@ruben1 thanks for the workaround!
I have the same issue (Chrome on MacOS), and using the `transform` hack worked for me.
