### ISSUE TITLE
Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

### ISSUE THREAD

**Issue by halt-hammerzeit** [react-dnd/react-dnd#749]
https://unpkg.com/react-dnd@2.3.0/lib/DragDropContext.js

```js

var CHILD_CONTEXT_TYPES = exports.CHILD_CONTEXT_TYPES = {
  dragDropManager: _react.PropTypes.object.isRequired
};
```

**Comment by rsolomon** [comment]
I believe this was fixed with [PR 729](https://github.com/react-dnd/react-dnd/pull/729) but never released.

**Comment by abharvey** [comment]
Any idea when this will be put into a release

**Comment by eMarek** [comment]
I see this issue fixed in this file https://github.com/react-dnd/react-dnd/blob/master/packages/react-dnd/src/DragDropContext.js#L8-L10.
@darthtrevino, any idea why this was not released?

**Comment by halt-hammerzeit** [comment]
@eMarek perhaps it's a sign of this package being abandoned

**Comment by eMarek** [comment]
I hope not. Those PropTypes warnings are really annoying.

**Comment by darthtrevino** [comment]
I've been on vacation, I'll cut a release today.
