### ISSUE TITLE
How to enable ES7?

### ISSUE THREAD

**Issue by pjanfred** [react-dnd/react-dnd#752]
Hello togther,

i´m new in using the react framework. At this moment i only created new react apps by using npm and create-react-app... . I tried for a few hours to activate ES7 for babel, but i can't find any ways to do that. Do you know of an easy way or a tutorial to do that? Many thanks.

pjanfred

**Comment by Mamoru1234** [comment]
Actually, your problem is not related to react-dnd.
I am pretty sure that you are using babel. In this case [transform-decorators-legacy](https://www.npmjs.com/package/babel-plugin-transform-decorators-legacy). NOTE that maybe some additional babel configuration will be needed.

**Comment by chinakids** [comment]
you need install a plugins
```
npm install transform-decorators-legacy --save-dev
```
then set your webpack configs(`webpack.config.js`)
```
"plugins": [
      "transform-decorators-legacy"
 ]
```
