### ISSUE TITLE
Dragging an element cause all other drag sources to render

### ISSUE THREAD

**Issue by chabb** [react-dnd/react-dnd#753]
Dragging an element cause all other element that act as drag sources to render, it happens because all elements that act as a dragSoure are updated with the props defined in their collect function. Is 
Is there a way to prevent this behaviour ? Or am i doing something wrong ?

Also, this issue does not affect 'lower-level' components ( = component that produces DOM element), as they do not have the props injected by the collect function, which is fine, and i can understand the use case of injecting the props in all dragSources ( = lyou may want to drag all/multiple drag sources in some situations ), but it can be quite bad on performance ( let's say you have 500 drag-sources elements, then they will be 500 method call .. ). 

One workaround i was thinking is to create a draggable element on the fly, when the user click.

**Comment by squirmsound** [comment]
@chabb did you come up with an approach?

**Comment by brakon** [comment]
this is happening to me also, any idea?

**Comment by lytc** [comment]
`shouldComponentUpdate` or `PureComponent` will help!
