### ISSUE TITLE
Same component with different types

### ISSUE THREAD

**Issue by anandrikka** [react-dnd/react-dnd#754]
How to use the same component for different types of drag and drop ? or Is there a way for dynamically giving type for the component, so that I will be able to use the same component for different set of items

```
@DropTarget('card', cardTarget, connect => ({
    connectDropTarget: connect.dropTarget(),
}))
@DragSource('card', cardSource, (connect, monitor) => ({
    connectDragSource: connect.dragSource(),
    isDragging: monitor.isDragging(),
}))
class Card extends Component { 
  render() {
    return <div>xxx</div>
  }
}
```

I want to use the same component for another set of drag and drop

```
@DropTarget('card2', cardTarget, connect => ({
    connectDropTarget: connect.dropTarget(),
}))
@DragSource('card2', cardSource, (connect, monitor) => ({
    connectDragSource: connect.dragSource(),
    isDragging: monitor.isDragging(),
}))
class Card extends Component { 
  render() {
    return <div>xxx</div>
  }
}
```

**Comment by Mamoru1234** [comment]
With DropTarget, you could achieve this pretty easy. The first argument could be an array of types.
Personally I prefer style like this.
```
@DropTarget(['val', 'val2'], {
  drop(props, monitor) {
    DROP_HANDLERS[monitor.getItemType()](props, monitor);
  }
}, (connect, monitor) => ({
  connectDropTarget: connect.dropTarget(),
  isOver: monitor.isOver()
}))
```

But in a case of DragSource, it sounds really confusing for me. What does it means? One UI element produce conceptually different sources. Pleace add more details.

**Comment by anandrikka** [comment]
@Mamoru1234 I have categories and each category will have a list of items,Each item in a list is a component and is needed to specify with unique drag and drop targets for category for sorting. So my question is how can I use the same component perse 'Item' in my case to give drag and drop targets based on category. I have uploaded a sample what I'm trying to do. Let me know whether it makes any sense.
![abc](https://cloud.githubusercontent.com/assets/8003265/25691119/f42c886e-3065-11e7-9878-3b39aa08bc51.jpg)

**Comment by iMoses** [comment]
> But in a case of DragSource, it sounds really confusing for me. What does it means? One UI element produce conceptually different sources. Pleace add more details.

@Mamoru1234 Another use case it to have an internal object with a custom type that we also want to be able to use as plain text if I drag it into a native element / outside the application.

**Comment by iMoses** [comment]
I gotta say that this new approach of ignoring issues then closing them for lack of interest is messed up.. It feels like a police station here
