### ISSUE TITLE
Drag from outside to inside an iframe

### ISSUE THREAD

**Issue by AdriVig** [react-dnd/react-dnd#759]
Hi there,

I'm trying to drag an element from outside to inside an iframe.

All components are from your example [Single target in iframe](https://github.com/react-dnd/react-dnd/tree/master/examples/01%20Dustbin/Single%20Target%20in%20iframe).
Here the code :
```
<DragDropContextProvider backend={HTML5Backend}>
  <div>
    <Frame style={{ heigth: '400px', width: '100%' }}>
      <div style={{ clear: 'both' }}>
        <Dustbin />
      </div>
    </Frame>
    <div style={{ overflow: 'hidden', clear: 'both' }}>
      <Box name="Glass" />
      <Box name="Banana" />
      <Box name="Paper" />
    </div>
  </div>
</DragDropContextProvider>
```
Or
```
<div>
  <Frame style={{ heigth: '400px', width: '100%' }}>
    <DragDropContextProvider backend={HTML5Backend}>
      <div style={{ clear: 'both' }}>
        <Dustbin />
      </div>
    </DragDropContextProvider>
  </Frame>
  <DragDropContextProvider backend={HTML5Backend}>
    <div style={{ overflow: 'hidden', clear: 'both' }}>
      <Box name="Glass" />
      <Box name="Banana" />
      <Box name="Paper" />
    </div>
  </DragDropContextProvider>
</div>
```
The example works perfectly (Dustbin and Boxes in Frame) but whith the boxes outside the Frame there is no event (original window.alert in example) on Drop.

Thank you for your help !

**Comment by rohmanhm** [comment]
@AdriVig why you closed this issue? any explain?

**Comment by AdriVig** [comment]
@rohmanhm Hi, I found another solution to my problem.
Not using react-dnd anymore, pure JS only.

**Comment by kjgraham** [comment]
@AdriVig would you mind sharing your pure JS solution?
