### ISSUE TITLE
Cherry pick 2.2.2 changes and sync up npm publishes to github versions

### ISSUE THREAD

**Issue by mattkrick** [react-dnd/react-dnd#760]
On NPM i see:
```
2.3.0 
2.2.4 
2.2.3 
2.2.0 
```

Here on github, i see `2.2.2`.

Oddly enough, the thing I care about #749 is in 2.2.2, but not in later releases. 
Can you please create a 2.3.1 that cherry picks from 2.2.2 and publish to github & npm?
Happy to help if things get hairy

**Comment by darthtrevino** [comment]
We just cut some new releases, let me know if this is still an issue
