### ISSUE TITLE
Invariant Violation: Expected targetIds to be registered.

### ISSUE THREAD

**Issue by miadabrin** [react-dnd/react-dnd#763]
Hi there. We are getting this error (although the functionality is okay and works fine). Do you have any idea how it can happen? couldn't figure it out from the source code.

**Comment by PorterNan** [comment]
I also met this problem, it show me Expected sourceIds to be registered, is there any case could cause this happen?

**Comment by mogelbrod** [comment]
I'm also getting error reports of this, but unable to reproduce myself.

![screen shot 2017-10-31 at 11 24 34](https://user-images.githubusercontent.com/150084/32219329-1f2d14a6-be2e-11e7-8950-558d1ec330aa.png)

**Comment by miadabrin** [comment]
Ignoring this wouldn't help so anyone?

**Comment by julienR2** [comment]
Hey there !
We got the same error, and after digging a bit it was due to uncontrolled drag'n'drops -> D'n'd not handled by the React-dnd directly. Since we wanted to make sure that all the dnd were controlled through React-dnd anyway, we `preventDefault` the `onDragStart` event depending on the `event.target`/`event.currentTarget`/etc..

Doesn't explain much the source of the issue, but I hope it helps !

**Comment by clytras** [comment]
I faced this issue when I've had `DndProvider` nested inside my components. Moving `<DndProvider backend={Backend}>` at the top level and wrapping the `<App/>` component with it made this error disappear.

**Comment by d07RiV** [comment]
Moved provider to the very top (even into the ReactDOM.render call), still getting the error after every hot reload and have to refresh the page.

**Comment by jjjhill** [comment]
@d07RiV did you ever find a solution? I have multiple drop targets (some nested), and have DndProvider as the top level component, and I'm getting this error on every hot-reload still.

**Comment by danteYoon** [comment]
Though [clytras 's try,](https://github.com/react-dnd/react-dnd/issues/763#issuecomment-589879466) this issue hasn't been resolved. It seems  `Invariant Violation: Expected targetIds to be registered` error still remains.

**Comment by danteYoon** [comment]
if this error only shows on "hot-reload",  problem might be resolved in production  mode, still, error free should be guaranteed before deploy..

**Comment by Xairoo** [comment]
This should be reopened. Problem appears after a hot reload when performing a dnd action.

**Comment by dieguiviti** [comment]
Make sure your imports in the file where your DND provider is being used are ordered correctly.

Ex:

WRONG:
import React from 'react'
import ReactDOM from 'react-dom'
import './index.css'
import App from './App'
**import { DndProvider } from 'react-dnd'
import { HTML5Backend as Backend } from 'react-dnd-html5-backend'**
import { AppStateProvider } from './AppStateContext'

RIGHT:
import React from 'react'
import ReactDOM from 'react-dom'
**import { DndProvider } from 'react-dnd'
import { HTML5Backend as Backend } from 'react-dnd-html5-backend'**
import './index.css'
import App from './App'
import { AppStateProvider } from './AppStateContext'

Conclusion: 
Do not import local modules before foreign modules

**Comment by kdfriedman** [comment]
Currently experiencing same problem but occurs only when I'm manually using `onDragStart` on child component which is wrapped in my `<DndProvider backend={HTML5Backend}>` parent component.

**Comment by Ho-yeong** [comment]
still occured

**Comment by adarshmishra07** [comment]
> Make sure your imports in the file where your DND provider is being used are ordered correctly.
> 
> Ex:
> 
> WRONG:
> import React from 'react'
> import ReactDOM from 'react-dom'
> import './index.css'
> import App from './App'
> **import { DndProvider } from 'react-dnd' import { HTML5Backend as Backend } from 'react-dnd-html5-backend'**
> import { AppStateProvider } from './AppStateContext'
> 
> RIGHT:
> import React from 'react'
> import ReactDOM from 'react-dom'
> **import { DndProvider } from 'react-dnd' import { HTML5Backend as Backend } from 'react-dnd-html5-backend'**
> import './index.css'
> import App from './App'
> import { AppStateProvider } from './AppStateContext'
> 
> Conclusion:
> Do not import local modules before foreign modules

This worked  for me thanks

**Comment by clytras** [comment]
@dieguiviti @adarshmishra07 There is an ESLint rule about the correct import order that does exacly that, warn you about (_or fix_) the wrong import order. Externmal module imports should always be placed before parent/sibling/current directories imports. You can read about the rule here [import/order: Enforce a convention in module import order](https://github.com/benmosher/eslint-plugin-import/blob/v2.22.1/docs/rules/order.md).

You should always use ESLint even not in auto/save mode, just to get some nice warnings/tips that will help resolve such issues.

**Comment by valtism** [comment]
Unfortunately, the workaround does not work for the larger codebase I'm working on, no matter how far up the import chain I put the imports. I would love to see this issue re-opened because it seems like something that should work regardless of import ordering.

**Comment by Xairoo** [comment]
> 
> 
> Unfortunately, the workaround does not work for the larger codebase I'm working on, no matter how far up the import chain I put the imports. I would love to see this issue re-opened because it seems like something that should work regardless of import ordering.

Totally agree. I imported the react-dnd `DndProvider` at the top level since I work with react-dnd.

```
ReactDOM.render(
	<DragAndDrop>
		<App />
	</DragAndDrop>,
	document.querySelector('#root'),
);
```
Cannot go higher =)

**Comment by ottworks** [comment]
bump

**Comment by dreamyguy** [comment]
Just wanted to mention that I get this error with a stripped-down example from DnD itself, on a NextJS app. https://react-dnd.github.io/react-dnd/examples/sortable/simple

**Comment by hlz** [comment]
I'm also having this issue with a fairly simple Next.js app. Dragging after a hot reload throws the error.

**Comment by raghurambachu** [comment]
Refresh the app/ run the app again probably this might help. For me this worked.

**Comment by valtism** [comment]
This seems to be fixed in v14.0.4 🥳

https://github.com/react-dnd/react-dnd/pull/3290

**Comment by beewolf233** [comment]
> This seems to be fixed in v14.0.4 🥳
> 
> #3290

are you sure??

**Comment by devinMcArthur** [comment]
Still experiencing this issue with v14.0.4. 

Using react-dnd in combination w/ SlateJS. Once an element is dragged, SlateJS is remounting the component. On this initial mount, the `useDrop` `handlerId` variable is not set and may be causing this error. It is functioning perfectly fine, but with NextJS this error is hard to ignore.

**Comment by beewolf233** [comment]
hello I am experiencing this issue too

**Comment by patrik-meixner** [comment]
Same for me on Next.js project.

**Comment by dimadk24** [comment]
For anybody experiencing this with NextJS's HMR, I found as a workaround to use automatic full page refresh instead of hot reload using the [live-server](https://github.com/tapio/live-server) package: the idea is to run live-server together with NextJS server and connect to live-server's Websocket from NextJS app:
1. Install [live-server](https://yarnpkg.com/package/live-server) and [concurrently](https://yarnpkg.com/package/concurrently)
2. Add this code (simplified version of [injected code from live-server](https://github.com/tapio/live-server/blob/01cd7f970439d42537bbe13b4885befb816a0446/injected.html)) to the main NextJS file (index.js or whatever):
```javascript
if (process.env.NODE_ENV === 'development') {
  if (typeof window !== 'undefined') {
    new WebSocket('ws://127.0.0.1:8080/ws').onmessage = function(msg) {
      if (msg.data === 'reload') window.location.reload()
    }
    console.log('Live reload enabled.')
  }
}
```
3. Change `dev` command to `concurrently "next dev" "live-server --no-browser"`

The drawback is that you'll entirely opt-out of NextJS's HMR and run 2 servers.

**Comment by hd-o** [comment]
This is my current working solution with Next.js, not pretty, but works for local development:

```js
// file: .scripts/monkey-patch-dnd.js

// Temporary monkey patch
// Comment-out invariant check from dnd-core
// Prevent https://github.com/react-dnd/react-dnd/issues/763

const fs = require('fs')
const path = require('path')
const hoverPath = 'node_modules/dnd-core/dist/esm/actions/dragDrop/hover.mjs'
const filePath = path.resolve(process.cwd(), hoverPath)

if (!fs.existsSync(filePath)) process.exit(1)

const content = fs.readFileSync(filePath).toString()
const invariantLineContent = `invariant(target, 'Expected targetIds to be registered.');`
const updatedContent = content.replace(invariantLineContent, '')

fs.writeFileSync(filePath, updatedContent)

console.log('• MONKEY PATCHED DND \n')

```

```jsonc
// file: package.json

{
  "scripts": {
    "postinstall": "node .scripts/monkey-patch-dnd.js"
  }
}
```

**Comment by hd-o** [comment]
This is my current working solution with Next.js, not pretty, but works for local development:

```js
// file: .scripts/monkey-patch-dnd.js

// Temporary monkey patch
// Remove invariant check from dnd-core
// Prevent https://github.com/react-dnd/react-dnd/issues/763

const fs = require('fs')
const path = require('path')
const hoverPath = 'node_modules/dnd-core/dist/esm/actions/dragDrop/hover.mjs'
const filePath = path.resolve(process.cwd(), hoverPath)

if (!fs.existsSync(filePath)) process.exit(1)

const content = fs.readFileSync(filePath).toString()
const invariantLineContent = `invariant(target, 'Expected targetIds to be registered.');`
const updatedContent = content.replace(invariantLineContent, '')

fs.writeFileSync(filePath, updatedContent)

console.log('• MONKEY PATCHED DND \n')
```

```jsonc
// file: package.json

{
  "scripts": {
    "postinstall": "node .scripts/monkey-patch-dnd.js"
  },
}
```

Note: `rm -rf .next` before starting `next dev`

**Comment by joshkel** [comment]
If I'm following these discussions correctly, there two or three common scenarios for this error message:

* Intermittently, in production builds, possibly related to load - see, e.g., #3403. I believe or hope that #3409 will fix this.
* When using hot reload with Next.js - as described by several comments here. Does anyone have a sample project that demonstrates this? I tried putting together a local test case but was unable to reproduce the error.
* When using SlateJS - [see here](https://github.com/react-dnd/react-dnd/issues/763#issuecomment-1022561727). Does anyone have a sample project or codesandbox.io page demonstrating this?

**Comment by Aromokeye** [comment]
There's a latest fix to this problem and after updating the package, the error no longer appears.

**Comment by rojiwon0325** [comment]
I 'm using it  latest version, but error is appeared. I think, this appear only in StricMode.

**Comment by brabbuss** [comment]
None of the above resolved the issue for me, but [this stack thread](https://stackoverflow.com/questions/63146094/react-dnd-expected-to-find-a-valid-target/63489336#63489336) helped me out - had to do with race conditions for me. In case it's helpful, my solution: 

I'm working in React. Placed my custom `onDrop` logic inside of a `useEffect` that only fires off when a piece of state `wasDropped` is `true`. 

`wasDropped` is set inside of the DropTarget specification (second param of the react-dnd `DropTarget` function).

**Comment by kvasa** [comment]
This issue could also appear if you are adding new DOM nodes during drag over elements, for example, based on `isOver` flag.
```
{isOver && <div .../>}
```
If you need to add special elements for a better UX I recommend having these elements already in the DOM for example with `display: none` style and only changing this style according to `isOver` flag.

**Comment by beewolf233** [comment]
> 

yes i also has this question

**Comment by SoTwinky** [comment]
Same here, anyone ?

**Comment by pushparajsingh** [comment]
if you remove strict mode in index.js file . it will solve

**Comment by PierrickMerliExt** [comment]
> if you remove strict mode in index.js file . it will solve

No Strict Mode on my website

**Comment by izhan** [comment]
We ran into this issue before and traced it to a dragged item unmounting while being dragged. I'd double check that you don't have any complex state transitions while hovering that would cause something similar

**Comment by wangjingbo-wang** [comment]
> > 
> 
> yes i also has this question

is have a solution?
