### ISSUE TITLE
drag ending prematurely

### ISSUE THREAD

**Issue by azadbolour** [react-dnd/react-dnd#766]
I have a situation in which the drag of a piece is immediately and unexpectedly aborted while I am still dragging. 

The sequence of calls to my drag source are: canDrag (returning true), beginDrag returning the item, and endDrag (with isDropped being false, as expected).

The application is a scrabble-like game, where pieces can be dragged to/from a board from/to a rack. Dragging a piece from the rack works. Dragging it from the board does not work - is aborted immediately.

In both cases I am using the same React component to represent the piece as the drag source.

I'd really appreciate any hints on how to go about debugging/troubleshooting this issue.

Thanks.

Azad

P.S. Using React 15.4.2, React DND 2.4.0, Webpack 1.12.1, and Chrome 58 on MAC OS/X.

**Comment by azadbolour** [comment]
I managed to reproduce a similar problem with a minor tweak to the Chessboard example. 

I cloned the latest react-dnd repository, and made sure the knight can be moved as expected.
Then I edited examples/00\ Chessboard/Tutorial\ App/BoardSquare.js to return true all the time for canDrop:

const squareTarget = {
  canDrop(props) {
    return true;
    // return canMoveKnight(props.x, props.y);
  },

Now when I bring up the application, I cannot drag the knight.

Not sure why this is happening. But I hope figuring out this simple test case can shed light on my original problem of inability to drag pieces.

Thanks in advance for hints on what is going on here and how to fix it.

Azad

**Comment by carlesba** [comment]
same here, but only in Firefox. Firefox stops calling canDrop after 3 times while Chrome is continuously calling it.

**Comment by ul** [comment]
I hit that problem in Firefox 58.0b4 as well. `canDrop` is called a few times and then `endDrag`, though I'm still dragging element.

**Comment by deanmaster** [comment]
Same issue here only on Firefox I'm using 52.6.0 ESR

**Comment by azadbolour** [comment]
My colleague Allen Haim (@misterfish) found the following workaround which for now is working for me. I have not, however, done exhaustive testing on all major platform x browser combinations. 

His idea is to make sure the drag item has actually moved before allowing a drop. Exactly why this solves the problem, I am not sure. 
  
Here is what my working code looks like:

    const MIN_MOVEMENT = 15;
    const vectorMagnitude = (x, y) => Math.sqrt(x ** 2 + y ** 2);
    const isMinimallyMoved = ({ x, y }) => vectorMagnitude(x, y) > MIN_MOVEMENT;

    canDrop: function (props, monitor) {
      let piece = getMonitorPiece(monitor);
      let point = props.point;
      let legal = props.isLegalMove(piece, point);
      // A workaround to avoid react dnd glitch preventing drag.
      let minimallyMoved = isMinimallyMoved((monitor.getDifferenceFromInitialOffset()));
      return minimallyMoved && legal && props.enabled;
    },
    // ...

If you do experiment with this technique, please share your findings and insights.

Cheers.

Azad

**Comment by jarben** [comment]
Not sure whether it is related but I sometimes end up here: 

![image](https://user-images.githubusercontent.com/561365/37900252-f1df90fe-30ed-11e8-9ede-2e690e95166c.png)

Which means dragging ends right after dragging starts.. Haven't been able to reproduce when exactly this happens but it seems like that some drag sessions are not finished correctly so it ends up here. 

I'd say that this is an issue inside this library as it shouldn't fail like this when this situation occurs.

**Comment by djErock** [comment]
I am experiencing this issue as well. I have a dragSource and a dropSource that are siblings in a component. They sit on top of one another and the draggable has interactive elements inside as well. Whenever I go to change the Z-index of the sibling and my drag handle is over the changed area; the drag handle is lost and the endDrag method is called terminating the drag sequence. We are getting this in Chrome. FF works without issue.

**Comment by AndriiTsarenko** [comment]
Hey.
I have a similar issue with chrome, but the root cause is different.
Hope that this information will help someone in the future.
https://stackoverflow.com/questions/59172584/javascript-dragend-event-fired-immediatly-after-dragstart

**Comment by RomanPanaget** [comment]
anyone has found a proper solution or a good explanation ?

**Comment by Guenolekikabou** [comment]
> I'm experiencing this as well. I've managed to make a small example https://codesandbox.io/s/7vmz86mpq
> It works in Firefox and Edge just fine, but doesn't work in Chrome.
> This example is also containing a workaround, replace it in `Panel.js`:
> 
> ```diff
> -let canDropIt = canDrop
> +let canDropIt = canDropSafe
> ```

Hey, having the exact same issue as your example. Did you have a solution ?

**Comment by rooks** [comment]
@Guenolekikabou What do you mean? You've quoted a solution for the problem → Instead of relying on react-dnd's state for `canDrop` I'm keeping my own state for this property. Just check out the codesanbox example I provided and yes, I'm still using this solution as a workaround for broken canDrop prop.

**Comment by binaryme** [comment]
I noted the canDrop gets cancelled because when you first drag it detects you are throwing the draggable over itself. 

My implementation includes evaluating that we are not over the same index.

` canDrop(item: any, monitor) {
        const { draggingElemIndex } = item

        const notSameIndex = draggingElemIndex !== dropIntoElemIndex
        const canDrop = notSameIndex && monitor.isOver()
        
        if (canDrop) {
          return true
        } else {
          return false
        }
 },`
