### ISSUE TITLE
Changelog for 2.4.*

### ISSUE THREAD

**Issue by renarsvilnis** [react-dnd/react-dnd#768]
Hi,
What are the changes for 2.4.*?

**Comment by kazazor** [comment]
This is highly important.
Not just that - it seems that `react-dnd-html5-backend` published version `2.4.1` while `react-dnd` is still stuck on `2.4.0` ( https://github.com/react-dnd/react-dnd/commit/fd0513ea76294a3ff4e5a3a8584d133a2b8ec765 )

Seems to be a mistake. Can someone please publish `react-dnd` as well?
