### ISSUE TITLE
warning.js: Failed propType: Calling PropTypes validators directly is not supported by the `prop-types` package. Use `PropTypes.checkPropTypes()` to call them.

### ISSUE THREAD

**Issue by huanhuan129129** [react-dnd/react-dnd#769]
I think this line caused the warning:
`export const CHILD_CONTEXT_TYPES = {
  dragDropManager: PropTypes.object.isRequired,
};`

https://github.com/react-dnd/react-dnd/blob/master/packages/react-dnd/src/DragDropContext.js#L9

**Comment by criticerz** [comment]
Upgrading React to 15.5.4 caused this warning to stop showing for me.

**Comment by CrocoDillon** [comment]
For me this warning disappeared after updating `prop-types` 15.5.8 to 15.6.0... after I already had updated React to latest 15.* without any luck
