### ISSUE TITLE
The prop connectDragSource  is undefined?

### ISSUE THREAD

**Issue by dandingol03** [react-dnd/react-dnd#771]
<b>Hi</b>
here is my case :
i write a component which i have named `View`,and it is also it's responsibility to render it's children component,which consists of `View` and other component.That's all,the whole components' level is controlled to 2.
For example , it may looks like:
```
<View>
  <Text/>
  <View/>
  <Image/>
</View>
```
while i render the `View` in second level,it just throw an error:<b>connectDropTarget is not a function</b> and a warning :<b>The prop connectDragSource  is undefined?</b>

**Comment by diiq** [comment]
Can you share your code, or make a minimal example that shows the error, or at least give more details about how you're defining View? You've not shared enough information to make much of a diagnosis.
