### ISSUE TITLE
Drag and drop not working in Firefox

### ISSUE THREAD

**Issue by carlesba** [react-dnd/react-dnd#778]
I can't drag elements when using Firefox in my app. I've tried with the chess example and seems not to be working either.

First time you try to drag, the dragged element seems to loose opacity (like when it's being dragged) but it doesn't move. Then you try again and the console shows the error: 

`Error: Cannot call beginDrag while dragging`
 
![dnd-firefox](https://cloud.githubusercontent.com/assets/1178459/26446733/9f7eab6c-4145-11e7-95b7-6f886c9858aa.gif)

*Using Firefox v53.0.3 (64 bits) in macOS 10.12.5*

**Comment by ktosiek** [comment]
I think I have this problem - it works on 54.0b8, but DnD can hang on 54.0a2 (Developer Edition).

**Comment by jnmandal** [comment]
Also seeing this in FF 54.0a2 (2017-04-18)

![screen shot 2017-06-01 at 6 50 13 pm](https://cloud.githubusercontent.com/assets/7440196/26705358/425c8a38-46fb-11e7-90f6-6afb9c760e2b.png)

**Comment by sAs59** [comment]
In my case example with chess works just fine. But, [Drag Around > Naive](http://react-dnd.github.io/react-dnd/examples-drag-around-naive.html) doesn't work.

Firefox 53.0.3 (64-bit)

**Comment by ktosiek** [comment]
yeah, it works on FF 53 for me too

**Comment by carlesba** [comment]
It still seems very random. Has someone any clue about what's happening there?

**Comment by senluchen2015** [comment]
I am running into this problem as well on the FF 54.0 both in the demo page and also using these versions locally: 
```
"react-dnd": "2.4.0",
"react-dnd-html5-backend": "2.4.1", 
```

I have narrowed down the problem to HTML5Backend.js. The "dragenter" event is not being called for some reason.

**Comment by wldcordeiro** [comment]
I'm seeing this issue on Firefox Nightly as well.

**Comment by carlesba** [comment]
Might this be related? https://bugzilla.mozilla.org/show_bug.cgi?id=804036

**Comment by lvpro** [comment]
Can confirm this is still an issue as of FF 56 on Linux.

Trying a simple example:  https://react-dnd.github.io/react-dnd/examples-sortable-simple.html, a line item will only move 1 position and then stop.

**Comment by yankopetrov** [comment]
@carlesba yes i think. Tried beta Nightly FF and the drag is working.

Can someone else confirm the bug is gone with FF Nightly(https://nightly.mozilla.org/)?

**Comment by carlesba** [comment]
I solved the issue on my side by adding a [customDragLayer](https://react-dnd.github.io/react-dnd/examples-drag-around-custom-drag-layer.html). Firefox had some issues when keeping the drag once started but by adding a view in the customDragLayer the drag didn't stop.

Hope this helps you.

**Comment by koox00** [comment]
@carlesba I am facing the exact same issue, can you explain what you mean by:
> adding a view in the customDragLayer

**Comment by carlesba** [comment]
@koox00 
Create a component using the HOC `DragLayer` (like [in this example](https://github.com/react-dnd/react-dnd/blob/master/examples/02%20Drag%20Around/Custom%20Drag%20Layer/CustomDragLayer.js))

There you can customize what item to drag when the drag event begins.

I'm not saying this was the problem but it solved my case.

**Comment by koox00** [comment]
@carlesba Ok I see.
 I am using a `customDragLayer`, but moving an item upwards in a sortable list (FF only) after first item the drag stops.

**Comment by carlesba** [comment]
@koox00 another think was happening is that the element that starts the drag _becomes not accessible for the mouse_ and this seems to be bad for keeping regular event flow in react-dnd. So maybe you can try to add some CSS to the handler that starts the sequence.
