### ISSUE TITLE
DropTarget hover only fires when pointer hovers over the component, not the dragged item box

### ISSUE THREAD

**Issue by vladar** [react-dnd/react-dnd#779]
There is a line in docs which says:

```
hover(props, monitor, component): Optional. Called when an item is hovered over the component
```

But in my tests (with HTML5 backend) hover is only fired when **mouse pointer** hovers over the drop target component. I'd expect that any boundary of the item crossing drop target would trigger this event.

Looks like it is HTML5 API behavor, but is there any way to make hover behave as I described (and as described in docs)?

The use case I have is that I need to drag and drop relatively big items and dragging point is usually at item's header, so the user experience when moving such items **up** is OK, but moving **down** is a pain, because you often have to scroll the page to drop.

**Comment by goldo** [comment]
We have the same problem here. Is there a way ?

**Comment by Gywem** [comment]
I need a solution on this as well.

**Comment by kafein** [comment]
@vladar @goldo @Gywem

have you found any solution?

**Comment by kafein** [comment]
@gaearon First, I'm sorry to bother you. Is there any solution for this situation?

**Comment by goldo** [comment]
@kafein  nope, juste using smaller elements to make it look nicer. Havent had time to try others things

**Comment by Pavel910** [comment]
@vladar I know it's an old thread but have you found a solution to this problem? Thx.

**Comment by schoettler** [comment]
Anyone figured this out yet?

**Comment by bergowic** [comment]
Is there any solution now?

**Comment by avines002** [comment]
Hi there.. trying to figure this out as well.. any update?

**Comment by Artem29383** [comment]
any solution? Why it trigger only on mouse cursor? 
Event onDragEnter must trigger on element, not mouse cursor
**A dragged element enters the drop target**
not **A dragged element with MOUSE CURSOR enters the drop target**
