### ISSUE TITLE
react-dnd 2.4.1 not published to npm

### ISSUE THREAD

**Issue by dschep** [react-dnd/react-dnd#781]
As @kazazor observed in #768, `react-dnd=2.4.1` isn't on npm. This should probably be remedied as the it fixes deprecation warnings about `React.createClass` and `React.PropTypes`.

**Comment by kazazor** [comment]
Can one of the maintainers of the repo share a reason for that?
Was that a mistake? Seems like something should be addressed fast since it's just a publish that needs to happen..
