### ISSUE TITLE
Typing issue with @DragDropContext decorator

### ISSUE THREAD

**Issue by sundriver** [react-dnd/react-dnd#782]
Hi There,
 I am new to react-dnd, I am using typescript to build up my first test project with dnd.

@DragDropContext(HTML5Backend)
export class DragTest extends React.Component<{}, undefined> {
    render() {return (<div></div>);}
}

And I get the following compile typing error:

```
 TS1238: Unable to resolve signature of class decorator when called as an expression.
  Type 'ContextComponentClass<{}>' is not assignable to type 'typeof DragTest'.
    Type 'ContextComponent<{}, any>' is not assignable to type 'DragTest'.
      Types of property 'render' are incompatible.
        Type '() => Element | null' is not assignable to type '() => Element'.
          **Type 'Element | null' is not assignable to type 'Element'.**
            Type 'null' is not assignable to type 'Element'.
```

I appreciate your comment, Thanks

**Comment by sundriver** [comment]
I get the same error with this sample as well:

https://github.com/react-dnd/react-dnd/blob/190d43db103483af5d4cadbf20527638bf2b134c/examples/05%20Customize/Handles%20and%20Previews/Container.js

**Comment by kaidez** [comment]
Same with me.

**Comment by arvind1234** [comment]
Running into same issue, with the decorator typings. It also doesn't allow for any private methods to be present in the component class.

Unable to resolve signature of class decorator when called as an expression.
  Type 'ContextComponentClass<DnDTestProps>' is not assignable to type 'typeof DnDTest'.
    Type 'ContextComponent<DnDTestProps, any>' is not assignable to type 'DnDTest'.
      Property 'renderRow' is missing in type 'ContextComponent<DnDTestProps, any>'.

**Comment by arvind1234** [comment]
FWIW, I don't get the error if I use the ES6 way:
export default DragDropContext(HTML5Backend)(DnDTest);

**Comment by JohannesKlauss** [comment]
Any updates on this issue? I encounter the same exact thing.

**Comment by abelkbil** [comment]
@JohannesKlauss I am also on same page

```
import * as React from 'react';
import { SignalTag } from '../../../../../Stores/DashboardStore';
import { DragSource } from 'react-dnd';

interface Props {
  item: SignalTag;
}
const Types = {
  CARD: 'card'
};

const cardSource = {
  beginDrag(props: Props) {
    const item = { name: props.item.name };
    return item;
  },
};

// Use the decorator syntax
@DragSource(Types.CARD, cardSource, (connect, monitor) => ({
  connectDragSource: connect.dragSource(),
  isDragging: monitor.isDragging()
}))

export class SignalTagItem extends React.Component<Props, {}>  {
  
  render() {
    const { item } = this.props;
    const connectDragSource = DragSource.connectDragSource;
    return connectDragSource(
      <div className="signalTag" >
        <span className="tagName">{item.name} <span className="tag">{item.tag}</span></span><br/>
        <span className="tagDescription">{item.label}</span>
      </div>
    );
  }
}
export default SignalTagItem;
```
Parent is in DragDropContext
```

import * as React from 'react';
import { observer, inject } from 'mobx-react';
import { withRouter } from 'react-router-dom';
import HTML5Backend from 'react-dnd-html5-backend';
import { DragDropContext } from 'react-dnd';


@DragDropContext(HTML5Backend)
@inject('dashboardStore')
@withRouter
@observer
export default class SingleDashboard extends React.Component<Props, {}> {
  
  render() {
    
    if (this.dashboardStore && this.dashboardStore.dashboardDataLoaded) {
      return (
        <div className="container-fluid">
          <div className="row">
            <div className={this.dashboardStore.config.dashboardPage.editClass.mainWrapper}>
              <SingleDashboardHeaderNav />
              <SingleDashboardGrid/>
            </div>
            <div className={this.dashboardStore.config.dashboardPage.editClass.rightWrapper}>
              <SingleDashboardSideNav />
            </div>
          </div>
        </div>
      );
    } 
    return ( <Loader/> );
    
  }
}

```

I tried this too 

> export default DragDropContext(HTML5Backend)(SingleDashboard);

The error I get is 

> react_dnd__.DragSource.connectDragSource is not a function

Thanks and appreciation for your support.

**Comment by tsriram** [comment]
@abelkbil not sure why you're doing this:
```
const connectDragSource = DragSource.connectDragSource;
```
`connectDragSource` will be passed as a prob to the decorated component by `react-dnd`.

Can you check if this works?
```
const { item, connectDragSource } = this.props;
```

**Comment by abelkbil** [comment]
@tsriram , Thanks for support.
I have tried it and get this lint error. I have used react-dnd in jsx but in typescript this is a pain.

> [ts] Type 'Readonly<{ children?: ReactNode; }> & Readonly<Props>' has no property 'connectDragSource' and no string index signature.
> [ts] 'connectDragSource' is declared but its value is never read.

You might have noticed my interface for pros

```
interface Props {
  item: SignalTag;
}
```
and 
`export class SignalTagItem extends React.Component<Props, {}>  {`

decorated component is not working. ES6 style also not working. The identified issue is related to `Props` interface missing `connectDragSource`
How is it in your typescrpt code ?

**How I Solved :?**
I added optional property to Props interface;

```
interface Props {
  item: SignalTag;
  connectDragSource?: any;
}
```
Is this the correct way.
I inject the Redux store to props similarly 

```
interface InjectedProps extends Props {
  dashboardStore: dashboardStoreType;
}

constructor(props: Props) {
    super(props);
    this.dashboardStore = this.injected.dashboardStore;
  }

  get injected() {
    return this.props as InjectedProps;
  }
```
Please comment on above.
Thank you again. @tsriram

**Comment by tsriram** [comment]
@abelkbil yeah, that should work. I think ideally you'd want to install `@types/react-dnd` and extend the interface that it exports for DragSource. I'm not sure if `@types/react-dnd` has definitions for all types. I think it should be okay to define `connectDragsource` as an optional prop as yourself - may be you can define it as `Function` instead of `any`.
