### ISSUE TITLE
TypeScript - Property is missing in type DndComponent

### ISSUE THREAD

**Issue by sundriver** [react-dnd/react-dnd#785]
Hi,

 Thanks for the react-dnd library, very nice work.
 I have the following two typing issues with the following sample code. I appreciate if someone could tell me what am i doing wrong ?

```
export interface TestProps {

}
@DropTarget<TestProps>("TEST", {
    drop(props: TestProps) {
    }
}, (connect, monitor) => {
    return { dragTarget: connect.dropTarget() };
})
export class TestComponent extends React.Component<TestProps, undefined> {
    constructor(props: TestProps) {
        super(props);
    }
    someHelper() {
        return (<h1>Test</h1>);
    }
    render() {
        return (this.props as any).dragTarget(this.someHelper());
    }
}

```
1. Is there a better way of doing 
`        return (this.props as any).dragTarget(this.someHelper());`
2. The following code produces the error below, any ideas?
`
    TS1238: Unable to resolve signature of class decorator when called as an expression.
  Type 'DndComponentClass<TestProps>' is not assignable to type 'typeof TestComponent'.
    Type 'DndComponent<TestProps, any>' is not assignable to type 'TestComponent'.
      Property 'someHelper' is missing in type 'DndComponent<TestProps, any>'.
`

Thanks

**Comment by VinceAnity** [comment]
Any luck? I get the same issue error on `@DragDropContext`.

**Comment by LeopoldLerch** [comment]
same here, I only managed to use constructor and render method inside Component. Any other function (like componentwillreceiveupdateprops) are throwing this error

**Comment by LeopoldLerch** [comment]
if you uninstall the typings for react-dnd, the error is gone and it works. However, of course, you loose intellisense, just a workaround

**Comment by lukescott** [comment]
I'm having the same issue. Anything added inside the React Component class causes an error - even the render function. An empty class is the only thing that doesn't produce an error. As far as I can tell it happens with DragSource, DropTarget, and DragDropContext decorators.

**Comment by Tsourdox** [comment]
Yeah, I have the same issue.. has anyone solved this?

**Comment by lukescott** [comment]
I gave up on the decorator style. I just use them as functions. You can use the lodash flow function to avoid the nesting.

**Comment by abelkbil** [comment]
@sundriver , @lukescott , I do face this issue, I removed decorator. Still component method not defined issue arise. Could you please share you sample code.

```
Interface Props {
    // tslint:disable-next-line:no-any
    connectDropTarget?: any;

}

interface InjectedProps extends Props {
  dashboardStore: DashboardStore;
}

const dashboardDropTarget = {

    // tslint:disable-next-line:typedef
    drop(props, monitor, component) {
        const item = monitor.getItem();
        component.addDropedItem(item);
        return { moved: true };
    }
};

// tslint:disable-next-line:typedef
function collect(connect, monitor) {
    return {
        connectDropTarget: connect.dropTarget(),
        canDrop: monitor.canDrop(),
        itemType: monitor.getItemType()
    };
}

@inject('dashboardStore')
@observer
class EditDashboardGrid extends React.Component <Props, {}> {
    static contextTypes = {
        addDropedItem: PropTypes.func
    };

    dashboardStore: DashboardStore;

    constructor(props: Props) {
        super(props);
        this.dashboardStore = this.injected.dashboardStore;
    }

    get injected() {
        return this.props as InjectedProps;
    }


    // tslint:disable-next-line:no-any
    addDropedItem(item: any) {
        alert(item);
    }
    render() {
        
        if (!this.dashboardStore.isLayoutLoading) {
            const { connectDropTarget } = this.props;
            return connectDropTarget  (
            <div id="widgets-container">
                <div className="startboard-layout edit-flowlayout">
                    <div className="flowlayout-childcontainer" />
                </div>
            </div>
            );
        }
        return (<Loader/>);
   
    }
}
export default DropTarget(['WIDGET', 'SIGNAL'], dashboardDropTarget, collect)(EditDashboardGrid);
```

Thank you.

**Comment by lukescott** [comment]
I don't use react-dnd anymore. I bit the bullet and implemented my own dnd solution as react-dnd was overkill for my needs, and I needed more direct control. But my code looked something like this:

```ts
export default
flow(DropTarget<Props>(...), DragSource<Props>(...))(
class Foo extends React.Component {
// ...
})
```
