### ISSUE TITLE
How to ensure that the 'drag' action handler has completed before the 'drop' action handler executes?

### ISSUE THREAD

**Issue by joetidee** [react-dnd/react-dnd#786]
I have a series of lists, for brevity they structure is pretty standard:

```
<ListContainer>
    <List>
        <Item />
        <Item />
    </ List>
    <List>
        <Item />
        <Item />
    </ List>
</ ListContainer>
```

An `<Item />` can be moved between each `<List>`, but the `<List>` order cannot be changed. 

I have the following `hover` method in the `<Item />` components. The `moveBlock` function will update the `Lists` state in the `<ListContainer>` component, where the `Lists` state maintains the order of the `<List>` components and the `<Item />` components within them:

```
const blockTarget = {
    hover(targetProps, monitor){
        ...
        targetProps.moveBlock(sourceBlockInstanceId, targetBlockInstanceId);
    }
};
```

I also have the following methods in the `<Item />` components, whereby the `updateListsInStore()` function will save the previously mentioned `Lists` state to a location within the Redux store.

```
const blockSource = {
    beginDrag(props) {
        return {
            ...
        };
    },
    endDrag(props, monitor) {
        if( monitor.didDrop() ){
            props.updateListsInStore();
        }
    }
};
```

I am concerned that `updateListsInStore()` will access the `Lists` state before the `moveBlock()` has finished updating it. Is there a way to ensure that this does not happen?

**Comment by sho13** [comment]
I am also having a similar problem, upon `endDrag`'s completion, for some reason the `props` in endDrag becomes undefined, although I am working on a removal of the dragged Item upon being dragged off.  Would love a solution to this!
