### ISSUE TITLE
Error in npm install

### ISSUE THREAD

**Issue by charlesondr** [react-dnd/react-dnd#791]
after extract react-dnd while npm install i got below error,

react-dnd-master@ postinstall C:\Rakesh\FusionUI\gitHub\react-dnd-master
> lerna bootstrap

lerna info version 2.0.0-rc.5
lerna info Bootstrapping 4 packages
lerna info lifecycle preinstall
lerna info Installing external dependencies
lerna ERR! execute Error: spawn yarn ENOENT
lerna ERR! execute     at notFoundError (C:\Rakesh\FusionUI\gitHub\react-dnd-master\node_modules\cross-spawn\lib\enoent.js:11:11)
lerna ERR! execute     at verifyENOENT (C:\Rakesh\FusionUI\gitHub\react-dnd-master\node_modules\cross-spawn\lib\enoent.js:46:16)
lerna ERR! execute     at ChildProcess.cp.emit (C:\Rakesh\FusionUI\gitHub\react-dnd-master\node_modules\cross-spawn\lib\enoent.js:33:19)
lerna ERR! execute     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
lerna ERR! execute  callback with error
lerna ERR! execute  { Error: spawn yarn ENOENT
lerna ERR! execute     at notFoundError (C:\Rakesh\FusionUI\gitHub\react-dnd-master\node_modules\cross-spawn\lib\enoent.js:11:11)
lerna ERR! execute     at verifyENOENT (C:\Rakesh\FusionUI\gitHub\react-dnd-master\node_modules\cross-spawn\lib\enoent.js:46:16)
lerna ERR! execute     at ChildProcess.cp.emit (C:\Rakesh\FusionUI\gitHub\react-dnd-master\node_modules\cross-spawn\lib\enoent.js:33:19)
lerna ERR! execute     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
lerna ERR! execute   errno: 'ENOENT',
lerna ERR! execute   code: 'ENOENT',
lerna ERR! execute   syscall: 'spawn yarn',
lerna ERR! execute   killed: false,
lerna ERR! execute   stdout: '',
lerna ERR! execute   stderr: '\'yarn\' is not recognized as an internal or external command,\r\noperable program or batch file.\r\n',
lerna ERR! execute   failed: true,
lerna ERR! execute   signal: null,
lerna ERR! execute   cmd: 'yarn install --mutex network:42424',
lerna ERR! execute   timedOut: false }
lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.
(node:10692) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): Error: spawn yarn ENOENT
(node:10692) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 6): Error: spawn yarn ENOENTtely.

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN react-frame-component@1.1.0 requires a peer of react@^15.5.9 but none was installed.
npm WARN react-frame-component@1.1.0 requires a peer of react-dom@^15.5.9 but none was installed.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! react-dnd-master@ postinstall: `lerna bootstrap`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-dnd-master@ postinstall script 'lerna bootstrap'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-dnd-master package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     lerna bootstrap
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-dnd-master
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-dnd-master
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Rakesh\FusionUI\gitHub\react-dnd-master\npm-debug.log

**Comment by luyao-wang** [comment]
You don't have yarn installed.

To install yarn, please refer to this page : https://yarnpkg.com/lang/en/docs/install/

For example you can use homebrew to install yarn : brew install yarn

**Comment by avidrucker** [comment]
This may be a Babel issue. I spent a few hours trying to resolve this via installing Yarn but with no resolution. May we get a final word on this issue? @charlesondr Were you able to resolve this issue?
