### ISSUE TITLE
node.addEventListener is not a function and React DnD and Redux

### ISSUE THREAD

**Issue by MBehtemam** [react-dnd/react-dnd#792]
in my app i have 2 part , one is a drag source and other is drop target. when user drag something on drop target , drop target detect which type is dropped and then add something to Redux store, after that in DropTarget with javascript map function i try to it iterate and create new element with React.createElement on this. but when component dropped on DropTarget i know which of components is dropped ind `drop()` but i get this error : 

``` 
HTML5Backend.js:191 Uncaught TypeError: node.addEventListener is not a function
    at HTML5Backend.connectDropTarget (HTML5Backend.js:191)
    at reconnectDropTarget (createTargetConnector.js:32)
    at connectDropTarget (createTargetConnector.js:54)
    at wrapConnectorHooks.js:36
    at StageRenderComponents.render (StageRenderComponents.js:41)
    at ReactCompositeComponent.js:796
    at measureLifeCyclePerf (ReactCompositeComponent.js:75)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (ReactCompositeComponent.js:795)
    at ReactCompositeComponentWrapper._renderValidatedComponent (ReactCompositeComponent.js:822)
    at ReactCompositeComponentWrapper._updateRenderedComponent (ReactCompositeComponent.js:746)
﻿

​```

and this is my DragSource : 

```
     import React, { Component } from 'react'
     import { Col, Row } from 'antd'
     import { DropTarget } from 'react-dnd';
     import DraggableItems from '../../../../../shared/DraggableItems'
     import StageComponentCreator from './StageComponentCreator'

      const boxTarget = {
          drop(props, monitor, component) {
           if(typeof monitor.getItem() !== 'undefined'){
           props.addComponent(monitor.getItem(),props.activitySelectedId)
          }
       },
         // hover(props, monitor, component){
          // }
          }

       const collect = (connect, monitor) => ({
            connectDropTarget: connect.dropTarget(),
              isOver: monitor.isOver(),
              isOverCurrent: monitor.isOver({ shallow: true }),
              didDrop:monitor.didDrop(),
              dropResult : monitor.getDropResult()
        })

          class StageRenderComponents extends Component {
           constructor(props) {
                   super(props)
                      this.renderComponents = this.renderComponents.bind(this)
                   }
                renderComponents() {
                return this.props.activity.components.map((component, i) => (
                   <StageComponentCreator component={component} i={i} {...this.props}/>
                   ))
               }
                    render() {
                    const { connectDropTarget,dropResult } = this.props;
                    return connectDropTarget(
                          this.props.activity.components.length !== 0 ? this.renderComponents() : <div style={{ minHeight: "100px" }}>No Component</div>
              )
               }
         }
            export default DropTarget(DraggableItems.DESINGER_COMPONENT, boxTarget, collect)
              (StageRenderComponents)
```
also i have DragDropContext in High Level , and ```props.addComponent``` is an action that add something to redux store

**Comment by abelkbil** [comment]
@MBehtemam How did you pass the drop item to State management ? can you share the logic code. Much Thanks
