### ISSUE TITLE
Wrong drag preview offset when dragSource is outside dragPreview box.

### ISSUE THREAD

**Issue by iamjager** [react-dnd/react-dnd#793]
Hi, first of all — thanks for a great job done! It seems, however, that I found some corner-case issue which I'd like to report.

I'm currently trying to create a draggable component with its drag handle (connect via `connect.dragSource()`) being placed outside of the component's box (using absolute positioning). Everything works fine, but drag preview seems to receive wrong offset coordinates when dragging begins. After quick code review, I believe the issue to be inside `react-dnd-html5-backend:OffsetUtils:getDragPreviewOffset` function: you can see that coordinates of a node connected via `connect.dragPreview()` are being used to define ghost's position.

I'm not completely sure whether it's an actual bug that needs to be fixed or there just has to be some workaround to set ghost with a proper offset. I would appreciate any help, thanks in advance.

**Comment by goldo** [comment]
👍  I'm having the same issue, with a `position:absolute` and an `overflow-x: hidden` for scrolling

**Comment by DenisBelkin** [comment]
Did someone resolved this problem?
