### ISSUE TITLE
Using React-DnD in multiple "views"

### ISSUE THREAD

**Issue by wldcordeiro** [react-dnd/react-dnd#794]
I'm trying to use React-DnD in my app and I've run into this error.

> 17:06:23.695 Error: Cannot have two HTML5 backends at the same time. HTML5Backend.js:88

Now I'm led to believe this is because I have multiple backends, but I'm not sure how I can work around this. I have two views one that is currently wired up with react-dnd and another that I'm trying to add react-dnd to. The goal is to be able to drag and drop a file on to the latter view and have react-router redirect to the former view with the file(s) that were dropped.

How would I go about getting react-dnd to reuse the backend?

**Comment by theTechie** [comment]
#708
