### ISSUE TITLE
issue while running npm start

### ISSUE THREAD

**Issue by charlesondr** [react-dnd/react-dnd#798]
Hi Team,

I am getting this issue while running npm start

> react-dnd-master@ start c:\Rakesh\FusionUI\gitHub\react-dnd-master
> ./scripts/startSiteDevServer.sh

'.' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! react-dnd-master@ start: `./scripts/startSiteDevServer.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-dnd-master@ start script './scripts/startSiteDevServer.sh'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-dnd-master package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./scripts/startSiteDevServer.sh
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-dnd-master
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-dnd-master
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\Rakesh\FusionUI\gitHub\react-dnd-master\npm-debug.log

**Comment by darthtrevino** [comment]
Try using this in the WSL. I don't think we're going to support windows natively anytime soon.
