### ISSUE TITLE
@DropTarget @DragSource gives unexpected token no matter what I try

### ISSUE THREAD

**Issue by sThig** [react-dnd/react-dnd#804]
I am learning React.js and have been trying utilize the 
`@DragSource(type, spec, collect)
export default class MyComponent {
  /* ... */
}
`

but keep coming up with an unexpected token.  I have poured over all docs, done searches here and asked on StackO but come up with nothing for an answer that works (I've tried plenty of things).  

I tried adding 
`  "stage": 0,` to my package.json, installed plugins, tried writing it in ES6 (which also opens up a new can of worms).  For now I'd just be happy to utilize the @DragSource and @DropTarget syntax.  Any help here would be great, thank you! :)

**Comment by JimTheMan** [comment]
I am using Es6 but still getting "Unexpected token" errors with the @ sign. How can I fix this?

**Comment by rhinoceraptor** [comment]
You need the decorators syntax for Babel:

[https://babeljs.io/docs/plugins/transform-decorators/](https://babeljs.io/docs/plugins/transform-decorators/)

Alternatively, since ```DragSource``` is just a higher order component, you can use it like this:

```
class MyComponent { /* ... */ }

export default DragSource(type, spec, collect)(MyComponent);
```
