### ISSUE TITLE
dropTarget, item not dropping

### ISSUE THREAD

**Issue by shofaizi** [react-dnd/react-dnd#812]
item is not being dropped at target, disappears.

**Comment by webchaz** [comment]
example?

**Comment by phantom0424** [comment]
I met the same problem

**Comment by shofaizi** [comment]
is there suppose to be an event handler to drop the item?

**Comment by augbog** [comment]
Can you provide the context for this issue and some code? If the question is if there is an event handler to drop the item, the answer is [yes, see the docs for a drop function](https://react-dnd.github.io/react-dnd/docs-drop-target.html)
