### ISSUE TITLE
Intermittent no drag, when using redux

### ISSUE THREAD

**Issue by webchaz** [react-dnd/react-dnd#816]
I'm using redux for some events, specifically I have `START_DRAGGING_FIELD` and `STOP_DRAGGING_FIELD` redux actions that are dispatched in `beginDrag` and `endDrag`.

Everything works as expected, however in some cases, randomly, these actions still get dispatched, however I'm unable to actually drag the component.  In other words, `beginDrag` is  being called, dispatching my action, however I'm unable to actually drag - it just doesn't do anything.

When I remove these actions, everything works as expected.  `beginDrag` is called and always, the item is dragging as expected.  

Any idea what could be causing this or if there's some nuances with using Redux and react-dnd that I can account for?

Thanks

**Comment by webchaz** [comment]
Also, the mouse cursor seems to get stuck as a vertical resize pointer.

![](https://i-msdn.sec.s-msft.com/dynimg/IC725678.png)

**Comment by bongione** [comment]
I had something similar happening in the past when I dispatched the Redux end drag action on the DropTarget only. The only guaranteed endDrag call is when you define the DragSource, as far as I'm aware, so it's not a bad idea to put a failsafe end drag action there.

```
myDragSource = {
  beginDrag: ...

  endDrag: (props. monitor) => {
     if (!monitor.didDrop()) dispatchYouReduxAction
  }
}
```
