### ISSUE TITLE
Add an element dynamically

### ISSUE THREAD

**Issue by SmashedBird** [react-dnd/react-dnd#817]
Is there any feature allowing me to create a new card and push it to a selected container?
Right now I can only move existing cards, but the container doesn't refresh when the redux store of my application updates.

**Comment by pfarnach** [comment]
@SmashedBird  Did you ever figure this out?

**Comment by SmashedBird** [comment]
@pfarnach No, if I remember correctly we had to do something a bit wacky like reloading the entire component with the extra card.

**Comment by dominikgronkiewicz** [comment]
Not sure if my problem was 100% same as yours. In my case DragSource and DropTarget were the same component. I had to edit second parameter in 'DropTarget' decorator (cardTarget object in examples)

**Comment by rblalock** [comment]
Im def. seeing this right now.
