### ISSUE TITLE
expose isDragging to DropTargetMonitor

### ISSUE THREAD

**Issue by jedwards1211** [react-dnd/react-dnd#818]
I want to make a drop target that appears on top of other content once the user starts dragging something.

But `DropTargetMonitor` doesn't provide an `isDragging` method, so it's basically impossible for me to do this without some kind of ugly hack.  Why was `isDragging` excluded from `DropTargetMonitor`?

**Comment by subins** [comment]
You can use monitor.isOver()

**Comment by jedwards1211** [comment]
@subins `isOver` won't help with what I'm trying to do.  I want the drop target to be `display: none` when the user isn't dragging and `display: block` while they are dragging, even if `monitor.isOver()` is false.

**Comment by jedwards1211** [comment]
The hack I implemented was to put `redux-dnd`'s store on context as `dndStore` and then `connect` to it to get the drag state.  Not a very happy solution...

**Comment by subins** [comment]
Ok, Can you use a combination of Drag Source Specification methods like beginDrag, endDrag, isDragging. May be trigger a redux action that toggles a store boolean to indicate some one is dragging something.?

**Comment by jedwards1211** [comment]
@subins I could do that, though I like that workaround less than just connecting to `react-dnd`'s store directly...

**Comment by jedwards1211** [comment]
Ultimately, I think `react-dnd` should expose `isDragging` to drop targets.

**Comment by theTechie** [comment]
@jedwards1211 - have you wondered how it's done in the chessboard tutorial? 

There is a yellow overlay shown on the boxes indicating possible moves (i understand this is what you want to do; instead hide/show an element ?)

Looks like we are using `!isOver && canDrop`

https://github.com/react-dnd/react-dnd/blob/master/examples/00%20Chessboard/Tutorial%20App/BoardSquare.js#L70

**Comment by subins** [comment]
@theTechie His case is different, Drop Targets are hidden by default. So isOver wont be triggerred unless he change it to display block when dragging happens. Thats why he needs isDragging in drop target monitor.

**Comment by jedwards1211** [comment]
@theTechie oh.  The meaning of `canDrop` was kind of ambiguous to me, I think the docs are wrong (emphasis mine):

> canDrop(): Returns true if no drag operation is in progress, and the owner's canDrop() returns true or is not defined.

That says "if **no** drag operation is in progress", shouldn't it be "if a drag operation **is** in progress"?

**Comment by jedwards1211** [comment]
@theTechie I PRed corrections to the docs here: https://github.com/react-dnd/react-dnd/pull/824

**Comment by jedwards1211** [comment]
@subins it sounds like I can use `canDrop` to control whether the drop targets are visible.  Then when they're visible it's possible for `isOver` to be triggered.

**Comment by jedwards1211** [comment]
Closing this, as my PR for the docs was merged.
