### ISSUE TITLE
Release/npm publish issue?

### ISSUE THREAD

**Issue by bebbi** [react-dnd/react-dnd#829]
Latest version published on npm is still 2.4.0, and in github the latest tag is called "vundefined"

**Comment by olavk** [comment]
Yes, i'm also having trouble with the NPM package. It seems that **react-dnd-html5-backend** NPM package is still pointing to the [legacy repo](https://github.com/react-dnd/react-dnd-html5-backend). The html5-backend in this monorepo has some bugfixes which I am missing

**Comment by ms88privat** [comment]
Any news here? Having the same problem right now.

**Comment by ms88privat** [comment]
What about now?

**Comment by darthtrevino** [comment]
So even though our Lerna setup is configured to use a single version across libraries, it won't publish a library if there have been no changes to it. That being said, there are some updates that need to be released, and I plan on cutting a new version today.
