### ISSUE TITLE
The board is not displayed correctly

### ISSUE THREAD

**Issue by PhucNgo1711** [react-dnd/react-dnd#830]
![screen shot 2017-07-16 at 11 35 35 pm](https://user-images.githubusercontent.com/14838084/28254941-971f04cc-6a7f-11e7-90b1-7150bb0f8b07.png)
I followed the tutorial and got the exact js code (ES6), but the board is not displayed correctly.

It's blue because I changed only 2 lines of code in Square.js to make it show.
```
const backgroundColor = black ? 'black' : 'blue';
const color = black ? 'blue' : 'black';
```

**Comment by m2mathew** [comment]
Try giving the `<Board />` this css property:

`height: '100vh',`

That is how I got mine to properly display.

**Comment by jess010** [comment]
Thanks @m2mathew, this was very helpful!
