### ISSUE TITLE
Sortable example doesn't work by passing ref

### ISSUE THREAD

**Issue by TrevorHinesley** [react-dnd/react-dnd#831]
The example is:

```
return connectDragSource(connectDropTarget(
      <div style={{ ...style, opacity }}>
        {text}
      </div>
    ));
```

But using the alternative ways to connect, such a passing ref (using innerRef because I'm using [`styled-components`](https://github.com/styled-components/styled-components)), if I do:

```
return (
      <MyElement 
        innerRef={instance => connectDragSource(connectDropTarget(findDOMNode(instance)))}
        style={{ ...style, opacity }}
      >
        {text}
      </MyElement>
);
```

Only the inner call works (in this case, `connectDropTarget`, but if I swap `connectDropTarget` and `connectDragSource`, then only `connectDragSource` will work).

This works, though:

```
return (
      <MyElement 
        innerRef={instance => {
          const domNode = findDOMNode(instance)
          connectDragSource(domNode)
          connectDropTarget(domNode)
        }}
        style={{ ...style, opacity }}
      >
        {text}
      </MyElement>
);
```

Any reason why?

**Comment by noosxe** [comment]
Any news on this issue ?

**Comment by rholliger** [comment]
It would be great if React DnD works with Styled-Components (with innerRef) and not only native div elements.
