### ISSUE TITLE
Wrong dragPreview in Chrome

### ISSUE THREAD

**Issue by tTwisTt** [react-dnd/react-dnd#832]
1) Screenshot below shows strange issue related to dragPreview. In my case draggable table row node is both source and target. For some reasons drag preview contains not only source node screenshot, but all rows below too! In the same time drag operation is called only for 1 source and swap in drop handler works fine.

![image](https://user-images.githubusercontent.com/11016637/28375032-1a4994da-6caf-11e7-8a5b-02f584b885c3.png)

![image](https://user-images.githubusercontent.com/11016637/28375081-380391f6-6caf-11e7-8f25-6eb8d024a2d1.png)

2) Also there is weird error connected woth debuging: when I place breakpoint into the render method of dragSource node and continue running the app I get an error during the drag

> Uncaught Error: Cannot call hover after drop.
>     at invariant (browser.js?72b5:40)
>     at DragDropManager.hover (dragDrop.js?3115:111)
>     at Object.eval [as hover] (DragDropManager.js?b07f:92)
>     at HTML5Backend.handleTopDragEnter (HTML5Backend.js?5f50:495)

![image](https://user-images.githubusercontent.com/11016637/28407401-b1417c4e-6d3c-11e7-905a-b1f58422cdf2.png)

But issue with dragPreview described above disappears and drag-drop works fine (one time). Then somewhere after drop event 'Cannot call beginDrag while dragging' error occurs and drag stops to work at all.

> Uncaught Error: Cannot call beginDrag while dragging.
>     at invariant (browser.js?72b5:40)
>     at DragDropManager.beginDrag (dragDrop.js?3115:50)
>     at Object.eval [as beginDrag] (DragDropManager.js?b07f:92)
>     at HTML5Backend.handleTopDragStart (HTML5Backend.js?5f50:361)

![image](https://user-images.githubusercontent.com/11016637/28407457-df7269b6-6d3c-11e7-8964-a5ec8783e857.png)

Bug appears only in Chrome (57 and 59). Any ideas?

**Comment by kaiomagalhaes** [comment]
@tTwisTt I'm facing this exactly issue, did you figure out the fix?

**Comment by tTwisTt** [comment]
@kaiomagalhaes In my case I was getting this issue due one of child element of row (cell content) in fact had height that was greater than row height, but was hidden by visibility: hidden by css. So dragSource had width of rows and height of hidden control. I hope you'll find this helpful.

**Comment by matthiaskrieft** [comment]
@tTwisTt  I can confirm that,  same happens with overflow: hidden. is there a way to drag elements like these without the wrong preview?

**Comment by canastro** [comment]
This issue is closed, but it seems to still be a issue, shouldn't it be reopened?

**Comment by olee** [comment]
I also have this same issue - when I start dragging the preview is too large and does not respect parts which should be hidden by overflow.
Here you can see how I drag an element but the "border" left next to it is part of the preview as well.

![image](https://user-images.githubusercontent.com/6547794/46524858-60ceae80-c88a-11e8-9d79-b644fcd7d87f.png)

**Comment by willbuckingham** [comment]
I experienced a similar issue when I try and drag a div wrapped material ui Expansion Panel that is collapsed, it ends up giving me a preview that is the height of the panel expanded but includes elements from the page around the panel, since the visible portion of the panel is smaller than the preview.

**Comment by RahulRameshNarayan** [comment]
i resolved this issue on chrome by adding transform: translate3d(0, 0, 0) to my containing element.

**Comment by jsyvino** [comment]
@RahulRameshNarayan this also worked for me.  THANK YOU!
Any idea why this fixes the issue??

**Comment by RahulRameshNarayan** [comment]
@jsyvino its a repaint issue on chrome. translate3d  forces better hardware acceleration on that element. This is also a hack that people use to solve flickering of scrolling elements in screens of higher resolutions. you can read further about this topics  in the following articles. 

Let's Play With Hardware-Accelerated CSS-
[https://www.smashingmagazine.com/2012/06/play-with-hardware-accelerated-css/](url)

Accelerated Rendering in Chrome
[https://www.html5rocks.com/en/tutorials/speed/layers/](url)

Simplify Paint Complexity and Reduce Paint Areas 
[https://developers.google.com/web/fundamentals/performance/rendering/simplify-paint-complexity-and-reduce-paint-areas](url)

**Comment by makr11** [comment]
transform3d(0,0,0) fixes issue of whole page screenshot but has  wrong position of an element.

**Comment by mismith** [comment]
I'm also getting this issue on Chrome 75 when using a Material-UI ListItem as the draggable node. I think the Ripple element that is contained by overflow: hidden is what's causing the sizing mismatch.

**Comment by faraonkicu** [comment]
Same here, i'm getting this issue on Chrome 75, on Firefox works fine... This should be reopened!

**Comment by makr11** [comment]
My use case is specific but maybe it will help someone, I use velocity-dashboard which uses react-dnd, and inside widgets (which is a draggable component) is rendered react-chart-js. The problem happened when chart-js was rendered inside widget. I just set that when widget is draggable, basic div is rendered inside widget and not chart-js component.

Again, it's pretty specific and i'm not an expert for the subject but maybe this will help someone.

**Comment by artem-tkachenko** [comment]
Issue still reproduced (Chrome 75.0.3770.100 )but resolves by adding **transform: translate3d(0)** to contain element.

**Comment by whois42** [comment]
I'm also experiencing the same trouble. I tried to solve it by adding `transform: translate3d(0, 0, 0)`, but have the same issue as @makr11 here: https://github.com/react-dnd/react-dnd/issues/832#issuecomment-501292272

**Comment by idMolotov** [comment]
Issue is still presence in the:
Safari 13.0.1
Chrome 80

`transform: translate3d(0, 0, 0)` helps, but can affect on other styles/elements in your interface.

**Comment by dotbear** [comment]
@mismith I am struggling with exactly this problem (also using MUI ListItem), did you come up with a solution?

**Comment by mismith** [comment]
@dotbear Sadly no, I am just living with it :(

**Comment by acroyear** [comment]
I agree this issue should not be closed without an official workaround that avoids the giant offset problem.

**Comment by Kroeg93** [comment]
Any news refering to this problem?

**Comment by tanmoytb** [comment]
This issue is still an open problem. It should really be re opened!

**Comment by ffjanhoeck** [comment]
Any updates here ? This issue still exists

**Comment by pwyssmuller** [comment]
Same here. `transform: translate3d(0, 0, 0)` works in Chrome but not in Safari

**Comment by mubbahser** [comment]
I resolved this bug by disabling Ripple effect of material UI.
disableRipple
      disableFocusRipple
      disableTouchRipple

**Comment by lightandbright** [comment]
<ListItemButton disableRipple={true}> worked for me

**Comment by edcaron** [comment]
from: https://github.com/react-dnd/react-dnd/issues/1608#issuecomment-634826018

> I ran into this issue, and in my case it ended up being bad css, I had a child element with a height greater than the parent element.
> 
> Steps to reproduce:
> 
> * create a draggable element with dimensions 200x200
> * create a child of that element with dimensions 200x600
> * the result will be an element that appears to be 200x200, but the drag preview image will be 200x600
> 
> Hope this helps some people

**Comment by jsduffy** [comment]
This issue seems like it's still present.  Adding transform: translate3d(0, 0, 0) to the parent container fixed in Chrome... but is that it?  Seems like this isn't completely resolved.

**Comment by focomoso** [comment]
Want to second that this is an issue on Chrome 119.0.6045.199 and using `transform: translate3d(0, 0, 0)` is not an option for us because of the way we use transforms in the draggable card itself.

Specifically, we have a Three.js canvas that sometimes draws HTML elements "offscreen" which are clipped with `overflow: 'hidden'` which cause the preview to be larger than it should.
