### ISSUE TITLE
[refactor] build process

### ISSUE THREAD

**Issue by Andarist** [react-dnd/react-dnd#834]
Im willing to make a PR with all of this, just would like to get a green light first.

Proposed changes:
- make use of lerna's `hoist` option - no more `"clean": "../../node_modules/.bin/rimraf lib"`, be explicit about each package's dependency and leverage lerna to make the hard lifting
- use `loose` option for babel - transpile less for classes
- provide `module` entry points for all packages - those will allow better tree-shaking and scope hoisting possibilities for webpack3
- output flat bundles - biggest win here would be deduped babel helpers, included only once per package, not once per file
- i could forget about something, is there anything u would like to tweak?

**Comment by darthtrevino** [comment]
Most of this has been done by now. I'm sorry I didn't see your suggestions earlier though.
