### ISSUE TITLE
HTML5 backend - Way to enable only file DnD and not directory

### ISSUE THREAD

**Issue by wldcordeiro** [react-dnd/react-dnd#840]
I'm not sure if this is a limitation in the HTML5 drag and drop spec or react-dnd but is it possible to allow only files to be dropped? Our app doesn't support directories but react-dnd accepts them and we end up in a weird error state.

**Comment by kdavidmoore** [comment]
The way I handle this is examine whether the "type" is an empty string, and if so, don't accept the file. The target box still appears to accept the directory by displaying the green (+) cursor, but the directory is filtered out of the droppedFiles array. I haven't figured out how to display a message to the user that it was unable to add the directory. Modified from the [example](https://github.com/react-dnd/react-dnd/blob/master/examples/06%20Other/Native%20Files/Container.js):

`
import React, { Component } from 'react';
import { DragDropContext, DragDropContextProvider } from 'react-dnd';
import HTML5Backend, { NativeTypes } from 'react-dnd-html5-backend';
import TargetBox from './TargetBox';
import FileList from './FileList';

class Container extends Component {
  constructor() {
    super();
    this.state = {
      droppedFiles: [],
    };
  }

  handleFileDrop = (item, monitor) => {
    if (monitor) {
      const droppedFiles = monitor.getItem().files;
      const filtered = droppedFiles.filter((f) => f.type.length > 0);
      if (filtered.length === 0) {
        console.log('***** Whoops, tried to upload a directory.');
      } else {
        console.log('***** Ah ok, a file.');
      }
      this.setState({ droppedFiles: filtered });
    }
  }

  render() {
    const { FILE } = NativeTypes;
    const { droppedFiles } = this.state;

    return (
      <DragDropContextProvider backend={HTML5Backend}>
        <div>
          <TargetBox accepts={[FILE]} onDrop={this.handleFileDrop} />
          <FileList files={droppedFiles} />
        </div>
      </DragDropContextProvider>
    );
  }
}

export default DragDropContext(HTML5Backend)(Container);
`

**Comment by tomfairbs** [comment]
@kdavidmoore as you may have discovered since writing this, the 'type' property is empty for some file extensions. The first example I found was .msi files but I'm sure there are others.

Are you still using this solution for filtering out directories or did you end up pursuing an alternative approach? I'm trying to do the same thing and this is the best approach I've found so far.

**Comment by igormalyk** [comment]
@kdavidmoore Just to add to what @tomfairbs wrote. Today I learned the `type` property for `.mxf` files is empty on Windows but is present on Mac. As noted in [MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/File/type#Example) this field should not be the only way of validation.

**Comment by fsdiogo** [comment]
I too was testing against an empty string, but many file types accused as empty so it's a no go as @tomfairbs 	and @igormalyk pointed out.

So, is there a straightforward way to validate if we dropped a file or a folder?

**Comment by ufukomer** [comment]
@fsdiogo https://stackoverflow.com/questions/25016442/how-to-distinguish-if-a-file-or-folder-is-being-dragged-prior-to-it-being-droppe
