### ISSUE TITLE
Current component context for DropTarget

### ISSUE THREAD

**Issue by atulmy** [react-dnd/react-dnd#841]
In this example (https://github.com/react-dnd/react-dnd/blob/master/examples/01%20Dustbin/Multiple%20Targets/Dustbin.js#L20) on Line 20, there is props.onDrop(monitor.getItem()); this code where the function onDrop passed to component Dustbin via props is called.

I need to know if there is a way of calling a method defined inside Dustbin instead of passing via props.

Eg: this.onDrop(monitor.getItem()); or currentComponent.onDrop(monitor.getItem());

**Comment by sAs59** [comment]
Drop function accepts 3rd parameter called component. You can call the methods of current component using this parameter.
``` 
drop (props, monitor, component) {
  component.onDrop(...)
}
```

**Comment by neekey** [comment]
Hi @sAs59 I just tried the third parameter for DropTarget, but it seems that it is not the component that we want, it's the component (I guess) used to wrapper our component:

![image](https://user-images.githubusercontent.com/499870/31805160-61394770-b5aa-11e7-8e2a-3e96c66b9681.png)

while the third parameter for DragSource seems correct:

![image](https://user-images.githubusercontent.com/499870/31805206-d28ca232-b5aa-11e7-85b9-b9403459e3d7.png)

My use case is that I want to pass down a context to this DropTarget/DragSource Component, but I failed to get access to the context in the callbacks

**Comment by atulmy** [comment]
@neekey, I did not use the third parameter to get the component as it does not provide the actual component, instead, I wrapped the DropTarget/DragSource into its own container component.

**Comment by neekey** [comment]
@atulmy thanks for sharing your use case. But I still think the API itself should keep the parameter consistent, hope someone can response to this

**Comment by Nixton** [comment]
I have the same problem. Anyone knows how to solve this?
![screenshot 5](https://user-images.githubusercontent.com/2395240/43391055-ed2c0280-93ef-11e8-901f-a673f6369522.png)

**Comment by atulmy** [comment]
@Nixton, I've done a very simple implementation of Kanban using react-dnd which you can check out here: https://github.com/atulmy/hire-smart/tree/master/code/web/src/modules/dashboard/Content/Overview

Hope that may come of some help.
