### ISSUE TITLE
Tough Tutorial

### ISSUE THREAD

**Issue by DZuz14** [react-dnd/react-dnd#844]
I had a tough time with the tutorial. Just some slight criticism, but if the actual drag and drop functionality was explained as well as how to make the chessboard(which is 3/4 of the tutorial), I might have left with a better understanding of how it actually works.

I am pretty familiar with React, but nowhere near the level of understanding of the people that create these modules(Thank you). It seems to me that the DustBin example would have been a much easier way to teach people. That is probably what I am going to use to learn it, instead of the tutorial.

**Comment by dilipMaharjan** [comment]
I have spent my entire week and this is the second week trying to implement in my existing code and I am not anywhere near , the implementation is weirdly difficult.

**Comment by augbog** [comment]
I feel this issue would be a lot more useful if there were examples of which topics specifically people struggled on. I have been using this project for the past few weeks and I feel getting an example working was not too difficult but I also went off of a lot of examples. 

@DZuz14 and @dilipMaharjan do you mind clarifying what you guys struggled on?

**Comment by dilipMaharjan** [comment]
I am not being able to implement it in my project which has existing code and not clearly separated into container and box way.

**Comment by JCLaHoot** [comment]
I agree. The tutorial isn't sufficiently generic. There's too much stuff about the chess game to sift through, and it makes it considerably less digestible (not to mention intimidating when you see the size of the scrollbar!) 

I see things like
```
const squareTarget = {
  drop(props, monitor) {
    moveKnight(props.x, props.y);
  }
};
```
and I'm like, what's `moveKnight()` ? Is this a react-dnd thing or an example specific thing? Then I have to search for it on the page, figure out what it actually does, and determine whether it's relevant or not for what I'm doing. 
A simpler tutorial would go a long way towards making the react-dnd easier to implement.

**Comment by JCLaHoot** [comment]
related: https://github.com/react-dnd/react-dnd/issues/719

**Comment by JCLaHoot** [comment]
this line is problematic: " In a real app, I might also use monitor.getItem() to retrieve the dragged item that the drag source returned from beginDrag" 
Nowhere does it show how to actually do this. (or how to replace moveKnight with something generic) If it does it wasn't clear.

**Comment by nero120** [comment]
That's a tutorial?? Feels more like an exam!

**Comment by johnking** [comment]
I also found the tutorial was not easy to follow ...
