### ISSUE TITLE
 Expected targetIds to be registered

### ISSUE THREAD

**Issue by PorterNan** [react-dnd/react-dnd#845]
Every thing works fine in local and most of clients, but there is about 0.5% - 1% users will meet this crash every day, is there anyone know what might cause this situation? It is really hard to repro...

**Comment by dej611** [comment]
Are you facing this issue with iframes?
I was having the same problem with Firefox and iframes, so I've submitted [a PR to fix it](https://github.com/react-dnd/react-dnd/pull/850). Maybe it can help.

**Comment by HereSinceres** [comment]
Expected targetIds to be registered. @dej611 when drag to a empty element(is a target)
![aa0d40b4fa18172df1d22e6e163b0d89](https://user-images.githubusercontent.com/11225986/39246018-f850bf20-48c7-11e8-9eb9-7c87e7de2d2b.png)
