### ISSUE TITLE
can only certain element of component be made drag source and drop target.

### ISSUE THREAD

**Issue by dilipMaharjan** [react-dnd/react-dnd#849]
Suppose I have a component with 
<div>
       <div>
             some texts
       <div>
       <div>
           how can I make only this div drop target or drag source??
       <div>
</di>

**Comment by JoshMcguigan** [comment]
You could make a new React component which only contains that div.

**Comment by john-d-pelingo** [comment]
There's an example about that here. http://react-dnd.github.io/react-dnd/examples-customize-handles-and-previews.html

**Comment by PatNeedham** [comment]
The link in the previous comment leads to a 404, but I think the same example now lives here: https://react-dnd.github.io/react-dnd/examples/customize/handles-and-previews
Excellent example by the way.
