### ISSUE TITLE
Multiple drags are supported at the same time?

### ISSUE THREAD

**Issue by yunchancho** [react-dnd/react-dnd#854]
I am developing a webapp using react-dnd library to support interaction with users. 
First, I checked drag & drop with custom drag layer works well. 
I appreciate efforts of maintainers and folks in react-dnd.

I should support multiple users on large touch device, and make them drag something at the same time.
But, I couldn't find the way to make it. 

Is there a way to implement multiple drags using react-dnd?

**Comment by Kronenberg** [comment]
I am looking the same, hope somebody reply!
