### ISSUE TITLE
Has anyone been able to implement DND with a modal?

### ISSUE THREAD

**Issue by tjones0808** [react-dnd/react-dnd#855]
I am using react-modal, what i want is when i start dragging my object a fullscreen modal pops up and i can drag and drop to that. but whenever i open my modal drag layer disappears.

**Comment by Artem-Zinchenko** [comment]
@tjones0808 finally, what is a solution here? please, comment

**Comment by tjones0808** [comment]
@Artem-Zinchenko did you get this working? i can post my solution if you still need

**Comment by Artem-Zinchenko** [comment]
@tjones0808 finally it was shifted to low prio. But anyhow, it would be great to look at your solution.

**Comment by tjones0808** [comment]
i believe something was closing my modal as soon as it was opened, so i added a check, and a timeout on the end drag method. no problems anymore. 
` beginDrag(props, monitor, component) {

        // open modal for dragging and dropping here
        setTimeout(function () {
            props.openCloseSocialModal(props.product.inWishList);
            component.setState({ modalOpen: true })

        })


        const { id, product, left, top } = props;
        return { id, product, left, top };
    },
    endDrag(props, monitor, component) {

        if (component == undefined || component.state.modalOpen) {
            setTimeout(function(){
                props.openCloseSocialModal();
            }, 700)
            

        }


    }`

**Comment by abhishekmg** [comment]
I'am trying to use react-dnd  inside a react portal , I think this is similar to a modal , and the dnd implementation is not working , but it is working fine in components outside the portal , any solutions ? I have been stuck in this one for quite some time

**Comment by darthtrevino** [comment]
Can you wire up a live sandbox demonstrating your issue @abhishekmg

**Comment by abhishekmg** [comment]
@darthtrevino , I have fixed that issue. Nothing wrong with react-dnd , it was a problem from my implementation . Anyway here is a codesandbox link https://codesandbox.io/s/green-frog-3ddiw for a very basic implementation of using react-dnd in a modal  , if this would help anyone .

**Comment by CoderOO7** [comment]
> @darthtrevino , I have fixed that issue. Nothing wrong with react-dnd , it was a problem from my implementation . Anyway here is a codesandbox link https://codesandbox.io/s/green-frog-3ddiw for a very basic implementation of using react-dnd in a modal , if this would help anyone .

Is their any benefit of using portal here ? Like I don't have any modal implementation. But would like to know if it can be good code practice to use portal ?
