### ISSUE TITLE
Is it possible to start the drag immediately, on mouse down?

### ISSUE THREAD

**Issue by ndbroadbent** [react-dnd/react-dnd#861]
I've noticed that when I click and start dragging an element, I have to move the mouse around 4px before the drag event actually starts. This is happening in all the examples, as well as in the [dragstart event docs](https://developer.mozilla.org/en-US/docs/Web/Events/dragstart), so I think this is just a limitation of the HTML5 drag API.

Is it possible to manually start the drag as soon as the click happens? Maybe adjust the "tolerance" somehow so that the `dragstart` event fires immediately?

**Comment by ndbroadbent** [comment]
See the new [Draggable](https://github.com/Shopify/draggable) library from Shopify. 

I would really like to see a backend that supported "mouse events" instead of the native HTML5 API. Draggable uses mouse events by default, and it's a much more responsive user experience: https://github.com/Shopify/draggable#options

**Comment by cormacrelf** [comment]
I'm quite sure this is a limitation of Html5 in general.

You might have a look at https://github.com/zyzo/react-dnd-mouse-backend, which has stagnated but would be a good starting point for a mouse events backend.

**Comment by ndbroadbent** [comment]
@cormacrelf Awesome, thanks for the link! I was just starting to work on my own mouse backend using mouse events. I think I might have to continue working on my new backend though, because this looks like it's very out of date.

**Comment by ndbroadbent** [comment]
I'm going to start working on it over here - https://github.com/FormAPI/react-dnd-mouse-backend

**Comment by cormacrelf** [comment]
Watching your repo because I target IE10 ☹️  Did you actually try it? I don't think the backend interface has changed very much.

It might be worth stealing some code from something like https://github.com/bevacqua/dragula or even Draggable JS itself. Getting cloned elements and tracking the mouse is a pretty well beaten to death problem.

**Comment by ndbroadbent** [comment]
Haha wow, I should have tried it first. I didn't expect it to work after a year of no updates, but yeah, it actually works perfectly fine. Wow that makes such a big difference to my app.

There might be a few missing things, but I haven't run into anything problems yet. I'm also not sure if @zyzo is still maintaining it, but everything seems fine for now.

**Comment by ndbroadbent** [comment]
@gaearon - Would it be possible to merge the react-dnd-mouse-backend into react-dnd and provide official support for this?

**Comment by cormacrelf** [comment]
I doubt it, but at least a section in the docs to list more backends and frontends would help.

My upcoming Angular front end deserves a shout out even if it’s Facebook policy to pretend Angular doesn’t exist :) I wish I could use React, I really do. I don’t know of many other front ends (someone copied this repo and called it preact-dnd), but there’s also react-dnd-multi-backend for switching backends based on browser capability. Very cool.
