### ISSUE TITLE
Bug when you drag a YouTube video (I frame), the item disappears in Chrome

### ISSUE THREAD

**Issue by fabriceci** [react-dnd/react-dnd#866]
[screenshot](http://hpics.li/3016258)

Edit: the screenshot was taken in the previous version, now there is always the bug but no more message:

The bug is reproducible [here](https://codesandbox.io/s/1r24rrlx5q)

**Comment by KevinBusch** [comment]
Has anyone had a chance to look into this issue?  We are experiencing this error specifically with youtube videos when using either the React-Player (https://www.npmjs.com/package/react-player) or React-JW-Player (https://www.npmjs.com/package/react-jw-player) wrapping the youtube link.

**Comment by JoshRandall-Andculture** [comment]
This seems to only be happening for us on Chrome in our app.  It doesn't happen on Firefox or Edge.  @fabriceci is the same true for your issue?

**Comment by fabriceci** [comment]
@JoshRandall-Andculture  @KevinBusch

The bug is reproducible [here](https://codesandbox.io/s/1r24rrlx5q).

If I launch the video and move it:

- Chrome: the Drag item completely disappears

- Safari & Firefox : the video stop (but the element is still here)

**Comment by fabriceci** [comment]
The problem is simply a css property (opacity) not set correctly after a drop. The opacity is set to 0 instead of 1 only in Chrome : [screenshot](http://hpics.li/e040b71)
