### ISSUE TITLE
Warning: Failed context type: The context `dragDropManager` is marked as required in `DropTarget(ScheduleCell)`, but its value is `undefined`.

### ISSUE THREAD

**Issue by th3fallen** [react-dnd/react-dnd#872]
with the following...

```
import React, { Component } from 'react';
import PropTypes from 'prop-types';

import ShiftItem from './ShiftItem';

import { DropTarget } from 'react-dnd';

const cellTarget = {
  drop(props, monitor, component) {
    return Object.assign(component.state, props);
  },
  canDrop(props) {
    return true;
  },
};

const collect = (connect, monitor) => {
  return {
    connectDropTarget: connect.dropTarget(),
    isOver: monitor.isOver(),
  };
};

export class ScheduleCell extends Component {

  static propTypes = {
    shifts: PropTypes.object,
    positions: PropTypes.object,
    startOfWeek: PropTypes.object, // Date
  };

  renderShifts() {
    return this.props.shifts.map(shift => {
      const position = shift.position_id ? this.props.positions.get(shift.position_id) : null;
      return (
        <ShiftItem
          key={ `shift-${shift.id}` }
          shift={ shift }
          position={ position }
        />
      );
    }).toArray();
  }

  render() {
    return (
      <div className="schedule-row-cell">
        <div className="shift-holder">
          { this.renderShifts() }
        </div>
      </div>
    );
  }
}

export default DropTarget('shift', cellTarget, collect)(ScheduleCell);
```

am i missing something simple?

**Comment by th3fallen** [comment]
i wasnt adding context... derp

**Comment by willluck** [comment]
I am sorry that I have encountered the same problem after packaging. I would like to ask how you add the code, because the official example does not give clear instructions, thank you?

**Comment by th3fallen** [comment]
I had to do something like this `export default DragDropContext(HTML5Backend)(Layout);` on my layout that was wrapping the components i wanted to drag and drop on, since we use it many places i just did it on my entire applications layout component.

**Comment by willluck** [comment]
Thank you very much, because I haven't maintained this code for a long time, only modifying the underlying components and forgetting to modify the top-level components. However, this is only recently encountered by our team. The Decorator of es7 cannot be used after packaging, which is why I have to change this component to es6.

**Comment by nagendradarla** [comment]
You can also write a function in separate JS file as below

**const dndContext = DragDropContext(HTML5Backend);
export function getDragDropContext(Component) {
  return dndContext(Component);
}**

and then use this as decorator on the component which needs drag and drop context

**@getDragDropContext
class MyComponent extends Component {
}**
