### ISSUE TITLE
Issue on installing development server

### ISSUE THREAD

**Issue by costagolub** [react-dnd/react-dnd#873]
Got an error on trying to install dependencies and run the development server. 
OS: windows10
node: 7.10
npm: 4.2.0

This is what terminal says 
```
$ lerna bootstrap
lerna info version 2.1.2
lerna info Bootstrapping 4 packages
lerna info lifecycle preinstall
lerna info Symlinking packages and binaries
lerna info lifecycle postinstall
lerna info lifecycle prepublish
lerna ERR! execute Error: Command failed: npm run prepublish
lerna ERR! execute '..' is not recognized as an internal or external command,
lerna ERR! execute operable program or batch file.
```

**Comment by daveek** [comment]
I have the same Issue, After launch: "_**$npm install && npm start**_"

> lerna bootstrap

lerna info version 2.0.0
lerna info Bootstrapping 4 packages
lerna info lifecycle preinstall
lerna info Installing external dependencies
lerna info Symlinking packages and binaries
lerna info lifecycle postinstall
lerna info lifecycle prepublish
lerna ERR! execute Error: Command failed: npm run prepublish
lerna ERR! execute ".." no se reconoce como un comando interno o externo,
lerna ERR! execute programa o archivo por lotes ejecutable.

**Comment by StanislavMayorov** [comment]
I have the same issue, but version 2.2.4 works fine.
