### ISSUE TITLE
what does this exactly mean?

### ISSUE THREAD

**Issue by tahamshahzad** [react-dnd/react-dnd#880]
You may be tempted to put a reference to the component into it, but you should try very hard to avoid doing this because it couples the drag sources and drop targets. It's a good idea to return something like { id: props.id } from this method.

**Comment by darthtrevino** [comment]
Use IDs to reference things, not object references.

**Comment by tahamshahzad** [comment]
"because it couples the drop target" i dont exactly understand the point here, can you give me a "bad practice" example?
