### ISSUE TITLE
Drag from outside to inside an Iframe

### ISSUE THREAD

**Issue by nbwar** [react-dnd/react-dnd#886]
There seems to be a lot of talk about Iframe support and you can setup `DragDropContextProvider` from within an Iframe, however, it doesn't seem possible to drag from outside to inside of an iframe.

```
<DragDropContextProvider backend={HTML5Backend}>
  <div>
    <Frame style={{ heigth: '400px', width: '100%' }}>
      <div style={{ clear: 'both' }}>
        <Dustbin />
      </div>
    </Frame>
    <div style={{ overflow: 'hidden', clear: 'both' }}>
      <Box name="Glass" />
      <Box name="Banana" />
      <Box name="Paper" />
    </div>
  </div>
</DragDropContextProvider>
```

**Comment by nbwar** [comment]
Made a quick Backend to support cross iframe support. May not be the best solution but gets the job done for now. Main changes is the how `HTML5Backend` references `this.window`. Changed it to `this.windows` that stores all iframe windows within the parent window.

https://github.com/nbwar/react-dnd-multi-iframe-backend

**Comment by foreverzmy** [comment]
now react-dnd-multi-iframe-backend can not to use, has other method darg from outside to iframe

**Comment by Veath** [comment]
> now react-dnd-multi-iframe-backend can not to use, has other method darg from outside to iframe

What is the specific method？
@foreverzmy

**Comment by paztis** [comment]
problem is still present for me
I've a root application with HTML5Backend, and inside iframes driven with react-frame-component.
So the content of these iframes is composed by the top level application window.

When start dragging from outside, canDrop well appears inside the iframe,  but isOver never occurs, so I cannot drop anything
When start dragging from inside the iframe, isDragging never occurs

How can we resolve it ?

**Comment by paztis** [comment]
I've just found one way oy do it but I access private properties of HTML5Backend for this:

```
import {useDragDropManager} from 'react-dnd';
import Frame, {FrameContextConsumer} from 'react-frame-component';

...

const dragDropManager = useDragDropManager();

return (
  <Frame>
    <FrameContextConsumer>
      {
        // Callback is invoked with iframe's window and document instances
        ({document, window}) => {
          const backend = dragDropManager.getBackend();
          (backend as any).addEventListeners(window); // => add listeners on the chind iframe
        }
      }
     </FrameContextConsumer>
     <all the frame display I need />
  </Frame>
);

```


But to be able to do this, I need to be able to access addEventListeners / removeEventListeners method of the backend, that are not public at all.

Is is possible to make them public ?

**Comment by benjamingeorge** [comment]
I have a similar requirement of dragging from the main window and dropping into and iframe.  It would be nice to have a standard solution for this.

**Comment by monkeyphysics** [comment]
Still looking for a solution for this.

Would be great if there was an officially documented solution, or have it support parent=>iframe dropping out of the box.

**Comment by monkeyphysics** [comment]
So apparently I didn't search well enough 🙄

There's a simple solution: https://react-dnd.github.io/react-dnd/examples/dustbin/iframe

**Comment by shakdoesgithub** [comment]
> So apparently I didn't search well enough 🙄
> 
> There's a simple solution: https://react-dnd.github.io/react-dnd/examples/dustbin/iframe

The issue the author needs help with is dragging from outside an Iframe to inside an Iframe. 
The link you posted contains the Draggable item and the Droppable in the IFrame itself.
