### ISSUE TITLE
drag the sub image in source component cannot trigger drop in firefox 55

### ISSUE THREAD

**Issue by yungfu** [react-dnd/react-dnd#887]
I have a div including a sub image as the soure component, and another div as the target component. When I drag the source div to the target div, it worked well. But if I drag the sub image in the source div, the **drop** function in  target will never be triggered, anyone experience this issue? it woked well in _Chrome, Edge, and IE_.

**Comment by albertodotcom** [comment]
Same problem here, I've tested on this page as well http://react-dnd.github.io/react-dnd/examples-chessboard-tutorial-app.html

My version is `55.0.3`

**Comment by albertodotcom** [comment]
Actually, It has started working 😕
