### ISSUE TITLE
drop() isn't fired when file is dropped: handleTopDrop() not firing.

### ISSUE THREAD

**Issue by bewallyt** [react-dnd/react-dnd#888]
chrome: 56.0.2924.87
electron: 1.6.6
macOS sierra: 10.12.5

I'm running into an issue where _drop()_ isn't fired when a file is dropped in an electron app. I've done a bit of digging into _HTML5Backend.js_ and realized that `handleTopDropCapture()` triggers on drop:

```target.addEventListener('drop', this.handleTopDropCapture, true);```

but `handleTopDrop()` doesn't:

```target.addEventListener('drop', this.handleTopDrop);```

Is there any reason in particular the latter won't fire? Both are added as event listeners to the window.

**Comment by lihqi** [comment]
Hello, I have a same problem. How do you solve it?

**Comment by bewallyt** [comment]
@lihqi - hey so the codebase I had another `drop` event handler that was suppressing the `drop` event. I just deleted that handler. Not sure if that helps much.

**Comment by lihqi** [comment]
Thank you for your reply. I think my version of WebKit is too low.Because in the high version and IE9+ is normal.
