### ISSUE TITLE
Add LICENSE file to repository

### ISSUE THREAD

**Issue by HiDAl** [react-dnd/react-dnd#889]
Hi guys!

First, thanks for this awesome library!
Well, in my job we want use this library but the policies about third-party software force us to only use libraries with an explicit `LICENSE` file in the repo's root. 
As far as I know this library is licensed as MIT, so I can prepare a PR to add the LICENSE file, but first I need to know two things: Year of the license and Copyright Holders. Can you provide me that information?
Thanks again!

**Comment by darthtrevino** [comment]
I added a LICENSE file to the top-level, the individual packages already had LICENSE files available. It's actually under a BSD license, so the license field has been updated in the latest release.

**Comment by HiDAl** [comment]
Thanks @darthtrevino !!!
