### ISSUE TITLE
Ref is always called twice on the DropTargetConnector element (null, then the element)

### ISSUE THREAD

**Issue by ndbroadbent** [react-dnd/react-dnd#890]
Example code:

```js
@DropTarget(dragTypes, target, connect => ({
  connectDropTarget: connect.dropTarget(),
}))
export default class TestComponent extends PureComponent {
  constructor(props) {
    super(props)
    
    this.setContainerRef = (ref) => { 
      console.log("setting container ref", ref)
      this.container = ref
    }
  }

  render() {
    const { connectDropTarget } = this.props

    return connectDropTarget(
      <div ref={this.setContainerRef} />
    )
  }
}
```

Whenever the component is re-rendered, `setContainerRef` is called twice:

```
setting container ref, null
setting container ref, <div ... >
```

I just realized that this is [explained in the DropTargetConnector docs](https://react-dnd.github.io/react-dnd/docs-drop-target-connector.html):

> Internally it works by attaching a callback ref to the React element you give it.

I'm assuming that it wraps the existing ref I passed, and returns a new function each time.

I know refs are ugly, but in this case I really need to calculate the `scrollTop` of that div
in a different component. My code is breaking because ref gets set to null during the state change, so I can't calculate the scroll.

It would be awesome if `connectDropTarget` could do some memoization for the ref callback (like what I'm doing in the constructor.) That would solve my issue.

(As a workaround, I know that the element is never going to be `null`, so I'll just ignore `null` for now.)

**Comment by heyimalex** [comment]
You can do it yourself, as `connectDropTarget` is really just a ref callback.

```javascript
this.setContainerRef = (ref) => {
  console.log("setting container ref", ref)
  this.container = ref
  this.props.connectDropTarget(ref);
}
```

**Comment by ndbroadbent** [comment]
Oh that's a great point, thanks!
