### ISSUE TITLE
Example breaks down, because React 16 have no `react/lib/*`

### ISSUE THREAD

**Issue by suhaotian** [react-dnd/react-dnd#891]
This [example](https://github.com/react-dnd/react-dnd/blob/master/examples/04%20Sortable/Stress%20Test/Container.js#L2) import `update` from `react/lib/`.

But in [react 16 blog post](https://facebook.github.io/react/blog/#packaging):
> There is no react/lib/* and react-dom/lib/* anymore

**Comment by darthtrevino** [comment]
Yeah, my bad. That should be fixed in master now

**Comment by gazpachu** [comment]
Sorry, so what's the solution for this? Do I have to use https://www.npmjs.com/package/react-addons-update or is there another way of doing it? I had a look at the example but I couldn't find it. Thanks in advance!

**Comment by daniula** [comment]
For those who are upgrading from React 15 to React 16, used one of the deprecated examples in their code and end up here looking for help. The solution is simply to replace:
`import update from 'react/lib/update';` with `import update from 'immutability-helper';`

**Comment by icehongssii** [comment]
USING
`    "ajv": "^6.5.3",
    "react": "^16.5.2",
    "react-dnd": "^5.0.0",
    "react-dnd-html5-backend": "^5.0.1",
    "react-dom": "^16.5.2",
    "react-scripts": "1.1.5"
`

However 
import update from 'immutability-helper';
does no longer work

**Comment by icehongssii** [comment]
had to install new package. if there's a better way to fix it, I would love to know. thanks 
https://stackoverflow.com/questions/41677407/react-lib-update-multiple-splices-multiple-indexes
