### ISSUE TITLE
cannot have two HTML5 backends at the same time.

### ISSUE THREAD

**Issue by kishore-dumpa** [react-dnd/react-dnd#899]
Hi I'm trying to implement the same as 'http://bit.ly/2y4TwZz', unfortunatley its throwing an error 
**'Uncaught Error: Cannot have two HTML5 backends at the same time.'**

I tried in different ways also I tried all the possible ways from 
https://github.com/react-dnd/react-dnd/issues/186

but I'm unable to resolve it can anyonce help me to fix this

and below is my coe

`import React, { Component } from 'react'
import SortableTree from 'react-sortable-tree';
import { DragDropContext, DragSource } from 'react-dnd';
import HTML5Backend from 'react-dnd-html5-backend';
import './dnd.css'
//import { SortableTreeWithoutDndContext as SortableTree } from './src';
const externalNodeType = 'yourNodeType';
const externalNodeSpec = {
  beginDrag: componentProps => ({ node: [ ...componentProps.node ] }),
};
const externalNodeCollect = (connect /* , monitor */) => ({
  connectDragSource: connect.dragSource(),
});
class externalNodeBaseComponent extends Component {
  render() {
    const { connectDragSource, node } = this.props;

    return connectDragSource(
      <div
        style={{
          display: 'inline-block',
          padding: '3px 5px',
          background: 'blue',
          color: 'white',
        }}
      >
        {node.title}
      </div>,
      { dropEffect: 'copy' }
    );
  }
}

const YourExternalNodeComponent = DragSource(
  externalNodeType,
  externalNodeSpec,
  externalNodeCollect
)(externalNodeBaseComponent);

class App extends Component {
    constructor(props) {
      super(props);
  
      this.state = {
        treeData: [
          { title: 'Chicken', expanded: true, children: [{ title: 'Egg' }] }
        ]
      };
    }
  
    render() {
      return (
        
        <div>
        <div style={{ height: 300 }}>
          <SortableTree
            treeData={this.state.treeData}
            onChange={treeData => this.setState({ treeData })}
            dndType={externalNodeType}
          />
        </div>
        <tempp/>
        <YourExternalNodeComponent node={{ title: 'Baby Rabbit' }} />
        ← drag this
      </div>
  
        
      );
    }
  } 
  export default DragDropContext(HTML5Backend)(App);`

**Comment by blord-fullscreen** [comment]
Please format your code correctly. The preview button is your friend!

I find that generating the decorator in a separate module solved this problem for me. See the example at https://github.com/react-dnd/react-dnd/issues/186#issuecomment-282789420
