### ISSUE TITLE
Non-DOM Backend

### ISSUE THREAD

**Issue by lyleunderwood** [react-dnd/react-dnd#903]
The pluggable backend architecture of react-dnd seemed like a possible fit for my use case, which is a 2d `<canvas>` dnd project, but it seems like the core of react-dnd does actually have particular ties to the DOM. This is most obvious in `wrapConnectorHooks` which calls [`throwIfCompositeComponentElement`](https://github.com/react-dnd/react-dnd/blob/master/packages/react-dnd/src/wrapConnectorHooks.js#L4). This pretty explicitly shuts down any attempt to use react-dnd with non-DOM components:

```javascript
throw new Error(
	'Only native element nodes can now be passed to React DnD connectors.' +
		`You can either wrap ${displayName} into a <div>, or turn it into a ` +
		'drag source or a drop target itself.',
)
```

Am I wrong in my reading that react-dnd cannot actually be used on anything other than DOM nodes? Is there a compelling reason that this needs to be the case? It seems like a significant benefit of a pluggable backend would be to encapsulate these sorts of dependencies.

**Comment by jeroenransijn** [comment]
I am not sure either what the issue is here. Potentially if the problem is a implementation based on a ref we could make `connectDropTarget/connectDragSource` accept a function:

```
connectDropTarget((getRef) => <Box innerRef={ref => getRef(ref)} />)
```

I am still new to this project so I made be completely missing how it works.

**Comment by adampilks** [comment]
Pretty interested in the feedback here too.  Currently not seeing any widely used package for dnd in React Native, so would be intrigued to know if this is a potential solution.

**Comment by rardoz** [comment]
Would be nice to have. Using react-native-web. Need this!
