### ISSUE TITLE
Order does not change when hovering another list

### ISSUE THREAD

**Issue by kaiomagalhaes** [react-dnd/react-dnd#906]
When I have an item being dragged from list A to B the list B doesn't change on the hover, which makes it hard to know in which place the item will be dropped.

Is it possible to make it display the hover effect or is it an issue?

**Comment by PaulBrunache** [comment]
that's something you'd have to implement. 
you'd have to drop the item on hover, without actually dropping it & then sort as normal.

only down side to this approach is you'd have a hard time doing a cancelled drop
