### ISSUE TITLE
receive hover() call on but monitor.isOver() return false

### ISSUE THREAD

**Issue by 0x0d01** [react-dnd/react-dnd#908]
Hi,

Is there any possible case where hover() is called but monitor.isOver() returns false ?

I ask this since I have encounter the issue but still can't figure it out how to solve it. 
When I try to look into why monitor.isOver() return false, I found that it enters this if statement in DragDropMonitor.js:
```
                const targetIds = this.getTargetIds()
		if (!targetIds.length) {
			return false
		}
```

Is this a bug ?

**Comment by MikeYermolayev** [comment]
Encountered the same issue and was surprised a little. 

It's always reproducible. monitor.isOver return false on first `hover` invocation.

As a workaround I hover callback when monitor.isOver is false but looks like not very predictable behavior.

The repro: https://codesandbox.io/s/friendly-sutherland-7bex6
