### ISSUE TITLE
Problem when setting up React-DnD

### ISSUE THREAD

**Issue by codefacts** [react-dnd/react-dnd#913]
Hi,
I am building a form builder in react. I am using react dnd for drag & drop interaction. I ran 
npm install --save react-dnd and npm install --save react-dnd-html5-backend
Then I import HTML5Backend and DragDropContext. Then I ran webpack watch and getting the following error.

ERROR in ./node_modules/disposables/modules/index.js
Module build failed: ReferenceError: [BABEL] D:\NetBeansProjects\tracker-web-panel\node_modules\disposables\modules\index.js: Using removed Babel 5 option: D:\NetBeansProjects\tracker-web-panel\node_modules\disposables\.babelrc.stage - Check out the corresponding stage-x presets http://babeljs.io/docs/plugins/#presets
    at Logger.error (D:\NetBeansProjects\tracker-we

I am using babel, webpack and npm in windows 10. Following is my babelrc config
{
  "presets": ["env", "stage-2", "react"],
  "plugins": ["transform-decorators-legacy"]
}
and this is the webpack config file
var webpack = require('webpack');
var path = require('path');

var BUILD_DIR = path.resolve(__dirname, 'build');
var APP_DIR = path.resolve(__dirname, '');

var config = {
  entry: APP_DIR + '/index.jsx',
  output: {
    path: BUILD_DIR,
    filename: 'bundle.js'
  },
  module : {
    loaders : [
      {
        test : /\.jsx?/,
        include : APP_DIR,
        loader : 'babel-loader'
      }
    ]
  }
};

module.exports = config;

I am getting very frustrated. When I comment out the two imports HTML5Backend and DragDropContext. Then my application compiles and run perfectly. I don't know what to do. Could you help me please in this regard?

**Comment by gaearon** [comment]
You should have `exclude: /node_modules/` as an option to `babel-loader`.
