### ISSUE TITLE
How to render another component based on the dragged value?

### ISSUE THREAD

**Issue by SupunRajapaksha** [react-dnd/react-dnd#917]
I am new to react. I use react dnd to drag components in to a custom drag zone. Here I want to render another component based on the value that is being dropped. The new component has some html tags that should be displayed when the item is being dropped in the drag zone.  Any idea on how to achieve this? My codes are attached herewith.

**Container.js**
`import React from 'react';
import update from 'immutability-helper';
import ElementComponents from './ElementComponents';
import ItemTypes from './ItemTypes';
import Target from './Target';

export default class Container extends React.Component {
    constructor(props) {
        super(props)
        this.state = {
            elementcomponents: [
                { accepts: [ItemTypes.TARGET], lastDroppedItem: null },
                ],         
            boxes: [
                { name: 'Target', type: ItemTypes.TARGET },
                { name: 'Rule', type: ItemTypes.RULE },                
            ],
            droppedBoxNames: [],
        }
    }
    isDropped(boxName) {
        return this.state.droppedBoxNames.indexOf(boxName) > -0
   }
    render() {
        const {elementcomponents} = this.state

        return (
            <div className="container-fluid">
                <div style={{ overflow: 'hidden', clear: 'both' }}>
                    {elementcomponents.map(({ accepts, lastDroppedItem }, index) => (
                        <ElementComponents
                            accepts={accepts}
                            lastDroppedItem={lastDroppedItem}
                            onDrop={item => this.handleDrop(index, item)}
                            key={index}
                        />

                    ))}
                    **{(this.state.lastDroppedItem=={"name":"Target"}) && (<div><Target></Target></div>)}**
                   //this is the logic used to render the second component.

                </div>
            </div>
        )
    }
    handleDrop(index, item) {
        const { name } = item
        const droppedBoxNames = name ? { $push: [name] } : {}

        this.setState(
            update(this.state, {
                elementcomponents: {
                    [index]: {
                        lastDroppedItem: {
                            $set: item,
                        },
                    },
                },
                droppedBoxNames

            }),
        )  
    }
}`
Following is the second component I want to render in the container when the item is dropped in the drop zone.

**Target.js**
`import React from 'react';
import Select from 'react-select';
import {ReactDOM,findDOMNode} from 'react-dom';
import update from 'immutability-helper';

class Target extends React.Component {
    constructor(props) {
        super(props);
        this.state = {          
            valueselect2: "",
            valueselect3: ""
        }

        this.logChange2 = this.logChange2.bind(this);
        this.logChange3 = this.logChange3.bind(this);
        this.dismiss = this.dismiss.bind(this);
    }

    logChange2(val) {
        this.setState({valueselect2: val.value});
    }

    logChange3(val) {
        this.setState({valueselect3: val.value});
    }

    dismiss() {       
        this.el.remove();
     }

    render() {
        var equals = [
            {value: 'equals', label: 'equals'},
            {value: 'equals-data', label: 'equals-info'},
        ];
    
        return (
                <div data-alert className="alert-box error-box" ref={(el) => {this.el = el}}>
                   <button onClick={this.dismiss.bind(this)}>
                        <img
                            src="/images/add.png"
                            alt="my image"
                            width="10"
                            height="10"
                        />
                    </button>
                
                <div className="col-sm-6"
                     style={{
                         height: 20,
                         width: 150,
                         float: 'left',
                     }}
                >
                    <Select id="equals"
                            name="form-field-name"
                            value={this.state.valueselect2}
                            options={equals}
                            onChange={this.logChange2}
                    />
                </div>

                <div className="col-sm-6"
                     style={{
                         height: 20,
                         width: 200,
                         float: 'left',
                         _fontSize:'8px'

                     }}>
                    <input className="form-control" id="value"
                           placeholder="Value"/></div>

                <div className="col-sm-6"
                     style={{
                         height: 20,
                         width: 150,
                         float: 'left',

                     }}
                >                    
                </div>
            </div>
        );
    }
}
export default Target;`

Your help is appreciated.

**Comment by kigit2017** [comment]
1. import an instance of Target.js into Container.js
import {Target} from './Target.js';
2.Make container.js render to return the Target instance in the dropzone.
render(){
          return <Target/>;
        }
