### ISSUE TITLE
Is there a reason why component isn't passed to DropTargetSpec.canDrop?

### ISSUE THREAD

**Issue by scottcheng** [react-dnd/react-dnd#923]
In my app, the drop target could move during a drag, and parts of the drop target is not droppable. Therefore I need to read drop target's position from `ReactDOM.findDOMNode(component).getBoundingClientRect` (in addition to mouse position) to determine droppability. However, we don't currently have access to the component in `canDrop`.

Looking at the [drop target code](https://github.com/react-dnd/react-dnd/blob/c6bf3afa54786f856f4fc89241a66479b0f9d1e4/packages/react-dnd/src/createTargetFactory.js#L52) briefly, it seems pretty straightforward to pass `this.component` to `spec.canDrop` so it matches the interface of `hover` and `drop`. I'm curious if there's any reason why we don't do that?

**Comment by xMihai** [comment]
> It is purposefully missing from canDrop because the instance may not be available by the time it is called. If you want this method to depend on the component's state, consider lifting the state to the parent component, so that you can just use props. Generally your code will be cleaner if you rely on props instead whenever possible.


Source: https://react-dnd.github.io/react-dnd/docs-drop-target.html
