### ISSUE TITLE
Testing with Enzyme rather than React TestUtils

### ISSUE THREAD

**Issue by dwjohnston** [react-dnd/react-dnd#925]
I'm getting on with writing some tests, following [this documentation](http://react-dnd.github.io/react-dnd/docs-testing.html) and also this issue https://github.com/react-dnd/react-dnd/issues/453

The problem I have is regarding the test rendering. 

I can get the example that the documentation gives working, wrapping the component in a DragDropContext and rendering it with `TestUtils.renderIntoDocument`. 

This will return a `DragDropContextContainer` object. 

However, if I try use the Enyzme `mount` method to render the object, it returns a `$$typeof: Symbol(react.element)` object - which won't let me get the manager. 

I would prefer to use Enzyme - as that's what I'm using for my tests elsewhere. 

Anyone got any help with this?

**Comment by FreeMasen** [comment]
I just got this working, here is what it looks like. in typescript.

```ts
import { ThingIAmTesting } from '../file/where/it/lives';
describe('It is a test!', () => {
  let props;
  let component;
  const getComponent = () => {
    let OriginalComponent = (ThingIAmTesting as any).DecoratedComponent;
    let identity = el => el;
    if (!component) {
      component = Enzyme.shallow(
        <OriginalComponent {...props} connectDragSource={identity} />
       );
      return component
    }

    beforeEach (() => {
      props = {
         prop: 'stuff',
         }
      component = undefined;
     })
    it('should render', () => {
      let component = getComponent();
      expect(component).toMatchSnapshot();
    });
})
```

**Comment by gilleswittenberg** [comment]
Ran into this same problem. I could, and expect you should be able to, fix it using the `wrapper.instance()` method. Also described here https://github.com/react-dnd/react-dnd/issues/488. 

e.g.
```javascript
const Context = wrapInTestContext(Component)
const wrapper = mount(<Context />)
const manager = wrapper.instance().getManager()
const backend = manager.getBackend()
```

Additionally, I also needed to get the instances of child components to call `getHandlerId()`.

If it helps, here is one of my test files: https://gist.github.com/gilleswittenberg/142fe49e1115b5a1936562b2284e1ab7

**Comment by ericpoon** [comment]
Hey guys, I got an error saying **Invariant Violation: Expected sourceIds to be registered.** when I ran `backend.simulateBeginDrag([sourceId])`.

js
```
const wrapInTestContext = (DecoratedComponent) => {
    return DragDropContext(TestBackend)(
      class TestContextContainer extends React.Component {
        render() {
          return <DecoratedComponent {...this.props} />;
        }
      }
    );
  };
  let wrapper, backend;
  beforeEach(() => {
    const Wrapped = wrapInTestContext(ImageBoard);
    wrapper = mount(
      <Wrapped sortable>
        <div key={1} />
        <div key={2} />
      </Wrapped>
    );
    backend = wrapper.instance().getManager().getBackend();
  });

  it('should work', () => {
    console.log(wrapper.debug());
    const dragSource = wrapper.find('DropTarget(DragSource(SortableContainer))').at(0).find('DragSource(SortableContainer)').instance();
    const dropTarget = wrapper.find('DropTarget(DragSource(SortableContainer))').at(1).instance();

    const sourceId = dragSource.getHandlerId();
    const targetId = dropTarget.getHandlerId();

    console.log(sourceId, targetId);
    backend.simulateBeginDrag([sourceId]);
  });
```
