### ISSUE TITLE
IE  - > Expected "spec" provided as the second argument to DragSource to be a plain object. Instead, received [object Array Iterator]

### ISSUE THREAD

**Issue by tobiaskiel** [react-dnd/react-dnd#926]
Can not get this to work on IE
Heres my code:

    const specSource = {
    beginDrag(props) {
       return {
         name: 'Item'
       };
    },
    endDrag(props, monitor) {
       const item = monitor.getItem();
       const dropResult = monitor.getDropResult();
       if (dropResult) {
         SurveyStore.AppendItem(props.schema, props.uiSchema);
       }
       }
    };

    @DragSource('survey-item', specSource, (connect, monitor) => ({
      connectDragSource: connect.dragSource(),
      isDragging: monitor.isDragging()
    }))
    class FormItem extends React.Component {
      render() {
        return (
      <div className='template-item-wrapper'>
        <div className='template-description'>
          <Icon name='circle' size='tiny' />
          {this.props.description}
        </div>
        {this.props.connectDragSource(
          <div className='template-item'>
            <Icon className='template-icon' name={`${this.props.itemIcon}`} />
            <div className='template-text'>{this.props.itemText}</div>
          </div>
        )}
      </div>
    );
    }
     }
    FormItem.propTypes = propTypes;
    export default FormItem;

Following error occures:
Expected "spec" provided as the second argument to DragSource to be a plain object. Instead, received [object Array Iterator]. Read more: http://react-dnd.github.io/react-dnd/docs-drag-source.html

Any help is much appreciated!

**Comment by shahen94** [comment]
+ Same issue on IE11
