### ISSUE TITLE
Dragging canvases in Chrome makes the them fully transparent

### ISSUE THREAD

**Issue by Tsourdox** [react-dnd/react-dnd#932]
I have html canvases that I drag around. It works as expected in Safari and Firefox. Though in Chrome as the canvases becomes transparent when dragging them. Is this a bug in Chrome or a feature in Safari and Firefox?

Also transparent html elements in Chrome become opaque, bug?

Thx for a great library!

**Comment by fabriceci** [comment]
seem related to #866

**Comment by Tsourdox** [comment]
Maybe, it's only the items inside the canvas that disappears. For example, the css boxshadow of the canvas is still there.

**Comment by fabriceci** [comment]
I added a post to #866 : "The problem is simply a css property (opacity) not set correctly after a drop. The opacity is set to 0 instead of 1 only in Chrome : [screenshot](http://hpics.li/e040b71)".

Can you check if the opacity set to 0 on your div instead of 1 in Chrome?

**Comment by Tsourdox** [comment]
Cool I'll check it out.. I'll probably use a screenshot of the canvas with a custom drag layer anyways coz I need to support mobile and tablet.
