### ISSUE TITLE
Is there a simple example?

### ISSUE THREAD

**Issue by FruitAndAShape** [react-dnd/react-dnd#935]
I'm looking for the most simple example possible. The chess board tutorial is a little complicated for me.

**Comment by bjrmatos** [comment]
have you tried the examples [here](https://github.com/react-dnd/react-dnd/tree/master/examples), there are a lot, so maybe one can work for you.

**Comment by FruitAndAShape** [comment]
Great, thanks. I will try "Drag Around - Naive", that sounds about my level.

**Comment by heinhoang** [comment]
[here](http://blog.emiketic.com/2017/react-dnd-for-complex-drag-and-drop-interfaces/)'s also a good simple example

**Comment by icehongssii** [comment]
I am suffering as well

**Comment by bammoo** [comment]
Here is an alternative https://github.com/atlassian/react-beautiful-dnd

**Comment by AlisonWonderlandApps** [comment]
Agree with this.. some examples NOT in typescript would be a better introduction

**Comment by AlisonWonderlandApps** [comment]
Ok so if anyone wants to checkout the chessboard example in NON-typescript... https://github.com/AlisonWonderlandApps/kbworkflow :)

**Comment by karonlewin** [comment]
I need to say that I truly admire all the effort given to write the library and the tutorial, but in my opinion as a beginner on React is that the chess game adds a lot of complexity to the tutorial, it's difficult to understand the concepts about the drag and drop functionality while having to understand the logic around a chess board/game. I'll take a look at other examples, thank you.

**Comment by djnorrisdev** [comment]
I simply couldn't get the tutorial to work past the regular layout. I couldn't get past the `observer is not a function` error. This is frustrating when I'm copying from the tutorial. The icing on the cake is going to the example source code to find it's in Typescript. I think it's time to use another library.

**Comment by InsOpDe** [comment]
I find this one very good:
https://techdoma.in/simple-introduction-to-drag-and-drop-library-react-dnd-in-react/
