### ISSUE TITLE
Cannot have two HTML5 backends at the same time - having the same App twice on the page

### ISSUE THREAD

**Issue by devssc** [react-dnd/react-dnd#939]
Hi,
Is there any way to share HTML5 backend between multiple instances of the same app on one page?

Background:
We have an app using react-dnd that serves as a custom editor in the backend of our cms. This app was previously built-in via iframe. I'm trying to embed it directly into the page, which works fine so far, but there are two or more instances of the app on some pages.

```
App = DragDropContext(HTML5Backend)(App);
export default App;
```

**Comment by froatsnook** [comment]
I've never done this but I would try:

```javascript
export default () => DragDropContext(HTML5Backend)(App);
```

and then:

```javascript
import AppFactory from "./App";
const App1 = AppFactory();
const App2 = AppFactory();
ReactDOM.render(
  <App1 />
, target1);
ReactDOM.render(
  <App2 />
, target2);
```

**Comment by devssc** [comment]
@froatsnook thanks for the fast reply!
I tried it with your suggestion but sadly it still leaves the problem with two HTML5 backends

**Comment by devssc** [comment]
We resolved it by placing the App-Component in a DragDropContextProvider instead

	<DragDropContextProvider backend={HTML5Backend} window={fakeWindow}>
		<App />
	</DragDropContextProvider>

which accepts a (in our case fake-) window

	var fakeWindow=document.getElementById(mydiv);
	fakeWindow.document = {
		body: document.getElementById(mydiv)
	}

**Comment by ValeraT1982** [comment]
@devssc , can you please provide all code? I'm trying to do the same but I still have and error "Cannot have two HTML5 backends at the same time."
