### ISSUE TITLE
no Ghost Images

### ISSUE THREAD

**Issue by atburghardt** [react-dnd/react-dnd#946]
I just started implementing DnD and have some issues with the ghostimages.
Firefox works fine, but Chrome displays a File-Image while dragging and Safari displays nothing (just the normal cursor). The dragelement opacity changes to 0.5, like in the tutorial, so the dragging is working up to this point.

Checked other issues, but nothing has been able to help. Any ideas?

**Comment by rajaishwary** [comment]
@atburghardt  You need to wrap connectDragSource in connnectDragPreview like below to fix it cross-browser.

```
connectDragPreview(
      <div>
         {connectDragSource(
            <div className={className}>
                Sample Draggable Card
            </div>
        )}
     </div>
)
```

**Comment by atburghardt** [comment]
Thanks for the fast reply, but this don't seem to work. Maybe my code helps finding my Mistake?:

`
const bubbleSource = {
  beginDrag(props) {
    return {};
  }
};

function collect(connect, monitor) {
  return {
    connectDragSource: connect.dragSource(),
    connectDragPreview: connect.dragPreview(),
    isDragging: monitor.isDragging()
  };
}
class Bubble extends Component {
  render() {
    const { connectDragSource, connectDragPreview, isDragging } = this.props;
    return connectDragPreview(
      <div>{connectDragSource(<div>Bubble</div>)}</div>
    );
  }
}
const DragBubble = DragSource(ItemTypes.BUBBLE, bubbleSource, collect)(Bubble);
`

**Comment by atburghardt** [comment]
Ok, 
the reason Chrome and Safari have Problems is because my elements are inside a Slider.
It's rendered offscreen and transitioned to the screen, those browsers seem to have a problem with that.

**Comment by annietsai** [comment]
Hey @atburghardt we're getting a similar problem where we see the file icon on drag for Chrome but not for Safari or Firefox. Do you mind explaining more about what your problem ended up being?

**Comment by clydekarnage** [comment]
is there any workaround for this issue?
