### ISSUE TITLE
canDrop result

### ISSUE THREAD

**Issue by cristianfraser** [react-dnd/react-dnd#949]
First of all, I'm sorry if this isn't the right place for asking/saying this, but after some StackOverflow I guess I can give it a try here.

I'd like to know if a certain behaviour can be achieved with the current API, or using some hacky hacks, or isn't supported. If it isn't, may it could be added to the roadmap? Maybe it already is?

So, my scenario, using the tutorial's chess as an example. 
 * When dragging the knight, the overlay shows where it can be dropped, where it can't be dropped, and where it is currently being hovered on.
 * The `canDrop` method on the `dropTarget` says whether the knight can be dropped on each cell. Using the chess's knight rules or whatever complex rules to determine that.

So when a knight is dropped on a correct cell, it moves. Drop it on any other cell, nothing happens.

So this is my question: instead of nothing happening, could something happen? For example, the `canMove` function says the knight can be moved 1 cell in any direction, but only to black cells. So, if the knight is dropped further than one cell in a black one, I'd like to display "**You can only move the knight one cell away**". When one cell away, but a white one "**You can only move it to a black cell**". When neither condition is met "**You can only move it one away, to black**".

The problem is, I can't do this on the `canDrop` function, because it is constantly being called. Can't be done on the `drop` function because it isn't called when `canDrop` returns `false`. Can't be done on the drag source's `endDrag`, because there wouldn't be any result returned from the dropTarget. So, **how should it be done**?

I'd love to be able to simply use `canDrop` and use its result somehow. Like, when the item is dropped, call `canDrop` one last time with a new flag argument, like 

```
canDrop(props, monitor, droppedFlag) {
  const condition1 = ...
  const condition2 = ...

  const canDrop = condition1 && condition2
  if (droppedFlag && !canDrop) {
    props.doSomething() // or props.notify('condition1 or condition2 wasn't met [...]')
  }

  return canDrop
}
```

So that when the drop "fails", you could still handle that somehow.
Is it something that can be done with current version? Cleanly? Hackily? Can't be done?

**Comment by tsriram** [comment]
I'm not sure if I understood your question / problem fully, but how about checking for the condition outside `canDrop`? I mean, make all cells (or any targets) droppable so that `canDrop` always returns true and once the item is dropped, check if it meets the required conditions for that drop target and do whatever is required. For example, if condition1 & condition2 are not met after the item is dropped, just don't move the item to target and maybe call `doSomething().

**Comment by cristianfraser** [comment]
The problem with that is the `canDrop` prop passed to the component by the collect function, is used to render the corresponding overlay (red if it can't be dropped, green if it can).

I could eventually just remove the `canDrop` function from the drop target, but then the logic that says if a card can be dropped or not would start repeating in the methods called when the drop is successful and when rendering the overlay. So I'd have to remove the one place where the `canDrop` logic is (the drop target spec) and move it to *at least* to two other places, the success call and the overlay render method, and possibly more if it's ever decided the `canDrop` result is needed somewhere else.

That's the reason I personally like an additional flag in the `canDrop`, that could say **this is the last time** that function is going to be called, so you can notify or do whatever it the card can be dropped or not. And why I think it's not really simple to move the `canDrop` logic somewhere else than where it already is.

**Comment by cristianfraser** [comment]
Also, would have repeating logic in the `endDrag` method of every different card type that can be dropped, instead of it just being in the drop target. And not in every drag source and method called after a successful `drop`
