### ISSUE TITLE
It seems didn't work with Typescript

### ISSUE THREAD

**Issue by Sunzhuoyi** [react-dnd/react-dnd#951]

**Comment by tsriram** [comment]
I've been using it with TypeScript for quite some time without any problem. It'd help to post a detailed description of the issue.

**Comment by Sunzhuoyi** [comment]
@tsriram Thanks
<img width="1271" alt="2018-01-21 4 33 43" src="https://user-images.githubusercontent.com/11895051/35192221-e0570bca-fec8-11e7-9f81-38fa609afe0b.png">

**Comment by tsriram** [comment]
I'm sorry but I'm not able to see what's going wrong from the screenshot. Is it possible for you to share the code snippet of the component or a relevant part of it? If not, can you try reproducing this issue with a small example in [CodeSandbox](https://codesandbox.io/s/react-ts) or a similar service?

**Comment by abelkbil** [comment]
@tsriram , I have a doubt on Typescript. Can you please look here https://github.com/react-dnd/react-dnd/issues/782#issuecomment-367231472 

Thanks

**Comment by darthtrevino** [comment]
All the examples are written in Typescript, and the typings have improved a lot since we migrated over to TS.
