### ISSUE TITLE
how to implement remove item when it's dragged outside of container

### ISSUE THREAD

**Issue by witqq** [react-dnd/react-dnd#954]
I have a items container where i can add items by dropping them into.
Is it possible to remove items, by dragging them outside of my container?
Any workarounds?

**Comment by virajsoni06** [comment]
@witqq Did you find a solution to this?

**Comment by witqq** [comment]
> @witqq Did you find a solution to this?

yes, you can check `didDrop()` method of monitor in the item's `endDrag` event. If result is `false`, then it was an outside of a container drop

**Comment by virajsoni06** [comment]
Ah I see. I'm still a little unclear on how did you make the items draggable from the drop area/box? Do you have any code references you can share?

**Comment by virajsoni06** [comment]
The place I am stuck at is removing an item from the dropped container

**Comment by jt6677** [comment]
> The place I am stuck at is removing an item from the dropped container

  const [{ opacity }, drag] = useDrag(
    () => ({
      type: type
      item: { yourData },
      collect: (monitor: DragSourceMonitor) => ({
        opacity: monitor.isDragging() ? 0.4 : 1,
      }),
      end: (item, monitor) => {
        const didDrop = monitor.didDrop()
        if (!didDrop) {
          console.log("dropped outside")
// here is where you call your handleDrop that your pass from your container

        }
      },
    }),

    [yourData ]
  )
