### ISSUE TITLE
isDragging and isOver not consistent?

### ISSUE THREAD

**Issue by oyshan** [react-dnd/react-dnd#960]
Hi!

I have a List with draggable ListItems. When I drag a ListItem out of a List, I want to hide it, so I send the List's `isOver` (from the List's dropTarget) as a prop, `isOverList`, down to ListItem.
My thoughts are that I should hide ListItem when `isOverList = false` and ListItem's `isDragging = true`, i.e. the ListItem is being dragged and it is not over the list:

    class ListItem extends React.Component {
	    render() {
		const {
			connectDragSource,
			connectDropTarget,
			isDragging,
			isOverList,
		} = this.props

		const dragItemStyle = {}
		if (!isOverList && isDragging) {
			// Hide item if dragged outside parent list
			dragItemStyle.display = 'none'
		}

		return connectDropTarget(connectDragSource(
			<div style={dragItemStyle}>
				I AM LIST ITEM
			</div>
		))
	    }
    }

However, this does not work as expected, as `isDragging=true` and `isOverList=false` right after a drag has started. I.e. after a drag has started, the first render of the dragged ListItem will hide the ListItem, thus causing my list to be shuffled. In the next render, `isOverList=true`, and my ListItem becomes visible again, but now in another position (e.g. shifting from index 0 to 1).

Shouldn't `isOverList`and `isDragging` be set at the same time when a drag starts? It seems there is a latency from `isDragging` is set to `isOverList` is set. Or should I do this in another way?

PS. I've also noticed that the same occurs with the ListItem's `isOver` (`isOver` is false and `isDragging` is true at beginning of drag)

**Comment by prkagrawal** [comment]
Facing the same issue, Is there any update on this?

**Comment by AntonellaM** [comment]
Same here!!
