### ISSUE TITLE
Move event

### ISSUE THREAD

**Issue by qtbit** [react-dnd/react-dnd#962]
I'd like to use react-dnd to drag & drop container components into other container components to create a tree.
![image](https://user-images.githubusercontent.com/25822015/35795280-f60d0096-0a58-11e8-8a31-e036ba20ece6.png)

When moving a component, I'd liek to fire a redux action to update component positions on canvas to update e.g. the lines connecting the component with other components, move other components to create a space for the moving component etc.

![image](https://user-images.githubusercontent.com/25822015/35795549-cad72edc-0a59-11e8-80b1-1969eb124862.png)

**Troubles**
- react-dnd misses `onMove` event where a redux action updating positions and properties of canvas objects could be fired (e.g. updating the connecting lines, highlighting underlying component border etc.)
- react-dnd has `hover` event, but it is called only on hovering the target component not outside (on canvas, out of the canvas)
- creating places on drop-target component where you can't drop (e.g. title) is not possible?
- not possible to limit movement and remove lag as [mnquintana](https://github.com/react-dnd/react-dnd/issues/384#issuecomment-227601762) wrote

**Comment by tommedema** [comment]
@qtbit how would you implement such `onMove` event with a HoC?

**Comment by guchengjie** [comment]
I also want to get the event object at the end of the drag. Self monitoring is also blocked.

**Comment by jt3k** [comment]
I also want to get a move or drag event, as implemented in the DOM API

**Comment by ronen** [comment]
FWIW I've simply placed an `onDragOver` event on the relevant canvas component container, and it gets called normally with the drag event.  The handler dispatches redux actions and it seems to work fine, while `react-dnd` continues to do its stuff.
