### ISSUE TITLE
group elements together

### ISSUE THREAD

**Issue by unutoiul** [react-dnd/react-dnd#963]
So i have a list of elements and i want to group them together. EXAMPLE:

Array of elements:

var arr = [component_source, component_source1...]

I want to get event when component.source is touching component.source1 and reverse....

Is that possible? that the same element can be DragSource and DragTarget?

There is not example for doing this kind of interaction...

I will really appreciate your answer.

Thanks,
Lucas

**Comment by sunndeath** [comment]
How??
