### ISSUE TITLE
Unmounting the drop target while handling `hover` causes the drag source to not call `endDrag` until it is dragged again

### ISSUE THREAD

**Issue by dansaltmer** [react-dnd/react-dnd#964]
I've created a replication of this against the simple list example to keep it close to how it is intended to be used, and then a workaround that solves it in a repository.
https://github.com/dansaltmer/react-dnd-simple-multi-list/commits/master

When letting go after the hover has been handled which removed the component that handled the hover, `endDrag` is not called, and `isDragging` remains true until the item is picked up again, then it will fire `endDrag` then `beginDrag` immediately following it.

The workaround instead sets the item to display none instead of unmounting it. Given the workaround may not be feasible in some people's use case, then thought it worth raising despite having a workable fix for my use case.

**Comment by oleks-fedotov** [comment]
Having exactly the same issue

**Comment by shahankit** [comment]
Any workaround for this?
