### ISSUE TITLE
connectDragPreview remains a mystery

### ISSUE THREAD

**Issue by im1dermike** [react-dnd/react-dnd#967]
I've been reviewing the documentation and github issues for the past hour and `connectDragPreview` still remains a mystery to me.  I would like to define a custom preview for how the item appears when it is being dragged (just like the tutorial example with the horse image).  Here is my code:

```
export const tokenCollector: DragSourceCollector = (connect, monitor) => {
  return {
    connectDragSource: connect.dragSource(),
    connectDragPreview: connect.dragPreview(),
    isDragging: monitor.isDragging()
  };
};

class TokenClass extends React.Component<TokenProps> {
  componentDidMount() {
    const { connectDragPreview } = this.props;
    const img = new Image();
    img.src = '<encoded image>';
    img.onload = () => connectDragPreview(<div>{img}</div>);
  }
  render() {
    const { connectDragSource, isDragging, children } = this.props;
    return connectDragSource(
      <div style={{ opacity: isDragging ? 0.5 : 1 }}>
        {children}
      </div>
    );
  }
}
const dragSource = DragSource(DropType.Token, tokenSpec, tokenCollector)(TokenClass);
export { dragSource as Token };

```

The standard preview appears with this code.

I then tried to wrap my `connectDragSource` in my component's `render()` method with `connectDragPreview`, but that only appears to change the drag source where it was picked up from, not how it appears as it's being dragged.

**Comment by sebas5384** [comment]
yeah I have the same feeling, can't make it work 👎

**Comment by im1dermike** [comment]
@sebas5384 I got some feedback from a SO question, but it still didn't lead me to an answer and seemed more complicated than it should be. https://stackoverflow.com/q/48811165/1315956

**Comment by augbog** [comment]
So for those wondering yeah the key to getting a custom drag preview and using [Custom Drag Layer](https://react-dnd.github.io/react-dnd/examples-drag-around-custom-drag-layer.html). Worth reading the direct documentation of [Drag Layer](https://react-dnd.github.io/react-dnd/docs-drag-layer.html) in it's **entirety**.

It looks like one of the answerers brought it up in your SO question and you mentioned you can't see it working for other browsers? I believe that just might be some cross browser tweaks you might need to do on the Drag Preview component you define in the Drag Layer.

I also agree getting a drag preview going is kinda tough but I feel the documentation is pretty upfront about this. Getting custom drag previews working with the HTML5 drag/drop API is a pain in and of itself and it's pretty limited (I believe all they really have is the ability to [setDragImage](https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer/setDragImage) which naturally doesn't support React components).

**Comment by atkallie** [comment]
Like @augbog said, under the hood all that React DnD is doing is using [setDragImage](https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer/setDragImage). [CustomDragLayer](https://react-dnd.github.io/react-dnd/examples-drag-around-custom-drag-layer.html) tries to get around this by setting the drag preview image to an empty image. This is explicitly [stated in the docs](https://react-dnd.github.io/react-dnd/examples-drag-around-custom-drag-layer.html):

> The browser APIs provide no way to change the drag preview or its behavior once drag has started. Libraries such as jQuery UI implement the drag and drop from scratch to work around this, but react-dnd only supports browser drag and drop “backend” for now, so we have to accept its limitations.
> 
> We can, however, customize behavior a great deal if we feed the browser an empty image as drag preview. This library provides a DragLayer that you can use to implement a fixed layer on top of your app where you'd draw a custom drag preview component.

This is accomplished by using the `getEmptyImage` utility function that's included in the `react-dnd-html5-backend` package. You can see this in action in the [CustomDragLayer example](https://github.com/react-dnd/react-dnd/tree/master/packages/documentation/examples/02%20Drag%20Around/Custom%20Drag%20Layer) provided:

```
componentDidMount() {
	// Use empty image as a drag preview so browsers don't draw it
	// and we can draw whatever we want on the custom drag layer instead.
	this.props.connectDragPreview(getEmptyImage(), {
		// IE fallback: specify that we'd rather screenshot the node
		// when it already knows it's being dragged so we can hide it with CSS.
		captureDraggingState: true,
	})
}
```
You are then responsible for translating the CustomDragLayer yourself. This can be seen in the following code excerpt (taken from [this file in the same example](https://github.com/react-dnd/react-dnd/blob/master/packages/documentation/examples/02%20Drag%20Around/Custom%20Drag%20Layer/CustomDragLayer.js) as earlier):
```
function getItemStyles(props) {
	const { initialOffset, currentOffset } = props
	if (!initialOffset || !currentOffset) {
		return {
			display: 'none',
		}
	}

	let { x, y } = currentOffset

	if (props.snapToGrid) {
		x -= initialOffset.x
		y -= initialOffset.y
		;[x, y] = snapToGrid(x, y)
		x += initialOffset.x
		y += initialOffset.y
	}

	const transform = `translate(${x}px, ${y}px)`
	return {
		transform,
		WebkitTransform: transform,
	}
}
```

The CustomDragLayer is also not configured for a specific item type (like DragSource is), so you have to specifically check which item type is being dragged and then decide whether or not the CustomDragLayer should be displayed (following is from same file as above):

```
renderItem(type, item) {
	switch (type) {
		case ItemTypes.BOX:
			return <BoxDragPreview title={item.title} />
		default:
			return null
	}
}
```

Kind of a mess if you ask me. I've had a bit more success in the past by using the [dom-to-image](https://github.com/tsayen/dom-to-image) library to turn the DOM node that I want to use as the drag preview into an image and then passing the resulting image to the `connectDragPreview` function. Something like:

```
// Some node you want to use as your drag preview
const node = document.createElement("p");
const childNode = document.createTextNode("This is new.");
node.appendChild(childNode);

domtoimage.toPng(node)
.then(function (dataUrl) {
        const img = new Image();
	img.src = dataUrl;
	img.onload = () => this.props.connectDragPreview(img);
})
.catch(function (error) {
       console.error('something went wrong!', error);
});
```

**Comment by warpdesign** [comment]
I am having the same problem but most links pointed here (eg. [CustomDragLayer](https://github.com/react-dnd/react-dnd/tree/master/packages/documentation/examples/02%20Drag%20Around/Custom%20Drag%20Layer)) seem to be broken, so this doesn't help much :/

Anyone have a working link for CustomDragLayer example?

**Comment by atkallie** [comment]
Yeah, it seems the original links I referenced got axed.

Here is a link for a working example of CustomDragLayer:
http://react-dnd.github.io/react-dnd/examples/drag-around/custom-drag-layer

And here is the source code for that example:
https://github.com/react-dnd/react-dnd/tree/master/packages/documentation-examples/src/02%20Drag%20Around/Custom%20Drag%20Layer

**Comment by jithinkradhakrishnan** [comment]
Anyone have a working link for CustomDragLayer example? with Javascript

**Comment by atkallie** [comment]
I’m not sure why they keep changing the links, but if you go to the React DnD Github site you’ll find a working example of CustomDragLayer under the Examples tab (currently listed under the ‘Drag Around’ examples).

**Comment by mellis481** [comment]
@atkallie We are on the React DnD Github site and the CustomDragLayer example (at least the one that existed when I logged this issue) was what I unsuccessfully attempted to use as a guide previously.

**Comment by atkallie** [comment]
@mellis481 Here is a working example of the tutorial that you referenced that I put together. I used events in the code below since I wanted the code here to be self-contained, but in production you would probably use something like Redux to keep track of the changes to the knight's position. Hopefully this helps. (I kept it all in one file so that I could paste the code here for others to reference, so I apologize if it's a bit cluttered.)

```javascript
import _ from 'lodash';
import React, { Component } from 'react';
import PropTypes from 'prop-types';
import { DragDropContext, DragSource, DropTarget } from 'react-dnd';
import HTML5Backend from 'react-dnd-html5-backend';

// Example Chess Board where the knight is dragged to different squares and
// is only allowed to change position if the drop target has a position located
// in an L-shape relative to the current position (chess rule for knights)

// configure the knight's initial position
let knightPosition = [3, 4];

// this image is used below to demonstrate how to configure a custom drag preview
const crazyHorse = 'https://www.dhresource.com/100x100/f2/albu/g4/M01/B9/1D/rBVaEFmRPdeAJZ0pAAIcbxpSGmY771.jpg';

// function used to dispatch an event whenever the knight changes position
// whenever the event is dispatched, ReactDnDTutorial (top level component) will
// update
// NOTE: this is needed because knightPosition is a global variable --
// 		 not state or props -- of ReactDnDTutorial so it will not refresh when
//		 the variable changes. In a production application we would probably
//	 	 use Redux instead and map knightPosition to ReactDnDTutorial's props
//		 in mapStateToProps and React would then handle rerendering for us
//		 automatically, but I wanted the logic of this walkthrough to all be
//		 displayed in a single file.
const emitChange = () => {
	const event = new Event('KNIGHT_POSITION_CHANGED');
	window.dispatchEvent(event);
}

// utility function to change the knight's position
const moveKnight = (toX, toY) => {
	// if using Redux the following would be replaced by a call to an action creator
	// (i.e. store.dipatch({ type: 'KNIGHT_POSITION_CHANGED', payload: [toX, toY] }))
	knightPosition = [toX, toY];
	emitChange();
}


// utility function to check if the knight's location can be changed based on L-rule
const canMoveKnight = (toX, toY) => {
	const [x, y] = knightPosition;
	const dx = toX - x;
	const dy = toY - y;

	return (
		(Math.abs(dx) === 2 && Math.abs(dy) === 1) ||
		(Math.abs(dx) === 1 && Math.abs(dy) === 2)
	);
}


// create the constants for the draggable item types
const ItemTypes = { KNIGHT: 'KNIGHT'};

// Knight Piece (Drag Source)
class __Knight extends Component {
	componentDidMount() {
  		const img = new Image();
		img.src = crazyHorse;
		img.onload = () => this.props.connectDragPreview(img);
	}

	render() {
		const { connectDragSource, isDragging } = this.props;
		return connectDragSource(
			<div
				style={{
					opacity: isDragging ? 0.5 : 1, fontSize: 25,
					fontWeight: 'bold', cursor: 'move'
				}}
			>
				♘
			</div>
		);
	}
}

// Collecting Function
// 		the collecting function returns a plain object of
//		the props to inject into your component
function knightCollect(connect, monitor) {
	return {
		connectDragSource: connect.dragSource(), // connector
		connectDragPreview: connect.dragPreview(),
		isDragging: monitor.isDragging() // monitor
	}
}

// DragSource specification
// 		A plain JavaScript object with a few allowed methods on it.
//		It describes how the drag source reacts to the drag and drop events
const knightDragSourceSpec = {
	// beginDrag is required
	// 		Returns a plain JavaScript object describing the data being dragged.
	//		Object returned is the only information available to the drop
	//		targets about the drag source so it's important to pick the minimal
	// 		data they need to know
	beginDrag(props, monitor, component) {
		return {};
	}
}

const Knight = DragSource(
	ItemTypes.KNIGHT,  // (type) the item type (only the drop targets registered for the same type will react to the items produced by this drag source)
	knightDragSourceSpec,
	knightCollect
)(__Knight);

class Square extends Component {
	render() {
		const { black } = this.props;
		const fill = black ? 'black' : 'white';
		const stroke = black ? 'white' : 'black';

		return (
			<div
				style={{
			        backgroundColor: fill,
			        color: stroke,
			        width: '100%',
			        height: '100%'
		  		}}
			>
	        	{this.props.children}
	      	</div>
	    );
	}
}

class __BoardSquare extends Component {
	renderOverlay(color) {
		return (
			<div
				style={{
					position: 'absolute',
					top: 0, left: 0, height: '100%', width: '100%',
					zIndex: 1, opacity: 0.5, backgroundColor: color,
				}}
			>
			</div>
		);
	}

	render() {
		const { x, y, connectDropTarget, isOver, canDrop } = this.props;
		const black = (x + y) % 2 === 1;

		return connectDropTarget(
			<div style={{ position: 'relative', width: '100%', height: '100%' }}>
				<Square black={black}>
					{this.props.children}
				</Square>
				{isOver && !canDrop && this.renderOverlay('red')}
				{!isOver && canDrop && this.renderOverlay('yellow')}
				{isOver && canDrop && this.renderOverlay('green')}
			</div>
		);
	}
}

function squareCollect(connect, monitor) {
	return {
		connectDropTarget: connect.dropTarget(),
		isOver: monitor.isOver(),
		canDrop: monitor.canDrop()
	};
}

const squareDropTargetSpec = {
	canDrop(props) {
		return canMoveKnight(props.x, props.y);
	},

	drop(props) {
		moveKnight(props.x, props.y);
	}
}

const BoardSquare = DropTarget(
	ItemTypes.KNIGHT,
	squareDropTargetSpec,
	squareCollect
)(__BoardSquare);

class __Board extends Component {
	renderSquare(i) {
		const x = i % 8;
		const y = Math.floor(i / 8);
		return (
			<div key={i}
				style={{ width: '12.5%', height: '12.5%' }}>
				<BoardSquare x={x} y={y}>
					{this.renderPiece(x, y)}
				</BoardSquare>
			</div>
		);
	}

	renderPiece(x, y) {
		const [knightX, knightY] = this.props.knightPosition;
		if (x === knightX && y === knightY) {
			return <Knight />;
		}
	}

	render() {
		const squares = [];
		for (let i = 0; i < 64; i++) { squares.push(this.renderSquare(i)); }

		return (
			<div
				style={{
					width: '100vw', height: '100vh',
					display: 'flex', flexWrap: 'wrap'
				}}
			>
				{squares}
			</div>
		);
	}
}

// typechecking with prop-types
__Knight.propTypes = {
	connectDragSource: PropTypes.func.isRequired,
	isDragging: PropTypes.bool.isRequired
};
Square.propTypes = { black: PropTypes.bool };
__BoardSquare.propTypes = {
	x: PropTypes.number.isRequired,
	y: PropTypes.number.isRequired,
	connectDropTarget: PropTypes.func.isRequired,
	isOver: PropTypes.bool.isRequired,
	canDrop: PropTypes.bool.isRequired
};
__Board.propTypes = {
	knightPosition: PropTypes.arrayOf(PropTypes.number.isRequired).isRequired
};

// Wrap the root component of your application with DragDropContext to set up React DnD.
// This lets you specify the backend, and sets up the shared DnD state behind the scenes.
// const Board = DragDropContext(TouchBackend)(__Board);
const Board = DragDropContext(HTML5Backend)(__Board);

class ReactDnDTutorial extends Component {
	constructor(props){
		super(props);
		this.state = { eventListenerAdded: false }
	}

	componentDidMount(){
		this.handleEventListening();
	}

	componentWillUnmount(){
		this.handleEventListening();
	}

	handleEventListening = () => {
		if(!this.state.eventListenerAdded){
			window.addEventListener('KNIGHT_POSITION_CHANGED', this.handleRefreshComponent)
		}else{
			window.removeEventListener('KNIGHT_POSITION_CHANGED', this.handleRefreshComponent)
		}
	}

	handleRefreshComponent = (e) => { this.forceUpdate() }

	render(){
		return <Board knightPosition={knightPosition} />
	}
}

export default ReactDnDTutorial;
```

**Comment by darthtrevino** [comment]
After wrestling with this problem myself, I found this was due to a limitation in the HTML5 Drag-and-Drop API. 

You cannot define arbitrary, detached DOM to write up a drag preview. You have to use an image. 

To make this easier, we've added the DragPreviewImage component in the top-level API.
