### ISSUE TITLE
NativeFile drag works intermittently on Firefox 58

### ISSUE THREAD

**Issue by theTechie** [react-dnd/react-dnd#969]
Native file drag seems to not work as expected when the drag is cancelled. Next time we try to drag a native file onto a target, target fails to identify the drag item.

![firefox-dnd-bug](https://user-images.githubusercontent.com/1046486/36205733-bce6dfc6-11b5-11e8-9d28-00820f4c4b30.gif)

**Comment by theTechie** [comment]
Investigated a bit to see some Firefox specific quirks added in the codebase (probably bcoz of the previous behaviour of the browser).

Looks like Firefox has improvised and we no more need this quirk; which solves this problem.

**Comment by chrise86** [comment]
This is still an issue for me, and it only starts working again if I restart Firefox.
