### ISSUE TITLE
How to set another design to my dragged element clone in drag time

### ISSUE THREAD

**Issue by AnoushS** [react-dnd/react-dnd#972]
How to set another design to my dragged element clone in drag time
![example](https://user-images.githubusercontent.com/32042424/36247129-46c76d64-124c-11e8-8c1f-caa0180cb5cb.png)

**Comment by tsriram** [comment]
For custom drag preview, I guess you'll have to implement [DragLayer](http://react-dnd.github.io/react-dnd/docs-drag-layer.html). [[Example]](http://react-dnd.github.io/react-dnd/examples-drag-around-custom-drag-layer.html)
