### ISSUE TITLE
Getting current dropEffect to DropTarget's drop handler

### ISSUE THREAD

**Issue by rihok** [react-dnd/react-dnd#974]
Hey,

I'm probably missing something obvious here, but I can't seem to figure out how to get the current dropEffect on the DropTarget. Or to be more precise, the drop effect that was used on drop.

What I am trying to do is something like this:

```js
  const boxTarget = {
    drop (props, monitor) {
      if (monitor.getDropEffect() === 'copy') {
        // do something when copying
      }
      else {
        // do something different
      }
    }
  }
```

**Comment by tgrander** [comment]
I don't believe that getDropEffect is a method on monitor parameter. A complete list of available monitor methods can be found in the [monitor docs](https://react-dnd.github.io/react-dnd/docs-drop-target-monitor.html). 

What do you mean by 'drop effect' ?

**Comment by rihok** [comment]
That was an example of what I would expect from the monitor. Sorry I wasn't clearer.

When holding ALT and dragging, you are effectively in copy mode. So can I figure out inside of DropTarget what mode an item was dropped in with?

**Comment by rihok** [comment]
Any help with this? I'm simply trying to know what happened on drop. Was it a copy or a simple move? Basically whether ALT was held down during the drop.

**Comment by melvynhills** [comment]
In `endDrag` or `drop`:
```javascript
const dropResult = monitor.getDropResult();
if (dropResult) {
  console.log(dropResult.dropEffect);
}
```

**Comment by rihok** [comment]
getDropResult always returns null for me in the target's drop function

**Comment by rihok** [comment]
Nevermind, it seems I can only get the dropResult in endDrag of the source.
