### ISSUE TITLE
Error: DragDropContextProvider backend and window props must not change.

### ISSUE THREAD

**Issue by alexandraclaire** [react-dnd/react-dnd#975]
Hi there,
I am making a drag and drop web app that has many possible dragSources, so I was going to paginate them and update the state with the new set of dragSources. However, when I do, I get this error:
`DragDropContextProvider backend and window props must not change.`

Is it possible to change the list of dragSources with react-dnd, am I doing something wrong?

Help would be much appreciated!

**Comment by KacperKozak** [comment]
I had the same problem but with [TouchBackend](https://github.com/yahoo/react-dnd-touch-backend).
Make sure that you are not changing`backend` in `DragDropContextProvider` eg.:

```js
// error after re-render
render() {
return <DragDropContextProvider backend={TouchBackend({ enableMouseEvents: true })}>
```
```js
// backend as const outside of render
const touchBackend = TouchBackend({ enableMouseEvents: true });
…
render() {
   // ok
   return <DragDropContextProvider backend={touchBackend}>

**Comment by vilius** [comment]
straight into issue I was having, thanks @KacperKozak
