### ISSUE TITLE
DragLayer makes the element not to become draggable - pointer events

### ISSUE THREAD

**Issue by ancodeUDW** [react-dnd/react-dnd#977]
I was working to implement react-dnd in an already existing react project, and I had trouble adding the DragLayer in the existing components: if well the drag and drop worked properly, when I added the DragLayer to the project the dragging of the elements stop working totally.

After hours of checking the documentation, I realized that, even if I did as the documentation said, and I checked the examples, there was an SMALL detail that I forgot to add and its only shown in the code: **the DragLayer Dom element has to be defined with the css value "pointer-events: none" so it doesn't interfere with the draggable element**.

After that, it became obvious, however, due the nature of this mistake (is more related with css than react/dragAndDrop), and the fact that is not mention in the documentation (or at least I could not find any reference of it), other people might have the same error, and think that is something related with JavaScript or that they didn't understood something related with the react-dnd concept, rather than with css styles, as it happened to me.

I suggest to write in some place that the DragLayer should have that css style in order to work properly (for example, in the "Custom drag Layer" example and/or in the Top level api -> DragLayer section)

**Comment by RellaxxDev** [comment]
So haw can i fix it? I have pointer-events: auto under the drag layer, it breaks dnd
