### ISSUE TITLE
Safari scroll bug on sortable example (on the actual react-dnd examples page)

### ISSUE THREAD

**Issue by preciselywilliam** [react-dnd/react-dnd#978]
BUG REPORT

Browser: Safari
Version: 11.0.2 (12604.4.7.1.6)

Steps to reproduce:
1. Go to https://react-dnd.github.io/react-dnd/examples-sortable-simple.html
2. Inspect elements and set the height of the following element to 3000px:

```
<p data-reactid="89" style="height: 3000px;">
  <b data-reactid="90">
    <a href="https://github.com/react-dnd/react-dnd/tree/master/examples/04%20Sortable/Simple" data-reactid="91">
      Browse the Source
    </a>
  </b>
</p>
```
4. Scroll down and start dragging and dropping.

A drop will sometimes cause the page to scroll to almost the top of the page.
If it doesn't happen, refresh the page and try again. I haven't been able to figure out exactly what causes the behavior, it's very sporadic.

**Comment by glenn-allen** [comment]
I haven't seen this exact behaviour, and I wasn't able to replicate the above scenario, however we had a similar problem on our product which I'll describe here in case it helps.

We have contenteditable elements inside draggable elements.  In Safari if the contenteditable text was selected and then the draggable element was dragged it seems that the browser ended up in a confused state - appearing to drag the selected text while React DnD dragged the element.
From that point on the dragging behaviour was erroneous and often the drag would cause the screen to jump around, similar to what was mentioned above.

I didn't delve into the source to determine why this was happening as I found a workaround which avoided the problem.
By using `window.getSelection().removeAllRanges();` on `mousedown` (before the drag start occurs) the browser would no longer end up in the confused state and dragging behaved as expected.

Hopefully this is helpful & related to the above issue, below is a screen-grab of our issue.

![drag error](https://user-images.githubusercontent.com/14475082/37004621-207dc800-2125-11e8-9cb7-ffe590c23db6.gif)
