### ISSUE TITLE
在树形结构中，使用react-dnd，需要阻止冒泡，如何阻止事件冒泡，spec中没有提供事件对象event

### ISSUE THREAD

**Issue by chengzhenping** [react-dnd/react-dnd#982]
在树形结构中，使用react-dnd，需要阻止冒泡，如何阻止事件冒泡，spec中没有提供事件对象event

**Comment by zxlin** [comment]
In case a translation was needed:
> In a tree structure, while using react-dnd, I need to prevent event propagation, how do I stop event propagation, the spec doesn't mention anything about event targets
