### ISSUE TITLE
React-Dnd support for touch devices

### ISSUE THREAD

**Issue by Aarbel** [react-dnd/react-dnd#995]
Hi react-dnd contributors,

## Are you working on touch devices support ? 

I saw react-dnd-touch-backend but there's no direct examples like [react-dnd examples](http://react-dnd.github.io/react-dnd/examples-chessboard-tutorial-app.html), and this library seems buggy.

How can i contribute ?

Thanks for your work

**Comment by RomanProkhodsky** [comment]
There are some examples: https://github.com/yahoo/react-dnd-touch-backend#examples

**Comment by Aarbel** [comment]
@RomanProkhodsky thanks ;)

Not ready to test examples, can i add them to a public github page ?
