### ISSUE TITLE
"monitor.isOver()" returning false

### ISSUE THREAD

**Issue by Atmaks** [react-dnd/react-dnd#996]
In short, I've a homebrew tree-view React component with nodes as drag sources and overlays as drop targets. For some reason, `hover` event isn't firing and monitor.isOver() always returns false, as checked through canDrop. Also, canDrop is firing for every rendered tree node. Is this normal behaviour?

A more detailed description with code is posted at [StackOverflow](https://stackoverflow.com/questions/49604672/simple-tree-view-with-react-dnd). I can copy it here if necessary.

**Comment by wangzhe1995** [comment]
i encounter sample problem
